### ISSUE TITLE
Build fails on 7.0-RELEASE FreeBSD 7.0-RELEASE #167: Sat Jul  3 13:48:19 PDT 2010 amd64

### ISSUE THREAD

**Issue by kimo** [joyent/libuv#1004]
.....
....
  CC(target) /root/kguda/node-v0.10.22/deps/uv/out/Debug/obj.target/run-benchmarks/test/run-benchmarks.o
  CC(target) /root/kguda/node-v0.10.22/deps/uv/out/Debug/obj.target/run-benchmarks/test/runner.o
  CC(target) /root/kguda/node-v0.10.22/deps/uv/out/Debug/obj.target/run-benchmarks/test/runner-unix.o
  LINK(target) /root/kguda/node-v0.10.22/deps/uv/out/Debug/run-benchmarks
/root/kguda/node-v0.10.22/deps/uv/out/Debug/obj.target/libuv.a(core.o)(.text+0x1225): In function `uv__io_close':
../src/unix/core.c:718: undefined reference to`uv__platform_invalidate_fd'
gmake: **\* [/root/kguda/node-v0.10.22/deps/uv/out/Debug/run-benchmarks] Error 1
gmake: Leaving directory `/root/kguda/node-v0.10.22/deps/uv/out'

**Comment by indutny** [comment]
Thanks, its fixed in v0.10 branch: https://github.com/joyent/libuv/commit/026241ca67717679a7f79d92c4fe1d77f223318c. Should go into next v0.10 release of node.js.

**Comment by kimo** [comment]
Thank you.
