### ISSUE TITLE
file change event just call once?

### ISSUE THREAD

**Issue by ccoossdddffdd** [joyent/libuv#1013]
uv_fs_event_init(loop, (uv_fs_event_t*) malloc(sizeof(uv_fs_event_t)), _path.c_str(), run_command, 0);

i use this code to monitor my files change event, but when that file change, it just call run_command once, 

please help me, i used libuv version: 0.11.9

**Comment by saghul** [comment]
Cn you detail a bit more what operations you are doing to the file? A example test script might also help.

**Comment by ccoossdddffdd** [comment]
void readdir(const char \* path)
{
    uv_fs_t readdir_req;

```
uv_fs_readdir(loop, &readdir_req, path, 0, NULL);
if(readdir_req.ptr != NULL) {

    string base(path);
    string _path;

    char * buf = (char *)readdir_req.ptr;
    while (readdir_req.result--) {
        _path = base + "/" + buf;
        if(string(buf).substr(0,1) != ".") {
            if(isdir(_path.c_str()))
                readdir(_path.c_str());
            else {
                uv_fs_event_init(loop, (uv_fs_event_t*) malloc(sizeof(uv_fs_event_t)), _path.c_str(), run_command, 0);
                cout << _path << endl;
            }
        }

        size_t len = strlen(buf);
        buf += len + 1;
    }
}
uv_fs_req_cleanup(&readdir_req);
```

}

readdir('test_dir');

this is my code

**Comment by ccoossdddffdd** [comment]
void run_command(uv_fs_event_t *handle, const char *filename, int events, int status) {
    if (events == UV_CHANGE) {
        change_count++;
        cout << "change file: " << handle->filename << " count: " << change_count << endl;
    }

```
uv_close((uv_handle_t*)handle, NULL);
```

}

and this is callback code

it just the example code form joyent test, and i copy to my program.

**Comment by indutny** [comment]
On what OS are you testing it?

**Comment by ccoossdddffdd** [comment]
macosx  10.9

**Comment by indutny** [comment]
May I ask you to try latest libuv master? I've just pushed a commit that is fixing at least one problem with `uv_fs_event_t`.

**Comment by ccoossdddffdd** [comment]
ok, i try first

**Comment by ccoossdddffdd** [comment]
can u give me the lastest uv_fs_event_init test code?

i don't know how to use  uv_fs_event_\* functions.

**Comment by indutny** [comment]
Sure, https://github.com/joyent/libuv/blob/master/test/test-fs-event.c#L260

**Comment by ccoossdddffdd** [comment]
thank u

**Comment by ccoossdddffdd** [comment]
i use the test code, but it just call fs_event_cb_dir_multi_file when create anything...

it's great, but i want to call it when change ....

**Comment by ccoossdddffdd** [comment]
oh~  monitor file is need to uv_fs_event_start every files?

**Comment by ccoossdddffdd** [comment]
and now, i just use 

uv_fs_event_start(&fs_event, fs_event_cb_dir_multi_file, "src/main.cpp", 0);

to monitor the src/main.cpp..

but. when my program start, it call fs_event_cb_dir_multi_file once, 

and change the src/main.cpp, called fs_event_cb_dir_multi_file. 

but still only once call fs_event_cb_dir_multi_file.

i just add some space or some char to file and save it..

**Comment by saghul** [comment]
Yes, the API changed, you need to _init the fsevent handle and then start it.

**Comment by ccoossdddffdd** [comment]
@saghul yes, i get the test code from indutny~

**Comment by ccoossdddffdd** [comment]
i use libuv version: 0.11.16-pre

@indutny are u still here? i'm wait online....

**Comment by indutny** [comment]
Sorry, just trying to understand what exactly is happening on your side? May I ask you to explain it a bit?

From what I read above:
1. You call uv_fs_event_inti() and uv_fs_event_start() for a file main.cpp
2. Callback happens?! Without changes to file?
3. You edit file and save it
4. No callback happens?!

Is it correct?

**Comment by ccoossdddffdd** [comment]
https://gist.github.com/cosnis/7656611

sorry, please goto this page to see the code, it easy to watch

https://gist.github.com/cosnis/7656628   this is the makefile

**Comment by ccoossdddffdd** [comment]
this is all my code..

**Comment by ccoossdddffdd** [comment]
You call uv_fs_event_inti() and uv_fs_event_start() for a file main.cpp
     yes

Callback happens?! Without changes to file?
     callback happens, without change to file, but i think it maybe the sublime's bug..

You edit file and save it, No callback happens?!
     the callback just happens once,

**Comment by indutny** [comment]
How many times it should happen?

**Comment by ccoossdddffdd** [comment]
just happen once

**Comment by indutny** [comment]
Ok, isn't that how it should be? You save file once - it happens once!

**Comment by ccoossdddffdd** [comment]
yes, i want it is;

**Comment by indutny** [comment]
So it is _not_ happening?

**Comment by ccoossdddffdd** [comment]
yes.... T_T....

**Comment by indutny** [comment]
ok, may I ask you try doing the same process with a notepad, instead of a sublime? I mean:
1. uv_fs_event_init() + uv_fs_event_start()
2. open file in notepad
3. change file and save it

**Comment by ccoossdddffdd** [comment]
0.0      ok, i know it's a bug of sublime....  

so thanks very much...

**Comment by indutny** [comment]
Np, it took awhile to figure it out :) Thank you.

**Comment by ccoossdddffdd** [comment]
https://gist.github.com/cosnis/7657065

this is my new code to do this work.

i need to add a timer to close the change_lock when file & dir change

beacuse i use UV_FS_EVENT_RECURSIVE mode, and when file change, the dir change event is called too.

so if you can separate the two event, or stop call dir change event when file change,  it be better.
