### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by ccoossdddffdd** [joyent/libuv#1014]
...
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure: line 12274: syntax error near unexpected token `;'
./configure: line 12274:`; then'

i have this report when ./configure command, i tried lastest version from git, and v0.11.9.

this is the system info, is a virtual machine

[root@localhost libuv-v0.11.9]# cat /etc/issue
CentOS release 6.4 (Final)
Kernel \r on an \m

**Comment by saghul** [comment]
What autoconf version are you using? That error sounds familiar, it was caused by tan old versión of autoconf.

**Comment by JacksonTian** [comment]
What python version are you using? 2.7 please.

**Comment by saghul** [comment]
The Python version is not relevant when running ./configure

**Comment by ccoossdddffdd** [comment]
[root@localhost libuv]# autoconf -V
autoconf (GNU Autoconf) 2.63
Copyright (C) 2008 Free Software Foundation, Inc.

this is the autoconf version

and i use  Python 2.7.6 (default, Nov 27 2013, 17:13:51)

**Comment by saghul** [comment]
I got a similar problem with Autoconf 2.61, which also dates from 2008. Updating to 2.69 fixed the problem.

**Comment by ccoossdddffdd** [comment]
oh my god..... 

does libuv have some yum repo to install?

**Comment by saghul** [comment]
Not that I know of. You can use gyp to build it instead of autoconf though, instructions on the README.

**Comment by ccoossdddffdd** [comment]
ok......
