### ISSUE TITLE
question about uv_spawn

### ISSUE THREAD

**Issue by ccoossdddffdd** [joyent/libuv#1020]
i have made a child process by uv_spawn

and now when i kill the father process, the child process still live..

i want kill the child process when i kill the father process.

i use uv_process_kill to kill child process.

and i doesn't use UV_PROCESS_DETACHED flag.

**Comment by saghul** [comment]
Please use the mailing list (https://groups.google.com/forum/#!forum/libuv) for questions. If you find an issue, feel free to open it here though.
