### ISSUE TITLE
stream: create API for immediate writes

### ISSUE THREAD

**Issue by indutny** [joyent/libuv#1025]
`uv_write()`/`uv_write2()` may write data immediately on unixes, but it'll still queue up `uv_write_t` request and execute callback later. Its good for the most of the uses, but I'd like to propose API for handling immediate writes in user code and canceling queuing of the callback.

The few reasons for it:
- https://github.com/indutny/bud/commit/71ce128ac2a463c5e3334b27ce43dad3b05d4da8
- https://github.com/joyent/node/blob/master/lib/net.js#L659-L661

So having this API will allow us to eliminate allocations in node and other projects.

It could be something like this:

``` C
int uv_write_is_complete(uv_write_t* req);
int uv_write_finish(uv_write_t* req);
```

First one will return `1` if data was written to the socket and `0` otherwise.
Second one will execute request callback and remove request from the internal queue, so it could be reused by app.

**Comment by indutny** [comment]
@saghul @piscisaureus thoughts?

**Comment by indutny** [comment]
I know that it is most likely not case for windows, so we can make `uv_write_finish` return error on it unconditionally.

**Comment by saghul** [comment]
Hum, I tried to understand why you would need this, but it's still not very clear to me :-) Even if the write happens immediately you already allocated a uv_write_t struct which was passed to uv_write, right? On Unixes, if the request wasn't sent on the spot, no more malloc-ing is necessary if less than 4 buffers were used (https://github.com/joyent/libuv/blob/master/src/unix/stream.c#L1251-L1253) so the difference is that the callback is called on the next tick, right?

I guess I'm missing something obvious here, can you elaborate a bit please? :-)

**Comment by indutny** [comment]
Well, I'm mallocing it now. But it could be embedded in other struct if I'd be able to ask libuv to not call write_cb and dequeue `uv_write_t`.

**Comment by saghul** [comment]
Ah, I get you now. What about

```
int uv_try_write(uv_write_t* req);
```

or

```
int uv_try_write(uv_stream_t* stream, uv_buf_t* bufs, int bufcnt);
```

The idea being that a write is attempted and if it fails the request is dequeued. In the second form no callback would be called, it would be up to you. Internally, a stack allocated request could be used.

**Comment by indutny** [comment]
Hm... sounds like it would duplicate a lot of logic. I'm not totally against allocation, just want the `uv_write_t` to be reused. Any objections about API mentioned above?

Perhaps, we could just change naming here to make it reflect the process. What about `uv_write_dequeue()` instead of `uv_write_finish()`?

**Comment by saghul** [comment]
The idea would be not to duplicate logic. The functions you propose would exist, but they wouldn't be part of the public API, they'd be internal, only used on this uv_try_write thing.

**Comment by indutny** [comment]
So `uv_try_write(req)` would return 0 if write has happened immediately, right? And, let's say, UV_EINPROGRESS otherwise. Does it LGTY?

**Comment by saghul** [comment]
Not sure about what the return value in case of error should be, given that the request will be queued. EINPROGRESS could be a bit misleading, because it's not really in progress, you need to call uv_write yourself for that... maybe EAGAIN?

**Comment by indutny** [comment]
Yeah, looks good. So, just to make sure, the sequence is following:
1. `uv_write(req, stream ....)`
2. `uv_try_write(req)`
3. reuse `req` if (2) was successful

**Comment by saghul** [comment]
Hum, not really :) The sequence would be:
1. `uv_try_write(req)` with embedded struct request
2. If it returns 0, we are done!
3. else, malloc, uv_write(req) as usual

**Comment by indutny** [comment]
Hm... that'll mean that user will need to initialize request twice... perhaps, it is ok. So how do you imagine using `uv_try_write(req)` without `stream` and other arguments.

**Comment by saghul** [comment]
Oh, sorry, I forgot half of it :-(

```
int uv_try_write(uv_write_t* req,
                            uv_stream_t* handle,
                            const uv_buf_t bufs[],
                            unsigned int nbufs);
```

So, uv_try_write is essentially uv_write, but doesn't queue the request if it fails to write it. If it fails you can either reuse the request, malloc a new one or whatever.

In pseudocode, using the api you proposed, uv_try_write would be:

```
int uv_try_write(uv_write_t* req,
                            uv_stream_t* handle,
                            const uv_buf_t bufs[],
                            unsigned int nbufs) {

int r;

r = uv_write(req, handle, bufs, nbufs, NULL);
if (r!= 0)
    return r;
if (uv_write_is_complete(req) {
    return uv_write_finish(req);
}
return UV_EAGAIN;
}
```

I'm a bit uncertain about the callback argument, I left it out because the function is "blocking" if it succeeds the caller can just call the callback himself.

I hope it's clearer now, half of my brain was asleep before :-)

**Comment by indutny** [comment]
Yeah, LGTM

**Comment by piscisaureus** [comment]
I'm not sure about this... This was suggested by a user to do a micro optimization in node, but it won't be possible to do in windows.

**Comment by indutny** [comment]
@piscisaureus have you seen my pull request? Also it isn't a micro-optimization, it saves a lot of time and memory in bud, since I can just not buffer stuff, because I know that it was already written out.

Anyway, it'd be cool to hear your thoughts on that PR?

**Comment by indutny** [comment]
See PR for the comment.
