### ISSUE TITLE
build fail OS 10.6.8 in ./configure

### ISSUE THREAD

**Issue by skaller** [joyent/libuv#1030]
checking for pthread_mutex_init in -lpthread... yes
checking for clock_gettime in -lrt... no
checking for sendfile in -lsendfile... no
checking for socket in -lsocket... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure: line 11346: syntax error near unexpected token `0.20'
./configure: line 11346:`PKG_PROG_PKG_CONFIG(0.20)'

**Comment by indutny** [comment]
What version of autoconf are you using?

**Comment by saghul** [comment]
Works for me on OSX 10.6.8, but using autoconf 2.69, since the system one is too old: https://github.com/joyent/libuv/issues/851

**Comment by tjfontaine** [comment]
fwiw it's broken for all unix build slaves as well

http://jenkins.nodejs.org/job/libuv-master/374/

**Comment by indutny** [comment]
@tjfontaine I'm quite sure it is autoconf dependent thing, @saghul perhaps we should revert that change?

**Comment by saghul** [comment]
@tjfontaine I just tested it on my Linux machine and works here as well. Do the build slaves have the `pkg-config` package installed?

**Comment by tjfontaine** [comment]
it's possible they don't, but that's a fairly obtuse error if so, we should do a feature test for pkg-config first

**Comment by saghul** [comment]
Lets see if https://github.com/joyent/libuv/pull/1034 fixes it

**Comment by saghul** [comment]
This was "fixed" already. pkg-config is no longer an issue, but a new version of autoconf is required, the one on 10.6 is ancient.
