### ISSUE TITLE
Wrong compiler options by configure

### ISSUE THREAD

**Issue by skaller** [joyent/libuv#1031]
OSX 10.6.8 with gcc (it should be using clang .. but anyhow) xcodebuild:

/Users/johnskaller/felix/libuv/test/echo-server.c:222: warning: dereferencing type-punned pointer will break strict-aliasing rules

I have a lot of these. You need -fno-strict-aliasing. This is mandatory if you're really doing any typepunning, otherwise you can definitely get a crash from bad code generation. In fact the xcodebuild says -fstrict-aliasing, the opposite of what would be required if you're actually doing type punning.

I didn't see any of these with the autotools build.

**Comment by indutny** [comment]
I don't think we're in danger with it, since we usually don't have alias and pointer in the same scope. Having this in test is most likely ok, and I don't want to disable hard compiler optimizations because of this.

Please feel free to reopen this if you feel that this really breaks anything.

**Comment by indutny** [comment]
Thank you for reporting!
