### ISSUE TITLE
Best approach for parsing a simple RPC protocol

### ISSUE THREAD

**Issue by tarruda** [joyent/libuv#1033]
Hi

I'm writing a small program that reads messages from a stream, where each message is started by a 32bit integer, which specifies the size of the following message.

I understand libuv will call my own function to allocate buffers with a suggested size, but since I know the size of the incoming message, I'd like to use that as the buffer size.

What would be the 'pretty' way to handle this in libuv? I would rather not use global variables to store the size of the next message.

**Comment by indutny** [comment]
Sorry, but this isn't a place for such questions. Better try asking on a mailing list: https://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CCcQFjAA&url=https%3A%2F%2Fgroups.google.com%2Fd%2Fforum%2Flibuv&ei=UsGkUsD6A4bV4gSrr4DwBg&usg=AFQjCNGiLHBurHfvcNoz0rVf4jm9ftFn4w&sig2=yU556kPDv-osafMAOhtttg&bvm=bv.57752919,d.bGE&cad=rja
