### ISSUE TITLE
Wrong option -DPIC passed to compiler (autoconf)

### ISSUE THREAD

**Issue by skaller** [joyent/libuv#1035]
Passing -DPIC does nothing. The correct option is -fpic or -fPIC.

**Comment by skaller** [comment]
Data:

checking for clang option to produce PIC... -fno-common -DPIC
checking if clang PIC flag -fno-common -DPIC works... yes

**Comment by indutny** [comment]
Hm... I can't see it anywhere in our files, perhaps it is an autoconf's thing?

**Comment by saghul** [comment]
Yes, it's an autoconf thing, it probes and apparently decided that -DPIC is the right thing to do. What autoconf version are you using @skaller?

**Comment by skaller** [comment]
Sorry it so long to realise there was a message here to answer (I had GitHub pointing at my gmail account which I never use)

~/felix>autoconf --version
autoconf (GNU Autoconf) 2.69

**Comment by saghul** [comment]
Does it create any problem for you? Since autoconf seems to add it, I don't see what we can do here...
