### ISSUE TITLE
get_free_memory does not include cached memory

### ISSUE THREAD

**Issue by soumith** [joyent/libuv#1038]
When trying to determine the amount of usable memory on the system, just using 
get_free_memory does not suffice, as get_free_memory does not include the amount of cached memory.

get_total_memory - get_free_memory != total malloc-able memory

**Comment by indutny** [comment]
Which platform are we talking about? Linux, osx, windows?

**Comment by soumith** [comment]
I've tested this on Linux, more specifically Ubuntu 13.10 64-bit, but I believe it generally applies to linux.

**Comment by soumith** [comment]
Relevant outputs for cat /proc/meminfo 
MemTotal:       16401056 kB
**MemFree:          291932 kB**
Buffers:         1513496 kB
**Cached:          8338624 kB**
SwapCached:        94980 kB
Active:          7457824 kB
Inactive:        5767792 kB
Active(anon):    3173292 kB
Inactive(anon):   276640 kB
Active(file):    4284532 kB
Inactive(file):  5491152 kB

If you see, free memory reported is only 290MB, but there is 8.3GB of cached memory, which is mallocable and ready to be used.

**Comment by indutny** [comment]
I think the behavior of `uv_get_free_memory` is totally correct there, since it returns amount of free physical pages, reported by system.

I think it'd be incorrect to assume that in _every_ situation Page Cache could be reduced to free memory. @saghul do you have any thoughts about it?

**Comment by tjfontaine** [comment]
if people want more platform specific information they're free to open `/proc` and inspect it themselves, imo

**Comment by indutny** [comment]
@tjfontaine ok, glad to see anyone on my side :) Because I wasn't totally sure about it. Sorry, that is won't fix!

**Comment by soumith** [comment]
no problem, thanks for responding. 
I've implemented my own /proc workaround, it was more of an "if someone finds this annoying and comes to report it" kind of an issue.
