### ISSUE TITLE
Worker thread/queue health check?

### ISSUE THREAD

**Issue by pixelglow** [joyent/libuv#1042]
In libuv, you can end up tying up the worker threads with too much work or buggy code. Is there a simple function that can check the health of the worker threads or thread queue? It doesn't have to be 100% deterministic, after all it would be impossible to determine whether the worker thread is hanging on slow code or an infinite loop.

So any of the following heuristics would be good:
- Number of queued items not yet worked on. If this is too large, it could mean the worker threads are busy or hung.
- Does libuv have any thread killing mechanism where if the worker thread doesn't check back in n seconds, it gets terminated?

**Comment by saghul** [comment]
Are you referring the to the threadpool and `uv_queue_work` here? Not sure what you mean by "worker thread/queue".

In case you are referring to `uv_queue_work`, there is currently no way to kill any thread. There is also no way for checking the queued requests, other than digging into the loop struct and looking for requests of type `UV_WORK`: https://github.com/joyent/libuv/blob/master/include/uv.h#L2082

That field should probably be marked as private, so I wouldn't rely on it too much.

**Comment by pixelglow** [comment]
Thanks for that. Otherwise than performing the work itself and checking with a timer to see if it completed, it looks like there's no public way to determine if the worker threads are too busy.

**Comment by saghul** [comment]
As a final note: currently the threadpool is limited to 4 threads, which are also used for running the fs operations and getaddrinfo, so running too much work on it may impact performance of the aforementioned oeprations.

**Comment by pixelglow** [comment]
hmmm… do you not scale the thread pool to the number of cores?

**Comment by saghul** [comment]
Not at the moment.

**Comment by pixelglow** [comment]
Can you tell me roughly where the code is, so I can hack a version which scales the thread pool?

**Comment by sam-github** [comment]
Set UV_THREADPOOL_SIZE in env (on unix) to set thread pool size to a specific number, grep src for that env variable to see where libuv would scale to number of cores.

**Comment by saghul** [comment]
Doh, my (email) reply to this was lost somewhere :-/ You can check the Unix implementation in src/unix/threadpool.c, and use the env variable as mentioned by @sam-github. Note that regardless of the value you set through the env variable, it's capped at 128.
