### ISSUE TITLE
Remove unused tags.

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1049]
It would help browing if some tags could get removed.

multiplicity2/multiplicity3 is no longer relevant as it was used to add multiple loop support for libuv, which is already a core feature.

**Comment by indutny** [comment]
Thanks, done.

**Comment by txdv** [comment]
I mean like going through all the branches and removing the once who are obsolete/older than 5 months

**Comment by indutny** [comment]
@txdv do you want to help us with this? ;)

**Comment by txdv** [comment]
I don't have repo access and if I say something you still have to check it up yourself: blocking-pipes, c-ares, cleanup-gyp-build, dlopen, emfile_trick, file_watcher, fs, fs_link, ipc, ipc2, ipc-listen can get removed. They are really old.

Do wee need cpp-ify? I don't see the benefits of the one change in that branch.

What does funnel do?

**Comment by txdv** [comment]
@indutny please create topic branches in your own repository instead of creating branches in joyent/libuv. saghul does it like that and it is a good way to do it. people tend to forget to delete the branches and it is just clutter which is not really useful when a user is inspecting the repository. Look at how many branches we already have which are older then half a year because Igor forgot to delete them and nobody is deleting them now because it is "useless" work which doesn't really improve the lib itself.

It isn't useless, people who look into the project will appreciate a good branch structure.

Main repo should only have stable, unstable(master) branches. The current tagging mechanism is very good and specifies versions so I don't think we need a branch for every major version.

**Comment by indutny** [comment]
I did it only for one thing recently. But yes, I agree with you.

**Comment by txdv** [comment]
We still have 51 branches.

Please just remove every topic branch which are older than 1 year from the main repo. 90% of them are by piscisaureus and bnoordhuis and they won't be looking into them ever again.

**Comment by saghul** [comment]
I've been pruning them slowly, I'll get to just 3.

**Comment by txdv** [comment]
https://github.com/joyent/libuv/branches/all

35 branches are > 1k commits behind

**Comment by saghul** [comment]
I know. There is just som much time in a day, sorry.

**Comment by txdv** [comment]
One branch a day keeps the clutter away.

**Comment by saghul** [comment]
On 06/26/2014 02:33 PM, Andrius Bentkus wrote:

> One brunch a day keeps the clutter away.

Down to 45!

**Comment by txdv** [comment]
Down to 29.

Keep going, you are strong @saghul

**Comment by txdv** [comment]
We are at 15, now a person can with one simple look overview all the branches.

**Comment by saghul** [comment]
We are down to 10 now. I'm going to close this and leave it like that for the time being. Yes, some of those branches are old, but they contain some experiments I might want to look at some time :-) Also 10 is not that bad!
