### ISSUE TITLE
Error-checking cast macros for uv_*_t types

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#105]
Proposal:

``` c
#ifndef DEBUG

#define UV_AS_TCP(p) ((uv_tcp_t*)p)
#define UV_AS_TIMER(p) ((uv_timer_t*)p)
/* etc. */

#else

inline static void* uv__type_check(void* p, uv_handle_type type) {
  assert(((uv_handle_t*)p)->magic_header == 0xDEADBEEF);
  assert(((uv_handle_t*)p)->type == type);
  return p;
}

#define UV_AS_TCP(p) ((uv_tcp_t*)uv__type_check(p, UV_TCP))
#define UV_AS_TIMER(p) ((uv_timer_t*)uv__type_check(p, UV_TIMER))
/* etc. */

#endif
```

**Comment by DrPizza** [comment]
Relatedly (insofar as it's related to trapping type errors), it would IMO be nice if the handle types had an actual inheritance hierarchy when uv.h is included in C++ programs, so that certain safe conversions were implicit (e.g. passing a `uv_stream_t*` to `uv_close()`).

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
