### ISSUE TITLE
Fail to start fsevent handle if inotify doesn't support the filesystem?

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1054]
How about doing something similar to what libev does?

On uv_fsevent_start we check if the filesystem is supported by inotify, else return ENOTSUP.

```
3965          else if (!statfs (w->path, &sfs)
3966                   && (sfs.f_type == 0x1373 /* devfs */
3967                       || sfs.f_type == 0x4006 /* fat */
3968                       || sfs.f_type == 0x4d44 /* msdos */
3969                       || sfs.f_type == 0xEF53 /* ext2/3 */
3970                       || sfs.f_type == 0x72b6 /* jffs2 */
3971                       || sfs.f_type == 0x858458f6 /* ramfs */
3972                       || sfs.f_type == 0x5346544e /* ntfs */
3973                       || sfs.f_type == 0x3153464a /* jfs */
3974                       || sfs.f_type == 0x9123683e /* btrfs */
3975                       || sfs.f_type == 0x52654973 /* reiser3 */
3976                       || sfs.f_type == 0x01021994 /* tmpfs */
3977                       || sfs.f_type == 0x58465342 /* xfs */))
```

Thoughts?

/cc @indutny

**Comment by indutny** [comment]
Won't `uv__inotify_add_watch` fail in such cases?

**Comment by saghul** [comment]
Not sure, AFAIK it doesn't, it just won't get notified ever. @bnoordhuis maybe you can confirm?

**Comment by indutny** [comment]
Well, if this is the case... Ok.

**Comment by bnoordhuis** [comment]
I consider that check in libev an anti-feature: it excludes a lot of less common file systems that nevertheless perfectly support file notifications.  If you want to go down that route, you should blacklist known-broken file systems, like NFS (0x6969, see statfs(2) or linux/magic.h.)

**Comment by saghul** [comment]
Thanks Ben, xlosing then.
