### ISSUE TITLE
Preserve uv_write_t->bufs in uv_write()

### ISSUE THREAD

**Issue by unixwitch** [joyent/libuv#1059]
When the uv_write() callback is called, req->bufs has been set to NULL by uv__write_req_finish.  To avoid the user having to track the buffers separately, it would be useful if this value could be preserved.

I understand this might be complicated or impossible to do efficiently with the need to free(req->bufs) when nbufs > 4 (so bufs != bufsml).

**Comment by txdv** [comment]
https://github.com/joyent/libuv/blob/master/src/unix/stream.c#L677

**Comment by saghul** [comment]
libuv will just copy the pointers, it's the responsibility of the caller to free the memory and keep track of them. You can attach whatever you want to `req->data` and use it in the write callback.

**Comment by unixwitch** [comment]
Yep, but then this requires an additional malloc(): https://github.com/rtarnell/nts/commit/deefb9391afe95ecfe6655509f34651ef8057052

It's not a serious problem, just seems like something that would be useful to users.

**Comment by bnoordhuis** [comment]
You can embed the uv_write_t in another struct and use a container_of-like macro to look up the embedder.  Grep the libuv source tree for container_of examples and its definition.

**Comment by indutny** [comment]
Ok, I guess it is not a big concern, consider that you have `req->data` and can do any of mentioned things above.
