### ISSUE TITLE
fork() semantics

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#106]
How do we handle `fork()`? More specifically, should or should we not mark all file descriptors used by libuv as close-on-exec?

Open file descriptors survive `execve()` so not setting close-on-exec may leak information to the new process (bad).

Opinions?

**Comment by ry** [comment]
i think we should set closexec on our FDs - this is what's happening in node

**Comment by bnoordhuis** [comment]
Fixed.
