### ISSUE TITLE
win/tcp.c ,unsigned type value is never <0 ?

### ISSUE THREAD

**Issue by erehw** [joyent/libuv#1061]
since uv_active_tcp_streams_threshold is 0
and    active_tcp_streams is unsigned type                                            

const unsigned int uv_active_tcp_streams_threshold = 0;
unsigned int active_tcp_streams ;

so function "uv_tcp_queue_read"
line of 422
if (loop->active_tcp_streams < uv_active_tcp_streams_threshold) {
how to explain?

**Comment by saghul** [comment]
Please check the comments here: https://github.com/joyent/libuv/blob/master/src/win/tcp.c#L32-L37 The threshold used to be set to 50 but was disabled by https://github.com/joyent/libuv/commit/4e9edceb980401d92d45710a07b00872b430fd12
