### ISSUE TITLE
Instructions on compiling for OSX should include being careful about architecture selection for xcodebuild

### ISSUE THREAD

**Issue by nathanjsweet** [joyent/libuv#1065]
The current, free, version of xcode automatically builds for an i386 architecture. By simply adding ARCHS="x86_64" right after the "xcodebuild" command the headache of linking an invalid static library will be avoided. This took me a few hours to figure out how to do, because xcodebuild's documentation is scattered.

https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/64bitPorting/building/building.html#//apple_ref/doc/uid/TP40001064-CH208-BCGECFEJ

The xcodebuild command should look like this:

```
xcodebuild ARCHS="xxxx" -project uv.xcodeproj -configuration Release -target All
```

where ARCHS is the architecture(s) you wish to build for (you can build for multiple architectures simply by adding a space in the string, e.g. "x86_64 i386").

I really do think this will save people time.

**Comment by indutny** [comment]
Thank you! I'd merge pull request if you wish to open one, but don't have time to work on it myself.
