### ISSUE TITLE
SO_PEERCRED on Pipes

### ISSUE THREAD

**Issue by geertj** [joyent/libuv#1066]
Any advice on how I can get access to getsockopt(SO_PEERCRED) on Pipes (I know it's Unix specific)? There seems to be no way to get the file descriptor from a stream type.

**Comment by saghul** [comment]
Hi @geertj, you'd be dealing with the internals here, so this could change and break your code, but if you are willing to take the risk, you can get it as follows:

```
fd = ((uv_stream_t*)handle)->io_watcher.fd;
```

**Comment by geertj** [comment]
Thanks @saghul. Let me mull on that for a bit. I need this from Python so it's going to be harder still. I won't have access to the libuv headers that were used to compile pyuv.

Would this be an API that could be added to libuv? I'm not sure if Windows has a similar concept.

**Comment by saghul** [comment]
Windows has `HANDLE` things, but libuv won't expose the underlying fd or handle on streams, IIRC this was decided from the beginning and an API exposing those won't be accepted.

What you can do, is create a `socket.socket` yourself and use `Pipe.open` on it (on `sock.fileno() really). You can attach it to the pipe to have access to it a la`pipe._sock`and then get the fd with`pipe._sock.fileno()` when you need to.
