### ISSUE TITLE
test/simple/test-net-server-on-fd-0 obsolete?

### ISSUE THREAD

**Issue by HenryRawas** [joyent/libuv#107]
This test assumes that server has a property called fd and it has a value 0.
So far in net_uv this does not exist. It is easy to add this property and make the test pass.
I would rather remove the test unless there is a plan to support a fd property that has some meaning.

**Comment by bnoordhuis** [comment]
That test checks for the issue reported [here](https://github.com/joyent/node/issues/746) but that's not applicable to libuv since net.Server doesn't operate on raw file descriptors any more.

Henry, do you test with `make test` or `make test-uv`? The latter skips that test.

**Comment by HenryRawas** [comment]
I am trying to add to the list of tests in test-uv by fixing the non-working tests.

**Comment by bnoordhuis** [comment]
You can skip this one, it tests an implementation detail of the old back end.

**Comment by piscisaureus** [comment]
No longer relevant. Closing.
