### ISSUE TITLE
API - Need an advise

### ISSUE THREAD

**Issue by migounette** [joyent/libuv#1070]
Three quick questions for libuv developers (I will format and add answers to the wiki :))

What it is the more efficient for timers...
1. Suppose that you have 500 sessions in // for STUN operations.
   A timer is needed for sending stun operation.

What is the best, create a global timer (a session list) or one timer handle per session and queue them
1. Re transmission in UDP
   I want to re transmit a packet every 20ms if no answer is received.
   Which paradigm to use ?
2. Threading
   When the system has a lot of handles, what is the best for a proxy operation

A <--> Proxy <--> B

One thread for receiving, one thread for sending ? a unique loop or different loops ?

Thanks for your lights, I didn't find answers via Google or via the nice book written that gives nice examples but not for mass operations.

**Comment by indutny** [comment]
Sorry, please use mailing list. This is an issue tracker
