### ISSUE TITLE
Grand Central Dispatch vs. Queuing + Thread Pooling on OS X / iOS

### ISSUE THREAD

**Issue by srijs** [joyent/libuv#1073]
On modern OS X and iOS platforms there exists a high-performance queuing and thread pooling mechanism called [Grand Central Dispatch](https://developer.apple.com/library/mac/documentation/performance/reference/gcd_libdispatch_ref/Reference/reference.html).

This mechanism is integrated deeply into the OS and therefore provides an advantage over a user-land thread pooling by having more information about currently available resources as well as overall system load.

There exist a few benchmarks backing that up. Especially, in a web server context, see: http://deusty.blogspot.de/2010/11/introducing-gcd-based-cocoahttpserver.html
The graphs can be found [here](http://web.archive.org/web/20120528015450/http://deusty.com/blog/CocoaHTTPServer/benchmark_macbookAir.png) and [here](http://web.archive.org/web/20120528015451/http://deusty.com/blog/CocoaHTTPServer/benchmark_zoom_macbookAir.png).

Would there be interest in merging a GCD-based threadpool.c implementation for iOS/OS X platforms, when I implemented it?

**Comment by indutny** [comment]
+1 from me. And @saghul is on a vacation, but I don't think that it should stop you from working on it, if you wish.

**Comment by saghul** [comment]
Sure, feel free to open a PR with it when ready!
