### ISSUE TITLE
uv_spawn won't duplicate the same original fd to two fds in the child

### ISSUE THREAD

**Issue by sam-github** [joyent/libuv#1074]
Instead, it results in the child not having a valid fd at that position.

Reproduceable in node with https://gist.github.com/sam-github/8341916

strace shows what's happening in child: https://gist.github.com/sam-github/8341573

This results in fd 2 in child not being valid (an unusual condition, which libuv tries to avoid). The invalidity causes and write to fd 2 (console.error in node), to cause node to terminate (seemingly silently, its probably trying to write a stack trace, but since that would go to stderr, that doesn't work so well).

**Comment by indutny** [comment]
Should be fixed by https://github.com/joyent/libuv/pull/1083 , please verify.
