### ISSUE TITLE
uv_tcp_getpeername with Windows IPv6 Client

### ISSUE THREAD

**Issue by stakach** [joyent/libuv#1075]
When calling uv_tcp_getpeername for an IPv6 TCP client on Windows I'm getting the following error response: `bad address in system call argument`

Works fine with IPv4 clients on Windows and IPv6 works on unix platforms

**Comment by saghul** [comment]
Can you provide a failing test? I think the test suite does use ipv6 as a client.

**Comment by stakach** [comment]
Seems to no longer be a problem!

**Comment by saghul** [comment]
Kewl, thanks!
