### ISSUE TITLE
uv__fs_event_rearm return codes are ignored

### ISSUE THREAD

**Issue by joshwilsdon** [joyent/libuv#1078]
I ran into a problem where fs.watch would pretend to be watching a file when the port_associate call was actually returning ENOENT. The reason appears to be:

https://github.com/joyent/libuv/blob/6149b66ccb9998f561a207162195bf5cba647280/src/unix/sunos.c#L415

is not checking the return value from uv__fs_event_rearm() even though that should have returned the errno from the failed port_associate().

**Comment by indutny** [comment]
May I ask you to give a try to https://github.com/joyent/libuv/pull/1082 ?
