### ISSUE TITLE
linux-core: too strict assumption on /proc/stat parsing

### ISSUE THREAD

**Issue by lucab** [joyent/libuv#1080]
In the Debian build machine park we have an [UltraSparc II box (U60)](https://db.debian.org/machines.cgi?host=spontini) with the following `/proc/stat`:

```
$ cat /proc/stat
cpu  29733059 2644 2838265 32944962 2338973 15558 52150 0 0
cpu0 14908964 1765 1494903 15699901 1739345 15558 37979 0 0
cpu2 14824094 879 1343361 17245060 599627 0 14171 0 0
intr 147091428 134883696 0 0 0 0 0 0 901 14 6 0 2 0 0 7559720 2709164 1937925 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 185951785
btime 1389833870
processes 2239487
procs_running 1
procs_blocked 0
softirq 279821254 0 122089522 1415859 6656126 4202387 0 465 20866767 4418 124585710
```

This is tripping the assert at https://github.com/joyent/libuv/blob/v0.10/src/unix/linux-core.c#L606 which is expecting the `cpuX` in linear progression, and barking due to the missing `cpu1`. An example of it is the [libuv-0.10.22 testsuite failing](https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=sparc&ver=0.10.22-1&stamp=1390147318).

Not sure about your preferred solution, but we can either: 
1. skip /proc/stat when such weirdness appears (returning instead of asserting)
2. relax the assumption and just parse `numcpus` entries after the first one

**Comment by lucab** [comment]
With proposed patch, libuv is now building fine on the same machine and all tests are passing:
https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=sparc&ver=0.10.22-2&stamp=1390218210

**Comment by bnoordhuis** [comment]
For posterity: this issue was fixed in commit 993151bc, authored by @lucab and committed by that illusive maintainer called 'root'...

**Comment by indutny** [comment]
Hahahaha :)

**Comment by lucab** [comment]
Sorry, I closed it as I saw the linked PR merged and this issue still open...
