### ISSUE TITLE
Linker errors on Windows VS2012 VC11.0

### ISSUE THREAD

**Issue by sasmaster** [joyent/libuv#1089]
Hi.I have downloaded the lib and compiled it wti VC++ 11.0 on Windows.When linking to my project I am getting multiple link errors.The same happens if I set compiler to VC10.0

**Comment by indutny** [comment]
Hi! What link errors do you get?

**Comment by sasmaster** [comment]
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__htonl@4 referenced in function _uv_interface_addresses
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__htonl@4
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol _GetAdaptersAddresses@20 referenced in function _uv_interface_addresses
1>libuv.lib(util.obj) : error LNK2019: unresolved external symbol _GetProcessMemoryInfo@12 referenced in function _uv_resident_set_memory
1>libuv.lib(winsock.obj) : error LNK2019: unresolved external symbol __imp__closesocket@4 referenced in function _uv_winsock_init
1>libuv.lib(core.obj) : error LNK2001: unresolved external symbol __imp__closesocket@4
1>libuv.lib(tcp.obj) : error LNK2001: unresolved external symbol __imp__closesocket@4
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__closesocket@4
1>libuv.lib(poll.obj) : error LNK2001: unresolved external symbol __imp__closesocket@4
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__bind@12 referenced in function _uv_tcp_try_bind
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__bind@12
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__ioctlsocket@12 referenced in function _uv_tcp_set_socket
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__ioctlsocket@12
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__getpeername@12 referenced in function _uv_tcp_getpeername
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__getsockname@12 referenced in function _uv_tcp_getsockname
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__getsockname@12
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__getsockopt@20 referenced in function _uv_tcp_open
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__getsockopt@20
1>libuv.lib(poll.obj) : error LNK2001: unresolved external symbol __imp__getsockopt@20
1>libuv.lib(winsock.obj) : error LNK2001: unresolved external symbol __imp__getsockopt@20
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__listen@8 referenced in function _uv_tcp_listen
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__setsockopt@20 referenced in function _uv_process_tcp_accept_req
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__setsockopt@20
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__shutdown@8 referenced in function _uv_tcp_close
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__socket@12 referenced in function _uv_tcp_try_bind
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__socket@12
1>libuv.lib(winsock.obj) : error LNK2001: unresolved external symbol __imp__socket@12
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSAGetLastError@0 referenced in function _uv_tcp_getsockname
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__WSAGetLastError@0
1>libuv.lib(poll.obj) : error LNK2001: unresolved external symbol __imp__WSAGetLastError@0
1>libuv.lib(winsock.obj) : error LNK2001: unresolved external symbol __imp__WSAGetLastError@0
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSADuplicateSocketW@12 referenced in function _uv_tcp_duplicate_socket
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSAIoctl@36 referenced in function _uv_tcp_try_cancel_io
1>libuv.lib(poll.obj) : error LNK2001: unresolved external symbol __imp__WSAIoctl@36
1>libuv.lib(winsock.obj) : error LNK2001: unresolved external symbol __imp__WSAIoctl@36
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSARecv@28 referenced in function _uv_process_tcp_read_req
1>libuv.lib(udp.obj) : error LNK2001: unresolved external symbol __imp__WSARecv@28
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSASend@28 referenced in function _uv_tcp_write
1>libuv.lib(tcp.obj) : error LNK2019: unresolved external symbol __imp__WSASocketW@24 referenced in function _uv_tcp_import
1>libuv.lib(poll.obj) : error LNK2001: unresolved external symbol __imp__WSASocketW@24
1>libuv.lib(udp.obj) : error LNK2019: unresolved external symbol __imp__inet_addr@4 referenced in function _uv_udp_set_membership
1>libuv.lib(udp.obj) : error LNK2019: unresolved external symbol __imp__WSARecvFrom@36 referenced in function _uv_udp_init
1>libuv.lib(udp.obj) : error LNK2019: unresolved external symbol __imp__WSASendTo@36 referenced in function _uv__send
1>libuv.lib(poll.obj) : error LNK2019: unresolved external symbol __imp__select@20 referenced in function _uv__slow_poll_thread_proc@4
1>libuv.lib(getaddrinfo.obj) : error LNK2019: unresolved external symbol __imp__GetAddrInfoW@16 referenced in function _getaddrinfo_thread_proc@4
1>libuv.lib(getaddrinfo.obj) : error LNK2019: unresolved external symbol __imp__FreeAddrInfoW@4 referenced in function _uv_process_getaddrinfo_req
1>libuv.lib(winsock.obj) : error LNK2019: unresolved external symbol __imp__WSAStartup@8 referenced in function _uv_winsock_init
1>libuv.lib(winsock.obj) : error LNK2019: unresolved external symbol __imp__WSASetLastError@4 referenced in function _uv_wsarecv_workaround@28
1>libuv.lib(uv-common.obj) : error LNK2019: unresolved external symbol __imp__htons@4 referenced in function _uv_ip4_addr

**Comment by sasmaster** [comment]
Should I open some specific macros before compiling ?

**Comment by indutny** [comment]
No, I think that you should just link with `ws2_32.lib` in your project. (from msdn forum: `Add in Project Properties>Linker>Input>Additional Dependences Ws2_32.lib`).

**Comment by sasmaster** [comment]
Not so soon :)  Added the 
Now getting these:

Error   17  error LNK2019: unresolved external symbol _GetAdaptersAddresses@20 referenced in function _uv_interface_addresses   E:\Documents\visual studio 2012\Projects\XXXX\XXXX\libuv.lib(util.obj)

Error   18  error LNK2019: unresolved external symbol _GetProcessMemoryInfo@12 referenced in function _uv_resident_set_memory   E:\Documents\visual studio 2012\Projects\XXXX\XXXXX\libuv.lib(util.obj)

**Comment by indutny** [comment]
Hm... interesting question, how are you compiling it? :) Using `vcbuild.bat` ?

I would strongly suggest you to use it, but if you can't or do not want to, here is the list of all libraries:

```
              '-ladvapi32.lib',
              '-liphlpapi.lib',
              '-lpsapi.lib',
              '-lshell32.lib',
              '-lws2_32.lib'
```

**Comment by sasmaster** [comment]
Yeah,compiled with vcbuild.bat. Now added

#pragma comment(lib, "IPHLPAPI.lib")  #pragma comment(lib, "Psapi.lib")

And it compiles.

On Sun, Jan 26, 2014 at 3:03 PM, Fedor Indutny notifications@github.comwrote:

> Hm... interesting question, how are you compiling it? :) Using vcbuild.bat?
> 
> I would strongly suggest you to use it, but if you can't or do not want
> to, here is the list of all libraries:
> 
> ```
>           '-ladvapi32.lib',
>           '-liphlpapi.lib',
>           '-lpsapi.lib',
>           '-lshell32.lib',
>           '-lws2_32.lib'
> ```
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/1089#issuecomment-33316272
> .

## 

Michael Ivanov
Independent Pixel Commander
onlygraphix.com
Tel:+972 54 4962254

**Comment by indutny** [comment]
That's very odd, but since I am not a windows guy - I don't care :) /cc @piscisaureus

**Comment by sasmaster** [comment]
Yeah,that's what Linux guys usually say (or maybe OSX? :P

On Sun, Jan 26, 2014 at 3:31 PM, Fedor Indutny notifications@github.comwrote:

> That's very odd, but since I am not a windows guy - I don't care :) /cc
> @piscisaureus https://github.com/piscisaureus
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/1089#issuecomment-33316804
> .

## 

Michael Ivanov
Independent Pixel Commander
onlygraphix.com
Tel:+972 54 4962254

**Comment by sasmaster** [comment]
Btw,is there libuv independent implementation of uv_hrtime() ?

On Sun, Jan 26, 2014 at 4:04 PM, Michael IV explomaster@gmail.com wrote:

> Yeah,that's what Linux guys usually say (or maybe OSX? :P
> 
> On Sun, Jan 26, 2014 at 3:31 PM, Fedor Indutny notifications@github.comwrote:
> 
> > That's very odd, but since I am not a windows guy - I don't care :) /cc
> > @piscisaureus https://github.com/piscisaureus
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/1089#issuecomment-33316804
> > .
> 
> ## 
> 
> Michael Ivanov
> Independent Pixel Commander
> onlygraphix.com
> Tel:+972 54 4962254

## 

Michael Ivanov
Independent Pixel Commander
onlygraphix.com
Tel:+972 54 4962254
