### ISSUE TITLE
libuv doesn't compile on VC++ express

### ISSUE THREAD

**Issue by meegogo** [joyent/libuv#109]
after ares was added，libuv doesn't compile using VCExpress 2010（WIN32）,message after open sln:

C:\Users\meegogo\Desktop\joyent-libuv-9c19391\msvs\libuv.vcxproj : warning  : Platform 'x64' referenced in the project file 'libuv' cannot be found. Please make sure you have it installed under '%VCTargetsPath%\Platforms\x64'.

C:\Users\meegogo\Desktop\joyent-libuv-9c19391\msvs\libuv-test.vcxproj : warning  : Platform 'x64' referenced in the project file 'libuv-test' cannot be found. Please make sure you have it installed under '%VCTargetsPath%\Platforms\x64'.

C:\Users\meegogo\Desktop\joyent-libuv-9c19391\msvs\libuv-benchmark.vcxproj : warning  : Platform 'x64' referenced in the project file 'libuv-benchmark' cannot be found. Please make sure you have it installed under '%VCTargetsPath%\Platforms\x64'.

C:\Users\meegogo\Desktop\joyent-libuv-9c19391\msvs\c-ares.vcxproj : warning  : Platform 'x64' referenced in the project file 'c-ares' cannot be found. Please make sure you have it installed under '%VCTargetsPath%\Platforms\x64'.

error message after trying to build the solution:

The project file ' ' has been renamed or is no longer in the solution

**Comment by entity64** [comment]
I solved the "The project file ' ' has been renamed or is no longer in the solution" problem by deleting the included solution file and creating a new one, adding all projects back. The x64 platform warnings can probably be ignored.

**Comment by meegogo** [comment]
tried,didn't work

**Comment by japj** [comment]
@meegogo there has been a lot of work on the windows build structure, could you try again with latest master tree and confirm if this problem is still reproducable?
