### ISSUE TITLE
`getaddrinfo_fail` failed: exit code 6 Output from process `getaddrinfo_fail`:

### ISSUE THREAD

**Issue by electricface** [joyent/libuv#1090]
# 

`getaddrinfo_fail` failed: exit code 6
Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] 错误 1
make[2]:正在离开目录 `/home/time/libuv-0.11.18'
make[1]: *** [check-am] 错误 2
make[1]:正在离开目录`/home/time/libuv-0.11.18'
make: **\* [check] 错误 2

**Comment by indutny** [comment]
Does `dig xyzzy.xyzzy.xyzzy` success on your machine? Thanks for opening an issue anyway. I'm starting to think about removing this test /cc @saghul

**Comment by saghul** [comment]
I do get spurious failures every now and then, but so far it's not too anoying, lets keep the test around :-)
