### ISSUE TITLE
gyp: define a default value for `library`

### ISSUE THREAD

**Issue by ngryman** [joyent/libuv#1096]
Hey,

It would be nice to define a default value for the `library` variable:

```
'library%': 'static_library'
```

This would avoid to have to type `gyp --depth=. uv.gyp -Dlibrary=static_library` for example.

The reason I'm asking this, is because I'm currently developing a project using `libuv` as a `gyp` dependency.
So my `gyp` file is something like this:

```
...
'dependencies': [
  'deps/libuv/uv.gyp:libuv',
],
...
```

Unfortunately, I don't know if there is a method to tell `gyp` to define your `library` variable in my `gyp`'s scope. Given the fact I just need a static version of `libuv`, If you know how to do this, it could also solve my problem :)

Thanks!

**Comment by indutny** [comment]
Generally I do it in the following way:
- Create `common.gypi`: https://github.com/indutny/bud/blob/master/common.gypi (which contains `library` definition).
- Create `project.gypi`:https://github.com/indutny/bud/blob/master/bud.gyp
- Add `-I common.gypi` to your build line: https://github.com/indutny/bud/blob/master/gyp_bud#L71

I'm not exactly aware of the reasons for this, but if you wish to discuss it - please use a mailing list.
