### ISSUE TITLE
unresolved external symbol _run_test_spawn_fs_open

### ISSUE THREAD

**Issue by pmor13** [joyent/libuv#1098]
Hi libuv team!
I am trying to use libuv for the first time and trying to build it with VS using vcbuild.bat.
During compilation process I have next warnings:

```
src\win\tcp.c(274): warning C4133: 'function' : incompatible types - from 'int *' to 'const char *
test\test-threadpool-cancel.c(89): warning C4244: 'function' : conversion from 'double' to 'uint64_t', possible loss of data
```

But after compilation is done I have the following error:

```
run-tests.obj : error LNK2001: unresolved external symbol _run_test_spawn_fs_open
```

How we can solve it?

**Comment by indutny** [comment]
My mistake, fixed in 280469f . Thank you for reporting it!
