### ISSUE TITLE
Wanted: benchmark executable

### ISSUE THREAD

**Issue by ry** [joyent/libuv#11]
Similar to the test executable (and using the `test/test.h`) to run benchmarks in a cross platform fashion. First bench: max one-way TCP throughput between two sockets.

Want output to be simple and parsable for future CI system.

```
% test/benchmaks.exe
tcp-one-way-throughput  5782
tcp-ping-pong 12343
%
```

**Comment by piscisaureus** [comment]
Closed in 2cbcbdd1a4bdd87827b2 and 53f9d5a8411dc2db0d2c
