### ISSUE TITLE
libuv functions should not clobber errno

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#110]
libuv should be both carbon and errno neutral. Idiom:

```
int uv_foo(uv_handle_t* handle, ...) {
  int saved_errno;
  int status;

  saved_errno = errno;
  status = -1;

  if (foo_syscall(...) == -1) {
    uv_err_new(handle, errno);
    goto out;
  }

  status = 0;

out:
  errno = saved_errno;
  return status;
}
```

**Comment by piscisaureus** [comment]
-1

**Comment by bnoordhuis** [comment]
@piscisaureus motivation!

**Comment by DrPizza** [comment]
Why would one expect `errno`/`GetLastError()` to be preserved in a library such as libuv?

I mean, it's not like anyone is surprised that it's making syscalls, is it?

If the caller is hellbent on having it preserved, the caller can preserve it.

**Comment by bnoordhuis** [comment]
Okay, we're not going to do this. Closing.
