### ISSUE TITLE
unix/tcp.c: uv__tcp_nodelay() returns error code incorrectly

### ISSUE THREAD

**Issue by neoxic** [joyent/libuv#1102]
`uv__tcp_nodelay()` returns `setsockopt()`'s status rather than an error code

https://github.com/joyent/libuv/blob/master/src/unix/tcp.c#L235

which is a problem here:

https://github.com/joyent/libuv/blob/master/src/unix/tcp.c#L265

It should be probably somewhat closer to `uv__tcp_keepalive()`'s semantics instead.

**Comment by saghul** [comment]
Hi! I think you're right! Does this LGTY? https://gist.github.com/saghul/8897297 /cc @indutny

**Comment by indutny** [comment]
LGTM

**Comment by saghul** [comment]
Ok, I'll check to which branches the fix applies and commit it a bit later.
