### ISSUE TITLE
uv_close_cb marked as public in UV_HANDLE_FIELDS

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1109]
Hope I am following procedures, this relates to my query:
https://groups.google.com/d/msg/libuv/ful2GaPyUsM/rnYPKGpXKKsJ
to which Fedor Indutny replied:

> > I'm afraid it is not a public field (perhaps worth filling a bug report)

uv.h has:
# define UV_HANDLE_FIELDS \

/\* public _/\
uv_close_cb close_cb; \
void_ data;

I am new to using libuv and had incorrectly assumed one could set a uv_close_cb by setting this property, instead of passing the function pointer to uv_close().

**Comment by saghul** [comment]
I moved the field to the "private" area here: https://github.com/saghul/libuv/commit/c8e4db6e00186c7feb100027f518efb070431d80. @indutny: fields where not laid out in any particular order, right? LGTY?

**Comment by indutny** [comment]
@saghul I don't think so, LGTM

**Comment by saghul** [comment]
Thanks, Fedor, landed in https://github.com/joyent/libuv/commit/c8e4db6e00186c7feb100027f518efb070431d80
