### ISSUE TITLE
Test failure OSX 10.6.8, recent build

### ISSUE THREAD

**Issue by skaller** [joyent/libuv#1110]
make  check-TESTS

Output from process `platform_output`:
uv_get_process_title: /Users/johnskaller/libuv/test/.libs/run-tests
uv_resident_set_memory: 417792
uv_uptime: 98840.000000
uv_cpu_info:
  model: Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
  speed: 2400
  times.sys: 2822170
  times.user: 13116980
  times.idle: 82900480
  times.irq: 0
  times.nice: 0
  model: Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
  speed: 2400
  times.sys: 3004090
  times.user: 12662230
  times.idle: 83172610
  times.irq: 0
  times.nice: 0
uv_interface_addresses:
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: fe80::1
  netmask: ffff:ffff:ffff:ffff::
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: en1
  internal: 0
  physical address: 00:1e:52:72:d0:53
  address: fe80::21e:52ff:fe72:d053
  netmask: ffff:ffff:ffff:ffff::
  name: en1
  internal: 0
  physical address: 00:1e:52:72:d0:53
  address: 192.168.1.100
  netmask: 255.255.255.0
  =============================================================

`getaddrinfo_fail` failed: timeout
Output from process `getaddrinfo_fail`: (no output)
  =============================================================
[%  76|+ 157|-   1|T   0|S   0]: osx_selectgot some input
with a couple of lines
feel pretty happy

`fs_event_watch_dir` failed: timeout
Output from process `fs_event_watch_dir`: (no output)
  =============================================================

`fs_event_error_reporting` failed: exit code 6
Output from process `fs_event_error_reporting`: (no output)
  =============================================================

FAIL: test/run-tests
  =======================================================
1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues
  =======================================================

**Comment by indutny** [comment]
Thank you, I am aware of this.
