### ISSUE TITLE
EFBIG mapping

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#1112]
ftruncate(), pwrite() and maybe others can return EFBIG but there is no libuv mapping for that.

**Comment by saghul** [comment]
Forgive me if I'm too naive, is this all that's needed, Ben? https://github.com/saghul/libuv/commit/728998de5f6e6208b11941f76f5c007d84aaafb9

**Comment by bnoordhuis** [comment]
You also need to add it to the list in uv.h but that's pretty much it, yes.

**Comment by saghul** [comment]
Force pushed: https://github.com/saghul/libuv/commit/107be2bed38afa6279aa53b13b946eb60c204969

**Comment by bnoordhuis** [comment]
That should do it.  Cheers, Saúl.

**Comment by saghul** [comment]
Landed in https://github.com/joyent/libuv/commit/107be2bed38afa6279aa53b13b946eb60c204969, thanks for the review Ben!
