### ISSUE TITLE
cygwin compile error with CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by japj** [joyent/libuv#112]
Trying to compile master on cygwin I get:

<pre>
japj@PC-MD8860 /cygdrive/c/github/libuv-cygwin
$ make
gcc --std=c89 -pedantic -Iinclude -Isrc/ev -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Isrc/ares/config_cygwin -g -c src
/uv-cygwin.c -o src/uv-platform.o
src/uv-cygwin.c: In function `uv_hrtime':
src/uv-cygwin.c:33: error: `CLOCK_MONOTONIC' is hier niet gedeclareerd (eerste gebruik in deze functie)
src/uv-cygwin.c:33: error: (Elke niet-gedeclareerde naam wordt slechts 'e'en
src/uv-cygwin.c:33: error: keer vermeld voor elke functie waarin hij staat.)
make: *** [src/uv-platform.o] Fout 1
</pre>

**Comment by bnoordhuis** [comment]
Love the Dutch i18n! The error message is that CLOCK_MONOTONIC hasn't been declared. Some quick googling suggests that it was added in cygwin 1.7.6.

**Comment by japj** [comment]
yeah, really funny ;)

Strange thing is that I re-ran the cygwin setup tool and I am up to date.

On Fri, Jul 15, 2011 at 9:56 PM, bnoordhuis
reply@reply.github.com
wrote:

**Comment by japj** [comment]
it seems this is due to --std=c89 from the CSTDFLAG in config-unix.mk
and the combination of

<pre>
/usr/include/sys/features.h
#ifdef __CYGWIN__
#if !defined(__STRICT_ANSI__) || defined(__cplusplus) || __STDC_VERSION__ >= 199901L
#define _POSIX_MONOTONIC_CLOCK                  200112L

/usr/include/time.h
#if defined(_POSIX_MONOTONIC_CLOCK)
#define CLOCK_MONOTONIC (clockid_t)4
#endif
</pre>


If I remove --std=c89  then everything builds ok on cygwin

**Comment by bnoordhuis** [comment]
@japj can you try this patch?

``` diff
diff --git a/config-unix.mk b/config-unix.mk
index 2b44dd6..5da481f 100644
--- a/config-unix.mk
+++ b/config-unix.mk
@@ -65,6 +65,7 @@ endif
 ifneq (,$(findstring CYGWIN,$(uname_S)))
 EV_CONFIG=config_cygwin.h
 EIO_CONFIG=config_cygwin.h
+CSTDFLAG += -D_XOPEN_SOURCE=600
 CPPFLAGS += -Isrc/ares/config_cygwin
 LINKFLAGS+=
 UV_OS_FILE=uv-cygwin.c
```

**Comment by japj** [comment]
This does not seem to fix it, I still get the same error.

If I rename uv-cygwin.c to cc and adapt the makefile (in order for it
to behave like a cplusplus file then I get the next error which is:

<pre>
$ make
gcc --std=c89 -pedantic -Iinclude -Isrc/ev -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -Isrc/ares/config_cygwin -g -c src/uv-cygwin.cc
-o src/uv-platform.o
cc1plus: warning: command line option "-std=c89" is valid for C/ObjC
but not for C++
src/uv-cygwin.cc: In function `int uv_exepath(char*, size_t*)':
src/uv-cygwin.cc:48: error: `readlink' undeclared (first use this function)
src/uv-cygwin.cc:48: error: (Each undeclared identifier is reported
only once for each function it appears in.)
make: *** [src/uv-platform.o] Error 1
</pre>


We need to get around the following check in order for it to work:

<pre>
/usr/include/sys/features.h
#if !defined(__STRICT_ANSI__) || defined(__cplusplus) ||
__STDC_VERSION__ >= 199901L
</pre>


On Fri, Jul 15, 2011 at 10:51 PM, bnoordhuis
reply@reply.github.com
wrote:
