### ISSUE TITLE
RFC: Avoid doing malloc/free when creating/destroying loops.

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1120]
Currently we deal with loops like this:
- uv_default_loop: returns the one and only default loop, statically allocated.
- uv_loop_new: allocates and initializes a new loop, which is returned to us.
- uv_loop_delete: performs some cleanup tasks and frees a given loop.

The malloc/free usage here is not very consistent with how we deal with handles, so I'd like to propose some changes:
- uv_default_loop: returns the one and only default loop, statically allocated (same as before)
- uv_loop_init(loop): initializes the user-allocated loop.
- uv_loop_close/destroy: performs the cleanup tasks. (I'm not sure yet about the best name, but I lean towards uv_loop_close)

So, in the new model libuv would not be malloc-ing memory for free-ing it, the user is responsible for doing that.

Thoughts?

/cc @indutny @piscisaureus

**Comment by retep998** [comment]
I would certainly welcome this change towards providing a more consistent API.

**Comment by ghost** [comment]
+1

**Comment by indutny** [comment]
+1

**Comment by ghost** [comment]
Hi!

I would like a behaviour like janson lib: that malloc() and
free()functions can be overridden if custom behavior is needed.  (
https://jansson.readthedocs.org/en/2.5/apiref.html#custom-memory-allocation)

Regards
ginsmar

2014-02-16 23:16 GMT+01:00 Saúl Ibarra Corretgé notifications@github.com:

**Comment by saghul** [comment]
> I would like a behaviour like janson lib: that malloc() and free()functions can be overridden if custom behavior is needed. ( https://jansson.readthedocs.org/en/2.5/apiref.html#custom-memory-allocation) 

Less malloc-ing drives us closer to that, but lets try to do one thing at a time :-) Feel free to open a new issue for dealing with it.

**Comment by piscisaureus** [comment]
@saghul 

> uv_loop_init(loop): initializes the user-allocated loop.

+1

> uv_loop_close/destroy: performs the cleanup tasks. (I'm not sure yet about the best name, but I lean towards uv_loop_close)

+1
I'd go for `uv_loop_close`. Be aware that it is not safe to close a loop that still has handles attached to it. I think if this is the case `uv_loop_close()` should return `EBUSY`.

In order not to break any code that works today, can we retain `uv_loop_new` and `uv_loop_destroy`? They should just use the new functions and malloc/free. You can mark them deprecated though.

**Comment by saghul** [comment]
> I'd go for uv_loop_close. Be aware that it is not safe to close a loop that still has handles attached to it. I think if this is the case uv_loop_close() should return EBUSY.

Agreed.

> In order not to break any code that works today, can we retain uv_loop_new and uv_loop_destroy? They should just use the new functions and malloc/free. You can mark them deprecated though.

We can. However, since we will expose the version in headers applications could easily adapt :-)

**Comment by retep998** [comment]
If all handles have already been uv_close'd but the loop hasn't run yet to process all those close requests, then uv_loop_close should do a final run through to process the handle closings.

**Comment by saghul** [comment]
> If all handles have already been uv_close'd but the loop hasn't run yet to process all those close requests, then uv_loop_close should do a final run through to process the handle closings.

I don't think so. I'm not planning on changing the semantics with regards to the current uv_loop_delete. I will add extra checks, but closing all handles and running the loop until there is nothing left is something the user needs to do, and we do provide the tools to do it.

**Comment by saghul** [comment]
Fun continues in https://github.com/joyent/libuv/pull/1124/

**Comment by saghul** [comment]
This landed in 787f5ff.
