### ISSUE TITLE
Add ENOPROTOOPT error to the error map

### ISSUE THREAD

**Issue by neoxic** [joyent/libuv#1143]
Steps of the problem:
1. Call `uv_tcp_init`
2. Call `uv_tcp_bind` with an IPv4 address
3. Call `uv_tcp_bind` with an IPv6 address
4. The previous operation fails with resulting code -92 (-ENOPROTOOPT)
5. Call `uv_err_name` with that `err` value
6. End up in `assert(0)` (or segfault with NDEBUG)

Interestingly enough that if you swap steps 2 and 3, the error code is -22 (-EINVAL).

Also, please consider returning "UNKNOWN" from `uv_err_name` instead of asserting (symmetrical to `uv_strerror`'s behaviour).

Code snippet:

``` C
#include <assert.h>
#include <stdio.h>
#include <uv.h>

int main() {
    int err;
    struct sockaddr_in ba1;
    struct sockaddr_in6 ba2;
    uv_tcp_t tcp;

    uv_tcp_init(uv_default_loop(), &tcp);

    assert(uv_ip4_addr("0.0.0.0", 3333, &ba1) == 0);
    err = uv_tcp_bind(&tcp, (const struct sockaddr *)&ba1, 0);
    if (err) {
        printf("err: %d\n", err);
        printf("name: %s\n", uv_err_name(err));
        return 0;
    }
    printf("ipv4 bound ok\n");

    assert(uv_ip6_addr("::", 4444, &ba2) == 0);
    err = uv_tcp_bind(&tcp, (const struct sockaddr *)&ba2, UV_TCP_IPV6ONLY);
    if (err) {
        printf("err: %d\n", err);
        printf("name: %s\n", uv_err_name(err));
        return 0;
    }
    printf("ipv6 bound ok\n");
}
```

Output:

```
ipv4 bound ok
err: -92
test: src/uv-common.c:83: uv_err_name: Assertion `0' failed.
```

**Comment by saghul** [comment]
This should fix it: https://github.com/joyent/libuv/pull/1144
