### ISSUE TITLE
uv_shutdown: multiple consecutive calls allowed and lead to undefined beahviour

### ISSUE THREAD

**Issue by neoxic** [joyent/libuv#1153]
There is no any consistency check in `uv_shutdown` to prevent consecutive calls. Thus, being called again right **before** the previous callback had a chance to set _UV_STREAM_SHUT_ this function doesn't report an error nor does it launch its callback with any status. That leads to inconsistency and unpredicted behaviour. It looks reasonable to check if the `shutdown_req` field is already set in `uv_shutdown` similarly to what is done in `uv_tcp_connect` for example:

https://github.com/joyent/libuv/blob/master/src/unix/tcp.c#L108

(can't see any similar check in 'win/tcp.c' though, so currently, as the user, I am dubious whether I need to duplicate consistency checks myself or rely on libuv's error reporting mechanism).

**Comment by saghul** [comment]
This landed no so long ago: https://github.com/joyent/libuv/blob/master/src/unix/stream.c#L1111

If you call `uv_shutdown` multiple times you'll get UV_ENOTCONN.

**Comment by saghul** [comment]
Hum, you mean in Windows, I see. Yeah, checking for shutdown_req should be enough, care to send a PR? :-)

**Comment by neoxic** [comment]
Oh, I am really sorry! My bad missing the update.

What is a PR? :-)

**Comment by saghul** [comment]
No worries! A PR is a pull request. In this case there is nothing to fix though, because on Windows you'll get UV_EPIPE, because the UV_HANDLE_WRITABLE flag is reset when calling uv_shutdown.

**Comment by neoxic** [comment]
Exactly! Thanks! ))
