### ISSUE TITLE
Fix configure when PKG_CONFIG is set

### ISSUE THREAD

**Issue by thierry-FreeBSD** [joyent/libuv#1166]
If you define the environment variable PKG_CONFIG and assign it to pkgconf (or pkg-config), configure will say it's OK, but it won't be used.

Here is a fix for that:

--- patch-configure.ac begins here ---
--- configure.ac.orig   2014-02-27 03:04:23.000000000 +0100
+++ configure.ac    2014-02-28 22:03:02.000000000 +0100
@@ -47,8 +47,8 @@
 AM_CONDITIONAL([WINNT],   [AS_CASE([$host_os], [mingw*],   [true], [false])])
 PANDORA_ENABLE_DTRACE
 AC_CHECK_PROG(PKG_CONFIG, pkg-config, yes)
-AM_CONDITIONAL([HAVE_PKG_CONFIG], [test "x$PKG_CONFIG" = "xyes"])
-AS_IF([test "x$PKG_CONFIG" = "xyes"], [
+AM_CONDITIONAL([HAVE_PKG_CONFIG], [test "x$PKG_CONFIG" != "x"])
+AS_IF([test "x$PKG_CONFIG" != "x"], [
     AC_CONFIG_FILES([libuv.pc])
 ])
 AC_CONFIG_FILES([Makefile])
--- patch-configure.ac ends here ---

Best regards,

Th. Thomas.

**Comment by saghul** [comment]
Can you please submit a pull request with the patch? We'll also need that you sign the CLA in order to merge the code.

Thanks!

**Comment by thierry-FreeBSD** [comment]
Done, thanks!
