### ISSUE TITLE
libuv.pc is missing dependencies

### ISSUE THREAD

**Issue by jszakmeister** [joyent/libuv#1168]
On systems with `clock_gettime()`, `-lrt` should appear in the generated libuv.pc file.  And on FreeBSD, `-lkvm` needs to appear in there.  This will help those integrating with libuv to make sure the get the correct libraries linked in.

**Comment by indutny** [comment]
Hello!

Will you be interested in sending us a Pull Request with a fix for this problem?

Cheers,
Fedor.

**Comment by saghul** [comment]
@jszakmeister can you try https://github.com/joyent/libuv/pull/1171 please?

**Comment by jszakmeister** [comment]
@saghul Yes, that appears to get it correct now.

**Comment by saghul** [comment]
Kewl, thanks for confirming!

**Comment by saghul** [comment]
Landed the fix, thanks!
