### ISSUE TITLE
want uv_walk (which calls ev_walk on unix - need windows imlemenation)

### ISSUE THREAD

**Issue by ry** [joyent/libuv#117]
cc @jhurliman

**Comment by jhurliman** [comment]
On a related note, I hacked together a quick test exposing some of the ev_walk() functionality to JS. Only tested with a timer so far but appears to work fine. https://github.com/jhurliman/node/commit/9e556deb991f2b48da1d419663f283630126026e

**Comment by jhurliman** [comment]
I'm capturing stack traces in the IOWatcher constructor using:

```
v8::Local<v8::StackTrace> trace = v8::StackTrace::CurrentStackTrace(10, v8::StackTrace::kOverview);
```

But it looks like I'll need to possibly capture traces in the ObjectWrap constructor or in multiple constructors, since an IOWatcher does not get created for setTimeout(). Two IOWatchers are created when I call console.log though:

```
at exports.isIP (net_legacy.js:80:10)
at exports.FreeList.alloc (freelist.js:34:46)
at initSocket (net_legacy.js:193:34)
at Socket.open (net_legacy.js:253:3)
at Socket (net_legacy.js:236:10)
at WriteStream (tty_posix.js:313:14)
at startup.processStdio.stderr (node.js:226:18)
at exports.log (console.js:61:10)
at  (/Users/johnhurliman/Code/node/watchtest.js:2:9)
at Module._compile (module.js:420:26)
at Module._extensions..js (module.js:459:10)
at Module.load (module.js:335:31)
at Module._load (module.js:294:12)
at Module.runMain (module.js:479:10)
at startup.processNextTick.process._tickCallback (node.js:190:26)
```

**Comment by jhurliman** [comment]
Switched to capturing traces in the ObjectWrap constructor. A lot more traces are captured than necessary due to various IOWatcher/ObjectWrap objects being initialized internally in node for resource pools (my simple test program grabs about six traces when it only needs one). However, this approach should work for every type of watcher. I'll switch over to uv_walk() when it's in master.

Here is the current return value of process.watchers() in my test app:

```
[ { type: 'timer',
    handle: 
     { repeat: 0,
       _idleNext: [Object],
       _idlePrev: [Object],
       callback: [Function] },
    stack: '    at insert (timers_legacy.js:61:12)\n    at exports.active (timers_legacy.js:134:7)\n    at exports.setTimeout (timers_legacy.js:186:13)\n    at startup.globalTimeouts.global.setTimeout (node.js:136:27)\n    at  (/Users/johnhurliman/Code/node/watchtest.js:4:1)\n    at Module._compile (module.js:420:26)\n    at Module._extensions..js (module.js:459:10)\n    at Module.load (module.js:335:31)\n    at Module._load (module.js:294:12)\n    at Module.runMain (module.js:479:10)' },
  { type: 'signal' } ]
```

**Comment by isaacs** [comment]
Holy awesome.

**Comment by felixge** [comment]
This is exactly what I need! <3

**Comment by jhurliman** [comment]
Initial version is here: https://github.com/joyent/node/pull/1532

**Comment by jhurliman** [comment]
I updated to node HEAD this afternoon and process.watchers() broke. I can still call ev_walk() and successfully get a list of watchers, but running:

```
ObjectWrap* wrap = (ObjectWrap*)watcher->data;
obj->Set(handle_symbol, wrap->handle_);
```

Will sometimes segfault. My quick scan over some of the new code suggests that ev_watcher.data is not used to hold an ObjectWrap pointer now, but I may be misreading it. (I haven't had time to fully digest the changes.) Either way, I think getting uv_walk() in is the next step and I will track down the missing ObjectWrap pointer from there.

**Comment by felixge** [comment]
Can't help with the segfaults, but I just wanted to say thanks for continuing to work on this - this is awesome!

**Comment by bnoordhuis** [comment]
Superseded by the work on domains, closing.
