### ISSUE TITLE
[Wish] Please also sign tarballs

### ISSUE THREAD

**Issue by lucab** [joyent/libuv#1177]
Due to architecture constraints, most of the distribution systems that predate git still relies on tar.gz as the source origin for building (eg. deb and rpm packages).
As such, while signed git tags for releases exist, they are not directly used by packagers which relies instead on unsigned tarballs.

What I'm proposing here is to have whoever is in charge of releasing and moving tarballs to libuv.org to add a detached signature next to it, preferably from a well-linked key.

See here for a couple of pointers: http://www.debian-administration.org/users/dkg/weblog/106

**Comment by saghul** [comment]
Hi @lucab, we are currently a bit busy with the 0.12 release. I'll see what we can do afterwards. Thanks!

**Comment by lucab** [comment]
As per the subject tag, this is not high-priority, just a suggestion for future procedures. 

As a matter of fact, out of the 20ish packages I take care of, just a bunch of them recently started doing so. Still, more hygiene into the system :)

**Comment by saghul** [comment]
Lets see if we can squeeze this one in for 0.12.

**Comment by saghul** [comment]
Back to reality, I don't we'll have time to do this properly. I'd rather not do it than do it badly. Setting it for post 0.12. Sorry.

**Comment by saghul** [comment]
Continues on https://github.com/libuv/libuv/issues/409
