### ISSUE TITLE
unix: Infinite loop when file descriptors exhausted

### ISSUE THREAD

**Issue by alexcrichton** [joyent/libuv#1189]
I've discovered that it's possible for a TCP server to get stuck in an infinite loop when all file descriptors have been exhausted. I believe that the server can make progress, but it gets stuck in an infinite loop calling the `connection_cb` that an error occurred.
## Server program

https://gist.github.com/9478683

This program infinitely accepts connections, reads from them, and then closes them. The key part of this program is that there's a background thread opening and closing file descriptors (attempting to exhaust all file descriptors. Also note that the worker exits once an error has been encountered by the server, but this isn't really strictly necessary.

The infinite loop happens when libuv invokes `new_connection` continuously in a loop with `status` set to `-EMFILE`.
## Client program

https://gist.github.com/9478692

This is a pretty dumb client which just connects to the server until the client has run out of file descriptors. There's no infinite loop with the client, it's just making a bunch of connections
## Infinite loop

```
// Inside one shell
$ ulimit -n 128
$ ./server

// Inside another shell
$ ulimit -n 256
$ ./client
```

After that, the server will infinitely loop printing out errors. I would expect the server to at least continue to service the previously accepted requests before continuing to invoke the `connection_cb` notifying it that there are no file descriptors left.

**Comment by alexcrichton** [comment]
I should also mention that this only happens on linux, not on OSX

**Comment by saghul** [comment]
@alexcrichton here is what libuv currently does to try to mitigate this: https://github.com/joyent/libuv/blob/master/src/unix/stream.c#L434-L444

AFAIK there is no silver bullet, so I guess a good think to do would be to stop listening for a bit. Unfortunately we don't have uv_listen_start/stop, which is something I wanted to have for a while now. The unix version should be simple enough, not sure about windows, I'll take a look!

**Comment by alexcrichton** [comment]
I wasn't exactly sure what was going on, but it looked like the `emfile_trick` function was the reason that it kept infinitely looping. I would expect the loop to fall back to the outer event loop instead of continually trying to get more file descriptors. 

The comment about it being reliable in a multi-threaded environment seems a little fishy, and I think that's exactly my problem (the test is in a multi-threaded environment).

I do agree though, `uv_listen_{start,stop}` would fix our use case perfectly!

**Comment by saghul** [comment]
I know you folks are not using libuv anymore, but I'll leave the comment regardless. For 2.0 we plan to change how accepting connections works: https://github.com/libuv/libuv/issues/5 so the user would just stop doing `uv_accept`. Closing.
