### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1197]
Can this project support CMake? I would make the library easier to build with other projects that use CMake. I've make a fork and I'm working on the CMakeLists.txt already.

**Comment by indutny** [comment]
Thanks for opening this issue! I have nothing against CMake, but we already use 2 build systems: gyp and autoconf/automake. Adding another one will require us to update 3 files, each time new file is added or removed, and I don't really willing it support it.

Sorry!

**Comment by ghost** [comment]
Okay. I was a little hopeful though, because CMake supports builds for Visual Studio and Makefile (among others). If you successfully got a CMakeLists.txt file into the build, you would be able to discard your other build systems. But, I can see how all the other joyent projects already use the same build system, so I can see how that would be an issue.

Thanks anyway!

On Thu, Mar 13, 2014 at 11:13 PM, Fedor Indutny notifications@github.comwrote:

> Closed #1197 https://github.com/joyent/libuv/issues/1197.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/1197
> .

## 

-Taylor Holberton

**Comment by tjfontaine** [comment]
@taylorholberton for what its worth gyp is also a meta build system which is used to generate the build system desired for your platform. So on OSX it generates either makefiles or xcode projects, on  windows it will generate vs solutions. etc etc
