### ISSUE TITLE
close_cb_stack should be in a file of similar name

### ISSUE THREAD

**Issue by ry** [joyent/libuv#12]
that is, rename `test-callback-stack.c`

**Comment by ry** [comment]
in general i would like all of the tests to have a similar filename so that i can make my Makefile easier.

tests should have the form `test-*.c`. All other files should not: `test-runner.c` should change to `runner.c` (or something)

**Comment by piscisaureus** [comment]
Allright. I imagined having multiple tests in one file, hence test-<something>-stack in test-callback-stack.c.

**Comment by ry** [comment]
Ah, okay. That makes sense.

 i still would like `test-runner.c` to be called something else.

**Comment by piscisaureus** [comment]
I renamed the runner to just "runner".
