### ISSUE TITLE
If options.cwd isn't specified CreateProcess should a NULL lpCurrentDirectory param

### ISSUE THREAD

**Issue by ry** [joyent/libuv#120]
currently it does not - it seems to do unnecessary work

just remove this branch https://github.com/joyent/libuv/blob/master/src/win/process.c#L656-667  ?

**Comment by igorzi** [comment]
@ry: cwd is needed for search_path.  see https://github.com/joyent/libuv/blob/master/src/win/process.c#L725.

**Comment by ry** [comment]
ok
