### ISSUE TITLE
glibtoolize command not found when installing using autotools on OSX Mavericks

### ISSUE THREAD

**Issue by BioticPixels** [joyent/libuv#1200]
Using autotools on OSX Mavericks 10.9.2 to install libuv got this error message:

```
$ sh autogen.sh
+ glibtoolize
autogen.sh: line 43: glibtoolize: command not found
```

In [autogen.sh](https://github.com/joyent/libuv/blob/master/autogen.sh), changing [line 20](https://github.com/joyent/libuv/blob/master/autogen.sh#L20) from `LIBTOOLIZE=glibtoolize` to `LIBTOOLIZE=libtoolize` fixed the problem.

(libtool-2.4.2 was installed using `./configure`, `make`, `make install` on OSX Mavericks 10.9.2)

**Comment by Sannis** [comment]
`glibtoolize` is widely used on OS X because bundled libtool is not GNU version and may cause fails for some Linux-specific software. But if it works for libuv, I think you can make a patch for `autogen.sh` that checks `glibtoolize` existence.

**Comment by saghul** [comment]
Well, the script already checks for the existence of the `LIBTOOLIZE` env variable and sets it to `glibtoolize` on OSX: https://github.com/joyent/libuv/blob/master/autogen.sh#L19

The common trend seems to be to prefix those system tools with a g to prevent them from collinding with the ones from the system.

IMHO the current approach is flexible enough for you to use it without modifying any line of code. You could just export the `LIBTOOLIZE` env variable pointing to your binary and things should just work.

**Comment by schlamar** [comment]
Or `brew install libtool`.

**Comment by saghul** [comment]
We closed #1201 with no changes, closing this one as well.

**Comment by jhonsu01** [comment]
install http://packages.ubuntu.com/precise/libtool

**Comment by 4kzeng** [comment]
That 'glibtoolize' also can be  do not exist on my mac serira
