### ISSUE TITLE
TLS Destructors

### ISSUE THREAD

**Issue by tarqd** [joyent/libuv#1216]
When using `uv_create_key` and friends from C++ land the ability the specify a destructor function would greatly improve it's usefulness. Posix supports this already and Windows does too with a bit of [tinkering](https://github.com/mirrors/chromium/blob/master/base/threading/thread_local_storage_win.cc#L42).

I imagine this isn't high priority for use in node but it definitely has some use-cases. For example a C++ binding could use this to allow threads and tasks queued with `uv_queue_work` to access a thread-specific event loop (similar to v8's Isolate::GetCurrent()).

**Comment by saghul** [comment]
I noticed this myself a while ago but forgot to open an issue about it. I think it would be a welcomed addition. Are you willing to work on a patch?

**Comment by tarqd** [comment]
I'd be willing to give it a shot but it's been a while since I've touched Windows haha. From what I gather from chromiums source it won't be quite as straight forward as I'd like because the callback doesn't pass back any reference to the key (it's more of a global "on thread exit" type deal). libuv would need to:
- Keep a list of created keys and their associated destructor function 
- When our global TLS destructor callback is called, iterate through any active keys and call the user-defined destructor. 

Off the top of my head I'd probably approach this  by redefining `uv_key_t` on windows to this:

``` c
typedef struct uv_key_s uv_key_t;
typedef void (*key_dtor_cb)(void*);
struct uv_key_s {
  DWORD tls_index;
  key_dtor_cb dtor_cb;
  void* dtor_queue[2];
};
```

And have `uv_create_key` add the key to a static/global queue if the user has defined a non-null `key_dtor_cb` (otherwise just set everything but tls_index to null pointers).

The problem here is that `pthread_key_create` must be thread-safe and this obviously wouldn't be. Now I think the common and suggested use of these would imply that the user isn't creating a whole bunch of them on multiple threads at once so a global mutex lock seems like a pretty simple and clean solution to me. Otherwise we can get a bit creative and use `TLSAlloc` to create thread-specific `uv_key_t` queues which would allow you to create and delete keys without locking. It would only acquire a lock to the global/static `QUEUE` when the global TLS destructor / thread exit function is called to append undeleted keys to the global queue.

I'm of the opinion that a mutex would be fine as the common case won't have high if any contention since there's a limited number of TLS slots available anyway. If the user is really dedicated to avoiding the potential blocking they can do what chromium does and implement their own TLS on top of a single `uv_key_t`. 

What do you think? I want to make sure the approach I'd be going with would be acceptable and consistent with the thread of libuv before I get crackin'.

**Comment by tarqd** [comment]
By global I mean "shared by all threads" not a global variable. Sorry if the posts confusing I'm half asleep right now :P.

One last note: `uv_key_delete` would not call destructor functions, which matches the behavior of `pthread_key_delete`. The user is responsible for making sure that all threads using the key have exited (and therefore called the destructor) or cleaned up any resources assigned to the key.

**Comment by saghul** [comment]
Your reasoning sounds good to me!

**Comment by saghul** [comment]
Closing, please open a PR when you have some code ready for review.
