### ISSUE TITLE
uv_getaddrinfo sometimes not works

### ISSUE THREAD

**Issue by nareix** [joyent/libuv#1226]
in windows

**Comment by tjfontaine** [comment]
@go-av can you provide more details around this?

What specifically is your:
- platform
- execution environment
- test case

**Comment by saghul** [comment]
Jenkins and all the Windows machines I have access to disagree :-) uv_getaddrinfo depends on network connectivity, so it's expected to fail in case there is no connectivity for example. If you find a failure case which is not related to this, please open a new issue with a **detailed** explanation, ideally with a test case demonstrating it. Thanks!
