### ISSUE TITLE
pipe bug when use function pointer?

### ISSUE THREAD

**Issue by ccoossdddffdd** [joyent/libuv#1228]
i use libuv to build a pipe test program with unix domain socket.

and now , i made a custom function pointer to bind at uv_pipe_t.data object,
but, when client connected, i change the uv_pipe_t.data object to my function pointer,
it's a core dumped happend,

this is my code, please help to check.

``` c++

void on_connect(uv_connect_t* connect_req, int status) {
    __on_conn n = *(__on_conn *) connect_req->handle->data;
    (*n)(); // core dumped happend, but the pointer address is same as last output.
}

void pipe_conn(uv_loop_t * loop, const char * conn_sock_path, __on_conn cb) {
    uv_pipe_init(loop, &_send_pipe, 1);

       cout << &cb << endl; // print the original function pointer address;

    (*cb)();  // it can be used. work successful.

    _send_pipe.data = &cb;
    uv_pipe_connect(&_conn, &_send_pipe, conn_sock_path, on_connect);
}


```

**Comment by saghul** [comment]
How did you define `__on_conn`? Can you paste the full example code?

**Comment by ccoossdddffdd** [comment]
i'm sure __on_conn has been define, beacuse (*cb)() can used.

this is the typedef:

``` c++
typedef void (*__on_conn)(); 
```

this is the real code:

``` c++
void on_pipe_conn() {
    cout << "connected" << endl;
}
```

the core dumped just happend in on_connect function and use custom data with function pointer

**Comment by saghul** [comment]
Without seeing the rest, I'd say you need to do: 

```
_send_pipe.data = cb;
```

And then in the callback:

```
 __on_conn n =  connect_req->handle->data;
 n();
```

**Comment by ccoossdddffdd** [comment]
sorry, i tried this way, but it can't work

https://gist.github.com/cosnis/10015403

this is my all code's 
please make test and use ./bin/test-pipe-server and  ./bin/test-pipe-client to test it

i don't know why it allways had a core dumped when use function pointer

the error was happend at pipe.h 100 lines

**Comment by indutny** [comment]
It is crashing because you are passing pointer to on-stack variable, and not a pointer to function. Try replacing `&cb` with `cb` and replacing `*cb` with `cb` everywhere. Definitely not a libuv issue.
