### ISSUE TITLE
Windows: uv_get_process_title doesn't call LeaveCriticalSection in all code paths

### ISSUE THREAD

**Issue by Jasper-Bekkers** [joyent/libuv#1235]
LeaveCriticalSection should be called inside uv_get_process_title (win\util.c), the before all return statements. Currently one is missing before the line:

```
return uv__new_sys_error(GetLastError());
```

**Comment by indutny** [comment]
Thanks for reporting it! Should be fixed by https://github.com/joyent/libuv/pull/1236

**Comment by Jasper-Bekkers** [comment]
Shit that's fast. Thanks!
