### ISSUE TITLE
Building test projects with a shared library on Windows fails (VS2010)

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1238]
After creating the project with:

```
vcbuild.bat shared
['-Dtarget_arch=ia32', '-Duv_library=shared_library', '.\\uv.gyp', '-I', 
'.\\common.gypi', '--depth=.', '-Dhost_arch=AMD64', '-Dcomponent=static_library']
```

Building with VS2010 fails for `run-benchmarks` and `run-tests` (building `libuv` itself works fine):

```
Error   1   error C2491: '_snprintf' : definition of dllimport function not 
allowed c:\dev\projects\libuv\test\task.h   191 1
```

Using **v0.11.24**.

**Comment by saghul** [comment]
Doh, looks like this one fell through the cracks, sorry! That is currently unsupported, I'm afraid. Closing this in favor of https://github.com/joyent/libuv/issues/1382
