### ISSUE TITLE
UV_UDP_IPV6ONLY behaves different than UV_TCP_IPV6ONLY

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1247]
If I bind a IPv4 TCP handler by passing the UV_TCP_IPV6ONLY flag it just works (the IPv6 stuff is ignored as it makes no sense).

If I bind a IPv4 UDP handle by passing the UV_UDP_IPV6ONLY flag then uv_udp_bind() fails with "invalid argument".

**Comment by saghul** [comment]
Thanks for the report! Check https://github.com/joyent/libuv/issues/1248
