### ISSUE TITLE
Generic uv_datagram_t handle missing

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1251]
In the same way `uv_tcp_t` inherits from `uv_stream_t`, `uv_udp_t` may inherit from `uv_datagram_t` handle.

Currently I can safely use `uv_udp_open()` by passing a file descriptor created by me (a AF_UNIX SOCK_DGRAM socket) and it works perfectly with the libuv's UDP API.

But I cannot bind it because `uv_udp_bind()` requires that the sockaddr family is AF_INET or AF_INET6. Maybe I can use `uv_pipe_bind()` but it seems a bit "ugly" solution IMHO.

**Comment by ibc** [comment]
No, I cannot bind a manually created AF_UNIX SOCK_DGRAM socket because `uv_pipe_bind()` asserts some stuff:

```
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file src/unix/stream.c, line 1490.
```

This is a bit frustrating. The support for UnixSocket (in datagram mode) is too much limited in libuv. Well, it is not supported theorically. Instead it happens that it may work by using some `uv_xxx_open()` facilities.

**Comment by ibc** [comment]
This works (FIFO files are created in the given path), but obviously it is a hack:

```
uv_udp_t fifo;
[...]
uv_udp_open(&fifo, fd);

fifo.type = UV_NAMED_PIPE;
uv_pipe_bind((uv_pipe_t*)&fifo, path);
fifo.type = UV_UDP;
```

**Comment by saghul** [comment]
Hi there,

I'm all in for cross-platform-world-domination, unfortunately I don't have the time (nor the patience, truth be told) to address this, I have many more things on my table.

FWIW, Node used to have support for this, but it was removed long ago: https://groups.google.com/forum/#!topic/nodejs/iCzhcuxGP1I

In case you want Unix-only support you can use a `uv_poll_t` handle and borrow some code from here: https://github.com/bnoordhuis/node-unix-dgram/blob/master/src/unix_dgram.cc

Now, if you want to take a stab at this, note that support will need to be complete, as in Windows as well. Actually it looks like named pipes can be configured to use datagrams: http://msdn.microsoft.com/en-us/library/aa365150 (pipes of type PIPE_TYPE_MESSAGE) but I have NULL experience with those.

**Comment by saghul** [comment]
Closing as wontfix. If you feel like writing the code, go ahead and send a PR :-)

**Comment by ibc** [comment]
Don't worry. BTW I consider this other feature much more useful: #1320 :)
