### ISSUE TITLE
addr in uv_udp_recv_cb() is garbage when using uv_udp_open() in Linux

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1252]
I pass a non-blocking AF_UNIX SOCK_DGRAM socket to `uv_udp_open(fd)`, so I can use the UDP API of libuv. 

It works perfectly. But... when I inspect the `struct sockaddr* addr` given in the `uv_udp_recv_cb()`: 
- In OSX (Mavericks): I inspect the family of `addr` and, indeed, it is `AF_UNIX` (OK). 
- Linux (Debian 7): I inspect the family of `addr` and it is unknown. This is, the given `addr` is not a `struct sockaddr` at all, but garbage.

I expect this is a bug (in Linux) given that libuv should not provide a garbage `struct sockaddr`.

**Comment by ibc** [comment]
Sorry for opening this issue after publishing the same in the mailing list, in which I've got a very good response including a patch:

https://groups.google.com/forum/#!topic/libuv/VcL-AO2XasA

**Comment by ibc** [comment]
Opss, you must write "fix #NNN" instead of "fixes #NNN" if you want that Github automatically closes the issue :)

**Comment by saghul** [comment]
PR hasn't landed yet ;)

**Comment by ibc** [comment]
right, sorrry
