### ISSUE TITLE
simulation of pipe(2) for uv

### ISSUE THREAD

**Issue by cynron** [joyent/libuv#1257]
Hi, I need a simulation of pipe(2), as follows:

```
uv_stream_t stream[2];
make_anonymous_pipe(loop, stream); 
uv_read_start(loop, &stream[0], alloc_cb, read_cb);
uv_write_req req;
uv_write(&req, &stream[1], bufs, nbufs, write_cb);
```

Will uv support it in the future?
Or if i implement it, any idea? uv_tcp_t or uv_pipe_t should be used?

Thanks

**Comment by indutny** [comment]
I don't mind, but I wonder what it would be on the windows side. cc @piscisaureus @orangemocha
