### ISSUE TITLE
uv_queue_work semantics are inconsistent between platforms

### ISSUE THREAD

**Issue by tarqd** [joyent/libuv#1258]
On Windows libuv uses `QueueUserWorkItem` with the `WT_EXECUTELONGFUNCTION` flag which [more than likely creates a new thread per work item](http://blogs.msdn.com/b/oldnewthing/archive/2011/12/09/10245808.aspx). On unix the thread pool only uses the threads already created by libuv (defaults to 1 per processor core). 

Basically on windows `uv_queue_work` is not much different than just creating a new `uv_thread`. It might be better to allow the user to specify whether or not a task is long running in `uv_queue_work` or only use `WT_EXECUTELONGFUNCTION` for UV-related I/O threads which should be long running. 

It may also be worth it to implement a more powerful thread pool/task queue on unix that has comparable features to `QueueUserWorkItem`, allowing for specifying the expected length of a task and some form of work stealing (the [.net implementation](http://blogs.msdn.com/b/jennifer/archive/2009/06/26/work-stealing-in-net-4-0.aspx) comes to mind).

I do recognize that most short running tasks are probably better implemented by creating a callback executes on the event loops tick (idle/check/prepare) but it does seem strange that `uv_queue_work` has such different semantics on each platform. 

Additional References:
- [Mono's work stealing task scheduler](https://github.com/mono/mono/blob/master/mcs/class/Mono.Parallel/Mono.Threading.Tasks/ThreadWorker.cs)
- [pthread_workqueue](https://github.com/iwinulose/pthread-workqueues)

**Comment by saghul** [comment]
This is a known issue, unfortunately. It has been in our minds for a while but never had the time to tackle it. Some attempts were done in the past to use multiple thread pools (one for fs operations with lots of reduced stack size threads, and another one for getaddrinfo and uv_queue_work) but IIRC results were a bit inconclusive performance wise.

Thanks for putting the report together, it contains several useful references!

Also, in case you feel like giving it a try, patches are always welcome :-)

**Comment by saghul** [comment]
Closing this since after https://github.com/joyent/libuv/commit/8d11aacb79472009189c35e8953d0fa316bfd202 we are using the same threadpool implementation on all platforms, so we are at least consistent.

If you have suggestions / patches for improvements please open a new issue :-) Thanks!
