### ISSUE TITLE
make check

### ISSUE THREAD

**Issue by heysion** [joyent/libuv#1260]
# 

`getaddrinfo_fail` failed: exit code 6
Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
# FAIL: test/run-tests

1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues

**Comment by indutny** [comment]
Sorry, this is not an issue. Generally it is caused by odd local network dns configuration.
