### ISSUE TITLE
Does libuv support SocketCAN？if yes,how to to that?

### ISSUE THREAD

**Issue by hankchan** [joyent/libuv#1268]
I want to use libuv in a SocketCAN read/write app, but I am not sure whether  libuv already support that .  

any suggestion ? 

thanks.

**Comment by indutny** [comment]
I have no idea, but I think it should generally work. If it does not - please let us know.

Also, please use mailing list for non-issue questions.

**Comment by indutny** [comment]
The only quirk is that you'll need to create sockets yourself and pass the fds to the libuv.
