### ISSUE TITLE
uv_tcp_init  thread safe

### ISSUE THREAD

**Issue by noeat** [joyent/libuv#1269]
uv_loop_t *gLoop =  NULL;
void accept_thread(void *)
{
    uv_tcp_t server;
    uv_tcp_init(uv_default_loop(), &server);
    uv_tcp_bind(&server, uv_ip4_addr("0.0.0.0", TEST_PORT));
    uv_listen(&server, SOMAXCONN, connection_cb);
    uv_run(uv_default_loop(), UV_RUN_DEFAULT);
}

void work_thread(void *)
{
    gLoop = uv_loop_new();
    uv_async_t async;
    uv_async_init(loop, &async);
    uv_run(loop, UV_RUN_DEFAULT);
    uv_loop_delete(gLoop);
}

void connection_cb(uv_stream_t _handle, int status)
{
    uv_tcp_t *obj = (uv_tcp_t_)malloc(sizeof(uv_tcp_t));
    uv_tcp_init(gLoop, obj);
    uv_accept(handle, (uv_stream_t*)obj);
}

i use libuv like this, accept is a thread , socket read write is other thread ,I don't known uv_tcp_init(gLoop, obj); and uv_accept(handle, (uv_stream_t*)obj); is thread safe.

thanks!

**Comment by saghul** [comment]
The only thread safe function involving a handle is `uv_async_send`, the rest are not.

PS: Please use the mailing list for questions next time :-)
