### ISSUE TITLE
problem when using libuv for NFS file I/O

### ISSUE THREAD

**Issue by ramesh-rayaprolu** [joyent/libuv#1275]
I am using libuv for async file I/O. However, the files that my application accesses is on NFS mount.

and when the NFS server goes down for some reason when reading a file, the libuv's I/O thread is already running, and will never call back.

In this situation, my application has a timeout implemented, and this will trigger cleanup and deletion of all objects related to the file read. Also, my application continues to do other stuff and is running for ever.

When the NFS come back again (may be after few minutes/hours)...my application is still running, and libuv will end-up giving me the callback for the NFS read that hanged earlier. And, libuv will also try accessing the "uv_fs_req" (which I would have deleted).

I am temporarily holding on deleting this uv_fs_req, just to avoid a crash. This is not a clean fix for me because my application will eventually leak memory in case of negative testing. However, if would be nice if libuv handles such blocking situations and give callback with an error.

I have put this question on libuv groups, and Ben Noordhuis thinks it is possible, and has asked me to file an issue. Please refer to the attachment.

![libuv-nfs-q](https://cloud.githubusercontent.com/assets/7536844/2931930/55e9280a-d7a9-11e3-9924-2a5f01152c66.jpg)

**Comment by indutny** [comment]
Nice, this sounds feasible on some platforms: `uv_cancel` on fs requests. @saghul what do you think about it?

**Comment by ramesh-rayaprolu** [comment]
thanks! I see the point. 

currently uv_cancel would not do anything in such hung fs requests. However, libuv can implement appropriate cleanup with uv_cancel on such fs requests.

Thanks,
Ramesh

**Comment by saghul** [comment]
> Nice, this sounds feasible on some platforms: uv_cancel on fs requests. @saghul what do you think about it?

It would be nice to have, yes. But I guess there are cases which we simply cannot handle: imagine you create a pipe(2) and try to read it with uv_fs_read. Now do that 4 times. All threads of the pool are busy and we cannot do anything about it, since currently all requests are retried on EINTR, so signals won't help, as Ben said...

**Comment by ramesh-rayaprolu** [comment]
@saghul,

I am not completely aware of kernel implementations with respect to NFS read, but it looks like the system call "read" itself was blocked, when the NFS server goes down.

In such case, I guess the libuv thread will just be busy waiting for read to finish, doing nothing.
So my point is - can we cancel (unwind) this thread in such conditions, only if user requests for it by doing a uv_cancel() ? This way, both users and libuv will be in control of thier respective objects.

For instance, if some applications (like mine) intend to "explicitly" cancel the uv callbacks when it identifies that the callback for uv_fs_read() is not coming even after 5 minutes, they should ideally be able to do that right ?

**Comment by saghul** [comment]
Closing. Currently we have no way to deal with this, nor do I know how to do it, to be honest. If you can come up with a solution, please reopen the issue on libuv/libuv.

**Comment by ramesh-rayaprolu** [comment]
@saghul,

Sure, right now I have my alternate solution (as described before) within my application. It does not seem to be a serious issue, otherwise our test teams would have been on me by now. However, I still feel it can be dealt with inside libuv.

Right now, I am working on other stuff, and I shall re-open the issue whenever I get back on this.

Thanks,
Ramesh

**Comment by txdv** [comment]
What OS are you using?

**Comment by ramesh-rayaprolu** [comment]
I am using it on 64 bit centos 6.4. kernel ver - 2.6.32-358. Does it matter in any case ?
Or, do you think 3.x kernels might have different behavior WRT NFS mounts ?

Few weeks back, I really wanted to try using centos 7 and test the scenario, but our project is still using only centos 6.4 (i cant justify upgrading to centos7 yet).

please let me know if you have any better idea..
