### ISSUE TITLE
Assertion failed: ((handle)->flags & UV__HANDLE_CLOSING) == 0

### ISSUE THREAD

**Issue by JCMais** [joyent/libuv#1278]
I'm having this issue with the [libcurl bindings for node](https://github.com/JCMais/node-libcurl) that I'm working on. The same issue is reproducible using the [code present on the uvbook](https://github.com/nikhilm/uvbook/blob/master/code/uvwget/main.c).

It happens only on Windows, the issue is that, when a connection timeout, libcurl try to create a new connection to the next ip, however it fails with the given assertion error.

Example of output:

```
>node examples\simple-request.js www.google.com:81
* Rebuilt URL to: www.google.com:81/
* Hostname was NOT found in DNS cache
*�� Trying 200.149.119.118...
Action: 2
Socket: 00000000
* After 2390ms connect time, move on!
* connect to 200.149.119.118 port 81 failed: Timed out
*�� Trying 200.149.119.89...
Action: 4
Socket: 006A0898
Action: 2
Socket: 00000000
Assertion failed: ((handle)->flags & UV__HANDLE_CLOSING) == 0, file src\win\poll.c, line 190 
```

From what I can see from the curl source code, the connection socket is closed (https://github.com/bagder/curl/blob/master/lib/connect.c#L584), and the socket callback is called (https://github.com/bagder/curl/blob/master/lib/connect.c#L1245 and https://github.com/bagder/curl/blob/master/lib/multi.c#L2092), however when the next connection is made, libuv tries to use a handler that was closed before. (because of the given socket callback being called).

I don't know how the handler is, somewhat, being reused, because the socket callback is called correctly (you can check that on the ouput above, Action 2 means register the uv_handle and 4 means destroy it), and it does close the handler, check: https://github.com/JCMais/node-libcurl/blob/develop/src/Curl.cc#L447.

Anyway, I don't know if this is a bug on libuv, libcurl, on with my code, probably the last one.

**Comment by saghul** [comment]
Hi,

I think I might know what is going on. When you detect the socket needs to be destroyed you call uv_close(handle), which is fine. In order to stop in-flight poll requests libuv will do an extra special poll on Windows. However, when this extra poll is done we are getting AFD_POLL_LOCAL_CLOSE, which I guess it means the socket was closed, by libcurl I assume. That's why the assert blows, because uv__handle_stop checks for it, but the handle is already closing.

Please try this patch: https://gist.github.com/saghul/02567866644aac3d2ac2 which checks if the handle is active before stopping it.

/cc @piscisaureus can you confirm I guessed right?

**Comment by JCMais** [comment]
hm, the patch worked, no error anymore:

```
Added download http://google.com:81 -> 1.download
* Rebuilt URL to: http://google.com:81/
* Hostname was NOT found in DNS cache
*   Trying 173.194.118.135...
* After 938ms connect time, move on!
* connect to 173.194.118.135 port 81 failed: Timed out
*   Trying 173.194.118.136...
* After 462ms connect time, move on!
* connect to 173.194.118.136 port 81 failed: Timed out
*   Trying 173.194.118.131...
* After 228ms connect time, move on!
* connect to 173.194.118.131 port 81 failed: Timed out
*   Trying 173.194.118.142...
* After 111ms connect time, move on!
* connect to 173.194.118.142 port 81 failed: Timed out
*   Trying 173.194.118.128...
* After 48ms connect time, move on!
* connect to 173.194.118.128 port 81 failed: Timed out
*   Trying 173.194.118.129...
* After 17ms connect time, move on!
* connect to 173.194.118.129 port 81 failed: Timed out
*   Trying 173.194.118.132...
* Connection timed out after 2012 milliseconds
```

Btw, I've changed from <code>uv__handle_active</code> to <code>uv__is_active</code>.
There is any way to fix this directly on my code, without patching libuv?

**Comment by saghul** [comment]
> Btw, I've changed from uv__handle_active to uv__is_active.

Ups, typo :-)

> There is any way to fix this directly on my code, without patching libuv?

Thanks for confirming it works. I'll make a PR to get some feedback before landing it.

**Comment by saghul** [comment]
Fix here: https://github.com/joyent/libuv/pull/1282

**Comment by JCMais** [comment]
I'm asking that, because it's probably going to stay broken on nodejs, the current version is 0.10.28, if the PR is accepted, only the next version of node is going to get it, right? so I can probably expect it to be broken on any version <= this one?

**Comment by saghul** [comment]
I'll make a backport ;-)

**Comment by JCMais** [comment]
Ah, ok. Thank you!

**Comment by clemensg** [comment]
@JCMais Glad to hear the problem wasn't in my multi-uv curl example. Thanks for the heads up!

**Comment by saghul** [comment]
Closing, superseded by #1282
