### ISSUE TITLE
[new feature] Lock-free inter-thread communication queue

### ISSUE THREAD

**Issue by gagle** [joyent/libuv#1286]
Currently, as far as I know there isn't a mechanism in the libuv to send data from one random thread to a thread with V8 access. `uv_async_send()` does not guarantee that 1 call generates 1 event, therefore, we need to use some kind of mechanism for transfering the data from one thread to another if we don't want to lose it.

[Someone suggested to use a lock-free queue](https://groups.google.com/forum/#!topic/libuv/FSC643VKRxk) because they are fastest than blocking mutexes. I didn't know about the existence of these kind of algorithms, but I've seen that they are implemented using a [compare-and-swap (CAS) instruction](http://en.wikipedia.org/wiki/Compare-and-swap). I've also seen that libuv is already using this instruction ([atomic-ops.h](https://github.com/joyent/libuv/blob/master/src/unix/atomic-ops.h)), so my request is obvious. I'd like to have a lock-free queue implementation, 1 consumer, 1 producer. This will ease the inter-thread communication because right now we must use other libraries for a task that seems necessary and we currently don't have.

**Comment by indutny** [comment]
Hm... do you want to add this mechanism to libuv? I think it could be implemented as a 3rd party library, i.e. it doesn't need to be in uv.

**Comment by gagle** [comment]
But libuv needs this feature. It's like building a house (libuv) with doors that don't guarantee that you can pass (uv_async_send). IMO a lock-free queue should be included in libuv or at least it would be great to have a reliable function for sending data between 2 threads.

**Comment by saghul** [comment]
Sorry, but libuv doesn't _need_ this feature, you do :-) It could be a nice addition, depending on what you have in mind. Can you come up with a design we can discuss? Devise an API and write some small usage example, that should be enough to kickstart the discussion.

**Comment by indutny** [comment]
The question is how it will integrate into libuv? Via the means of existing `uv_async_send()`?

**Comment by gagle** [comment]
I'm trying to integrate a C lib into node.js. This library streams data from the raspberry pi camera. It internally creates a pthread and begin emitting buffers, so if I want to forward them to the nodejs streaming API I need to send them from a pthread to a thread with V8 context. If I use `uv_async_send()`, the stream gets corrupted because the function does not guarantee that what I send is what I receive. I need the fastest reliable mechanism, that's why I need a lock-free queue. For me it seems the best tool for streaming data from outside the libuv land, otherwise, how do you stream things?

I propose a new function: `uv_stream_send()` and `uv_stream_init()`, just like `uv_async_*`.

The internal code could be:

```
uv_stream_send(p: a pointer to the data):
  queue.enqueue(p)
  ...
```

Then, every loop iteration, execute this code:

```
p
//queue.dequeue() returns false if the queue is empty
while (queue.in_use && !queue.dequeue(&p)){
  callback (p);
}
```

Usage:

``` c
typedef struct {
  uint8_t* buffer;
  uint32_t length;
} chunk_t;

uv_stream_t stream;

void buffer_callback (uint8_t* buffer, uint32_t length){
  //Called from an external pthread, no V8 context

  chunk_t* chunk = (chunk_t*)malloc (sizeof (chunk_t));
  uint8_t* dup_buffer = (uint8_t*)malloc (sizeof (uint8_t)*length);
  memcpy (dup_buffer, buffer, length);

  chunk->buffer = dup_buffer;
  chunk->length = length;

  stream.data = (void*)chunk;
  uv_stream_send (&stream);
}

void buffer_callback_safe (uv_stream_t* handle, int status){
  //V8 context

  chunk_t* chunk = (chunk_t*)handle->data;

  //Convert the unit8_t array to a javascript Buffer object and emit it

  free (chunk->buffer);
  free (chunk);
}

Somewhere:
stream.preallocated_elements_in_the_queue = 100;
stream.dynamic_allocation = false;
uv_stream_init (loop, &stream, buffer_callback_safe);
```

Note: `uv_channel_*` instead of `uv_stream_*` would be also ok.

**Comment by saghul** [comment]
First, uv_stream is already a thing in libuv (the base struct for tcp, pipe and tty handle), so this thing would need another name.

Now, more importantly, I think you can achieve what you want just with libuv and the ck_ring from ConcurrencyKit. Here is the idea:

You'll need 3 handles:
- a uv_prepare_t handle, which will be used to dequeue the items from the ring
- an idle handle to prevent the loop from sleeping for i/o if the queue is not empty
- an async handle, to wakeup the loop

When you get a frame from the camera, you put it in the ring. After X amount of frames you use uv_async_send to wakeup the event loop, just in case it was blocked in an infinite poll.

In the prepare handle callback you process Y elements from the queue. If after Y elements the queue is not empty you start the idle handle. This will prevent the loop from blocking for i/o. As soon as you enter the prepare callback you stop the idle handle, to prevent the loop from spining.

The async / idle handle dance is needed for the eventloop to yield every now and then and allow for i/o to happen.

I hope that helps.

**Comment by gagle** [comment]
Ok, thanks for the help. I'll try your approach. If I succeed I'll post here the solucion along with the repo for a future reference.

**Comment by saghul** [comment]
Closing, not an issue.

**Comment by supercairos** [comment]
Hi, I'm having quite some trouble to understand the need for the idle handle "dance";
Wouldn't it be possible to dequeue directly inside the Async callback ?
