### ISSUE TITLE
uv_tcp_getpeername return -4047

### ISSUE THREAD

**Issue by ymonster** [joyent/libuv#1287]
I use function on_connection in test/test-getsockname.c and modify it a little.
When uv_accpet successed, i try 'uv_tcp_getsockname' and 'uv_tcp_getpeername' with client handle. 
'uv_tcp_getsockname' is successed, but uv_tcp_getpeername failed with return value = -4047, which equals socket error 10014. What happend?

**Comment by saghul** [comment]
Cab you paste the modified code?

**Comment by saghul** [comment]
`struct sockaddr` might not be big enough to hold the result. Use `struct sockaddr_storage` instead and cast it to `struct sockaddr`. Then check for the family using the ss_family field of `sockaddr_storage`, or sa_family if you use the casted `struct sockaddr`. If the family is AF_INET you can cast to `struct sockaddr_in`, if it's AF_INET6 then cast to `struct sockaddr_in6`.

**Comment by ymonster** [comment]
It works.Thank you!
