### ISSUE TITLE
Permission problem with libuv

### ISSUE THREAD

**Issue by holisticode** [joyent/libuv#1288]
Today I tried to install cjdns on a server machine running ubuntu 13.10.

I cloned the repo, and then ran ./do as the tutorial says.
But got a problem, libuv was not being built.

Here's the build log:
http://pastebin.com/cK7uDa2J

I tried to solve with some support at the #cjdns channel but people did not know what could be the problem...

**Comment by saghul** [comment]
What platform are you using? Looks like Python doesn't support cross process semaphores on that platform. This is needed when GYP is run in parallel mode. In order to disable parallel mode gyp needs to be run with ¨--no-parallel".

Closing this, since it's not a libuv issue.

**Comment by holisticode** [comment]
As mentioned in my first post, it's a ubuntu 13.10 system.
uname -a:
Linux vps22516 2.6.32-042stab081.8 #1 SMP Wed Oct 23 16:32:28 MSK 2013 x86_64 x86_64 x86_64 GNU/Linux
