### ISSUE TITLE
test failure on x86_64 Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Jianru-Lin** [joyent/libuv#1290]
<pre>make  check-am
make[1]: Entering directory `/home/jianru/work/libuv'
make  test/run-tests
make[2]: Entering directory `/home/jianru/work/libuv'
make[2]: `test/run-tests' is up to date.
make[2]: Leaving directory `/home/jianru/work/libuv'
make  check-TESTS
make[2]: Entering directory `/home/jianru/work/libuv'

Output from process `platform_output`:
uv_get_process_title: /home/jianru/work/libuv/test/.libs/lt-run-tests
uv_resident_set_memory: 745472
uv_uptime: 1000.000000
uv_getrusage:
  user: 0 sec 1079 microsec
  system: 0 sec 1426 microsec
uv_cpu_info:
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 277400
  times.user: 360500
  times.idle: 8675800
  times.irq: 18000
  times.nice: 11800
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 114400
  times.user: 511600
  times.idle: 8941800
  times.irq: 7700
  times.nice: 200
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 104900
  times.user: 389400
  times.idle: 9266500
  times.irq: 4800
  times.nice: 800
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 86200
  times.user: 415800
  times.idle: 9298100
  times.irq: 4400
  times.nice: 2300
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 67800
  times.user: 252100
  times.idle: 9634600
  times.irq: 1400
  times.nice: 200
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 1400
  times.sys: 67300
  times.user: 358700
  times.idle: 9512700
  times.irq: 1700
  times.nice: 600
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 71400
  times.user: 254400
  times.idle: 9622400
  times.irq: 2600
  times.nice: 14900
  model: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  speed: 800
  times.sys: 130500
  times.user: 256100
  times.idle: 9434900
  times.irq: 48600
  times.nice: 100
uv_interface_addresses:
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: wlan0
  internal: 0
  physical address: 00:08:ca:c0:36:58
  address: 192.168.0.102
  netmask: 255.255.255.0
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: wlan0
  internal: 0
  physical address: 00:08:ca:c0:36:58
  address: fe80::208:caff:fec0:3658
  netmask: ffff:ffff:ffff:ffff::
=============================================================

`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
=============================================================

FAIL: test/run-tests
=======================================================
1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues
=======================================================
make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory `/home/jianru/work/libuv'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/jianru/work/libuv'
make: *** [check] Error 2
</pre>

**Comment by saghul** [comment]
The getaddrinfo test can give false positives due to transient network problems. It's known to work fine. Closing.

**Comment by Jianru-Lin** [comment]
ok, thanks.
