### ISSUE TITLE
Clarify return values of uv_run(UV_RUN_NOWAIT)

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1297]
libuv.h does not clarify the return value of uv_run() when called with UV_RUN_NOWAIT:

```
UV_RUN_NOWAIT: Poll for new events once but don't block if there are no pending events.
```

Please document it.

**Comment by saghul** [comment]
Return value is same as UV_RUN_ONCE. I'll add a note.

**Comment by ibc** [comment]
Thanks.

**Comment by saghul** [comment]
https://github.com/joyent/libuv/commit/aab8d9dab45d03d9df01a7deab7ae1f2ebe9ada3
