### ISSUE TITLE
Add a version policy

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1299]
It would be really nice if the libuv version numbers mean something about the API. I suggest something like this:
- Two libuv versions with same MAJOR and MINOR numbers are 100% API compatible.
- A version with same MAJOR and MINOR numbers but a greater PATCH number just includes internal improvements or bug fixes.
- A version with different MAJOR or MINOR number includes new features and/or non backward compatible API changes.

This would really help developers whose code relies on libuv.

**Comment by saghul** [comment]
This is already the case. It not written anywhere, but that's how its currently done. ABI is also maintained within the same minor version.
