### ISSUE TITLE
Shared library

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1303]
Why did the libuv.so target disappear again?

**Comment by saghul** [comment]
When using autoconf I believe both the static and the shared library are built. Have you checked the .libs directory?

**Comment by txdv** [comment]
seems like it, confused me like shit

**Comment by jbergstroem** [comment]
Pretty sure `make install` would install them for you as well. Using libtool with autotools at least makes building/installing libraries easier.

**Comment by txdv** [comment]
Well, i don't want to install them, i want to compile them!
