### ISSUE TITLE
Notification of interface IP Address Change

### ISSUE THREAD

**Issue by Pagghiu** [joyent/libuv#1305]
Hi everyone,

I am planning to add IP Address change notifications to my software that already uses libuv and, according to what I know, no api for handling this notification exists in libuv.

Initially I will probably do something very simple and rude like checking ip address at regular intervals with a timer.
I've quickly been searching if an async API for those OS notification exists.
On Windows (XP+) there is an async function that looks for IPV4 Address change and posts to an overlapped port.

http://msdn.microsoft.com/en-us/library/windows/desktop/aa366329(v=vs.85).aspx

On Windows Vista+ there is an equivalent function that handles both IPV4 and IPV6 linked at the previous msdn page.

I still have a couple of questions: 

1) Does anyone know if  async equivalenst of this function actually exists for Unixes ?
2) May this issue fit into a "feature request" or is it completely uninteresting for libuv?

in case 2) answer could be "yes" it would be nice to know any previous work on the topic if it exists.

Thanks.

Stefano Cristiano

**Comment by indutny** [comment]
Hello!

Mind moving this conversation to the mailing list? It seems that it really belong here.
