### ISSUE TITLE
cross compile,  build

### ISSUE THREAD

**Issue by qvbige240** [joyent/libuv#1309]
Hi, I have a problem about cross-compiling with libuv, My ARM Linux Tool Chain is arm_linux_4.2, and there are some errors at 'make', The following is my operation:
$ ./autogen.sh 
$ ./configure --host=arm-linux --prefix=$PWD/_install
$ make
make  all-am
make[1]: Entering directory `/home/osource/libuv/libuv'
  CC     src/libuv_la-fs-poll.lo
In file included from ./include/uv.h:62,
                 from src/fs-poll.c:22:
./include/uv-unix.h:128: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'uv_rwlock_t'
./include/uv-unix.h:145: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'uv_barrier_t'
In file included from src/fs-poll.c:22:
./include/uv.h:2178: error: expected ')' before '_' token
./include/uv.h:2179: error: expected ')' before '_' token
./include/uv.h:2180: error: expected ')' before '_' token
./include/uv.h:2181: error: expected ')' before '_' token
./include/uv.h:2182: error: expected ')' before '_' token
./include/uv.h:2183: error: expected ')' before '_' token
./include/uv.h:2184: error: expected ')' before '_' token
./include/uv.h:2185: error: expected ')' before '_' token
./include/uv.h:2221: error: expected ')' before '_' token
./include/uv.h:2222: error: expected ')' before '_' token
./include/uv.h:2223: error: expected ')' before '_' token
./include/uv.h:2275: error: expected specifier-qualifier-list before 'uv_rwlock_t'
make[1]: *_\* [src/libuv_la-fs-poll.lo] Error 1
make[1]: Leaving directory `/home/osource/libuv/libuv'
make: **\* [all] Error 2

**Comment by saghul** [comment]
Sorry nobody followed up on this. Can you please try with latest 1.0 release and reopen in libuv/libuv if it still applies? Thanks!
