### ISSUE TITLE
uv_write crash from time to time

### ISSUE THREAD

**Issue by ymonster** [joyent/libuv#1314]
I wrote some codes to build a simple tcp-server with libuv.
I use one thread to run event loop like this

```
void thread_ffn( void *param ）
{
      while(true)
           uv_run ( (uv_loop_t *)param, UV_RUN_DEFAULT );
}
```

At main thread, Use _uv_listen_ to listen at some port, and in connection callback, allocate a uv_tcp_t pointer as client handle. Then I pass this handle to a worker thread. 

At worker thread, I use _uv_write_ to send message with that client handle. It will crash from time to time.

Crash at _UNREGISTER_HANDLE_REQ_ in function _uv_process_tcp_write_req_. It seems _uv_write_ increase activecnt and _uv_run_ decrease activecnt in different thread cause race condition.

How can i solve this problem ?

**Comment by saghul** [comment]
You cannot use libuv like this, it's not thread safe. If you have libuv usage questions please use the mailing list instead.
