### ISSUE TITLE
Implement cross-platform mkdtemp

### ISSUE THREAD

**Issue by Hinidu** [joyent/libuv#1315]
We at https://github.com/neovim/neovim have faced with the need of porting glibc's mkdtemp to Windows. Would it make sense to make PR in your project for this? Perhaps introducing `uv_fs_mkdtemp` function.

**Comment by saghul** [comment]
I'd be OK with it. @indutny?

**Comment by txdv** [comment]
Are you going to submit a patch for libuv?

**Comment by Hinidu** [comment]
@txdv Sorry I was quite busy last month. I hope that I can make a patch in the near future.
With what purpose you are asking? If you want to do it yourself I don't mind.

**Comment by txdv** [comment]
With the intent to close this issue if you leave it unresolved.

I'm currently working on tcp/udp so I have enough on my plate already.

@Hinidu are you going to come up with a patch?

**Comment by saghul** [comment]
@txdv you don't need to do it yourself. I also wanted to close all unresolved issues but then we might lose track. So I'll leave them open for now.

**Comment by txdv** [comment]
@saghul "you don't need to do it yourself." - you mean like going through all the issues and read them up?

**Comment by saghul** [comment]
@txdv no, I mean implement the requested feature. I would like to have this feature implemented, but if we close the issue we'll forget about it. I do feel distressed about the 100+ issues, but well, there so much that can be done.

**Comment by txdv** [comment]
This looks similar to this issue: https://github.com/joyent/libuv/issues/1277

**Comment by saghul** [comment]
Closing, continues on https://github.com/joyent/libuv/pull/1368.
