### ISSUE TITLE
unix: prepare handles run too early

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#1317]
The core event loop on UNIX currently looks like this:

``` c
uv__run_idle(loop);                                                          
uv__run_prepare(loop);                                                       
uv__run_pending(loop);                                                       
uv__io_poll(loop, timeout);
uv__run_check(loop);
```

Prepare callbacks are supposed to run right before entering uv__io_poll() but libuv currently runs pending callbacks after prepare callbacks and before polling.

To illustrate why that's problematic: taking node as an example, there are times where you want to relinquish control of the isolate so that another thread can enter the VM while you're waiting for I/O.

That's not possible now because I/O callbacks may run after prepare callbacks.  That means there is no point in time where it's safe to release control.

Node is just an example.  Any application that has a resource that it wants to release before sleeping is affected by this bug.

**Comment by saghul** [comment]
Hey Ben!

I think you are right. Here is how Windows does it:

```
    uv_process_timers(loop);                                                                     
    uv_process_reqs(loop);
    uv_idle_invoke(loop);
    uv_prepare_invoke(loop);

    /* poll */

    uv_check_invoke(loop);
```

So, in order to be consistent we could run the pending io callbacks before the idle handles, right after the timers. Thoughts?

**Comment by bnoordhuis** [comment]
Yes, that seems like the correct order.

**Comment by saghul** [comment]
Fixed, thanks Ben!
