### ISSUE TITLE
windows: Read console input using ReadConsoleW

### ISSUE THREAD

**Issue by retep998** [joyent/libuv#1322]
Currently libuv on Windows calls ReadConsoleA to read console input which causes unicode characters to turn into question marks. By switching to ReadConsoleW and then converting the utf-16 to utf-8, unicode will be fully supported.

https://github.com/joyent/libuv/blob/master/src/win/tty.c#L323

Unfortunately, this means libuv will need to have a second buffer into which it can temporarily read the console input before converting it into utf-8 to store in the output buffer.

**Comment by saghul** [comment]
Could you submit a PR with these changes? As for the buffer, maybe a in-stack auxiliary buffer can be used, IIRC we have done that for other utf-8 conversions.

**Comment by saghul** [comment]
PR lande, thanks a lot for working on this!
