### ISSUE TITLE
InitializeCriticalSection can throw an exception on out of memory conditions

### ISSUE THREAD

**Issue by mstewartgallus** [joyent/libuv#1329]
InitializeCriticalSection can throw an exception on out of memory conditions.

It's use should be replaced by InitializeCriticalSectionAndSpinCount so the error can be caught and reported.

The uses are:
- https://github.com/joyent/libuv/blob/master/src/win/signal.c#L38
- https://github.com/joyent/libuv/blob/master/src/win/thread.c#L133
- https://github.com/joyent/libuv/blob/master/src/win/tty.c#L97
- https://github.com/joyent/libuv/blob/master/src/win/util.c#L74

**Comment by indutny** [comment]
Hello, thank you!

Would it be interesting for you to provide a Pull Request fixing it?

**Comment by mstewartgallus** [comment]
Sure, I would like to but I don't think libuv builds on gcc's cross compiler or runs under wine and I don't have a Windows VM at the moment.

**Comment by saghul** [comment]
> Sure, I would like to but I don't think libuv builds on gcc's cross compiler or runs under wine and I don't have a Windows VM at the moment.

It does build!

```
./autogen.sh
./configure --host i686-w64-mingw32
make
```

That's how I do it, FWIW.

Anyway, I don't think you'll need to compile it, you just plan to `abort()` in case of error, right?

**Comment by mstewartgallus** [comment]
I'll double check building libuv but maybe I just have an old version
of the Windows headers on my old distribution.

I don't think libuv has a clear and documented policy on memory
management and if it should abort on memory allocation errors with
functions such as `InitializeCriticalSection`. Does libuv promise to
report back all errors of being unable to allocate memory? If it
doesn't then defining `ENOMEM` is a lie to users of libuv and should
be removed.  Having an inconsistent policy on this would be really,
really bad and possibly cause security vulnerabilities.

I have two ideas for possible good memory handling policies:
- libuv should report memory allocation failures back through error
  variables with all libuv function calls.
  - libuv is a low level IO abstraction method for servers and VMs. It
    should support handling out of memory conditions so that malicious
    VM programs and malicious server clients can't attack the VM or
    server and so that such attacks can be tracked and reported.
  - Moreover, having libuv not being able to handle out of memory
    failures means that low level privileged system service that must
    not fail can not use libuv.
- libuv should log and abort on all memory allocation failures
  - Current operating systems don't encourage handling out of memory
    conditions at a per function level anyways. They have overcommit
    policies and swap memory out to disk. For that reason, libuv
    should log and abort on all memory allocation failures so that a
    higher privileged and easier to audit tiny server manager can ban
    malicious clients, report the failure and restart the server or
    VM.
  - Moreover, even if memory could be locked in RAM it would be a
    possible security risk as malicious clients of a server or
    programs in a VM using libuv could mount Slowloris type attacks
    against the server or VM as connections couldn't be paged out of
    memory.
  - Failing is a fact of life. There can always be a sudden power
    outage or component failure. Properly written programs should be
    able to handle the user yanking the power cord.

**Comment by saghul** [comment]
> I don't think libuv has a clear and documented policy on memory
> management and if it should abort on memory allocation errors with
> functions such as InitializeCriticalSection. Does libuv promise to
> report back all errors of being unable to allocate memory? If it
> doesn't then defining ENOMEM is a lie to users of libuv and should
> be removed. Having an inconsistent policy on this would be really,
> really bad and possibly cause security vulnerabilities.

Unfortunately no, there is no clear documented policy. We do report memory errors, where/when possible. I'm not sure we could come up with a set of rules that can be applied always. Basically I'd say it boils down to:
- if a memory error  occurs when the user calls a function we report it
- if there is an unrecoverable error we abort()
- if there is an error in some internal processing or an unrecoverable condition is met, we usually abort(), but this studied on a case by case basis

**Comment by mstewartgallus** [comment]
Having a mix of both reporting errors and aborting is really, really bad. This means users have to pay the mental cost of checking for out of memory conditions and also have to handle the fact that libuv can abort their process on them.

For example, consider the case of Neovim which uses libuv for it's IO. Because libuv reports out of memory errors if Neovim doesn't check for out of memory conditions after calling functions from libuv Neovim could accidentally obtain a null pointer instead of an allocated buffer. If such a buffer was really big then Neovim could write not to the unmapped memory page starting at zero but past it and into valid to write to program memory and therefore cause memory corruption which when saved would corrupt one's file. Alternatively, because libuv can also abort on internal out of memory conditions if Neovim doesn't make sure to overwrite save files atomically then Neovim could abort on an out of memory condition and leave a corrupted file (I'm pretty sure that Neovim probably writes to a temporary file on the same filesystem and atomically renames over the old file but this is still an extra pitfall one has to handle). These all would be bugs in Neovim but libuv's current behaviour would make both bugs worse.

**Comment by saghul** [comment]
> Having a mix of both reporting errors and aborting is really, really bad. This means users have to pay the mental cost of checking for out of memory conditions and also have to handle the fact that libuv can abort their process on them.

I won't argue that the current situation is ideal, but it is what it is. There is no mental effort to be made AFAIS: libuv will report memory errors when it can, just like others, they are not treated different, so it's responsibility of the user to check for errors, of course. Yes, libuv may assert/abort() under certain exceptional conditions, but those are usually strategically placed to catch bugs, or when unrecoverable errors happen.

> For example, consider the case of Neovim which uses libuv for it's IO. Because libuv reports out of memory errors if Neovim doesn't check for out of memory conditions after calling functions from libuv Neovim could accidentally obtain a null pointer instead of an allocated buffer. If such a buffer was really big then Neovim could write not to the unmapped memory page starting at zero but past it and into valid to write to program memory and therefore cause memory corruption which when saved would corrupt one's file. 

That is not the case. If libuv cannot allocate memory for something it won't swallow the error, it will return it and the user needs to check for it, just like any other error.

> Alternatively, because libuv can also abort on internal out of memory conditions if Neovim doesn't make sure to overwrite save files atomically then Neovim could abort on an out of memory condition and leave a corrupted file (I'm pretty sure that Neovim probably writes to a temporary file on the same filesystem and atomically renames over the old file but this is still an extra pitfall one has to handle). These all would be bugs in Neovim but libuv's current behaviour would make both bugs worse.

If an unrecoverable error condition is met libuv will abort(), that's how things are. If you think you can improve this, please go ahead and write some design document and open a new issue where we can check it and analyze all current occurrences of abort().

**Comment by mstewartgallus** [comment]
> That is not the case. If libuv cannot allocate memory for something it won't swallow the error, it will return it and the user needs to check for it, just like any other error.

No, no. I'm not saying that libuv will swallow the error! I'm just saying that having libuv report the error instead of aborting and having the user check the error is yet another thing the user has to worry about.

> If an unrecoverable error condition is met libuv will abort(), that's how things are. If you think you can improve this, please go ahead and write some design document and open a new issue where we can check it and analyze all current occurrences of abort().

Sure, this conversation is off topic for this specific bug anyways.

**Comment by saghul** [comment]
> No, no. I'm not saying that libuv will swallow the error! I'm just saying that having libuv report the error instead of aborting and having the user check the error is yet another thing the user has to worry about.

The user already needs to check for errors, ENOMEM is in no way special, just look around the code. Also, libuv tries to malloc as little memory as possible. We push the responsibility to the user for allocating buffers, handles, loops and so on.

**Comment by saghul** [comment]
The discussion did derail a bit :-) I'm closing this, if you want go catch those erros in InitializeCriticalSection please send a pull request and I'll happily review it!

**Comment by txdv** [comment]
This is exactly what I said and I never read that post!

Open up this bug, I will fix it myself!

**Comment by saghul** [comment]
> Open up this bug, I will fix it myself!

Feel free to send a PR and ref this bug, thanks Andrius.

**Comment by txdv** [comment]
Reentrant library, do you remember?

**Comment by saghul** [comment]
Yep. We probably have some more, they'll show up with time and we can make things better gradually :-)

**Comment by txdv** [comment]
The reason why I didn't post more in the reentrant library pull request is because I thought 0.12 is just around the corner and you just want the current shit to be delivered.

**Comment by saghul** [comment]
Yeah. that was the idea. But in the end I want to ship the API docs, so there is a bit of time and we chan add a few more bugfixes there. As you have seen I also plan to add uv_fileno. If I work all the time on the docs I go nuts, gotta write some actual code :-)

**Comment by txdv** [comment]
uv_fileno is a function addition, not behavioral change - it can be added whenever one feels coding it.

**Comment by txdv** [comment]
According to http://msdn.microsoft.com/en-us/library/windows/desktop/ms683472(v=vs.85).aspx

```
Windows Server 2003 and Windows XP:  In low memory situations, InitializeCriticalSection can raise a STATUS_NO_MEMORY exception. This exception was eliminated starting with Windows Vista.
```

The function doesn't return the exception since Windows Vista, only on Windows XP and Windows Server 2003.

**Comment by saghul** [comment]
Windows < Vista will be going away after the next release, I wouldn't bother about it :-)

**Comment by txdv** [comment]
It is actually not that hard of an exception to check: http://msdn.microsoft.com/en-us/library/swezty51.aspx

I would add this.

**Comment by txdv** [comment]
Ok, actually it is, because mingw doesn't understand #include exception.

I don't think msys2/mingw/whatever has the header files for SEH exceptions.

**Comment by txdv** [comment]
Ok, only for Windows XP and Windows 2003 with the microsoft visual compiler and SEH extensions.

I think it is save to close this, because mingw doesn't even support SEH (or for that matter any other compiler) and Microsoft has removed it itself, because they didn't see any value in it.

**Comment by saghul** [comment]
Ok, closing then. Thanks for looking into it, Andrius.

**Comment by mstewartgallus** [comment]
@txdv that's great news then.
