### ISSUE TITLE
Darwin should let realpath allocate memory with a NULL argument

### ISSUE THREAD

**Issue by mstewartgallus** [joyent/libuv#1330]
I don't own a Mac so I can't contribute the change but at https://github.com/joyent/libuv/blob/master/src/unix/darwin.c#L79 realpath is passed a large buffer pointlessly when realpath can allocate the memory itself.

**Comment by saghul** [comment]
That doesn't work on OSX 10.5, we had it before (https://github.com/joyent/libuv/commit/637d976c195d690ef96344fd7415cfc29546b868). The current approach works on all versions and I see nothing wrong with it.
