### ISSUE TITLE
sizeof loop in the unstable version

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1334]
I see that the API for creating a loop instance has been changed.

It used to be uv_loop_t\* uv_loop_new() which would allocate the memory on its own, but now it is uv_loop_init(uv_loop_t\* loop) so the user has to manage the memory of the loop struct.

The problem here is that the size of uv_loop_t is not exposed through ffi calls (compared to all the request and handle sizes). This makes it more difficult to write bindings with languages which only support ffi.

uv_loop_t is neither a handle nor a request so I propose to add a function uv_loop_size which returns sizeof(uv_loop_t).

**Comment by saghul** [comment]
Sounds good to me! Mind writing the patch?

**Comment by txdv** [comment]
Here you go

**Comment by indutny** [comment]
Landed?
