### ISSUE TITLE
test: spawn_setuid_setgid fails on Linux

### ISSUE THREAD

**Issue by mguryanov** [joyent/libuv#1339]
Ubuntu 12.04.2 LTS (Precise Pangolin)

`spawn_setuid_setgid` failed: exit code 134
Output from process `spawn_setuid_setgid`:
Assertion failed in test/test-spawn.c on line 988: r == 0

**Comment by saghul** [comment]
Can you print the error you get? Either stick a printf there or run the individual test with `run-tests spawn_setuid_setgid spawn_setuid_setgid` and inspect the generated core file.

**Comment by recp** [comment]
This test also fails on my Fedora20 (on AWS). I run make check as root.

GCC version (4.8.3):

```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140624/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140624/obj-x86_64-redhat-linux/cloog-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140624 (Red Hat 4.8.3-1) (GCC) 
```

kernel name:

```
# uname -rm
3.11.10-301.fc20.x86_64 x86_64

# cat /etc/fedora-release
Fedora release 20 (Heisenbug)
```

Test results:

```
[%  76|+ 182|-   0|T   0|S   0]: spawn_setuid_setgid
`spawn_setuid_setgid` failed: exit code 6
Output from process `spawn_setuid_setgid`:
Assertion failed in test/test-spawn.c on line 1054: r == 0
=============================================================
[% 100|+ 237|-   1|T   0|S   0]: Done.
```

**Comment by saghul** [comment]
Can you get the error code?

**Comment by recp** [comment]
How can I get related error code? Debugging on Fedora using GDB? or is there any err-code on the test results?

I run the following cmd as you say before

```
# ./run-tests spawn_setuid_setgid spawn_setuid_setgid
Assertion failed in test/test-spawn.c on line 1054: r == 0
Aborted
```

it seems uv_spawn can't pass the following assert:

```
  r = uv_spawn(uv_default_loop(), &process, &options);
  ASSERT(r == 0);
```

**Comment by saghul** [comment]
We need to know what the value of r is. You can just add a print or inspect
the core file.

**Comment by recp** [comment]
It is -13. The uv_spawn returns this val. I've run twice. Same result: -13

**Comment by saghul** [comment]
That's EACCESS. It's probably not an issue, but I have no idea why it fails
:-S

If anyone has any idea I'm all ears.

On Friday, September 12, 2014, Recep ASLANTAS notifications@github.com
wrote:

> It is -13. The uv_spawn returns this val. I've run twice. Same result: -13
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joyent/libuv/issues/1339#issuecomment-55339528.

## 

/Saúl
bettercallsaghul.com

**Comment by saghul** [comment]
@recp who owns and what are the permissions of run-tests?

**Comment by recp** [comment]
```
# ls -l test/run-tests
-rwxr-xr-x. 1 root root 12088 Sep 11 22:38 test/run-tests
```

The SELinux is active, can SELinux cause the issue (Ive no idea how)?

```
# getenforce
Enforcing
```

**Comment by saghul** [comment]
I'm 99.999% possitive this is a environment issue, not a libuv issue. But I'd like to know what it is to point people in some direction before we close this.

**Comment by recp** [comment]
@saghul Ive just run the test codes (spawn_setuid_setgid) in a separate file like below, it passed. Maybe this is not good idea but it works on Fedora (also on OS X). But that fails in make check :/

``` C
#include <stdio.h>
#include <assert.h>
#include <uv.h>

uv_process_t process;
uv_process_options_t options;

int exit_cb_called = 0;
int close_cb_called = 0;

void on_close(uv_handle_t* handle) {
    close_cb_called = 1;
}

void on_exit(uv_process_t * req, int64_t exit_status, int term_signal) {
    exit_cb_called = 1;
    uv_close((uv_handle_t*) req, on_close);
}

int main() {
    int r;

    /* if not root, then this will fail. */
    uv_uid_t uid = getuid();
    if (uid != 0) {
        fprintf(stderr, "spawn_setuid_setgid skipped: not root\n");
        return 0;
    }

    //   init_process_options("spawn_helper1", exit_cb);
    char * filename = "echo";
    char* args[3];
    args[0] = filename;
    args[1] = "Hello";
    args[2] = NULL;
    options.file = filename;
    options.args = args;
    options.exit_cb = on_exit;
    options.flags = 0;

    /* become the "nobody" user. */
    struct passwd* pw;
    pw = getpwnam("nobody");
    assert(pw != NULL);
    options.uid = pw->pw_uid;
    options.gid = pw->pw_gid;
    options.flags = UV_PROCESS_SETUID | UV_PROCESS_SETGID;

    r = uv_spawn(uv_default_loop(), &process, &options);
    assert(r == 0);

    r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
    assert(r == 0);

    assert(exit_cb_called == 1);
    assert(close_cb_called == 1);

    printf("Test Passed. \n");
    return 0;
}
```

```
# gcc -o spawn-test ./spawn-test.c -I /usr/local/include -L /usr/local/lib -luv -std=gnu89
# ./spawn-test 
Test Passed. 
```

**Comment by saghul** [comment]
Did you change anything in the test? I can't just eyeball it :-/

**Comment by recp** [comment]
@saghul I just changed process file name to "echo" and exit_cb as my previous comment.

**Comment by recp** [comment]
I've just changed test-spawn.c like below (All tests passed on Fedora):

I think uv_spawn couldn't spawn itself by exepath (uv_exepath). Because I think it is behave like a recursive fn and Linux does not approve the operations. Its my idea.

``` C
// I duplicated this fn for exit_cb2 
static void init_process_options2(char* test, uv_exit_cb exit_cb) {
  /* Note spawn_helper1 defined in test/run-tests.c */
  int r = uv_exepath(exepath, &exepath_size);
  ASSERT(r == 0);
  exepath[exepath_size] = '\0';
  args[0] = "echo";// exepath;
  args[1] = test;
  args[2] = NULL;
  options.file = "echo"; // exepath;
  options.args = args;
  options.exit_cb = exit_cb2;
  options.flags = 0;
}

// I duplicated this fn for one ASSERT for echo
static void exit_cb2(uv_process_t* process,
                    int64_t exit_status,
                    int term_signal) {
  printf("exit_cb\n");
  exit_cb_called++;
 /* I duplicated the fn for the ASSERT (it was exit_status==1). Because echo exits with 0  */
  ASSERT(exit_status == 0); 
  ASSERT(term_signal == 0);
  uv_close((uv_handle_t*)process, close_cb);
}

TEST_IMPL(spawn_setuid_setgid) {
  int r;

  /* if not root, then this will fail. */
  uv_uid_t uid = getuid();
  if (uid != 0) {
    fprintf(stderr, "spawn_setuid_setgid skipped: not root\n");
    return 0;
  }

  init_process_options2("spawn_helper1", exit_cb); // I changed this
// ....
```

**Comment by saghul** [comment]
This test passes for me on all Linux boxes I have available, and also Jenkins. It has to be an environment problem somehow.

**Comment by recp** [comment]
Which environment settings can cause the test issue? There are two run-tests in the folder test/.libs/

```
# ls test/.libs/
lt-run-tests  run-tests
```

I was printed exepath for the test and I saw it was trying spawn the `lt-run-tests` file so it couldn't. The my OS X has only run-tests file :/

**Comment by saghul** [comment]
I don't know what causes it, unfortunately :-( When I run the tests on my Debian machine I have both files too and the test passes.

**Comment by recp** [comment]
All tests passed on my OS X (10.10) but when I run the test individual as the following cmd AFTER MAKE CHECK I got the same assert like Fedora:

```
% 100|+ 239|-   0|T   0|S   0 : Done.
PASS: test/run-tests
=============
1 test passed
=============
recp:libuv-master recp$  sudo ./test/run-tests spawn_setuid_setgid spawn_setuid_setgid
Password:
r: -13
Assertion failed in test/test-spawn.c on line 1055: r == 0
```

Is it expecting result?

**Comment by recp** [comment]
I guess if we will use another process for spawn tests such as `echo | mkdir | custom-executable` rather than itself (lt-run-tests  or run-tests) the tests will be passed on all systems (if there are no err :) ). Maybe I'm missing somethings about the tests. Because the test also fails on OS X like my prev-comment.

**Comment by saghul** [comment]
I think I know why it might fail: the test is skipped when not running as root, which means that if the test is actually executed, you are root. Now, when downgrading to Mr. "nobody", you might not have enough rights to reach the executable in the path.

Also, FWIW, test passes for me on OSX 10.10 when I run it just like you do.

**Comment by saghul** [comment]
Ok I'm closing this since my previous comment has proved to be correct. See also #1488. A patch which skips the test if `uv_spawn` gives the proper error would be acceptable, but as a general rule of thumb, don't run the tests as root in a directory where only root can read.
