### ISSUE TITLE
make check failed / FAIL: tests/run-tests on getaddrinfo_fail

### ISSUE THREAD

**Issue by paulctan** [joyent/libuv#1341]
name: eth0
  internal: 0
  physical address: 90:e6:ba:d6:08:0f
  address: fe80::92e6:baff:fed6:80f
#   netmask: ffff:ffff:ffff:ffff::

`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `/home/ptan/libuv/libuv-master'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`/home/ptan/libuv/libuv-master'
make: **\* [check] Error 2
ptan@Arcanine:~/libuv/libuv-master$

ptan@Arcanine:~/libuv/libuv-master$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:        12.04
Codename:       precise
ptan@Arcanine:~/libuv/libuv-master$

ptan@Arcanine:~/libuv/libuv-master$ ifconfig
eth0      Link encap:Ethernet  HWaddr 90:e6:ba:d6:08:0f
          inet addr:10.1.77.31  Bcast:10.1.77.255  Mask:255.255.255.0
          inet6 addr: fe80::92e6:baff:fed6:80f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3715692 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2440597 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3113402392 (3.1 GB)  TX bytes:303721631 (303.7 MB)
          Interrupt:44 Base address:0xc000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:441364 errors:0 dropped:0 overruns:0 frame:0
          TX packets:441364 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:555479988 (555.4 MB)  TX bytes:555479988 (555.4 MB)

ppp0      Link encap:Point-to-Point Protocol
          inet addr:172.20.0.8  P-t-P:216.151.180.4  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1392  Metric:1
          RX packets:901316 errors:0 dropped:0 overruns:0 frame:0
          TX packets:630916 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:999347251 (999.3 MB)  TX bytes:57408581 (57.4 MB)

ptan@Arcanine:~/libuv/libuv-master$

**Comment by saghul** [comment]
This test can fail due to network conditions, closing since it's not an actual bug.

**Comment by paulctan** [comment]
Yes, I saw the previous similar closed bug.  You guys should really make it a warning then instead of a failure.  I would consider this a problem with the testing methodology instead of the test itself.
Just my $0.02 worth.

**Comment by saghul** [comment]
The test suite can only report success or failure, unfortunately.
