### ISSUE TITLE
pread returns 0 instead of read bytes on iOS

### ISSUE THREAD

**Issue by BlackWolf** [joyent/libuv#1346]
I am using https://github.com/node-app/Nodelike and am therefore running libuv on iOS devices. Today I got around to inspecting problems with asynchronous file reads (which always returned an empty response) and noticed the following: 

`uv__fs_read` in _fs.c_ calls `pread` in _unistd.h_, which seems to return 0 instead of the number of read bytes on iOS. Using `read` instead fixes the issue. Since I have extremely limited C-knowledge I haven't put together a pull request, because I have not really much of an idea how to do this cleanly (or if this fix is even a good one). Any opinions?

**Comment by saghul** [comment]
Did you find any reference to this online? pread works just fine on OSX and I'd guess they use the same implementation on iOS.

What value are you passing to offset? -1?

**Comment by BlackWolf** [comment]
Hi, thanks for the response.
I just checked, and you are right - this is not a general issue but an issue specific to the call Nodelike makes. And you are also right that the issue is caused by the offset being `-1`, temporarily changing that to `0` fixes the problem. Is -1 supposed to work or is Nodelike passing the wrong parameters?

**Comment by saghul** [comment]
AFAIK -1 should work. It does work on OSX, Windows and Linux, since it's what the libuv test suite uses. Maybe iOS doesn't like it so much, though it's weird. Anyway, 0 should do :-)
