### ISSUE TITLE
unix: fix pipe_bind_error_addrinuse preferably without lock file

### ISSUE THREAD

**Issue by ry** [joyent/libuv#135]

**Comment by bnoordhuis** [comment]
Yes, please. Seeing that test fail makes me sad. But how without a lock file?

That `fcntl(sockfd, F_GETOWN)` hack you suggested doesn't work as I think you think it does: you can't `open()` UNIX sockets (raises ENXIO) and calling `fcntl(sockfd, F_GETOWN)` on an unbound socket is an exercise in futility - the owner is always the current process.

**Comment by bnoordhuis** [comment]
Duplicate of #124, continues there.
