### ISSUE TITLE
Set SO_REUSEADDR for binding tcp on windows

### ISSUE THREAD

**Issue by retep998** [joyent/libuv#1352]
On unix SO_REUSEADDR is enabled for tcp listeners, but it isn't enabled on windows despite the same option existing.

Either this is a bug that needs to be fixed, or there is a good reason why it is like this and it should be documented properly.

**Comment by saghul** [comment]
Thanks for the report, looks like a bug indeed, I'll look into it.

**Comment by saghul** [comment]
@retep998 can you provide a patch?

**Comment by retep998** [comment]
Patch created as #1360

**Comment by saghul** [comment]
Continuing there.
