### ISSUE TITLE
Not initialized fields.

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1361]
Hey, I found this: https://github.com/joyent/libuv/blob/c44f264641bd60bdc53b6e3f2e56d82ba43011d8/test/test-tcp-try-write.c#L44-L48

I wonder if the fields need to be initialized.

I think that this is undefined behavior and the compiler can do what ever it wants it just happens that most of the time it is initialized with 0 on most of the systems.

**Comment by saghul** [comment]
Static variables are always initialized to 0.
