### ISSUE TITLE
unused variables warning

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1362]
How about we turn on the unused variable flag for the C compiler.

I noticed that when reviewing my patch, saghul found some unused variables. Should be the compilers jobs to check for those little buggers.

I bet it would reveal a lot of those unused variables.

**Comment by saghul** [comment]
How do you compile it? I use GYP and always get the warnings. We have a pending issue for turning on **all** warnings, but requires careful checking of each of the ones produced right now, and unfortunately I have no time for it ATM.

**Comment by txdv** [comment]
make

**Comment by saghul** [comment]
> make

Well, I also use make, but how do you generate the makefile, with autotools or GYP?

**Comment by txdv** [comment]
autotools!

**Comment by saghul** [comment]
Can you try this patch?

```
diff --git a/Makefile.am b/Makefile.am
index e62fbac..16ea7ca 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -81,6 +81,7 @@ else  # WINNT

 include_HEADERS += include/uv-unix.h
 AM_CPPFLAGS += -I$(top_srcdir)/src/unix
+libuv_la_CFLAGS += --std=gnu89 -pedantic -Wall -Werror -Wno-unused-parameter
 libuv_la_SOURCES += src/unix/async.c \
                    src/unix/atomic-ops.h \
                    src/unix/core.c \
```

Those are the flags we set in GYP.

**Comment by saghul** [comment]
@indutny, what do you think about my patch above? I think we should have it, sans -Werror, which should only be set in debug builds. Thoughts?

**Comment by indutny** [comment]
I agree, may be add `-g` to it?

**Comment by saghul** [comment]
> I agree, may be add -g to it?

Only in debug mode, right?

**Comment by indutny** [comment]
Ok, ok :) Is it adding that much space in Release mode?

**Comment by mmalecki** [comment]
+1 to including `-g` in Release. Makes post-mortem analysis and debugging so much easier.

**Comment by saghul** [comment]
Folks, please check this out, as the previous patch I attached was wrong. https://github.com/joyent/libuv/pull/1438

-g is added all the time, just as in gyp builds.

**Comment by txdv** [comment]
I checked that thing and it looks good to me.

**Comment by saghul** [comment]
Thanks @txdv, will land later today.
