### ISSUE TITLE
Allow microsecond resolution in fs.utimes?

### ISSUE THREAD

**Issue by joliss** [joyent/libuv#1371]
Node's `fs.utimes` currently only supports 1-second-resolution time (see [fs.c:580](https://github.com/joyent/libuv/blob/dc1ea27c736f0d21c7160c790bcd1b113d20abd9/src/unix/fs.c#L580)), making the round-trip to `fs.stat` lossy.

It seems we might be able to use the [utimes](http://linux.die.net/man/3/utimes) system call instead of [utime](http://linux.die.net/man/2/utime) to get microsecond resolution.

@tjfontaine [points out](https://github.com/joyent/node/issues/7000) that you can use `fs.futimes` as a workaround. However, this still doesn't cover the case where we want to set the time on directories, because `mkdir` doesn't give us a file descriptor. So now I'm sad about the lack of microsecond resolution.

**Comment by saghul** [comment]
Do you have any proposal in mind?

**Comment by joliss** [comment]
I don't know the code well enough, unfortunately.

**Comment by txdv** [comment]
There is no need to know the code.

```
grep utime -r src/unix/
```

Change to utimes, make it compile, add test case, make pull request.

**Comment by saghul** [comment]
No follow-up, closing. Please open a PR in libuv/libuv if any of you want to work on this.
