### ISSUE TITLE
Should uv calls return error(not UV_EINVAL) immediately when there is a callback param?

### ISSUE THREAD

**Issue by huxingyi** [joyent/libuv#1378]
For example:

``` c
int uv_tcp_connect(uv_connect_t* req,
                   uv_tcp_t* handle,
                   const struct sockaddr* addr,
                   uv_connect_cb cb) {
  unsigned int addrlen;

  if (handle->type != UV_TCP)
    return UV_EINVAL;

  if (addr->sa_family == AF_INET)
    addrlen = sizeof(struct sockaddr_in);
  else if (addr->sa_family == AF_INET6)
    addrlen = sizeof(struct sockaddr_in6);
  else
    return UV_EINVAL;

  return uv__tcp_connect(req, handle, addr, addrlen, cb);
}
```

```
void on_connect_result(..., int status)
{
    if (0 != status)
    {
        //do something when error
    }
}

int r;
r = uv_tcp_connect(..., on_connect_result);
if (0 != r)
{
    //do something when error
}
```

When some error(not UV_EINVAL) happened, report the error in the callback, other than report it immediately as return value.
It could be better?
Then, I can safely assert the return value instead of detailed checking.

**Comment by saghul** [comment]
Functions in libuv will return early if the arguments passed are "wrong". If you pass an invalid address, as in your example, there is no point in attempting to connect.

There sule is as followws: any function may fails early, by returning an error, but if 0 was returned, when the result of the operation will come in a callback.

**Comment by huxingyi** [comment]
I mean, I need handle error twice. If return 0, or no return values when the arguments are all passed, then i just need to handle the error in callback.

**Comment by saghul** [comment]
No, it's not the same error, they are different errors. Not all functions get a mandatory callback, so how would we report the error?

Anyway, this is by design: if arguments are bogus error is returned immediately, otherwise if it's a runtime error which happens asynchronously it's reported in the callback.

**Comment by huxingyi** [comment]
First of all,It's not an issue of libuv. Sorry for open an issue, but I don't known where to post such a suggestion.
Which I want to say is the design.
If there is a callback, I think report the error through callback could be better(for example, report maybe_new_socket fail through callback, not through return value.). 
Currently, I must handle the return value/status in two different places.
(If without callback, report the error through the return value.)

**Comment by saghul** [comment]
No worries :-) The mailing list is usually more appropriate for this kind of discussions, though.
