### ISSUE TITLE
Making junctions via uv_fs_symlink is inconsistent on Windows

### ISSUE THREAD

**Issue by tkelman** [joyent/libuv#1385]
Built libuv from latest master, in MSYS2, with this MinGW-w64 version: http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.1/64-bit/threads-win32/seh/x64-4.8.1-release-win32-seh-rev5.7z

Test program, called `uv_symlink.c`:

``` c
#include <stdio.h>
#include "uv.h"

int main(int argc, char* argv[])
{
    uv_loop_t *jl_io_loop;
    uv_fs_t req;
    int ret, flags = UV_FS_SYMLINK_JUNCTION;
    if (argc != 3) {
        printf("Must provide 2 inputs\n");
        return 1;
    }
    jl_io_loop = uv_default_loop();
    ret = uv_fs_symlink(jl_io_loop, &req, argv[2], argv[1], flags, NULL);
    printf("ret = %d\n", ret);
    uv_fs_req_cleanup(&req);
    return ret;
}
```

Compiled as `gcc -Iinclude -L. -luv-11 uv_symlink.c -o uv_symlink`

Ran

```
$ ./uv_symlink "C:\Users\Tony\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
ret = 0

$ ls -al /c/Users/Tony/symlinktest
lrwxrwxrwx 1 Tony None 24 Jul 29 16:03 /c/Users/Tony/symlinktest -> /home/Tony/github/libuv/

$ ./uv_symlink "D:\code\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
ret = -4048
```

`D:\code` exists and is writable, there's no existing file `D:\code\symlinktest` in the way, so why does creating a junction work in `C:\Users\Tony` but not in `D:\code`? There are some other directories on my D: drive that I can create junctions in, but not all.

Note that using `mklink /j` works just fine:

```
$ rm /c/Users/Tony/symlinktest

$ cmd //c mklink //j "C:\Users\Tony\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
Junction created for C:\Users\Tony\symlinktest <<===>> D:\code\msys64\home\Tony\github\libuv

$ ls -al /c/Users/Tony/symlinktest
lrwxrwxrwx 1 Tony None 23 Jul 29 16:08 /c/Users/Tony/symlinktest -> /home/Tony/github/libuv

$ cmd //c mklink //j "D:\code\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
Junction created for D:\code\symlinktest <<===>> D:\code\msys64\home\Tony\github\libuv

$ ls -al /d/code/symlinktest
lrwxrwxrwx 1 Tony None 23 Jul 29 16:09 /d/code/symlinktest -> /home/Tony/github/libuv
```

**Comment by saghul** [comment]
The error seems to be EPERM. Do you have proper permissions on those directories? Are you running with elevated rights? IIRC it was required for junction points.

**Comment by tkelman** [comment]
When I run the Julia-wrapped equivalent of this, it does work when I start the Julia process with admin rights. However that should not be required for junctions (otherwise `mklink /j` wouldn't work), only file symlinks.

`mklink` without `/j` doesn't work without admin rights:

```
$ cmd //c mklink "D:\code\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
You do not have sufficient privilege to perform this operation.

$ cmd //c mklink "C:\Users\Tony\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
You do not have sufficient privilege to perform this operation.
```

**Comment by tkelman** [comment]
Threw in a few printf's. The EPERM appears to come from an invalid handle in this call: https://github.com/joyent/libuv/blob/beb54fe72da0dad40dc671a3b4c1edfa3a55203f/src/win/fs.c#L1394-L1406

**Comment by saghul** [comment]
Are you able to create junctions anywhere in D? You mentioned it but you didn't paste the output. Junction points can only be created for NTFS local volumes, is your volume NTFS and local?

If you have the rights and D matches those requirements I'm out of ideas :-S So try to print the error before SET_REQ_WIN32_ERROR, maybe it will give us more information.

**Comment by tkelman** [comment]
> Are you able to create junctions anywhere in D? You mentioned it but you didn't paste the output. 

Yes I can create junctions pretty much anywhere on D via `mklink /j`, or in my `D:\cygwin64` directory, but seemingly not any other folders, via `./uv_symlink`. I wonder whether Cygwin sets some unusual permissions on its install directory?

```
$ ./uv_symlink "D:\cygwin64\symlinktest" "D:\code\msys64\home\Tony\github\libuv"
ret = 0

$ ls -al /d/cygwin64/symlinktest
lrwxrwxrwx 1 Tony None 24 Jul 30 22:02 /d/cygwin64/symlinktest -> /home/Tony/github/libuv/
```

> Junction points can only be created for NTFS local volumes, is your volume NTFS and local?

Yes, my D drive is just another volume of my local HDD.

> So try to print the error before SET_REQ_WIN32_ERROR, maybe it will give us more information.

Can you describe how to print the error? Do you just mean the result of `GetLastError()`?

**Comment by saghul** [comment]
> Can you describe how to print the error? Do you just mean the result of GetLastError()?

Yep. Just save it to some variable, print it and pass the result along to SET_REQ_WIN32_ERROR. Then see is that gives us more info on MSDN.

**Comment by tkelman** [comment]
`GetLastError()` appears to return 5, Access is denied. Not that much more useful. Maybe I'll have a look at how ReactOS implements `mklink` and see if they're doing something extra that `uv_fs_symlink` doesn't.

**Comment by saghul** [comment]
Let me know if you find something useful there! Thanks for looking into this!

**Comment by tkelman** [comment]
Hm. The biggest difference between what ReactOS does and what libuv does is setting `GENERIC_WRITE` instead of `GENERIC_ALL` in the call to `CreateFile` (they're also not using the wide-char version) to open the directory. If I change this line https://github.com/joyent/libuv/blob/beb54fe72da0dad40dc671a3b4c1edfa3a55203f/src/win/fs.c#L1396 accordingly, then it works!

**Comment by tkelman** [comment]
I'm testing whether it also fixes the problem when wrapped by Julia. If so, should I file a PR?

**Comment by saghul** [comment]
Sure thing!
