### ISSUE TITLE
netbsd build

### ISSUE THREAD

**Issue by sabazk** [joyent/libuv#1391]
building with netbsd 6.99.49

make command ends with this

  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-kqueue.lo
  CC       src/unix/libuv_la-netbsd.lo
src/unix/netbsd.c: In function 'uv_get_free_memory':
src/unix/netbsd.c:104:17: error: storage size of 'info' isn't known
   struct uvmexp info;
                 ^
**\* Error code 1

**Comment by saghul** [comment]
Hi!

I don't have a NetBSD environment at the moment, can you provide a patch?

**Comment by sabazk** [comment]
Yes
netbsd.c missing an include uvm/uvm_external.h
