### ISSUE TITLE
uv_fs_mkdtemp prototype error on osx

### ISSUE THREAD

**Issue by bisegni** [joyent/libuv#1394]
UV_EXTERN int uv_fs_mkdtemp(uv_loop_t\* loop, uv_fs_t\* req, const char\* template, 
    uv_fs_cb cb);

using last xcode this prototype give problem, changing "const char\* template" with "const char\* tmp" all work.

**Comment by saghul** [comment]
Can you paste some output log? Also, what version of Xcode are you using? Latest stable or latest development?

**Comment by bisegni** [comment]
i'm sorry i have read to late the answer but i see that you have patch the code. thanks
