### ISSUE TITLE
test: tcp_writealot fails frequently

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1395]
This test fails for me almost always on OSX and Windows, never on Linux, though.

This patch seems to be the culprit: https://github.com/joyent/libuv/commit/4d905fbe07be8aa7eca878435aa2f0b7a48b2d63

I can see the intent of the patch, but maybe it's a better idea for the echo server not to ever close the connection, and always have the remove do it. That is, wait until reading EOF to shutdown / close.

A partial revert which doesn't ever close on write callbacks should do.

/cc @indutny, @trevnorris

**Comment by trevnorris** [comment]
Heh, I needed to revisit the ticket to remember the intent of the patch.

Can you post the partial revert? I'd like to see if it's possible to reproduce the same issue discussed in the original PR: https://github.com/joyent/libuv/pull/1249

Also, have any idea why it's failing on OSX/Windows, or even a link to show the failure? Just curious why it would be different between those and Linux. Especially the OSX case.

**Comment by saghul** [comment]
> Heh, I needed to revisit the ticket to remember the intent of the patch.

No problem. I know there are some flaky tests, which I plan on hunting after 0.12, I just didn't want to lose track of this one. It's not "urgent" because the fault is in the test, not the core.

> Can you post the partial revert? I'd like to see if it's possible to reproduce the same issue discussed in the original PR: #1249

I just tried a full revert and had a quick look at how to fix it, I didn't dive deep yet. It does make the test pass on OSX and Windows though.

> Also, have any idea why it's failing on OSX/Windows, or even a link to show the failure? Just curious why it would be different between those and Linux. Especially the OSX case.

Here is how it fails:

```
(many ECANCELED errors)
uv_write error: ECANCELED - operation canceled
uv_write error: ECANCELED - operation canceled
uv_write error: ECANCELED - operation canceled
Output from process `tcp_writealot`:
GOT EOF
Assertion failed in ../test/test-tcp-writealot.c on line 170: bytes_received_done == TOTAL_BYTES
```

**Comment by trevnorris** [comment]
@saghul Thanks for the info.

Now, to figure out how the hell to debug this stuff on windows. :P

**Comment by saghul** [comment]
Lets try to fix this before 0.12, so much red is making me cry.

**Comment by trevnorris** [comment]
@saghul For kicks, mind assigning this one to me? I'd like to take another crack at it.

**Comment by saghul** [comment]
Sure, go for it. I'm working on the docs.

**Comment by saghul** [comment]
I plan to make the 1.0.0 release by the end of next week. Do you have some time to work on this Trevor? Alternatively we can remove it from the milestone since it's the actual test what is wrong.

**Comment by trevnorris** [comment]
@saghul I can't get this to fail on Windows 8.1 x64 VM. Going to try some more, but not sure how to proceed if I can't reproduce.

**Comment by trevnorris** [comment]
Ok. I've gotten it to fail. Seems to only happen with Release builds. Not Debug builds.

**Comment by trevnorris** [comment]
Nix that. It failed for me once. Now it's not failing for me. The only thing I can attribute it to is the fact when the test started a request came to allow the firewall open. Now that I've allowed that, the test is passing.

**Comment by trevnorris** [comment]
PR for fix we discussed: https://github.com/joyent/libuv/pull/1466

**Comment by saghul** [comment]
PR was solid and landed, closing!
