### ISSUE TITLE
linux: strndup requires _GNU_SOURCE with glibc pre-2.10

### ISSUE THREAD

**Issue by tkelman** [joyent/libuv#1398]
Just noticed this warning for the first time. It may be harmless, and I believe RHEL5 is the only distribution still in somewhat common use with a glibc version this old.

```
  CC       src/unix/libuv_la-linux-core.lo
../src/unix/linux-core.c: In function 'read_models':
../src/unix/linux-core.c:553: warning: incompatible implicit declaration of built-in function 'strndup'
../src/unix/linux-core.c:603: warning: incompatible implicit declaration of built-in function 'strndup'
```

**Comment by indutny** [comment]
`_GNU_SOURCE` is a source of many problems and could hide some other declarations. If this problems appears to be happening only on old RHEL5, and is actually just a warning - I would rather not touch our defines. Do you agree?

**Comment by tkelman** [comment]
It could be gated under a glibc version-checking macro and only defined for old enough versions that we know are going to encounter the warning. But given that it isn't causing a build failure and I haven't seen problems in any higher-level code wrapping libuv from this, ignoring it seems like a reasonable choice.

**Comment by indutny** [comment]
Ok, great! @saghul : closing?

**Comment by saghul** [comment]
Yes!
