### ISSUE TITLE
may be optimized

### ISSUE THREAD

**Issue by laoshunn** [joyent/libuv#1399]
In Threadpool.c line 106
static void post(QUEUE\* q) {
  uv_mutex_lock(&mutex);
  QUEUE_INSERT_TAIL(&wq, q);
  uv_cond_signal(&cond);
  uv_mutex_unlock(&mutex);
}

may be:
static void post(QUEUE\* q) {
  uv_mutex_lock(&mutex);
  QUEUE_INSERT_TAIL(&wq, q);
  uv_mutex_unlock(&mutex);
  uv_cond_signal(&cond);
}

I think it will reduce a syscall some time.

**Comment by saghul** [comment]
Do you have any benchmarks on this?

**Comment by laoshunn** [comment]
I just review the project code.
I think here predictable scheduling behaviour is required, please close this issue, thx!
