### ISSUE TITLE
libuv C++ member functions

### ISSUE THREAD

**Issue by recp** [joyent/libuv#1404]
Hello,

Recently, I have contacted Ben Noordhuis (@bnoordhuis) and Saúl Ibarra Corretgé (@saghul) for contributing libuv. Ben has recommended me to get feedbacks from you before coding. The libuv doesn’t support `C++ member functions`. I want to append some codes (a bit) to libuv for support C++ member functions. Maybe there are such solution for do that and I know you will not want to change the project such but there is no require to change such.  

Let me show you my idea shortly on a sample:

The currently uv_listen function:

``` C
typedef void (*uv_connection_cb)(uv_stream_t* server, int status);

UV_EXTERN int uv_listen(uv_stream_t* stream, int backlog, uv_connection_cb cb);
```

All libuv callbacks defined in the uv.h header file. We just need to overload some functions for C++ using __cplusplus macro and append their declerations to uv.h like this:

``` C++
#ifdef __cplusplus
typedef std::function<void (uv_stream_t *, int) > uv_connection_cb2;

UV_EXTERN int uv_listen(uv_stream_t* stream, int backlog, uv_connection_cb2 cb);
#endif
```

Now IDEs such as Xcode, Qt Creator or MS-VS will suggest two overloaded uv_listen functions which I declared above if C++ is active.

Let me show you all related codes (brief):

``` C++
// libuv codes
/******************************************************************************/

// I appended the last-line for show you my mind. This name may change
//
#define UV_STREAM_PRIVATE_FIELDS                                              \
  uv_connect_t *connect_req;                                                  \
  uv_shutdown_t *shutdown_req;                                                \
  uv__io_t io_watcher;                                                        \
  void* write_queue[2];                                                       \
  void* write_completed_queue[2];                                             \
  uv_connection_cb connection_cb;                                             \
  int delayed_error;                                                          \
  int accepted_fd;                                                            \
  void* queued_fds;                                                           \
  UV_STREAM_PRIVATE_PLATFORM_FIELDS                                           \
  void * connection_cb_cpp;  /* This will be callback for C++ member fn */    \ 

// Maybe we would not declare as type and pass it to function directly
// This type will be declared in uv.h using __cplusplus macro
typedef std::function<void (uv_stream_t *, int) > uv_connection_cb2;

UV_EXTERN int uv_listen(uv_stream_t* stream, int backlog, uv_connection_cb2 cb) {
    // ...
    // Because cb is an object so we can pass any object address to void * 
    // We can convert cb to pointer if that will be need
    tcp->connection_cb_cpp = &cb;

    /* Do somethings */
    return 0;
}


// Sample End-User Codes:
/******************************************************************************/

class EchoServer {
private:
  uv_loop_t * m_loop;
  uv_tcp_t m_server;
  struct sockaddr_in m_bind_addr;

  // UV Slots / Event Handlers
  void on_new_connection(uv_stream_t *server, int status);
public:
  uv_loop_t * loop();
  EchoServer(int port, const char* ip = "0.0.0.0");
  int listen();
};

EchoServer::EchoServer(int port, const char* ip) 
                            : m_loop(uv_default_loop()), m_bind_addr({0}) {
  uv_tcp_init(m_loop, &m_server);

  uv_ip4_addr(ip, port, &m_bind_addr);
  uv_tcp_bind(&m_server, (struct sockaddr *)&m_bind_addr, 0);
}

uv_loop_t * EchoServer::loop() {
  return m_loop;
}

void EchoServer::on_new_connection(uv_stream_t *server, int status) {
    /* Do somethings about the connection */
}

int EchoServer::listen() {
    // Attach listen to this class member function
    uv_listen((uv_stream_t*) &m_server, 128, 
                         std::bind(&EchoServer::on_new_connection, this, 
                                   std::placeholders::_1, std::placeholders::_2));  

    // Or attach listen to a lambda with reference
    uv_listen((uv_stream_t*) &m_server, 128, [&] (uv_stream_t * stream, int status) {
         /* Do somethings about the connection */
    });
  return 0;
}

int main() {
  auto echoServer = new EchoServer(1234);
  echoServer->listen();

  return uv_run(echoServer->loop(), UV_RUN_DEFAULT);
}
```

Now we can use any `C and C++` functions as callbacks for any libuv event. I think there is no require such changes. Am I wrong? 

Thank you for your feedbacks/comments

**Comment by indutny** [comment]
+1 for it. The only thing that I dislike, though, is a additional pointer on all structs... Can't we just use existing cbs to store different kinds of pointers in them? Or should these functions be invoked in a different fashion?

**Comment by saghul** [comment]
Hi @recp, thanks for opening an issue on GH. I did get your emails but I've been a bit busy lately so I haven't had time to process them as of yet. Once 0.12 is out I'll look at this more closely.

**Comment by recp** [comment]
The existing cbs points C/C++ functions and we can't cast legally member function pointers to C function pointers so I think, we need to additional pointer to store member functions. Just extra 32bit or 64bit in memory :)

**Comment by recp** [comment]
@indutny if we will define callbacks such as `void * connection_cb_cpp` in structs using #if __cplusplus we can avoid extra cb pointer in C programs also we can avoid currently callback definitions such as `uv_connection_cb` for C++ programs using __cplusplus as well as. Because the type:

``` C++
typedef std::function<void (uv_stream_t *, int) > uv_connection_cb2;
```

can call C++ member functions and non-member functions...

**Comment by recp** [comment]
I think actually we don't need additional pointers and overloaded functions if we will replace all callback types with wrappers for C++. I have updated uv.h like this on new branch (libuv-cpp):

https://github.com/recp/libuv/compare/libuv-cpp

So if we will force C++ to use std::function as callbacks (or custom wrappers such as uv_function, Im working on), **we don't need any changes on existing codes** but uv.h (I've already updated). We just need to compile codes with C++ and export them to C with extern "C" { } .

Are there any concerns?

**Comment by edhemphill** [comment]
+1 ..especially since libuv is used for a lot of v8 work - and that's when work is C++11.

**Comment by txdv** [comment]
What is this?

Why can't you use node.native?

**Comment by saghul** [comment]
> +1 ..especially since libuv is used for a lot of v8 work - and that's when work is C++11.

I haven't had the time to look at this yet, but I'd like to point out that Node is the only project (that I know of) which uses libuv + V8.

**Comment by lucab** [comment]
How is the external interface affected by this commit (eg. symbol naming and mangling)? I'm particularly interested/concerned in ABI stability when fully going for C++.

**Comment by saghul** [comment]
FWIW, we will consider this after 1.0.0 was released, and as announced, 1.x will maintain a stable ABI.

**Comment by recp** [comment]
I’m working on this. I've not tested on Windows yet but it works on my OS X. If you will interested in you can download the version (unstable) and samples (The sample also is woking for C version):

https://github.com/recp/libuv 
https://github.com/recp/libuv-samples

All tests are failing (make check) for me for now but its will be fixed when porting to C++ completed (after v1.0.0)

The uv.h header has already surrounded by extern “C” so almost all uv functions should not be mangled (I think). But ABI stability; I’ll keep it in my mind when doing somethings :)

@saghul I converted implicit casts to explicit casts for avoid errors/warings on the commit[s]:

https://github.com/recp/libuv/compare/libuv-cpp

I don’t get errors and warnings like #1444 when compiling

**Comment by saghul** [comment]
@recp I had a quick peek at the code, and honestly, I suggest you stop working on it until we agree on the direction forward. AFAIS it goes way beyond defining some typedefs for callbacks, which I'm not confortable with. I'll take a deeper look as soon as I can.

**Comment by recp** [comment]
Got it. I'm waiting

**Comment by saghul** [comment]
Hi @recp, sorry for the delay. I looked at the code, and I can't really accept it. It changes everything. libuv is a C library, I don't mind helping C++ users, but this goes way too far.

I don't know if there is a simpler way to accomplish the same, but if there is, feel free to open a PR at libuv/libuv, we moved the delopment over there.

**Comment by unknownbrackets** [comment]
To workaround this myself, I used a simple ticket / unordered_map system and mutexes, which I think is not unlike what node.native does.  But there is extra overhead since it has to look up the stored std::functions.

You can of course do simple member functions using data as a context pointer with a simple dispatch function.

-[Unknown]

**Comment by recp** [comment]
Hi @saghul I see that the last idea changes everything because of moving to C++ completely, you're right. But I think we can still consider the first approach or like this without change the existing C codes. I mean that adding some cpp files for just supporting member funcs without modifing the existing files even though file extension. I'll work again on this as soon as possible I can, and try a chance to support C++ mem-fn on the new location (libuv/libuv) by a PR. If it will not acceptable by you again, I'll use myself ;) if there will not be licence issue or like this by your side.

**Comment by saghul** [comment]
@recp sure, if there is a way which we can agree upon I'll be happy to merge it!

**Comment by recp** [comment]
I'm glad to hear that, thank you very much @saghul

**Comment by splinterofchaos** [comment]
@recp FWIW, gcc [has an extension](https://gcc.gnu.org/onlinedocs/gcc/Bound-member-functions.html) that lets you convert members to regular function pointers, but you don't really need that if you define your callback as a function that calls the member of some global or do an unsafe cast to the appropriate callback type and put your object as the _data_ for the callback.

**Comment by recp** [comment]
@unknownbrackets I've never experienced with node.native, I just wanted use member-fn (maybe also lambda) as cb, not change/create-a-new libuv completely like node.native, also it seems the project need to maintenance for newest versions of libuv

@splinterofchaos, I'm not sure for use this gnu-ext or not but I'll take a look at this extension, thank you for the information

**Comment by felipealmeida** [comment]
Is writing to poll->data allowed for the user?

**Comment by unknownbrackets** [comment]
@recp will, lambda will afaik require more than just ->data, unless you store a pointer to a std::function, so long as you use arguments.  It's not just a context pointer and func pointer.

@felipealmeida yes.  That's its goal in life.  See here:
http://nikhilm.github.io/uvbook/utilities.html#passing-data-to-worker-thread

-[Unknown]

**Comment by felipealmeida** [comment]
You can use the code below to use it like this:

```
  uv_poll_t handle;
  uv_poll_init(uv_default_loop(), &handle, 1);
  std::cout << "handle " << &handle << std::endl;
  call_with_func_object(uv_poll_start, &handle, UV_READABLE
                        , [] (uv_poll_t* h, int a1, int a2)
                        {
                          std::cout << "handle " << h << " a1 " << a1 << " a2 " << a2 << std::endl;
                        });
  uv_run(uv_default_loop(), UV_RUN_DEFAULT);
```

https://github.com/felipealmeida/libuv-template-data-pointer

http://pastie.org/9747382
http://pastie.org/9747384

**Comment by recp** [comment]
Hi @felipealmeida, I've looked at this stuff a bit. Thank you for sharing your idea/codes...

I think we really don't need an invoker/fn-caller. If we will use wrapper functions for C++ for invoking callbacks, I think we can use like this (brief):

file uv-cpp.h:

``` C++
#include <uv.h>
#include <functional>

typedef std::function<void (uv_stream_t* server, int status)> uv_connection_cb2;
// ... orher uv_ cbs

int uv_listen_x(uv_stream_t* stream, int backlog, const uv_connection_cb2& cb);
// ... orher uv_ functions

void uv_release_cpp_cb_ptr(uv_handle_t * handle);

```

file uv-cpp.cc:

``` C++
#include "uv-cpp.h"

/*************************************************************************************************/

struct uv_function_wrapper_base {
  virtual ~uv_function_wrapper_base() = 0;
};

template <typename F>
struct uv_function_wrapper : public uv_function_wrapper_base {
  uv_function_wrapper(const F& cb) : m_cb(cb) { }

  template<typename... ArgTypes>
  void operator()(ArgTypes ...args) {
    m_cb(args...);
  }

  F m_cb;
};

/*************************************************************************************************/

void uv_release_cpp_cb_ptr(uv_handle_t * handle) {
  if (!handle->data)
    return;

  uv_function_wrapper_base *cb = static_cast<uv_function_wrapper_base *>(handle->data);
  delete cb;
}

/*************************************************************************************************/

void uv_listen_x_on_connection_cb(uv_stream_t* server, int status) {
  auto cb = *static_cast<uv_function_wrapper<uv_connection_cb2> *>(server->data);
  cb(server, status);
}

int uv_listen_x(uv_stream_t* stream, int backlog, const uv_connection_cb2& cb) {
  stream->data = new uv_function_wrapper<uv_connection_cb2>(cb);
  return ::uv_listen(stream, backlog, uv_listen_x_on_connection_cb);
}

// ....

```

Some uv functions need multiple callbacks so we can store them into STL container or static array... and release them by a func like `uv_release_cpp_cb_ptr`. Also if users will use ->data pointer, we should define another pointer in handle like void \* cpp_cbs ... But I'm not sure @saghul will like this or not ;) This seems good way to invoke C++ mem-fn/functors/lambdas... for now. Because there is no need to change existing C codes, just extra two files (uv-cpp.h, uv-cpp.cc) and one data pointer...
