### ISSUE TITLE
some platform os of windows send  data too fast could cause crash

### ISSUE THREAD

**Issue by xzzh999** [joyent/libuv#1409]
```
    hello, please forgive my pool english. i am a new to libuv,  i had used libuv try to make a c++ wrappered network lib about for 2 Month。i found its realy a very nice library after i compare with zeromq、libev,etc.  and when i test it, i had follow problems:

  i used the release version of v0.10.27 。 i write a demo and it works fine on my win7 machines. and later i test it on some other win7 and win8 machines, its ofen crash stoped(in win 8 its more like to crash), and the call stack like this:

  >if ( !anybuf(stderr) )
  >_assert
  >assert(handle->write_queue_size >= req->queued_bytes);  --- (win/tcp.c)
  >uv_process_tcp_write_req

 i  traced into the source, and found the assert value is true, not false. it can't be crash here. its happed both sometimes in client or server session's send function call.  i do send buffers in another thread, i need to send h264 video stream to a client session in this thread, so in real play stuation its
```

send data maybe very fast(fps=25). in some win7 machines it works fine, but in some win7 or win 8 machines its always crash in that place, can you give some help about this?

```
thank you very much. 
```

**Comment by saghul** [comment]
> i do send buffers in another thread

Are you calling `uv_write` from a thread different than the loop runs on?

**Comment by xzzh999** [comment]
yes, i first call uv_run(loop,UV_RUN_DEFAULT) in a thread, and later when client connected, i send video stream buffer by uv_write. the h264 buffer frames were in a queue, and i use condition wait to notify send, the send thread pop the buffer and call uv_write to send it.

**Comment by saghul** [comment]
`uv_write` is not thread-safe. You need to call it from the same thread which is running the loop. Closing as it's not a libuv issue.
