### ISSUE TITLE
`spawn_closed_process_io` test fails on Solaris

### ISSUE THREAD

**Issue by mmalecki** [joyent/libuv#1413]
```
  libuv git:(master)  ac./out/Debug/run-tests spawn_closed_process_io                                                                                                  

`spawn_closed_process_io` failed: exit code 134
Output from process `spawn_closed_process_io`:
Assertion failed: fd > STDERR_FILENO, file ../src/unix/core.c, line 463
=============================================================
```

I dug into this and I'm pretty sure that I know what's causing that, but I'm not sure how to fix it.

The assertion that's triggering can be found here: https://github.com/joyent/libuv/blob/4c90cc8e14e4d45f6d7896e61a2588e602f89d48/src/unix/core.c#L463

I believe that the assertion is caused by the fact that in the test itself we call [`close(0)`](https://github.com/joyent/libuv/blob/4c90cc8e14e4d45f6d7896e61a2588e602f89d48/test/test-spawn.c#L705), and later [call `pipe(2)`](https://github.com/joyent/libuv/blob/4c90cc8e14e4d45f6d7896e61a2588e602f89d48/src/unix/process.c#L176) in [`uv_spawn`](https://github.com/joyent/libuv/blob/4c90cc8e14e4d45f6d7896e61a2588e602f89d48/src/unix/process.c#L429), which returns fd 0 as first one of the file descriptors, since that's the lowest fd available. Later on, still in `uv_spawn`, we [try to close `uv__close` that fd](https://github.com/joyent/libuv/blob/4c90cc8e14e4d45f6d7896e61a2588e602f89d48/src/unix/process.c#L471), which triggers the `> 2` assertion.

**Comment by saghul** [comment]
FTR, the test was added by this commit: https://github.com/joyent/libuv/commit/fd77a5d6c6466f8c9d7ea6221b946599320702bb, which does the `close(0)` intentionally, to verify we don't try to close it again.

I guess a regression was introduced later on or something.

An interesting fact is that this test only fails on SmartOS.

**Comment by saghul** [comment]
Can you try again with latest master @mmalecki? I believe https://github.com/joyent/libuv/commit/1552184238a49e748a04d0cb2cdf2d34c2d3c7cb actually fixed this.

FWIW it no longer fails on Jenkins.

**Comment by saghul** [comment]
Closing, as I've never see this one fail again.
