### ISSUE TITLE
Feature request: uv_fs_readdir to report the type of the entries

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1416]
This is in order to support the following feature request in joyent/node#8146. The text is copy paste from there.

`readdir()` and `FindNextFile()` both return if the dir entry is file or directory, but node.js returns only the list of the names. This means if you have directory of 1000000 entries you need to call `fs.stat()` 1000000 times to find the types of the entries which is big waste. This addition would positively impact applications like recursive walking of directories and recursive deletion of directories.

And basically one needs to stat the result of `readdir()` almost 100% of the time because folders and files needs to be treated separately. The only common thing you can do with them is basically `exists()`. Even `rename()` is different because existing files are replaced with rename and folders are not.

**Comment by saghul** [comment]
This landed a while ago in master. Have a look at `uv_fs_readdir_next`: http://docs.libuv.org/en/latest/fs.html#c.uv_fs_readdir
