### ISSUE TITLE
Error while running make check

### ISSUE THREAD

**Issue by sausax** [joyent/libuv#1418]
Output 

make[2]: Entering directory `/home/fs-user/softwares/libuv'

Output from process `platform_output`:
uv_get_process_title: /home/fs-user/softwares/libuv/test/.libs/lt-run-tests
uv_resident_set_memory: 774144
uv_uptime: 1329991.000000
uv_getrusage:
  user: 0 sec 999 microsec
  system: 0 sec 2999 microsec
uv_cpu_info:
  model: Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GHz
  speed: 2500
  times.sys: 536949400
  times.user: 1141773500
  times.idle: 9732593100
  times.irq: 10500
  times.nice: 884100
  model: Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GHz
  speed: 2500
  times.sys: 537655100
  times.user: 1092081900
  times.idle: 9828724800
  times.irq: 0
  times.nice: 867300
uv_interface_addresses:
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: eth0
  internal: 0
  physical address: 22:61:ff:7f:b3:35
  address: 192.168.128.160
  netmask: 255.255.255.0
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: eth0
  internal: 0
  physical address: 22:61:ff:7f:b3:35
  address: fe80::2061:ffff:fe7f:b335
#   netmask: ffff:ffff:ffff:ffff::

`spawn_setuid_setgid` failed: exit code 134
Output from process `spawn_setuid_setgid`:
# Assertion failed in test/test-spawn.c on line 1054: r == 0
# FAIL: test/run-tests
#1 of 1 test failed

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `/home/fs-user/softwares/libuv'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`/home/fs-user/softwares/libuv'
make: **\* [check] Error 2

**Comment by saghul** [comment]
What platform are you running the tests on?

**Comment by sausax** [comment]
CentOS 6.5 VM

**Comment by saghul** [comment]
Can you run the individual test like this:

```
/home/fs-user/softwares/libuv/test/.libs/lt-run-tests spawn_setuid_setgid spawn_setuid_setgid
```

inspect the core file generated and see what value is returned in r? Alternatively, you can just add a printf.

**Comment by deleisha** [comment]
This is same as the second issue reported at issue 1401. 
The fix for issue 1401 is delayed quite a long time due unavailability of ubuntu.

**Comment by saghul** [comment]
Closing in favor of #1401 then.
