### ISSUE TITLE
Process hangs on SmartOS when reading from a stdin that was piped in from a process that closed stdout

### ISSUE THREAD

**Issue by misterdjules** [joyent/libuv#1419]
Given the following code:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <uv.h>

uv_buf_t alloc_buffer(uv_handle_t *handle, size_t suggested_size)
{
    static char buffer[1 << 16]; 
    return uv_buf_init(buffer, 1 << 16);
}

void read_stdin(uv_stream_t *stream, ssize_t nread, uv_buf_t buf)
{
    if (nread < 0)
    {
        uv_read_stop(stream);
        return;
    }
}

int main(int argc, char *argv[])
{
    uv_tty_t input;
    uv_tty_init(uv_default_loop(), &input, STDIN_FILENO, 1);
    uv_read_start((uv_stream_t *)&input, alloc_buffer, read_stdin);

    uv_run(uv_default_loop(), UV_RUN_DEFAULT);

    return EXIT_SUCCESS;
}
```

built it on SmartOS using the following command line:

```
cc ~/source.c -I PATH_TO_LIBUV/include/ PATH_TO_LIBUV/libuv.a -lsocket -lnsl -lsendfile -lkstat
```

and run like this:
`
find . 1>&- | ./a.out
`
libuv's event loop will use 100% of a CPU and the process will never exit.

Using dtrace, I was able to determine that the event loop would never exit because a `POLLHUP` event was set on the standard input stream.

Thanks to @tjfontaine, I was able to identify the breaking change in libuv to be 442d11d618d0eff7297c922f401550138fbf8555.

In commit 442d11d618d0eff7297c922f401550138fbf8555, one of the changes is:

```
+  /* Ignore POLLHUP here. Even it it's set, there may still be data to read. */
+  if (events & (UV__POLLIN | UV__POLLERR))
     uv__read(stream);
```

It seems that the comment doesn't reflect the code. According to the comment, shouldn't the code read:

```
if (events & (UV__POLLIN | UV__POLLERR | UV__POLLHUP))
```

?

Anyway, it seems that with 442d11d618d0eff7297c922f401550138fbf8555, `uv__stream_eof` is not called anymore when `UV__POLLHUP` is set. If I change the code so that `uv__stream_eof` gets called at some point (via `uv__read` or by calling `uv__stream_eof` directly) when UV__POLLHUP is set, the process exits gracefully.

**Comment by saghul** [comment]
By looking at the code, I think you are right. If POLLHUP ends up being set, we will never call `uv__read` AFAIS, and `uv__stream_eof` will only be called if and only if POLLHUP was set and there was a previous partial read.

Can you please make a pull request with this change? It will also need a test.

Thanks!

**Comment by misterdjules** [comment]
@saghul Sure, thank you for looking into this!

**Comment by misterdjules** [comment]
@saghul I just created a PR for that, please let me know what you think!

**Comment by saghul** [comment]
Closing, continues on #1422
