### ISSUE TITLE
libuv (0.10) testsuite fails bit on arm64 (AArch64)

### ISSUE THREAD

**Issue by lucab** [joyent/libuv#1443]
Hi,
Debian recently gained an arm64 port, so the latest 0.10.28 was also autobuilt on that architecture.

However, it looks like there is something going wrong as more than 154 tests are failing.
Full build log for 0.10.28-3 at https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=arm64&ver=0.10.28-3&stamp=1409264299

As there is not (yet) a porterbox available, I have no more details/debug-traces to offer. I'll try to ask  arm64 porters and get some more data on it.

**Comment by saghul** [comment]
Thanks for looking into it @lucab.

**Comment by saghul** [comment]
Can you try to apply this patch? https://github.com/joyent/libuv/commit/861de3d71d40bdd22712f0079cd38f41be75010d

**Comment by lucab** [comment]
Cherry-picked it on top of 0.10.28, all tests are now passing on arm64:
https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=arm64&ver=0.10.28-5&stamp=1411736962

Please backport it to 0.10 branch and close this bug.

**Comment by saghul** [comment]
Great, thanks for confirming! Will do a  round of backports in the upcoming days.

**Comment by saghul** [comment]
A backport landed in https://github.com/joyent/libuv/commit/ef7b783d8d581f49a68f32f426c18b0fff9c78e3, it will be part of the next release.
