### ISSUE TITLE
add uv_listen_stop or any other api to remove the callback.

### ISSUE THREAD

**Issue by w359405949** [joyent/libuv#1450]
hi, i am try to write a coroutine network library like gevent by libuv and lua-coroutine .

project home: 
https://github.com/w359405949/luua

i handle coroutine resume&yield by a simple rule:
main coroutine run the uv_loop, 
resume any other coroutine by the uv callback, 
'invoke' to the loop from other coroutine by yield.

the key point is that when the coroutine 'invoke' to the loop, it should stop the previous uv handle and regist a new handle when the right event happened it can resume the right place.

like

function msleep(timeout)
    -- stop precious event
    local timer = uv.uv_timer_new(loop)
    uv.uv_timer_start(timer, coroutine.running(),  timeout, 0)
    coroutine.yield() 
    -- or stop the timer manally.
end

everything seems ok until i write the Socket.listen and accept, 
something unexpected happen .

(develop branch).
function Socket:listen()
    -- self.socket is a uv_tcp_t create before.
    uv.uv_listen(self.socket, self) -- uv_listen need to regist a callback
    -- coroutine.yield() ? no! uv_listen can be called many times?
end

function Socket:accept()
    local peeraddress = coroutine.yield()
    -- initial the peer 
    uv.uv_accept(self.socket, peer)
end

it's a disaster that user must call accept after listen or sink into a "god knows" situation, and it also could not accept more like gevent:

local socket = Socket()
socket.listen(100)
while true then
    local new_connection = socket.accept()
    -- max connection? sleep(sometime)
    -- servive stop? just break.
end

**Comment by saghul** [comment]
And what is the question here? Yes, having uv_listen_stop would probably be nice, but so far nobody wrote a patch for it :-)

After 1.0.0 uv_listen and uv_accept will change pretty dramatically (that's the plan at least): uv_listen will just set the backlog in the socket, and uv_accept will be a request. More details will follow soon after the release.

**Comment by saghul** [comment]
Related: https://groups.google.com/forum/#!msg/libuv/LYW_5eILaVk/SF7CXoGCL9sJ

**Comment by w359405949** [comment]
yeah, it's what i need, just stop the callback but don't need to stop the socket.

if you are interesting of my work, you can just read the lib/Socket.lua and you can get the answer.

**Comment by saghul** [comment]
Closing, here is the proposal for the new API: https://github.com/libuv/libuv/issues/5 The user would just need to stop calling `uv_accept`.
