### ISSUE TITLE
[unix] Simplify uv__run_pending()

### ISSUE THREAD

**Issue by trevnorris** [joyent/libuv#1454]
Just wanted to know if I'm missing something in the following simplification, or if I should open a PR for it?

``` diff
diff --git a/src/unix/core.c b/src/unix/core.c
index aaced4c..349fd6b 100644
--- a/src/unix/core.c
+++ b/src/unix/core.c
@@ -666,14 +666,11 @@ static void uv__run_pending(uv_loop_t* loop) {
   QUEUE* q;
   uv__io_t* w;

-  while (!QUEUE_EMPTY(&loop->pending_queue)) {
-    q = QUEUE_HEAD(&loop->pending_queue);
-    QUEUE_REMOVE(q);
-    QUEUE_INIT(q);
-
+  QUEUE_FOREACH(q, &loop->pending_queue) {
     w = QUEUE_DATA(q, uv__io_t, pending_queue);
     w->cb(loop, w, UV__POLLOUT);
   }
+  QUEUE_EMPTY(&loop->pending_queue);
 }
```

**Comment by saghul** [comment]
QUEUE_EMPTY doesn't empty the queue, it returns 1 if the queue is empty, 0 otherwise.

Usually I only use foreach when there are no callbacks invoved, which could modify the queue while iterating it.

**Comment by trevnorris** [comment]
Ah, duh. I should inferred that from the `while()` conditional. Is there a quick way to empty the queue?

**Comment by saghul** [comment]
The queue is not a generic container where elements are put inside, it's an inclusive or embedded data structure, so everything you "put in" is aware of it. You can reset your pointers, but the elements in the queue would still be chained. You need to iterate it and reset the queue on each element.

**Comment by trevnorris** [comment]
thanks. that answers it. wanted to see if there was a quicker way than removing each queue item individually.
