### ISSUE TITLE
darwin: the select trick doesn't work when there are more than 1024 fds

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1461]
Issue report on Node: https://github.com/joyent/node/issues/8326

Fix attempt: https://github.com/saghul/libuv/tree/darwin-unlimited-select

I think we need to manage the fd_set manually since we are going beyond 1024 fds.

/cc @indutny

**Comment by saghul** [comment]
I wonder if we can use poll() instead of select() for this.

**Comment by saghul** [comment]
I tried to use `poll(2)` here: https://github.com/saghul/libuv/commit/754d21c9b3dca5c6ccf4205c38eaccc06af488bd but it doesn't seem to work with /dev/tty on OSX, still.

Long story short: poll continues to be broken on OSX, so we need to use select with manual fd_set mangling I think.

**Comment by indutny** [comment]
Hm... yeah, I think that `poll()` is actually emulated by a kqueue on OSX.

**Comment by indutny** [comment]
Anyway, I am at nodeconf right now. Will try to look into it tomorrow, but can't really promise!

**Comment by saghul** [comment]
Thanks!

**Comment by indutny** [comment]
Should be fixed by https://github.com/joyent/libuv/pull/1462

**Comment by saghul** [comment]
Fix landed.
