### ISSUE TITLE
WriteFileGather ReadFileScatter instead of ReadFile and WriteFile in the windows file system operations.

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1472]
Currently we are using [ReadFile](https://github.com/joyent/libuv/blob/master/src/win/fs.c#L572-L581)  and [WriteFile](https://github.com/joyent/libuv/blob/master/src/win/fs.c#L628-L637) over the entire nbufs collections with a while loop.

However, there are two functions called [WriteFileGather](http://msdn.microsoft.com/en-us/library/aa365749%28v=vs.85%29.aspx) and [ReadFileScatter](http://msdn.microsoft.com/en-us/library/windows/desktop/aa365469%28v=vs.85%29.aspx). They guarantee atomicity between concurrent writes and reads.

We should like totally use them. AIO has something similar on linux, but it sucks.

**Comment by piscisaureus** [comment]
Have you read those msdn pages in their entirety?
Pay special attention to alignment and file offset restrictions.

**Comment by txdv** [comment]
_Each element can receive one page of data. To determine the size of a system page, use GetSystemInfo._

_Each buffer must be at least the size of a system memory page and must be aligned on a system memory page size boundary. The system reads one system memory page of data into each buffer._

So sad.

**Comment by txdv** [comment]
Maybe we could check for the alignment?

Would that introduce too much overhead? I mean, the first check would probably reveal most of the time if it is not fit for the Gather/Scatter functions.

**Comment by txdv** [comment]
_The array must contain enough elements to store nNumberOfBytesToRead bytes of data, plus one element for the terminating NULL. For example, if there are 40 KB to be read and the page size is 4 KB, the array must have 11 elements that includes 10 for the data and one for the NULL._

This limitation makes it really hard to implement it, because the bufs have always the exact size.

We would need to create it on our own and I don't think this is a good idea.
