### ISSUE TITLE
adding uv_compare

### ISSUE THREAD

**Issue by deepak1556** [joyent/libuv#1480]
Following this thread https://groups.google.com/forum/#!topic/libuv/hrVIAyurYm0 , providing pthread#equal like helper would be nice. I am currently requring such an helper here https://github.com/deepak1556/node-ffi/blob/nan_upgrade/src/callback_info.cc#L153,   Any suggestions ?

**Comment by saghul** [comment]
I think I would entertain such a patch. But please don't call it `uv_compare`, call it `uv_thread_equal`, which would map to `pthread_equal` on Unix, and an arithmetic equal on Windows. Thread ids would also need to be typedef'd to their respective types an have some `uv_thread_id_t` type.

**Comment by saghul** [comment]
Superseded by #1516

**Comment by deepak1556** [comment]
:+1:
