### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [joyent/libuv#1484]
Would you like to [replace any double quotes](https://github.com/joyent/libuv/blob/06f9e1438ed20dd83618bca78759ea8635a79289/include/uv.h#L48) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by saghul** [comment]
I don't think so, since those need to be looked up in that particular directory, that is, include/

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html) from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf) in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) for header files of your software?

**Comment by saghul** [comment]
> Would you like to restrict the searched directories for header files of your software?

Yes. Users are meant to just include uv.h, which pulls everything they need.

**Comment by elfring** [comment]
Can the "[double quote file name specification](http://en.cppreference.com/w/cpp/preprocessor/include)" result also in the inclusion of header files from outside the specified include directories?

**Comment by saghul** [comment]
It can, if they are not on the current directory, AFAIK, but those files we are including are.

**Comment by elfring** [comment]
Thanks for your acknowledgement of this possibility. I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories.
Can such a security detail become a bit more important?

**Comment by saghul** [comment]
Regardless using "" or <> the compiler will check in standard locations, so there is still a chance someone places a file with the right name somewhere. I'm not sure what trying to avoid here, perhaps you can detail the problem you are trying to solve?

**Comment by elfring** [comment]
I try to clarify and improve the fine-tuning for header file search directories. I'm curious if other software developers care also for the affected implementation details.

**Comment by saghul** [comment]
Ah, well: https://github.com/realXtend/tundra/issues/778
