### ISSUE TITLE
Make a named pipe or socket without opening it.

### ISSUE THREAD

**Issue by splinterofchaos** [joyent/libuv#1495]
Hi. I'm working with some very old code that does something like this:

``` c
system("grep ... > outfile");
// ... lots of code
fopen("outfile", "r");
while (fgets(...) != NULL) {
  // ...
};
```

I found I could improve the efficiency of this by calling `mkfifo("outfile", ...)` and running `system("grep ...")` asynchronously. Yes, other ways might better solve this problem, but none seem as orthogonal to this code as making a pipe and using shell redirection and I actually wasn't able to achieve the same efficiency with callbacks.

Unfortunately, looking through the API, I only see `uv_pipe_connect()` and `_bind()` as ways of naming a pipe, and both assume that the process with read from or write to it. A non-OS specific way of creating a named pipe (or socket) without actually opening it would be much appreciated. Thank you.

**Comment by mattn** [comment]
It's not asynchronized call. You can use popen POSIX API instead of libuv.

**Comment by saghul** [comment]
> Unfortunately, looking through the API, I only see uv_pipe_connect() and _bind() as ways of naming a pipe, and both assume that the process with read from or write to it. A non-OS specific way of creating a named pipe (or socket) without actually opening it would be much appreciated. Thank you.

I really don't understand what you need.  The code you pasted above deals with a file, so you'd use the `uv_fs_*` API, not the pipe API. Pipes in libuv are an abstraction on top of Unix domain sockets and Windows named pipes. What do you need?

**Comment by splinterofchaos** [comment]
> It's not asynchronized call. 

I had forgotten; I did have to modify the code significantly to use an asynchronous version of system that spawns the external program with redirection.

> You can use popen POSIX API instead of libuv.

Breaks code standards of OS-independence.

> What do you need?

To create the pipe, then to start running the external program writing to it, then to open the file and begin reading from it in a function that only knows the name of the file. Theoretically, the `fgets()` line happens while the program is still running.

If I understand the API correctly, libuv doesn't offer an `fgets()` equivalent so while I could modify these functions to accept a `uv_handle_t` (unfortunately, creating lots of duplicate code), I'd have to do my own buffering and split the input line-wise, which could be error prone.

**Comment by saghul** [comment]
> To create the pipe, then to start running the external program writing to it, then to open the file and begin reading from it in a function that only knows the name of the file. Theoretically, the fgets() line happens while the program is still running.
> 
> If I understand the API correctly, libuv doesn't offer an fgets() equivalent so while I could modify these functions to accept a uv_handle_t (unfortunately, creating lots of duplicate code), I'd have to do my own buffering and split the input line-wise, which could be error prone.

libuv doesn't support pipes on Unix, `uv_pipe_t` is an abstraction over Unix domain sockets. The equivalent to `fgets` would be `uv_fs_read` if you are dealing with files or `uv_read_start` if you want o read from a `uv_stream_t` handle. I think you need to adapt what you try to do to what libuv can offer you. If you need to start a process that creates otuput and then process it line by line, you could use `uv_spawn` to spawn a subproces which would output to stdout, and use a `uv_pipe_t` as that stdout, so you can read the oputput of that process.

In any case, please ask questions in the mailing list (https://groups.google.com/forum/#!forum/libuv) instead of the issue tracker.
