### ISSUE TITLE
uv_alloc_cb inteface not exposed in rendered sphinx docs

### ISSUE THREAD

**Issue by KennethWilke** [joyent/libuv#1498]
Howdy!

I was perusing the rendered sphinx docs and noticed that while most callback interfaces are exposed `uc_alloc_cb` seems to have missed the cut. I found the typedef in the `uv.h` header easily enough but thought it'd be helpful to see this in the sphinx output as well (which is looking really nice btw).

http://docs.libuv.org/en/latest/search.html?q=uv_alloc_cb

**Comment by KennethWilke** [comment]
I'd submit a PR for this myself but I'm not too savvy on how it works :cry:  and figured someone else would probably get this corrected pretty quickly

**Comment by saghul** [comment]
Thanks for the report Kenneth!

**Comment by saghul** [comment]
Here you go! https://github.com/joyent/libuv/commit/5e822033b457618f0a3ca1c7fcc990f36d22822c (the online version should be regenerated shortly)

**Comment by KennethWilke** [comment]
Awesome! Thank you!
