### ISSUE TITLE
Need a way to return failed oio_req to the user.

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#15]
consider:

void after_read(oio_req *req, int read) {
  free(req);
}

oio_handle_init(&handle, close_cb);

req = (oio_req*)malloc(sizeof(oio_req));
oio_req_init(req, &handle, after_read);
oio_read(req, &whatever_buf, 1);

oio_close(&handle);
// after_read is never called -> allocated req leaked.

**Comment by ry** [comment]
before the close_cb all pending reqs should have their callback called.

**Comment by ry** [comment]
need tests for this.

**Comment by piscisaureus** [comment]
Need api first. How is the callback gonna tell if the request completed successfully or if it was cancelled?

**Comment by ry** [comment]
we could have an err param for each cb

**Comment by ry** [comment]
alternatively add a function:

```
oio_err oio_req_get_error(oio_req*)
```

**Comment by piscisaureus** [comment]
Let's have an extra argument to the callback.
void after_read(oio_req *req, int cancelled);
cancelled is nonzero if the request failed / was cancelled.

**Comment by ry** [comment]
sure

**Comment by piscisaureus** [comment]
To be rubber-stamped:

```
/* The status parameter is 0 if the request completed successfully /*
/* and -1 if the request was cancelled or failed. */
/* For oio_close_cb, -1 means that the handle was closed due to an error. */
typedef void (*oio_read_cb)(oio_req* req, size_t nread, int status);
typedef void (*oio_write_cb)(oio_req* req, int status);
typedef void (*oio_accept_cb)(oio_handle* handle);
typedef void (*oio_close_cb)(oio_handle* handle, int status);
typedef void (*oio_connect_cb)(oio_req* req, int status);
typedef void (*oio_timer_cb)(oio_req* req, int64_t skew, int status);
```

**Comment by ry** [comment]
_stamp_
