### ISSUE TITLE
test tcp echo server does not write echo fully

### ISSUE THREAD

**Issue by darren** [joyent/libuv#1500]
with latest commit 49cb40c47902dd04c7787e6543e9e13368dc1840 
./run-tests  tcp4_echo_server

$ for a in $(seq 1 100000); do echo $a >> input.txt; done

$ md5 input.txt
MD5 (input.txt) = dea9193b768319cbb4ff1a137ac03113

$ while :; do cat input.txt |nc localhost 9123 |md5 ;done
dea9193b768319cbb4ff1a137ac03113
2d08e52d088bf1a1f5f9570c02570c92
dea9193b768319cbb4ff1a137ac03113
87216b5332a9d927014ae2bbbe5d41c8
9fab6dd6e9aff999c435f32f29700f0c
dea9193b768319cbb4ff1a137ac03113
dea9193b768319cbb4ff1a137ac03113
dea9193b768319cbb4ff1a137ac03113
e920d75e79eedb5b87e8ccd488cf2303
77f3e126f035b34302404f2ca4372e10
^C

**Comment by saghul** [comment]
Can you try with the v1.x branch? It included a fix for this: https://github.com/joyent/libuv/commit/3d38eae37727f06df8ce9b634bac1c42e610dd64

**Comment by darren** [comment]
Great! v1.x branch works with no memleak, no sigpipe and no partial writes.

**Comment by saghul** [comment]
Sweet, closing then!
