### ISSUE TITLE
uv_loop_t's data member isn't usable.

### ISSUE THREAD

**Issue by creationix** [joyent/libuv#1503]
According to the [docs](http://docs.libuv.org/en/latest/loop.html#c.uv_loop_t.data), I should be able to use the `data` member of the `uv_loop_t` struct for my own uses.

> void\* uv_loop_t.data
> Space for user-defined arbitrary data. libuv does not use this field

But I'm finding this is not the case and it has caused me several hours of segfault debugging in gdb.  I hope the docs are correct and it's just a bug in libuv that will be fixed.

I can show easily that `uv_loop_init` it setting `data` to `NULL`.

``` c
#include <stdio.h>                                                                                                         
#include <stdlib.h>                                                                                                        
#include "uv.h"                                                                                                            

typedef struct {                                                                                                           
  const char* name;                                                                                                        
  int age;                                                                                                                 
} person_t;                                                                                                                

void main(void) {                                                                                                          
  uv_loop_t loop;                                                                                                          
  person_t* person = malloc(sizeof(*person));                                                                              
  printf("0 &loop=%p loop.data=%p\n", &loop, loop.data);                                                                   
  loop.data = person;                                                                                                      
  printf("1 &loop=%p loop.data=%p\n", &loop, loop.data);                                                                   
  uv_loop_init(&loop);                                                                                                     
  printf("2 &loop=%p loop.data=%p\n", &loop, loop.data);                                                                   
}                                                                                                                          
```

This outputs:

```
[tim@localhost luv]$ cc testloop.c -I libuv/include libuv/out/Debug/libuv.a -lpthread -o testloop
[tim@localhost luv]$ ./testloop 
0 &loop=0x7fff8e803900 loop.data=0x7ff94f3df4d8
1 &loop=0x7fff8e803900 loop.data=0x143d010
2 &loop=0x7fff8e803900 loop.data=(nil)
```

I can [work around](https://github.com/luvit/luv/blob/4383295ceca9723524a4613577a6d541e968a7a7/src/loop.c#L35-L37) this by not using data till after init, but the harder to reproduce problem is libuv will overwrite `data` with new values later in my program.  Sometimes it's `0xfffffff` and I think I've seen other values.

**Comment by saghul** [comment]
Ah, I think we need to clarify the docs :-( The loop is initialized to 0 here: https://github.com/joyent/libuv/blob/v1.x/src/unix/loop.c#L106 and when the loop is closed, it poisons the structure to help catch bugs: https://github.com/joyent/libuv/blob/v1.x/src/unix/loop.c#L66

**Comment by txdv** [comment]
Yeah, because the init is overwriting everything.

In between init and close you should be safe to use the data field.

**Comment by creationix** [comment]
Interesting.  I'd rather init not mess with it since it's convenient in my code to set data before calling init, but I can work around that if need be.  I checked my code and yes, I was trying to access data right after calling close.  That part was an easy fix.
