### ISSUE TITLE
libuv-v1.0.0-rc1 can't passed tests!!! on ubuntu 14.04 x64 / win8.1 x64(vs2012 x86, x64)

### ISSUE THREAD

**Issue by shrimpz** [joyent/libuv#1504]
game@ubuntu:~/libuv-v1.0.0-rc1/out/Debug$ ./run-tests 

Output from process `platform_output`:
uv_get_process_title: ./run-tests
uv_resident_set_memory: 712704
uv_uptime: 834.000000
uv_getrusage:
  user: 0 sec 1961 microsec
  system: 0 sec 2141 microsec
uv_cpu_info:
  model: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  speed: 3199
  times.sys: 190100
  times.user: 112500
  times.idle: 7826500
  times.irq: 20400
  times.nice: 31000
  model: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  speed: 3199
  times.sys: 139600
  times.user: 88600
  times.idle: 8043900
  times.irq: 1200
  times.nice: 28100
  model: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  speed: 3199
  times.sys: 154400
  times.user: 105500
  times.idle: 8050500
  times.irq: 1100
  times.nice: 2400
  model: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  speed: 3199
  times.sys: 140900
  times.user: 100400
  times.idle: 8044500
  times.irq: 11800
  times.nice: 1600
uv_interface_addresses:
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: eth0
  internal: 0
  physical address: 00:0c:29:f7:5c:df
  address: 192.168.116.137
  netmask: 255.255.255.0
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: eth0
  internal: 0
  physical address: 00:0c:29:f7:5c:df
  address: fe80::20c:29ff:fef7:5cdf
#   netmask: ffff:ffff:ffff:ffff::

`pipe_connect_to_file` failed: exit code 134
Output from process `pipe_connect_to_file`:
# Assertion failed in ../test/test-pipe-connect-error.c on line 53: status == UV_ENOTSOCK || status == UV_ECONNREFUSED

`fs_event_watch_file_twice` failed: exit code 134
Output from process `fs_event_watch_file_twice`:
# Assertion failed in ../test/test-fs-event.c on line 331: 0 == uv_fs_event_start(watchers + 0, fail_cb, path, 0)

`fs_readdir_file` failed: exit code 134
Output from process `fs_readdir_file`:
# Assertion failed in ../test/test-fs.c on line 1845: r == UV_ENOTDIR

`dlerror` failed: exit code 134
Output from process `dlerror`:
# Assertion failed in ../test/test-dlerror.c on line 48: strstr(msg, dlerror_desc) != NULL

**Comment by saghul** [comment]
Don't run the tests from the out/Debug directory, the test suite assumes you are in the root directory. Run them like this: https://github.com/joyent/libuv#running-tests

I got the same failures when running the tests like you, 0 when running them as the README says, closing.
