### ISSUE TITLE
I compile libuv-v1.0.0-rc1 use VS2012/VS2013 (x86 / x64) has many warnings!!!

### ISSUE THREAD

**Issue by shrimpz** [joyent/libuv#1505]
When fixed the warnings?
Thx

**Comment by saghul** [comment]
Please update the issue by showing **what** warnings you get.

**Comment by shrimpz** [comment]
Warning 1   warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data  D:\libuv-v1.0.0-rc1\src\inet.c  175
Warning 2   warning C4244: 'initializing' : conversion from '__int64' to 'unsigned int', possible loss of data  D:\libuv-v1.0.0-rc1\src\inet.c  202
Warning 3   warning C4244: 'initializing' : conversion from '__int64' to 'const int', possible loss of data D:\libuv-v1.0.0-rc1\src\inet.c  298
Warning 4   warning C4244: 'function' : conversion from 'ssize_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\fs-poll.c   187
Warning 5   warning C4244: '=' : conversion from 'ssize_t' to 'int', possible loss of data  D:\libuv-v1.0.0-rc1\src\fs-poll.c   190
Warning 6   warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss    D:\libuv-v1.0.0-rc1\src\win\fs.c    1
Warning 7   warning C4244: 'function' : conversion from 'ssize_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\fs.c    185
Warning 8   warning C4244: 'function' : conversion from 'ssize_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\fs.c    199
Warning 9   warning C4267: 'function' : conversion from 'size_t' to 'unsigned int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\fs.c    1197
Warning 10  warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\fs.c    1358
Warning 11  warning C4267: '=' : conversion from 'size_t' to 'USHORT', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\fs.c    1415
Warning 12  warning C4267: '=' : conversion from 'size_t' to 'USHORT', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\fs.c    1416
Warning 13  warning C4267: '=' : conversion from 'size_t' to 'USHORT', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\fs.c    1444
Warning 14  warning C4267: '=' : conversion from 'size_t' to 'USHORT', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\fs.c    1445
Warning 15  warning C4267: '+=' : conversion from 'size_t' to 'int', possible loss of data  D:\libuv-v1.0.0-rc1\src\win\getaddrinfo.c   131
Warning 16  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1673
Warning 17  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1687
Warning 18  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1720
Warning 19  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1753
Warning 20  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1774
Warning 21  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1797
Warning 22  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1817
Warning 23  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1837
Warning 24  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1860
Warning 25  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1881
Warning 26  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1904
Warning 27  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1925
Warning 28  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1946
Warning 29  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1960
Warning 30  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    1980
Warning 31  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2000
Warning 32  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2014
Warning 33  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2035
Warning 34  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2049
Warning 35  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2063
Warning 36  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2080
Warning 37  warning C4267: '=' : conversion from 'size_t' to 'ULONG', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2093
Warning 38  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2100
Warning 39  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2123
Warning 40  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2140
Warning 41  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2164
Warning 42  warning C4244: 'return' : conversion from 'ssize_t' to 'int', possible loss of data D:\libuv-v1.0.0-rc1\src\win\fs.c    2182
Warning 43  warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\fs-event.c  69
Warning 44  warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\fs-event.c  378
Warning 45  warning C4244: 'function' : conversion from 'ULONG_PTR' to 'DWORD', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\pipe.c  1020
Warning 46  warning C4244: 'function' : conversion from 'ULONG_PTR' to 'DWORD', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\pipe.c  1039
Warning 47  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\pipe.c  2003
Warning 48  warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data  D:\libuv-v1.0.0-rc1\src\win\process.c   628
Warning 49  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\process.c   748
Warning 50  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\process.c   784
Warning 51  warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\process.c   803
Warning 52  warning C4244: 'function' : conversion from 'ULONG_PTR' to 'DWORD', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\tcp.c   330
Warning 53  warning C4244: 'function' : conversion from 'ULONG_PTR' to 'DWORD', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\tcp.c   349
Warning 54  warning C4244: 'initializing' : conversion from 'ULONG_PTR' to 'DWORD', possible loss of data   D:\libuv-v1.0.0-rc1\src\win\tty.c   789
Warning 55  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\util.c  91
Warning 56  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\util.c  93
Warning 57  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\util.c  106
Warning 58  warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data    D:\libuv-v1.0.0-rc1\src\win\util.c  740

**Comment by shrimpz** [comment]
The warnings just compiled "libuv“ project,
NOT containe run-tests & run-benchmarks

**Comment by saghul** [comment]
Thanks! These seem harmless, yet annoying. A patch would be welcome, otherwise we'll address them when we've got time.

**Comment by saghul** [comment]
Closing. If you'd like to take a stab at this please open a PR at libuv/libuv.
