### ISSUE TITLE
1.0.0rc sets library version to 1.0.0. Intentional?

### ISSUE THREAD

**Issue by jbergstroem** [joyent/libuv#1508]
Since the library version is now 1.0.0 but the release says it's an rc; should consumers of libuv treat the release as abi stable? There already seems to be some changes in the 1.0.0 branch (for instance #1431) that could potentially conflict with this.

**Comment by saghul** [comment]
No, ABI might change a bit. I wanted to avoid it but couldn't. Either way, AFAIS the soname cannot be set to something like 1.0.0rcX , hence the 1.0.0.

Once 1.0.0 is released there will be no ABI breakage, until 2.0.0, that is.

**Comment by jbergstroem** [comment]
Thanks for elaborating. This pretty much makes pkg-config checks pointless since it wouldn't know the difference between 1.0rc\* and 1.0 though :( Hopefully package managers that exposes libuv handles dependencies differently.

There's really no problem bumping abi versioning differently from package version -- so the cleanest approach would just be major bumping abi on the "real" 1.0.

**Comment by saghul** [comment]
Well, package managers shouldn't package rc versions anyway :-)

**Comment by jbergstroem** [comment]
@saghul The problem with that statement is that everyone treats versioning and naming differently. I can imagine a pretty common use case is downloading latest available through github releases which doesn't really mention "do not trust this abi version".

At the end of the day, what we want to trust is really abi versioning. Worst case, people could have two versions of the libuv dylib/shared object with the same name.

**Comment by saghul** [comment]
@jbergstroem I understand your concern. I did a quick test and while the soname will stay as 1:0:0, we can set the version to 1.0.0-rc1 in autoconf and the pc file is generated just fine:

```
$ pkg-config --modversion libuv
1.0.0-rc1
```

So, my bad. Will fix for rc2!

**Comment by jbergstroem** [comment]
Perfect. I guess another "solution" would be avoiding distributing releases publicly, but through controlled environment (mailing list, whatnot) where people also would understand the possible implications of using said release.

**Comment by saghul** [comment]
Just released rc2 including this fix. Thanks for reporting @jbergstroem!
