### ISSUE TITLE
Port to Hurd

### ISSUE THREAD

**Issue by olijens** [joyent/libuv#1509]
Hi, please port libuv to Hurd.

I tried to build it on Hurd but the tests fail since all calls to uv_*, defined in kernel specific files in src/unix, fail.

Cheers, Oli

**Comment by jbergstroem** [comment]
Please provide more information about your system, environment and build output. Point being that others should be able to reproduce and assist with further qa. Attach instead of paste where relevant.

**Comment by bnoordhuis** [comment]
I daresay that a Hurd port is unlikely unless you are prepared to do the work yourself.  It's work enough to support the major Unices + Windows.

**Comment by txdv** [comment]
Yeah, I doubt that anybody will move a finger for hurd, unless it is yourself.

A simple "doesn't compile, plz port" won't really cut it.

**Comment by olijens** [comment]
yeah, expected as much :-)

Will give it a try then one day.

**Comment by jbergstroem** [comment]
Disregarding whether someone will implement it or not, I thought it would be good to collect information about it which is why I asked.

**Comment by saghul** [comment]
Feel free to open a PR when you have some basics working. Until then, I'm closing this, as Ben said it's enough work to deal with all Unices and Windows.
