### ISSUE TITLE
Handle EHOSTDOWN

### ISSUE THREAD

**Issue by indutny** [joyent/libuv#1512]
`connect()` may return it on OSX. see https://github.com/joyent/node/issues/8490.

Btw, is it really necessary to fail on that assert? Perhaps we could just print unknown or numeric code?

**Comment by bnoordhuis** [comment]
Caveat emptor: EHOSTDOWN is not a POSIX error code.  It's visible by default on Linux but on FreeBSD and Darwin, you need to compile without _POSIX_SOURCE.

**Comment by saghul** [comment]
Will look into it.

**Comment by Ognian** [comment]
Any news?

**Comment by jacob** [comment]
I am seeing this as well in my local dev environment, good to know that it's OSX specific.

**Comment by saghul** [comment]
Moved to https://github.com/libuv/libuv/issues/195
