### ISSUE TITLE
uv_cwd includes trailing \0 in size

### ISSUE THREAD

**Issue by creationix** [joyent/libuv#1514]
Given these identical bindings to `uv_execpath` and `uv_cwd`, I get the correct output with execpath, but wrong with cwd.

``` c
static int luv_execpath(lua_State* L) {
  size_t size = 2*PATH_MAX;
  char exec_path[2*PATH_MAX];
  int ret = uv_exepath(exec_path, &size);
  if (ret < 0) return luv_error(L, ret);
  lua_pushlstring(L, exec_path, size);
  return 1;
}

static int luv_cwd(lua_State* L) {
  size_t size = 2*PATH_MAX;
  char path[2*PATH_MAX];
  int ret = uv_cwd(path, &size);
  if (ret < 0) return luv_error(L, ret);
  lua_pushlstring(L, path, size);
  return 1;
}
```

Output:

``` lua
> uv.execpath()
"/usr/local/bin/luajit-2.0.3"
> uv.cwd()
"/home/tim/Code/luv\0"
```

**Comment by creationix** [comment]
Either the docs need to be changed to mention that cwd includes the null in size, or the code needs the +1 removed at https://github.com/joyent/libuv/blob/fabafd6236e976580a2153aa1dfc985af400feee/src/unix/core.c#L640

**Comment by saghul** [comment]
I fixed those to be consistent a while back, what version are you using?

**Comment by creationix** [comment]
I'm using the latest in the `v1.x` branch. https://github.com/joyent/libuv/blob/v1.x/src/unix/core.c#L640

Maybe you fixed in in master, but not here?

**Comment by saghul** [comment]
Will check!

**Comment by saghul** [comment]
Fixed in https://github.com/joyent/libuv/commit/8a8cff4b34c6dbaf6d31a2c9dda8afa3b1509cf0 Thanks for the report and help testing Tim!
