### ISSUE TITLE
Windows. uv_interface_addresses does not fill all structures

### ISSUE THREAD

**Issue by moteus** [joyent/libuv#1517]
When we calculate number of intrefaces we have loop

``` C
    for (unicast_address = (IP_ADAPTER_UNICAST_ADDRESS_XP*)
                           win_address->FirstUnicastAddress;
         unicast_address != NULL;
         unicast_address = unicast_address->Next)
```

But when we fill results we have 

``` C
    for (unicast_address = (IP_ADAPTER_UNICAST_ADDRESS_XP*)
                           win_address->FirstUnicastAddress;
         unicast_address != NULL && prefix != NULL;
         unicast_address = unicast_address->Next, prefix = prefix->Next) 
```

On my WinXP SP3 for `MS TCP Loopback interface` `win_address->FirstPrefix` is NULL.
So we count Loopback interface but does not fill it.

**Comment by saghul** [comment]
I believe https://github.com/joyent/libuv/pull/1482 addresses this. Hopefully I can review it next monday.

**Comment by orangemocha** [comment]
Yes, this is fixed by https://github.com/joyent/libuv/pull/1482

**Comment by saghul** [comment]
Thanks for confirming, @orangemocha, closing this one then!
