### ISSUE TITLE
Windows. uv_poll_init returns windows error codes not libuv error codes.

### ISSUE THREAD

**Issue by moteus** [joyent/libuv#1518]

**Comment by saghul** [comment]
Good catch! Do you feel like providing a patch? :-)

**Comment by moteus** [comment]
> Do you feel like providing a patch?

Thanks for the offer but I am not very comfort in libuv sources.

**Comment by saghul** [comment]
No worries, will fix!

**Comment by cjihrig** [comment]
@saghul would the fix be as simple as passing the result of `WSAGetLastError()` to `uv_translate_sys_error()`? If so, I'd be glad to submit a patch.

**Comment by saghul** [comment]
Yep, that's all there is to it.
