### ISSUE TITLE
Doc. Document when and how close handle which we send to process.

### ISSUE THREAD

**Issue by moteus** [joyent/libuv#1523]
Pseudocode

``` JS
srv.listen(function()
  cli = srv.accept()

  // send socket to child process
  worker.pipe.write2(cli, function() 
    // should we close cli here ?
  end)

  // or  we can close cli here ?
end)
```

**Comment by saghul** [comment]
You can close the handle once it has actually been sent to the process. Same concept as when freeing the memory which you write on a connection. That is, on the write completed callback.

If you think something might need clarification in the docs please do send us a PR :-)
