### ISSUE TITLE
Use `make dist` tarball for release instead of tag

### ISSUE THREAD

**Issue by jbergstroem** [joyent/libuv#1531]
..this way users get a baked auto\* environment, omitting the need to run `./autogen.sh`. Less dependencies and a quicker build.

**Comment by saghul** [comment]
I'm not sure about this. autoconf is just one of the supported build systems, those using it need to run autogen as stated in the README. Those using gyo need to install gyp. Should we bundle gyp? I don't think so.

Also, right now we can make releases on Windows, and we wouldn't be able to do it if we need to use make dist. (not that's it's a big problem, just pointing out a downside)

@bnoordhuis thoughts?

**Comment by bnoordhuis** [comment]
No strong opinions.  A tarball with no dependency on autotools is nice but, on the other hand, our users are developers and almost certainly have autotools installed anyway.

**Comment by saghul** [comment]
My thoughts exactly. Closing.
