### ISSUE TITLE
 test failed

### ISSUE THREAD

**Issue by yuaom** [joyent/libuv#1532]
os: unbuntu 12.04

`getsockname_tcp` failed: exit code 134
Output from process `getsockname_tcp`:
server socket: 0.0.0.0:9123
accepted socket: 127.0.0.1:9123
# Assertion failed in test/test-getsockname.c on line 95: memcmp(&check_addr.sin_addr, &compare_addr.sin_addr, sizeof compare_addr.sin_addr) == 0

`spawn_setuid_setgid` failed: exit code 134
Output from process `spawn_setuid_setgid`:
# Assertion failed in test/test-spawn.c on line 1054: r == 0
# FAIL: test/run-tests

1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues

**Comment by saghul** [comment]
How are you running the tests? As what user?
