### ISSUE TITLE
SIGPIPE thrown when a web browser closes the connection

### ISSUE THREAD

**Issue by imzyxwvu** [joyent/libuv#1535]
When a uv_write_t request is in progress, and the client (web browser) closes the connection, a SIGPIPE will be thrown before the callback called.

**Comment by txdv** [comment]
Can you provide a test case?

**Comment by imzyxwvu** [comment]
I didn't handle the uv_write error. It's my fault.

**Comment by imzyxwvu** [comment]
My program started a write request, then the read callback reported that the connection has been closed, soon the write request will cause a SIGPIPE. (Linux, v0.11) I don't know how to deal with it except handling SIGPIPE. Cancelling the request?

**Comment by indutny** [comment]
You need to ignore SIGPIPE signal using sigaction.
