### ISSUE TITLE
build: Failed to connect to chromium/gyp.git via https

### ISSUE THREAD

**Issue by odeke-em** [joyent/libuv#1547]
Following the README
  `$ mkdir -p build`
  `$ git clone https://git.chromium.org/external/gyp.git build/gyp`
I get:
 `fatal: unable to access 'https://git.chromium.org/external/gyp.git/': Failed to connect to git.chromium.org port 443: Connection refused`

However, using:
`$ git clone http://git.chromium.org/external/gyp.git build/gyp`
clones gyp successfully.
OR better:
`git clone https://chromium.googlesource.com/external/gyp.git`
   OR
`svn co http://gyp.googlecode.com/svn/trunk build/gyp`
- These urls were copied from github.com/indutny/bud.git

**Comment by odeke-em** [comment]
This issue is a subset of #1545

**Comment by saghul** [comment]
#1548 landed, closing.
