### ISSUE TITLE
Allowing multiple versions of libuv API to coexist

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1551]
_Context: I've been toying with libuv and to my chagrin I've discovered that my Archlinux has unstable 0.11, Debian has stable 0.10, and a 1.0 release is imminent. That makes it very hard to release my application without stuffing it with #ifdef's._

Seeing that a new release that breaks the API is coming and further changes can be expected in the near future, I think it'd be for the best if different "generations" of the API were able to co-exist.

The way e.g. GLib & co. do it is by using a different library name as well as pkg-config name, that is glib-2.0, gtk-3.0. Different applications can then call `pkg-config --libs libuv`, `pkg-config --libs libuv-1.0` or `pkg-config --libs libuv-1.1` as they need.

API breakage is nasty, please help the application developers.

**Comment by saghul** [comment]
I'm not sure about how we can help at this point. 0.10 didn't have pkg-config support, 0.11 was a development release, which gained pkg-config support at some point, and 1.0 is / will be properly versioned.

So, starting with 1.0 things will be OK, but we cannot change the past :-/ Also, packaging 0.11 given that it was unstable, might not have been the greatest idea.

**Comment by ghost** [comment]
I realize the past cannot be changed. My point was rather about being able to have multiple API/ABI versions of the library installed next to each other in the future. Right now would be a good moment to make the change. I'm not saying that you absolutely have to, however I fail to see any cons.

It's not solely about pkg-config. It means that different API/ABI versions should have a different name for headers, the library, and the pkg-config file. (The pkg-config file can include `-I/usr/lib/name-9.9` in cflags, so `#include <uv.h>` can stay.) This way applications that have not yet been modified to use the new API/ABI can still be compiled on the same system.

Right now that is not possible with this library. The new 1.0 will collide with the old 0.10 because they're both going to be named "libuv".

Generally I've noticed two basic naming schemes are used widely: name-9.9 and name9.

**Comment by saghul** [comment]
As I said, we cannot change the past, so 0.10 and 1.0 will collide, that's life :-( Now, for 1.0 we have promised stable ABI and backwards compatible API, so users should just use the latest and greatest version of libuv, and in case they depend on some specific bugfix the version can be checked easily at runtime.

When 2.0 is finished it won't be API compatible so we'll probably install it in libuv2 and have users import "uv2.h" probably. Anyway, this is way far for now :-)

I'm going to close this for now for the reasons mentioned above, in a nutshell, we'll address this when 2.0 is a thing.

**Comment by jbergstroem** [comment]
@saghul FWIW, you shouldn't really have to do "uv2.h" as long as you properly use pkg-config. That way its basically up to distros/packagers to utilise sane install paths – `pkg-config --cflags libuv-2.0` would return `-I/usr/include/uv2` or similar (if you really insist of breaking everything).
