### ISSUE TITLE
broken-down timer

### ISSUE THREAD

**Issue by yoonghm** [joyent/libuv#1552]
#### Is there an implemention broken-down timer in libuv

Currently **uv_timer_t** implements relative time. However I am looking for a timer library which could trigger called at, say "**Every Wednesday 3:00pm**", "**Every first day of the month at 12:00am**", etc.

Any suggestion?

**Comment by txdv** [comment]
libuv is a general async IO abstraction library for various async IO implementations on differnet OSes.

What you seek is a library like Chronic but written in C. Not the best place to ask for.

**Comment by saghul** [comment]
These kind of questions are better suited for the mailing list.
