### ISSUE TITLE
Bizzare build failure involving uv_spawn

### ISSUE THREAD

**Issue by kvanbere** [joyent/libuv#1553]
I have the code:

```
  if (uv_spawn(loop, &worker->req, &worker->options) < 0) {
    return -1;
  }
```

This fails on Mac OS X but works on Linux. If I remove the &, suddenly Linux builds and Mac OS X is broken:

```
/Users/kvanb/git/ocelot/src/ocelot/cluster.c:45:36: error: passing 'uv_process_options_t *'
      (aka 'struct uv_process_options_s *') to parameter of incompatible type
      'uv_process_options_t' (aka 'struct uv_process_options_s'); remove &
  if (uv_spawn(loop, &worker->req, &worker->options) < 0) {
                                   ^~~~~~~~~~~~~~~~
```

It's almost like they have two completely different API.

Mac OS X libuv is from homebrew, updated to latest, whereas Linux is built from git master.

Has the API silently changed ... ?

**Comment by saghul** [comment]
It might, what version do you run on each system?

**Comment by kvanbere** [comment]
I don't know anymore, sorry. I uninstalled it and cloned from master, ran `make install` on OS X and the issue went away. Now both boxes are in sync.

**Comment by saghul** [comment]
Oh. OK, we'll close this then! :-)

**Comment by kvanbere** [comment]
Don't close this! This means homebrew desperately needs updating! :)

**Comment by saghul** [comment]
Well that's a homebrew issue. libuv works fine in that regard unless a test
failure shows otherwise ;-)
