### ISSUE TITLE
doc: mention homebrew in README

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1554]
There's been a homebrew formula for libuv for a while: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libuv.rb
It allows one either to install a pre-built package or build it from scratches:

```
brew install libuv
brew install --HEAD libuv
```

I personally think this deserves to be mentioned in README.

**Comment by saghul** [comment]
I'd be OK with that! Mind sending a pull request? :-)

**Comment by ghost** [comment]
Not at all.

**Comment by kvanbere** [comment]
Maybe it's worth mentioning you MUST use --HEAD at the moment, as non-head is way too old #1553

**Comment by ghost** [comment]
Yes, I didn't mention the non-head option in the pull request at all.

**Comment by take-cheeze** [comment]
BTW there is `--devel`(latest unstable release which is 1.0.0-rc2 currently) option too.

**Comment by saghul** [comment]
PR landed, closing!
