### ISSUE TITLE
src/win/fs.c have not ANSI character, generate warning C4819.

### ISSUE THREAD

**Issue by zhaozg** [joyent/libuv#1581]
....\portable\libuv\src\win\fs.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

**Comment by saghul** [comment]
Not sure what that means, can you translate?

**Comment by zhaozg** [comment]
File include character can not display use codepage 936,please save as Unicode format.
I think some specail char include,not ASCII code
