### ISSUE TITLE
File system events stop working after file editing with vim

### ISSUE THREAD

**Issue by doppioandante** [joyent/libuv#1585]
```
$ uname -a
Linux arch 3.17.3-1-ARCH #1 SMP PREEMPT Fri Nov 14 23:13:48 CET 2014 x86_64 GNU/Linux
```

The system is a guest inside virtualbox, but this should not be a problem in this case, as the file is not located in a shared folder.
Steps to reproduce:
- Create a file
- Run https://gist.github.com/doppioandante/aadde9de9f5aef503830 using the file path as command line argument
- Edit the file **using vim**, then write using `:w`
  After the file is written, further changes to the file aren't caught by the program.

Program output:

```
➜  codes  ./test file.js
Adding watch on file.js
Change detected(1) in file.js: renamed file.js
Change detected(2) in file.js: changed file.js
Change detected(1) in file.js: renamed file.js
Change detected(1) in file.js: renamed file.js
```

Commands run:

```
 codes  ls
file.js  test  test.c
➜  codes  vim file.js
➜  codes  echo a > file.js
➜  codes  touch file.js
➜  codes  mv file.js file2.js
➜  codes  mv file2.js file.js
```

None of the above commands after vim editing is detected.

strace output: https://gist.github.com/doppioandante/67da576ec82c06b6ffd2

Using a different editor(I've tried nano) doesn't cause this bug. This led me to think that maybe the fd passed to inotify gets invalid after vim has done something strange while saving the file.
I'm unable to test this on windows ATM.

**Comment by indutny** [comment]
Ok, as figured it out in IRC - the cause is VIM, who creates the tmp file, and removes original file, and moves the tmp file to original file's location. Not an issue.
