### ISSUE TITLE
want test: port test-fs-sir-writes-alot.js from node to C

### ISSUE THREAD

**Issue by ry** [joyent/libuv#159]
https://github.com/joyent/node/blob/d2defa3012a5448a16a6cdab276a64f7bbd367e0/test/simple/test-fs-sir-writes-alot.js

**Comment by ry** [comment]
@igorzi interested?

**Comment by igorzi** [comment]
@ry - yep.

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
