### ISSUE TITLE
Put back dtrace probes

### ISSUE THREAD

**Issue by misterdjules** [joyent/libuv#1594]
dtrace probes [have been removed recently](https://github.com/joyent/libuv/issues/1478) because:
- They were causing build issues on some platforms.
- Only 2 probes were defined, which even on a platform where they would work properly, was not considered a sufficient use case.

However, given the usefulness of dtrace probes for troubleshooting issues in general and in node.js, my opinion is that we should investigate how to:
- Make these probes work properly on platforms where they do not.
- Identify other places in the code base where such probes would be useful.

**Comment by saghul** [comment]
I don't disagree :-) If you are willing to do the work please open an issue / PR at https://github.com/libuv/libuv so we can discuss the way forward.
