### ISSUE TITLE
Utilize lock-free queue for worker thread pool

### ISSUE THREAD

**Issue by jnicholls** [joyent/libuv#1598]
I think it would be far more efficient to utilize a lock-free queue (e.g. using compare-and-swap) to hand work off to the worker threads rather than using a mutex.  Has this even been considered and/or benchmarked against a lock-free queue for applications that are heavily utilizing the worker thread pool for blocking file I/O, etc.?

**Comment by saghul** [comment]
No, this hasn't been benchmarked,but I'm curious to see some numbers :-)

**Comment by saghul** [comment]
Ups, wrong project, closing.

**Comment by jnicholls** [comment]
Haha sorry, I mirrored it over at https://github.com/libuv/libuv/issues/188
