### ISSUE TITLE
MinGW errors and Makefile?

### ISSUE THREAD

**Issue by luislavena** [joyent/libuv#16]
Hello,

I was peeking into the project (heard from Rubinius guys at CodeConf) and was trying to build it using mingw-w64 GCC native on Windows.

http://mingw-w64.sourceforge.net/

It seems there are only two supported builds: Unix Makefile, which depends on libev and Windows solution files for Visual Studio.

Attempt to compile locally with it resulted in warnings and failure:

https://gist.github.com/925560

Considering not everybody will use Visual Studio, perhaps adding a `Makefile.mingw` could help others to get started and help out?

Thank you.

**Comment by piscisaureus** [comment]
The library and test runner now builds without error using MinGW. I didn't try with mingw-w64 as I don't have that on my machine and I'm not installing it anytime soon.

A makefile for MinGW builds _is_ welcome although it may be a little early to start maintaining that; I think it should be based on the linux makefile and I expect that one to change a lot.

**Comment by luislavena** [comment]
Can you tell me which version of MinGW did work for you?

GCC 3.4.5, official build from mingw.org:

https://gist.github.com/925638

mingw-w64 in 32bits mode provides better headers, but normally everything should work.

I can create a Makefile for it, but first need to get it to compile ;-)

**Comment by luislavena** [comment]
Scratch that, forgot to pull.

Now both 3.4.5 and 4.7.0 experimental compiles perfectly. Will create a makefile and supply in a pull request. Thank you.

**Comment by piscisaureus** [comment]
I'm changing a bit more because apparently the "normal" MinGW sucks.

**Comment by ry** [comment]
can the makefile be the same as the linux one? i'd like to attempt to setup a cross-compile env here

**Comment by luislavena** [comment]
@ry, yes, it could be the same, but dependencies on libev and `-unix` files will need to be conditional.

Let me think about it a bit more and will send a pull request.

**Comment by piscisaureus** [comment]
You'll also need to link with libws2_32.a, and leave out libev.

**Comment by luislavena** [comment]
Hello,

I was not able to associate a pull request and since my current makefile is incomplete, decided to gist it instead:

https://gist.github.com/949647

It misses the benchmark tasks because I'm unable to compile yet:

`make -f Makefile.mingw`

Produces this: https://gist.github.com/949649

Also the makefile is able to provide basic cross-compiler support. Either you can compile natively on Windows or cross compile using mingw-w64 builds doing:

`make -f Makefile.mingw PREFIX=i686-w64-mingw32-`

That will prefix all gcc, ar and others to use the right ones.

You can get mingw-w64 automated builds from their SourceForge page, under automated builds targeting Win32.

http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Automated%20Builds/
