### ISSUE TITLE
Adding the way to set affinity

### ISSUE THREAD

**Issue by kuebk** [joyent/libuv#160]
I would like to add a possibility of setting/getting affinity for each spawned process.

I want to:
- extend uv_process_options_t to contain an array(?) of cores to set process affinity to,
- add functions to set/get affinity on given process

What you think?

**Comment by ry** [comment]
can you suggest some API?

**Comment by kuebk** [comment]
Extend uv_process_options_t with unsigned long cpu_affinity?

int uv_set_affinity(uv_process_t\* process, unsigned long cpu_affinity);
int uv_get_affinity(uv_process_t\* process, unsigned long cpu_affinity*);

EDIT: Missclicked comment & close.

**Comment by bnoordhuis** [comment]
Closing, we're not going to do this.
