### ISSUE TITLE
can uv_timer_start be called multiple times?

### ISSUE THREAD

**Issue by jfirebaugh** [joyent/libuv#1603]
Could the [documentation](http://docs.libuv.org/en/v1.x/timer.html) state more about the invariants, pre-conditions, and post-conditions for the various uv_timer functions?
- May `uv_timer_start` be called a second time, after the callback from a previous call to `uv_timer_start` has been called?
- May `uv_timer_start` be called a second time, _before_ the callback from a previous call to `uv_timer_start` has been called?
- May `uv_timer_stop` be called if `uv_timer_start` has not been called?

**Comment by saghul** [comment]
The answer to all of them is "yes". If you want to improve the docs please open an issue or pull request in https://github.com/libuv/libuv
