### ISSUE TITLE
Multiplicity / thread-safety issues

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#166]
- uv_hrtime() and uv_exepath() can't report an error code (not bound to a loop)
- uv_hrtime() runs one-time initialization code, but is not thread-safe
- the uv_strerror() return value becomes invalid when uv_strerror() is called another time
- the "active tcp streams" is not thread-safe and not bound to a loop
- there's no way to fully clean-up and delete a loop. uv_loop_delete is not implemented.

**Comment by bnoordhuis** [comment]
> uv_hrtime() and uv_exepath() can't report an error code (not bound to a loop)

Doesn't strike me as a problem. The other issues have all been resolved.

**Comment by piscisaureus** [comment]
@bnoordhuis Closing is fine. We should probably stratify the api to return uv_err_t from non-loop functions.
