### ISSUE TITLE
Encoding specification in API

### ISSUE THREAD

**Issue by dolmen** [joyent/libuv#172]
The API should be capable of accepting Unicode strings in file names and paths, domain names, error messages, command line arguments.

Currently, those strings are just defined as "char *" which says nothing about the expected encoding.

**Comment by bnoordhuis** [comment]
Fixed in 72b5976. Possibly needs documenting in uv.h. @piscisaureus or @igorzi?

**Comment by piscisaureus** [comment]
This issue is valid - it's a documentation bug. We should document that on windows filenames (and other stuff) are expected to be in utf-8, whereas on unix the "terminal encoding" (for tty) or "binary" strings are expected.

**Comment by dolmen** [comment]
This issue is _not_ issue #201.

Here I'm talking about encoding in other areas than just the file I/O: domain names, error messages, command line arguments. Please add references to others commits if those are fixed too.

**Comment by piscisaureus** [comment]
Domain names: utf8 (probably just ascii) on windows, don't know about unix
Error messages: ascii
Command line arguments: utf8 on windows, binary on unix.

**Comment by bnoordhuis** [comment]
> Domain names: utf8 (probably just ascii) on windows, don't know about unix

A restricted subset of ASCII on all platforms.

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
