### ISSUE TITLE
windows: need uv_fs_t.path implementation

### ISSUE THREAD

**Issue by ry** [joyent/libuv#177]
see https://github.com/joyent/libuv/blob/a18860aec6416e4e6a9540471c61e9a497f55703/test/test-fs.c#L243-244

for https://github.com/joyent/node/blob/01bf209a3d8e89143739a0a9c5b4c523fb28e383/src/node_file.cc#L89-93

**Comment by piscisaureus** [comment]
This has been fixed for a long time. Closing.
