### ISSUE TITLE
uv_write_t and error handling

### ISSUE THREAD

**Issue by pietern** [joyent/libuv#179]
It seems that there is no logic in place to clean up queued uv_write_t's after a write error. When an attempted write for the head of the queue fails, its callback is executed by `uv__stream_io`. Subsequent uv_write_t's are ignored.

I don't think an API for iterating over write requests is a good idea. Maybe libuv should call every write callback with -1 status after the head failed to allow for cleanup (in a blocking way)? When a write error occurs, you generally want to call uv_close as soon as possible. Since the callback to uv_close is called by the reactor, we'll know for sure that the entire write queue was drained before the close callback gets called.

In addition: the current behavior shows that the write is immediately executed when the write queue is empty. When this fails, uv_write returns a -1 status and the uv_write_t can be cleaned up. Shouldn't the write callback for this request be called in the next reactor tick? (this is clearly a performance vs behavioral consistency thing, but am keen to find out what you think about this)

**Comment by bnoordhuis** [comment]
> Since the callback to uv_close is called by the reactor, we'll know for sure that the entire write queue was drained before the close callback gets called.

As discussed on IRC: that's the expected behaviour but it's not fully implemented yet. Fixing it turned out harder than I thought it would be - there's a bug hiding somewhere in tcp.c or stream.c that turns the write_completed queue into a circular list.

**Comment by bnoordhuis** [comment]
Fixed in 431195c, test added in 98b9f58.

**Comment by pietern** [comment]
Awesome, thanks!
