### ISSUE TITLE
x-platform error handling

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#18]
Need an API for it. 
- Define error constants / strings / ... to unambiguously identify errors in a portable way.
- Retain the original error code somewhere so the platform's strerror / FormatMessage functionality can be used.
- Do it in a way that integrates nicely with node, and play nice with other parts of node that also report system errors.

**Comment by ry** [comment]
I think we should define our own messages instead of using strerror. We do not need to retain the original code.

I'd like the error codes to be Unix-y, e.g. `OIO_CONNRESET`

**Comment by ry** [comment]
we will use int only for errors: 111536c9e567a08530516b904c6d7f34d307538a

The library needs to have a [one-to-one mapping](http://en.wikipedia.org/wiki/Injective_function) from the OS error codes into the OIO error codes. This will allow strerror look ups given any _used_ OIO error code.

**Comment by piscisaureus** [comment]
I agree that 1 to 1 mappnings would be ideal. The only thing is that windows has this: 

```
#define ERROR_TOO_MANY_OPEN_FILES  24
#define WSAEMFILE                  10004

#define ERROR_INVALID_PARAMETER  87
#define WSAEINVAL                100022
```

So do you want to have OIO_EMFILE1 and OIO_EMFILE2? That sucks.

I think it would be better if we left the error number untouched, and then provide something like:

```
/* Translate an error to a symbolic name, e.g. "EINVAL" or "EMFILE". */
/* Rare errors or those indicating total fuckup just become "EUNKNOWN" or maybe NULL. */
/* This translation not reversible. */
const char* oio_err_symbol(oio_err err);

/* Ask the system to describe an error. */
char *oio_strerror(oio_err err);
```

Also maybe we shouldn't use int -- users will be tempted to make assumptions.

```
typedef oio_err_s {
  int sys_errno_;
} oio_err;
```

**Comment by piscisaureus** [comment]
Or we could not expose error numbers at all. Just use `const char* oio_last_err()` and `char* oio_last_err_describe()` to obtain a symbolic name and a description for the last error.

**Comment by ry** [comment]
we should wrap the errnos for full control. i guess the mapping can't be one-to-one given your example, but you'll still need a way to take OIO_EMFILE and pull it back to one of those two codes.

**Comment by piscisaureus** [comment]
Sure. This is what I mean: we keep the original OS error number somewhere. We expose two apis, one that translates the error number to a cross-platform symbolic name, and another api that lets the os describe the error.

**Comment by ry** [comment]
my pref would be for a single int. if you want `struct { int errorno; int os_errorno; };` then go ahead.

**Comment by piscisaureus** [comment]
Then that "single int" shall be the original OS error number.
We provide an API for translating that to a platform independent error.

I think the most convenient would be:

```
const char OIO_EINVAL[] = "EINVAL";
const char OIO_EMFILE[] = "EMFILE";

const char* oio_translate_error(int errno) {
  switch (errno) {
     case EINVAL:
        return (const char*)&OIO_EINVAL;
     case EMFILE:
        return (const char*)&OIO_EMFILE;
  }
}

/* So this is possible */
if (oio_translate_error(err) == OIO_EINVAL) {
  fprintf(stderr, "Wrong arguments, heh? GFY!\n");
}

/* Or this. */
ExceptionObject->Set(error_symbol, 
                     String::New(oio_translate_error(err)));
```

**Comment by ry** [comment]
I want the values of the codes to be cross platform - otherwise we're leaking platform specific stuff into the program. We should have our own set of error descriptions. 

(But obviously having some way of accessing the platform's error strings is going to be important for debugging.)

```
DEF_ERR_MAP(ECONNRESET, OIO_CONNRESET, "Connection was reset by peer");
```

**Comment by piscisaureus** [comment]
> I want the values of the codes to be cross platform - otherwise we're leaking platform specific stuff into the program

Ok, so we could have:

```
typedef struct {
  int the_very_secret_os_errno_;
} oio_err;
```

> We should have our own set of error descriptions.

Ok, but bear in mind that windows defines _a lot_ (several thousands) of error codes. So either we're going to ignore a lot of them, or we'll add a 100kb or more to the executable. Most of these errors you'll rarely see if ever, but when you _do_ encounter one and liboio only tells you "unknown error", debugging is going to suck bigtime. And it'll likely affect node users.

**Comment by piscisaureus** [comment]
OK some final details. We agreed that functions return 0 on success and -1 on failure.
- You want to store errors on a per-handle basis or globally? So would we use oio_last_error() or oio_last_error(handle) to obtain the error. The latter is less convenient but more flexible imho.
- What to do with callbacks that have an error parameter (currently connect_cb and close_cb). Should 'error' be the actual error code or just 0|-1? I would vote for the second option.

**Comment by ry** [comment]
- I think we should follow Windows and do `oio_last_error(void)` 
- i also vote for second option.
