### ISSUE TITLE
write callback order (windows)

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#188]
Patch from Pieter Noordhuis here: https://github.com/joyent/libuv/commit/f0044c007a24ea4dd18f979c59b16c5f1b02fa8f, awaiting CLA.
Should fix https://github.com/joyent/node/issues/1697

@pietern Could you sign the node.js CLA please? http://nodejs.org/cla.html

**Comment by luislavena** [comment]
@piscisaureus @pietern was this merged in?

**Comment by pietern** [comment]
It wasn't, but can't be applied to the current tree as is anyway.

**Comment by bnoordhuis** [comment]
@piscisaureus: This got fixed, right?

**Comment by piscisaureus** [comment]
It didn't get fixed, but we fixed node to not crash when write callbacks arrive out of order. So we're not going to fix this unless anyone complains.
