### ISSUE TITLE
upgrade c-ares to 1.7.5

### ISSUE THREAD

**Issue by ry** [joyent/libuv#190]
http://c-ares.haxx.se/mail/c-ares-archive-2011-08/0020.shtml

warning: we're currently floating significant changes.

we should also attempt to contribute a .gyp file for c-ares upstream - it would help the upgrade process.

**Comment by saghul** [comment]
Hi,

Is anyone working on this at the moment? If not, I'd like to help :-) I need to parse NAPTR query results, which was just recently merged into c-ares master, so upgrading would make my life easier :-)

Appart from the fact that the files are organized in different directories, what significant changes are you referring to, @ry? Do you mean changes made to the c-ares inside libuv or potential changes made upstream?
