### ISSUE TITLE
modify uv_spawn to also accept uv_file for stdio

### ISSUE THREAD

**Issue by ry** [joyent/libuv#192]
we need this to pass test-child-process-custom-fds in Node. See https://github.com/joyent/node/blob/b20c98e42708668c564d5f83bad83cf074cf4f58/test/simple/test-child-process-custom-fds.js#L47

The test only checks file file descriptors - never socket fds. Non-file non-tty fds in uv_spawn can remain broken

**Comment by ry** [comment]
14:55 < piscisaureus> but it will prevent is from using FILE_FLAG_OVERLAPPED files in the future
14:55 < ryah> piscisaureus: can you explain?
14:55 < piscisaureus> since normally processes will not like it when their stdio is open in overlapped mode
14:56 < piscisaureus> ryah: if you're passing a file fd to a child process that's fine
14:56 < piscisaureus> ryah: but not so much if you have opened the file with FILE_FLAG_OVERLAPPED
14:57 < ryah> what if we change the overlapped file to an fd before sending it to the child?
14:57 < ryah> (does that change anything? probably not)
14:57 < piscisaureus> ryah: you can't change the overlapped/nonoverlapped mode I think
14:57 < piscisaureus> although we could just re-open the file and pass the new fd to the child
14:58 < ryah> so basicaly you're saying either uv_fs cannot support overlapped files OR we cannot support passing 
              files to children
14:58 < piscisaureus> yes
14:58 < ryah> i think i'd rather have overlapped uv_fs methods :)
14:58 < piscisaureus> well...
14:58 < piscisaureus> it's still questionable whether that's ever going to work well enough
14:59 < piscisaureus> but it seems kind of stupid to shut that door forever at this point
14:59 < ryah> sure
14:59 < ryah> well we're not going to do this immediately anyway
14:59 < piscisaureus> okay

**Comment by bnoordhuis** [comment]
Not relevant anymore, closing.
