### ISSUE TITLE
Wrong error message for fs_* operations

### ISSUE THREAD

**Issue by creationix** [joyent/libuv#210]
Here is an example from latest node on Linux showing the problem:

```
> require('fs').openSync('foobaz', 0, 0)
Error: ENOENT, Success 'foobaz'
```

I'm using latest libuv in my project and I have the same behavior.  From tracing the code, it looks like `.code` is set in the struct, but `.sys_errno_` is zeroed out and that's all the unix function looks for.  Thus it always says `Success`.

**Comment by bnoordhuis** [comment]
Provisionally fixed in c787046.
