### ISSUE TITLE
 throw new Error('Socket is not writable');

### ISSUE THREAD

**Issue by tommypowerz** [joyent/libuv#211]
i run  node v0.412 and this http://github.com/einaros/socket.io

my server is getting stabler... sometimes it crashes due to segmantion faults:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd0a4cf36f0 (LWP 24039)]
0x000000000062a873 in v8::internal::FlexibleBodyVisitor<v8::internal::StaticMarkingVisitor, v8::internal::FixedArray::BodyDescriptor, void>::Visit ()
Current language:  auto; currently asm

and sometimes i had this error: can this somehow be catched? i cannot find a send or emit without try/catch in my code

net.js:391
    throw new Error('Socket is not writable');
          ^
Error: Socket is not writable
    at Socket._writeOut (net.js:391:11)
    at Socket.write (net.js:377:17)
    at WebSocket.write (/var/www/web17/chatserver/node_modules/socket.io/lib/transports/websocket/hybi-07-12.js:180:17)
    at WebSocket.packet (/var/www/web17/chatserver/node_modules/socket.io/lib/transport.js:515:15)
    at WebSocket.heartbeat (/var/www/web17/chatserver/node_modules/socket.io/lib/transport.js:330:10)  
    at Object._onTimeout (/var/www/web17/chatserver/node_modules/socket.io/lib/transport.js:301:12)
    at Timer.callback (timers.js:83:39)

Program exited with code 01.

**Comment by bnoordhuis** [comment]
Do you get the crash or the exception with the latest master?

**Comment by tommypowerz** [comment]
which one is the latest master? 

i used: http://github.com/einaros/socket.io (downloaded it 4-5 days ago)

**Comment by bnoordhuis** [comment]
I mean Node's master, the project you filed a bug report with...

**Comment by tommypowerz** [comment]
sorry for the confusion.. this was suppost to be posted on socket.io

they told me they only support 0.4.12

but i plan ofcourse let this run on the latest version of nodes to report you the bugs

**Comment by bnoordhuis** [comment]
Oh wait, you posted this at joyent/libuv, not joyent/node (oversight on my part, I get mail for both). Sorry, but you're in the wrong place here.

If socket.io only supports 0.4.12 then I suppose there's not much point in trying out the master branch but I'd be curious if you still get that segfault.
