### ISSUE TITLE
Making uv_udp_t subclass uv_stream_t

### ISSUE THREAD

**Issue by erickt** [joyent/libuv#215]
There are a lot of benefits having `uv_udp_t` merge with the `uv_stream_t`. It'd let us cut out a lot of redundancy between the two codepaths (at least for unix). For the users, it'd let them optionally use `connect`, and then they can use `send`/`recv` instead of `sendto`/`recvfrom`. Or, the user could use `uv_getaddrinfo` to generically configure a socket.

The downside is that we'd have to protect against users passing non-sockets to `uv_sendto`, but we have to do that kind of error handling for a lot of cases anyway.

For the unix implementation, I'd suggest adding a `struct sockaddr_storage` and `socklen_t` to `UV_WRITE_PRIVATE_FIELDS`, and just switching UDP/TCP/PIPEs to use sendmsg, leaving everything else to use `write`/`writev`. I'm not yet sure what would need to be done for windows though.

**Comment by bnoordhuis** [comment]
We've discussed this when we implemented UDP and the conclusion was that a UDP socket is fundamentally not a stream. To name just one important distinction: TCP is 1-to-1, UDP is many-to-1 - one UDP socket can receive datagrams from many peers.

Embedding sockaddr_storage is quite costly. On most systems it's around 140 bytes whereas `sizeof(sockaddr_in)` is usually 8 to 16 bytes.
