### ISSUE TITLE
win\udp.c ENOSYS undefined

### ISSUE THREAD

**Issue by bradacina** [joyent/libuv#218]
win\udp.c
line 226:

int uv_udp_set_membership(uv_udp_t\* handle, const char\* multicast_addr,
  const char\* interface_addr, uv_membership membership) {

  /\* not implemented yet */
  uv__set_sys_error(handle->loop, ENOSYS);
  return -1;
}

ENOSYS is undefined on windows.
Replaced with E_NOTIMPL (from WinError.h)

**Comment by bnoordhuis** [comment]
Thanks. Fixed in 04daabd.
