### ISSUE TITLE
possible to allocate large memory block on win32

### ISSUE THREAD

**Issue by mei-rune** [joyent/libuv#225]
I'm not sure it is not a bug, please check......

deps \ uv \ src \ win \ util.c (64): utf16Buffer = (wchar_t *) malloc (sizeof (wchar_t) \* \* size);

It has two **

**Comment by leetreveil** [comment]
That's not a bug, the second \* is dereferencing size.

**Comment by bnoordhuis** [comment]
Like @leetreveil said, not a bug.
