### ISSUE TITLE
Win: uv_fs_event_init should not do i/o on the main thread

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#231]
See 

https://github.com/joyent/libuv/blob/9c6103a479b295bb22e4e109561f71f16a8e52fd/src/win/fs-event.c#L158 
https://github.com/joyent/libuv/blob/9c6103a479b295bb22e4e109561f71f16a8e52fd/src/win/fs-event.c#L176
https://github.com/joyent/libuv/blob/9c6103a479b295bb22e4e109561f71f16a8e52fd/src/win/fs-event.c#L194

**Comment by igorzi** [comment]
I'll take it.

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
