### ISSUE TITLE
crt calls are not safe from the thread pool

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#240]
Windows only: we're supposed to use _beginthread to create threads; a windows managed thread will leak memory when it uses crt functions.

**Comment by igorzi** [comment]
I just went through all crt functions that we run on thread pool, and looks like none of those functions use _getptd() (which is responsible for allocating the TLS struct that could leak).  I don't think we need to do anything for this, especially if we're planning to stop using crt functions for fs.

**Comment by piscisaureus** [comment]
Not really. We export uv_tp_queue work, which libuv users can use for anything. Node, for example, uses it to run openssl methods on the thread pool.

**Comment by saghul** [comment]
We use `_beginthread` for `uv_thread_t`, which is what we use for the threadpool now, closing! :-)
