### ISSUE TITLE
Support for threads analogous to child_watcher

### ISSUE THREAD

**Issue by paddybyers** [joyent/libuv#246]
I don't know if this is of interest:

https://github.com/paddybyers/libuv/commit/93015792f109180afe14266c51507ed1ced723d6

This was done as part of the work to support multiple node isolates. The requirement was to be able to watch for thread exit in the same way as process exit. The watcher itself is just ev_async, but helper functions also create pipes to pipe stdio in the same way as uv_spawn does for processes.

**Comment by bnoordhuis** [comment]
Thanks Paddy but we won't take it. Appreciate the effort though.

**Comment by paddybyers** [comment]
Yes, understood, it's long-since overtaken by events. It looks like I can still migrate to the libuv thread support you added, although I still have to figure out how to maintain the isolate stuff long term :)

**Comment by bnoordhuis** [comment]
Isolates are dead / have never existed as far as I'm concerned but if there's something we can do to make your job easier, let me know.

**Comment by paddybyers** [comment]
Thanks :)
