### ISSUE TITLE
Build in Visual Studio Express 2010

### ISSUE THREAD

**Issue by bigeasy** [joyent/libuv#25]
I've been able to follow along find in Visual Studio Express 2010. Keeping the Visual Studio Projects at the Express level will make it easier to get new developers involved, since there is no cash requirement beyond the Windows license.

With the latest Visual Studio solution file, there is a new feature in use, "Solution Items", that is disabled on Visual Studio Express. The code appears to build, but the current branch is not building for other reasons.

I'm not sure what "Solution Items" are. I'm waiting to see if I can still build in Express. If they are not a big win for other developers, if you were just trying something out, I'm letting you know that it doesn't work in Express.

I'd like to keep this issue around, opened and closed, for general discussion of Visual Studio Express, if we continue to support it. If we don't, I'd like to at least commit an alternative express compatible build in a subdirectory. If that's not cool, I suppose I can create a project that sits in a sibling directory.

**Comment by ry** [comment]
I agree, if at all possible we should target Express.

**Comment by piscisaureus** [comment]
It currently doesn't build in express because it doesn't build at all.

**Comment by bigeasy** [comment]
I know.

I'm noting that I get a warning message that "Solution Items" are not supported. An there is grayed area in the sidebar.

I noting this before someone sinks eight hours into the perfect "Solution Items" configuration.

**Comment by piscisaureus** [comment]
VS express 2010 will be supported. If there are problems, you should indeed create a an issue.

Wrt. the "solution items", it's just a stale reference. I'll remove it in a minute.

**Comment by bigeasy** [comment]
Thank you. If in the future there's a new issue, I'll reopen this issue so that we can keep the conversation in one place.

**Comment by rmtew** [comment]
I just cloned this, opened up a Visual Studio 2010 Express command prompt and typed "vcbuild.bat".  It failed to build any of the three projects (main, test and benchmark) due to inability to find "stdint.h" for each.

d:\VCS\GIT\libuv-clone\include\uv.h(35): fatal error C1083: Cannot open include file: 'stdint.h': No such file or direc
tory [D:\VCS\GIT\libuv-clone\uv.sln]
...

I can get it to compile by making the following approximate addition in the three respective places, but it is clearly not the correct solution.

```
       'include_dirs': [ ...
```
-            'C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/include',
         ],

**Comment by rmtew** [comment]
Okay, this was because it generated VC2008 Express solutions and projects, which do not appear to have "stdint.h".  Presumably if I can get it to use 2010 instead, it will just work.

**Comment by nikolaybotev** [comment]
Hi what is the status of this exactly?  I just cloned libuv and gyp generates vs2008 project files for me still. I have both vs2008 ultimate and 2010 ultimate installed. Is there a way to tell gyp to generate vs2010 project files?

**Comment by nikolaybotev** [comment]
I figured out this is a gyp issue. I am posting here for other unfortunate souls who stumble upon the same issue:

If multiple versions of Visual Studio are installed, gyp picks 2008 first, then 2005, then 2010 (as of time of this writing):

http://code.google.com/p/gyp/source/browse/trunk/pylib/gyp/MSVSVersion.py#207

To force gyp to generate VS 2010 projects, the easiest way is to set the GYP_MSVS_VERSION environment variable to 2010.

http://code.google.com/p/gyp/source/browse/trunk/pylib/gyp/MSVSVersion.py#245

Cheers,
-Nikolay

**Comment by gigi81** [comment]
The Nikolay post was really helpfull, thanks.
For others that stumble on this add this:
set GYP_MSVS_VERSION=2010
in the first lines of vcbuild.bat

**Comment by gigi81** [comment]
Fixed on #504
