### ISSUE TITLE
ETIMEDOUT not translated in unix/error.c's uv_translate_sys_error

### ISSUE THREAD

**Issue by hnsr** [joyent/libuv#250]
libuv doesn't properly translate ETIMEDOUT to EV_ETIMEDOUT in uv_translate_sys_error() in src/unix/error.c, leading nodejs to print the somewhat uninformative error "connect Unknown system errno 110" when it fails to connect to something

I am not very familiar with libuv code but it looks like it can be trivially fixed in src/unix/error.c by adding "case ETIMEDOUT: return UV_ETIMEDOUT;" in the switch statement at line 60

**Comment by bnoordhuis** [comment]
Fixed in 248ca5d6.
