### ISSUE TITLE
Enable omitting pages from filesystem cache on/after read

### ISSUE THREAD

**Issue by networkimprov** [joyent/libuv#256]
Necessary when reading a large number of files exactly once, as for backup or indexing or synchronization.

On Linux, posix_fadvise() provides this. I don't believe it's in libeio. Note, on ARM Linux the syscall is

```
long arm_fadvise64_64(int fd, int advice, loff_t offset, loff_t len);
```

**Comment by baudehlo** [comment]
This would be worth adding to fs-ext rather than node core. Patches are always welcome.

**Comment by networkimprov** [comment]
I don't understand why it doesn't belong in libuv. Flagging whether or not to impact the filesystem cache is required for any procedure reading a large number of files once each (backup, indexing, synchronization).

Please reopen, unless this is covered by another issue.

**Comment by baudehlo** [comment]
It's probably hard to do cross platform and isn't really necessary for core use of node. Honestly there are WAY more important things that should be in core than this (flock, for example).

**Comment by networkimprov** [comment]
The fact that the APIs are so different on unix & windows is a strong argument to do this in libuv. At least writing an flock binding is trivial for all platforms.

**Comment by baudehlo** [comment]
Flock is probably equivalently "hard".

**Comment by networkimprov** [comment]
Oh, I'd thought it or fcntl were common C lib functions; apparently not...

**Comment by bnoordhuis** [comment]
I don't see a pressing need to add this to libuv. Closing unless you can convince me otherwise.

**Comment by networkimprov** [comment]
Some apps need to read a potentially large tree of files, each exactly once, for synchronization or backup purposes, which will wipe out the file cache, unless this feature is available.

I'd be glad to provide a patch. (Tho won't get to it for a while yet.)

**Comment by bnoordhuis** [comment]
If someone can show me a real world libuv application where fs cache trashing is the bottleneck, I'll consider it. Until then, I won't be taking patches.

**Comment by piscisaureus** [comment]
I can't speak for unix variants, but at least windows is quite good in detecting access patterns and adjusting caching behavior accordingly. If it detects a serial read it'll quickly start doing only read-ahead caching and nothing else. If you really care, there is a flag for CreateFile (the winapi equivalent of open) that tells windows that the read is going to be serial. I don't really think we need this.

I would consider adding proper file stream support, and adding an option to use O_DIRECT. That would also allow us to do truly async file io on linux and windows, so it could have significant benefits.

**Comment by networkimprov** [comment]
Imagine the disk is virtual, accessed over a network. Reloading a large cache from that source would cause a significant drop in throughput.

It's a fair Q whether a series of sequential reads will really wipe out most of the cache, and I have verified that, as recently as Linux 2.6.32 with ext4, reading each file in a tree sequentially does pull most/all of the tree into the cache.

O_DIRECT might be a solution, however libuv would have to mask this:

> The O_DIRECT flag may impose alignment restrictions on the length and address of userspace buffers and the file offset of I/Os.  In Linux alignment restrictions vary by file system and kernel version and might be absent entirely.  However there is currently no file system-independent interface for an application to discover these restrictions for a given file or file system.

http://www.kernel.org/doc/man-pages/online/pages/man2/open.2.html
