### ISSUE TITLE
Remove all UV_EAI error codes

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#259]
These are currently mapped from a special set of error values that getaddrinfo() returns. Remap getaddrinfo errors to normal error codes and remove all UV_EAI errors.

**Comment by bnoordhuis** [comment]
@piscisaureus: You still want to do this? There are only three UV_EAI\* codes left and I don't see anything wrong with them.

**Comment by piscisaureus** [comment]
It's not consistent. At some point we decided that we wanted to drop EAI error codes and map them to normal ones. Now I don't want leave just 3 of them.

**Comment by bnoordhuis** [comment]
Okay, go and fix it then. Us unix folk don't use them.

**Comment by saghul** [comment]
We now report EAI codes consistently AFAIS, and replace EAI_SYSTEM with whatever the error was on Unices. Can this be closed now?

**Comment by saghul** [comment]
/me assumes we can close this now :-)
