### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [joyent/libuv#260]
I would like to point out that the preprocessor symbols "[`_UV_TREE_H_`](https://github.com/joyent/libuv/blob/b47c474cfd62eaf0030e069c160b363a2cb8ec2a/include/uv-private/tree.h#L26)" and "[`_NGX_QUEUE_H_INCLUDED_`](https://github.com/joyent/libuv/blob/b47c474cfd62eaf0030e069c160b363a2cb8ec2a/include/uv-private/ngx-queue.h#L7)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming conventions of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by bnoordhuis** [comment]
I suppose you're technically correct (the best kind of correct, according to some). Fixed in 7a2bd05.

**Comment by elfring** [comment]
Thanks for your source code adjustment.

I have found a few more update candidates. I would like to point out that identifiers like "[`ARES__H`](https://github.com/joyent/libuv/blob/2e4eca3b5e200171c3b446b53992aaac3f4106e7/include/ares.h#L18)" and "[`ARES__VERSION_H`](https://github.com/joyent/libuv/blob/2e4eca3b5e200171c3b446b53992aaac3f4106e7/include/ares_version.h#L2)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.

**Comment by bnoordhuis** [comment]
You should report those to c-ares, we only bundle it.
