### ISSUE TITLE
Slim Reader/Writer Locks only present on Windows Vista or greater

### ISSUE THREAD

**Issue by luislavena** [joyent/libuv#263]
Hello,

Seems libuv is using SRWLOCK in it's `uv_rwlock_t`.

The problem is that SRWLOCK is not defined when `_WIN32_WINNT=0x0501` (at least not under MinGW)

It requires define `_WIN32_WINNT=0x0600` (Vista) so SRWLOCK is defined.

This means libuv is bumping it's minimum required version?

**Comment by luislavena** [comment]
Forgot to include links associated with this:

http://msdn.microsoft.com/en-us/library/windows/desktop/aa904937(v=vs.85).aspx
http://msdn.microsoft.com/en-us/library/windows/desktop/ms683483(v=vs.85).aspx
http://msdn.microsoft.com/en-us/library/aa383745(v=vs.85).aspx

**Comment by bnoordhuis** [comment]
No, libuv should fall back to mutex based read/write locks on XP/2K and Vista.

**Comment by luislavena** [comment]
But is expecting SRWLOCK be defined at compile time, which means _WIN32_WINNT needs to be 0x0600 for MinGW properly define it.

**Comment by bnoordhuis** [comment]
Yes, we'll bump _WIN32_WINNT to 0x600.

**Comment by luislavena** [comment]
Ok, thank you.

**Comment by luislavena** [comment]
Hello @bnoordhuis seems b471b33da88da0ca0b913573370cc6919ec134e7 solved the issue for `config-mingw.mk` but the gyp file still defines `0x0502`:

https://github.com/joyent/libuv/blob/master/uv.gyp#L118

**Comment by bnoordhuis** [comment]
Thanks for pointing that out, Luis. It's fixed in 65bbf02.
