### ISSUE TITLE
Foreign file descriptors

### ISSUE THREAD

**Issue by waywardmonkeys** [joyent/libuv#265]
I have some libraries that I'd like to use in conjunction with libuv that expose their file descriptors for integration into a foreign event loop (in this case, I'd like that to be libuv).

libev seems to support this, so I suspect that it is a matter of adding a new handle type with readable / writable callbacks?

Examples of publicly available libraries that do this include libpq's asynchronous support and ZeroMQ.

**Comment by bnoordhuis** [comment]
Sounds reasonable. @ry?

**Comment by saghul** [comment]
I'd love too see this, and perhaps I could help (at least with the Unix part). Is anyone working on this atm?

And, how should the API look like? Should it be a thin wrapper around ev_io or perhaps make it inherit from uv_stream_t?

Thanks!

**Comment by bnoordhuis** [comment]
> Is anyone working on this atm?

No.

> And, how should the API look like? Should it be a thin wrapper around ev_io or perhaps make it inherit from uv_stream_t?

I haven't thought deeply about it but it should probably be a direct descendant of uv_handle_t. The file descriptor could very well be fundamentally incompatible with the concept of streams (think datagram sockets).

**Comment by saghul** [comment]
Thanks for the info, Ben. I'll see if I can work something out! :-)

**Comment by bnoordhuis** [comment]
Continues in #316.
