### ISSUE TITLE
struct sockaddr_in(6) arguments as pointers

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#275]
The function definition and implementastion of uv_ip4_addr is as follows:

``` c
struct sockaddr_in uv_ip4_addr(const char* ip, int port) {
  struct sockaddr_in addr;

  memset(&addr, 0, sizeof(struct sockaddr_in));

  addr.sin_family = AF_INET;
  addr.sin_port = htons(port);
  addr.sin_addr.s_addr = inet_addr(ip);

  return addr;
}
```

I would like it to change to:

``` c
void uv_ip4_addr(const char* ip, int port, struct sockaddr_in *addr) {

  memset(addr, 0, sizeof(struct sockaddr_in));

  addr->sin_family = AF_INET;
  addr->sin_port = htons(port);
  addr->sin_addr.s_addr = inet_addr(ip);
}
```
# Cons:
## Beauty of code

The code looks uglier at some place, instead of a one liner

``` c
struct sockaddr_in addr = uv_ip4_addr("127.0.0.1", TEST_PORT);
```

you have to do something like this

``` c
struct sockaddr_in addr;
uv_ip4_addr("127.0.0.1", TEST_PORT, &addr);
```

And code like this:

``` c
struct sockaddr_in addr1 = uv_ip4_addr("0.0.0.0", TEST_PORT);
struct sockaddr_in addr2 = uv_ip4_addr("0.0.0.0", TEST_PORT_2);
```

turns into

``` c
struct sockaddr_in addr1, addr2;
uv_ip4_addr("0.0.0.0", TEST_PORT, &addr1);
uv_ip4_addr("0.0.0.0", TEST_PORT_2, &addr2);
```

which makes it quite awkward if you have more variables defined, because then the actual assignment of the sockaddr variables are seperated from the definition 

``` c
struct sockaddr_in addr1, addr2;
// some other structs and variables
int r;

uv_ip4_addr("0.0.0.0", TEST_PORT, &addr1);
uv_ip4_addr("0.0.0.0", TEST_PORT_2, &addr2);
```

and easy to read stuff like this:

``` c
r = uv_tcp_bind(handle, uv_ip4_addr("127.0.0.1", TEST_PORT));
```

turns into 

``` c
struct sockaddr_in addr;
int r;

uv_ip4_addr("127.0.0.1", TEST_PORT, &addr);

r = uv_tcp_init(loop, handle);

r = uv_tcp_bind(handle, addr);
```

but at some other occasions, the readability doesn't change too much:

``` c
addr6 = uv_ip6_addr("::0", TEST_PORT);
```

``` c
uv_ip6_addr("::0", TEST_PORT, &addr6);
```

Well the addr assignment is not as as clear as it was, but it is not that bad either
# Breaks code

This change will break like everything. The changes are not that hard to make to get it going again, but they are annoying as hell. Making the entire test suite work again was a quite repetitive and rather boring task.

But since libuv has no **_stable**_ release yet, the impact might not be that significant.
# Pros:
## Stable API across different platforms/Easier function definition

The size of sockaddr_in and sockaddr_in6 can be different(in theory) on varying platforms. Well, everyone uses BSD sockets nowadays, but still, the possibility exists: The function definition would be different on different platforms if the sockaddr sizes are different.

I am facing this particular problem now while trying to provide some .NET bindings for libuv using DllImport (basically dlsym/dlopen/dlclose for C#). I don't know if the size on every possible libuv supported platform is the same. This means that if the size actually differs on a platform, my code will break and I will have to provide the specific definition for that one.

The technical problem behind this is that if the size of the struct is variable, I might end up calling the function while pushing the wrong amount of bytes onto the stack. This could shift the arguments and result in horrible segfaults.

Using a pointer would solve this problem: now I would end up pushing either 32bits or 64bits according to the underlying CPU architecture which DllImport and other similar solutions for other languages take into account therefore making it much easier to port. 
## No more stack pollution

We might have a lot of memory nowadays available and our stacks on operating systems are rather big compared to what we had before, but the sizes of these 2 structs (sizeof sockaddr_in = 16, sizeof sockaddr_in6 = 28) are not that small. If we would replace the definitions with pointers we might save 12 bytes, 20 bytes every time we call a function with a pointer to the struct instead of the struct itself. 

libuv is used for nodejs and in javascript you see a lot of of cascading async function calls, which all push these structs onto the stack.

And it feels somehow more right if you consider that the struct variables are different.

It might be not the best **Pro**, but if you are obsessed with **right** APIs it might be quite a big deal. 
# Speculations

Please comment on this:
## Thread safety?

I wonder if the current implementation of uv_ip4_addr is thread safe.
Well, we are using the stack, every thread has its own stack, so IMO it should thread safe.
If my logic is correct, my proposed implementation is not thread safe, since multiple calls at the same time at one variable could happen (because we are passing the address). 
# TO BE CONTINUED
# opinions and comments are very welcome

**Comment by bnoordhuis** [comment]
> The size of sockaddr_in and sockaddr_in6 can be different(in theory) on varying platforms. Well, everyone uses BSD sockets nowadays, but still, the possibility exists: The function definition would be different on different platforms if the sockaddr sizes are different.

Does it matter? Even if the size of sockaddr_in and sockaddr_in6 vary across platforms, they're still fixed for the platform you compile libuv for.

> We might have a lot of memory nowadays available and our stacks on operating systems are rather big compared to what we had before, but the sizes of these 2 structs (sizeof sockaddr_in = 16, sizeof sockaddr_in6 = 28) are not that small. If we would replace the definitions with pointers we might save 12 bytes, 20 bytes every time we call a function with a pointer to the struct instead of the struct itself.

It makes no difference (for x86 and x86_64 at least) since the caller allocates. To wit:

``` c
struct address
{
  int a, b, c, d;
};

struct address resolve1(void)
{
  struct address addr = {-1, -1, -1, -1};
  return addr;
}

void resolve2(struct address *addr)
{
  addr->a = addr->b = addr->c = addr->d = -1;
}
```

That compiles down to (snipped for brevity):

``` asm
resolve1:
        pushl   %ebp
        movl    %esp, %ebp
        movl    8(%ebp), %eax
        movl    $-1, 12(%eax)
        movl    $-1, 8(%eax)
        movl    $-1, 4(%eax)
        movl    $-1, (%eax)
        popl    %ebp
        ret     $4

resolve2:
        pushl   %ebp
        movl    %esp, %ebp
        movl    8(%ebp), %eax
        movl    $-1, 12(%eax)
        movl    $-1, 8(%eax)
        movl    $-1, 4(%eax)
        movl    $-1, (%eax)
        popl    %ebp
        ret
```

**Comment by txdv** [comment]
seems like my proposal totally sucks
