### ISSUE TITLE
read watcher for uv

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#288]
libev has a readwatcher - it just notifies if there is at all something to read so the user itself can decide how to read the data.
This would be useful for node-ncurses, since it uses the ev read_watcher to determine if there is something to read and then it uses getch (provided by the curses library) to actually get the data.
So it is impossible to compile node-ncurses on windows.

getch returns an integer of the key pressed including information like weather 'alt', 'ctrl', etc. was pressed or not.
Using the uv approach to read from the TTY object does not take this kind of information into consideration.

**Comment by txdv** [comment]
https://github.com/txdv/libuv/tree/read_watcher

**Comment by txdv** [comment]
I updated the branch, took boords comments into consideration.
But we need a windows implementation for this as well, someone out there with windows please?

**Comment by txdv** [comment]
I talked to bnoordhuis on irc and he suggested to make the read_watcher a handle that you can instantiate from an arbitrary fd.
There is a draw back: kqueue needs all file descriptors to be in the same kqueue (loop).

So I coded it that one can instantiate a read_watcher handle from an arbitrary stream (so the read_watcher ends up in the same loop as the stream itself). The handle is an abstraction, all the action is done in the stream anyway, it makes the API just look nicer.

https://github.com/txdv/libuv/tree/read_watcher2

Any comments bnoordhuis?

**Comment by piscisaureus** [comment]
Maybe we can somehow have full ev_io like support for some handle types? I can provide it for windows, although it will be much less efficient than overlapped io. I think it could be useful because it is sometimes needed for integration with other libraries (e.g. c-ares).

**Comment by txdv** [comment]
what other ev_io functionality are you missing?

On a comment on the read_watcher2 (it has a uv_read_watcher_t which is a handle).
I don't know, the implementation is kind of heavy for a simple callback.
In my opinion this would be nicer:

``` c
UV_EXTERN int uv_read_start(uv_stream_t*);
UV_EXTERN int uv_read_stop(uv_stream_t*);

UV_EXTERN int uv_read_set_callbacks(uv_stream_t*, uv_alloc_cb, uv_read_cb,
    uv_read2_cb, uv_read_watcher_cb);
```

Any comments?

**Comment by bnoordhuis** [comment]
Closing, continues in #316.
