### ISSUE TITLE
add shared library target

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#289]
A shared library build target would make my life much easier.

https://github.com/txdv/libuv/tree/sharedlibrary

Here is a branch with the functionality for the makefile/linux build system.
I don't know if the windows variant works, need some tester and I do not know about gyp anything at all.

**Comment by luislavena** [comment]
@txdv work towards a shared library has already been implemented in master, but not completed.

See the TODOs about symbol hiding that are still pending:
https://github.com/joyent/libuv/blob/master/include/uv.h#L45

(and use `-fvisibility=hidden` for when compiling?)

PS: wonder why is this a Issue and not a pull request?

**Comment by txdv** [comment]
maybe because of code review? further suggestions?

You said that there is already a shared library target in master? Can you point out where it actually is?

Edit: Ok, I see now what you meant with your last post, people can read more on this issue on http://gcc.gnu.org/wiki/Visibility

I have to admit that I did not care about the visibility because I just wanted to have a shared library so I could access the functions from C#. But I'll look into this.

**Comment by txdv** [comment]
So I have updated the my branch.

Now I have to somehow distinguish between the object files created for the shared and the static library.
The shared library object files should be compiled with -DBULDING_UV_SHARED, while the static library should be compiled without this macro.

Currently I am adding that macro manually to the clags in the config-unix.mk but this is a bad solution I guess.
There is also USING_UV_SHARED.

Could someone (preferably the committer of the windows dllimport definitions Bert Belder) tell me how one is supposed to set those flags?

**Comment by nikolaybotev** [comment]
I just managed to build uv as a DLL on windows. I had to:
1) open the project in vs2010 and convert it (generated sln was in vs2008 format and did NOT build from the command line due to missing stdint.h pre-vs2010)
2) created a new configuration Debug-dll
2.1) change configuration type to DLL
2.2) add the BUILDING_UV_SHARED preprocessor directive
2.3) add Ws2_32.lib, Psapi.lib, Iphlpapi.lib as additional dependencies to the Linker input

compiles fine and dumpbin shows all exports and imports look fine, but have yet to test the generated dll

**Comment by nikolaybotev** [comment]
run-benchmarks linked to the DLL works like a charm. Do you guys plan on providing first-class support for building as a shared library as part of the standard gyp infrastructure?

I could look into updating gyp with a new target for windows, and Linux and Mac at a later point. Would that be useful or do you guys already have this in place/coming soon?

**Comment by txdv** [comment]
Do that in a branch and post the branch in here!
Do that for windows first and I'll try to do it for linux :)

**Comment by nikolaybotev** [comment]
I was wrong, I do not have the time for dealing with gyp and posting a branch here. The manual steps I documented here are good enough for me for now. Hopefully someone else with more gyp expertise and/or time can tackle this.

**Comment by judofyr** [comment]
What's the status on this?

**Comment by jbergstroem** [comment]
I guess the next relevant question is if libuv will offer an versioned ABI. Guess the library is still in its conception, but all this static compiling and embedding feels "wrong".

**Comment by bnoordhuis** [comment]
Building a shared library should already Just Work(TM), provided you pass `-Dlibrary=shared_library` to gyp. I will entertain patches to the Makefiles but in all honesty, I don't care - gyp is the way forward.

@jbergstroem: re: versioned ABI: Eventually maybe, there's no rush so far.

**Comment by luislavena** [comment]
> Building a shared library should already Just Work(TM), provided you pass -Dlibrary=shared_library to gyp

As long gyp is supported by your platform (hint: mingw still isn't) :wink:

**Comment by txdv** [comment]
At least provide some information how to build with gyp :(

**Comment by bnoordhuis** [comment]
@txdv Look at how gyp_uv or vcbuild.bat calls gyp. `make -C out BUILDTYPE=Debug` (or Release) is how you build with the Makefile target.

**Comment by avalanche123** [comment]
Addressed in #428
