### ISSUE TITLE
[unix] Crash on uv_guess_handle if error is produced

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#293]
On unix uv_guess_handle calls uv__set_sys_error with NULL as the loop argument, causing a segfault. Should it just return UV_UNKNOWN_HANDLE instead?

**Comment by bnoordhuis** [comment]
Thanks for the report, Saúl. It's fixed in bf8ccfc.

**Comment by saghul** [comment]
That was quick! Thanks @bnoordhuis!
