### ISSUE TITLE
Create junction points instead of symlinks

### ISSUE THREAD

**Issue by kkaefer** [joyent/libuv#296]
Symlinks require admin access and are only available from Windows Vista on. libuv should create [junction points](http://support.microsoft.com/?kbid=205524) ([C++ interface](http://www.flexhex.com/docs/articles/hard-links.phtml#download)) if possible. Junction points only work on directories, so plainly using them for everything won't work either. Not sure what's the best way to do this.
@gissues:{"order":87.5,"status":"backlog"}

**Comment by piscisaureus** [comment]
Don't want "instead of" but "in addition to" should be fine.

(Old) code to create symlinks is already here: https://github.com/piscisaureus/node/blob/abbc52482809081c01ed06d08ba2c8d50bc65d5d/src/platform_win32_fs.cc#L21-174

**Comment by kkaefer** [comment]
That code already seems to create junction points. https://github.com/piscisaureus/node/blob/abbc52482809081c01ed06d08ba2c8d50bc65d5d/src/platform_win32_fs.cc#L193-199 has a bool parameter for creating a junction point instead of a symlink.

**Comment by Bonuspunkt** [comment]
shouldn't be a creation of hard link (file) and junction (dir) considered?
this would work around the "requires admin privileges" issue

**Comment by piscisaureus** [comment]
@Bonuspunkt 
No. If the user wants to create a hard link, he should just use uv_fs_link.

**Comment by piscisaureus** [comment]
This has been fixed by @igorzi in 60af28a.
