### ISSUE TITLE
Child process doesn't terminate after longjmp in threadpool

### ISSUE THREAD

**Issue by kkaefer** [joyent/libuv#308]
Demo code is at https://gist.github.com/1760397

It looks like child processes don't terminate correctly when a `longjmp` has happened before in a threadpool function. The child process closes stdout and stderr, but node fails to report that it terminated. After that, I can only terminate node with `kill -9`. Am I using `longjmp` incorrectly?

**Comment by kkaefer** [comment]
(not sure this is a libuv problem, but the same code worked in node v0.4)

**Comment by bnoordhuis** [comment]
It should work. However:
1. This is not a libuv bug.
2. It's generally not a good idea to longjmp() around in programs that use mutexes. (Should be harmless in this particular case but the advise stands.)
3. You probably need to use `siglongjmp()`.

**Comment by bnoordhuis** [comment]
@kkaefer: Late addendum, I forgot to mention in my previous comment that you need to declare your locals `volatile`, they're getting clobbered now.

**Comment by kkaefer** [comment]
Thanks for your feedback. In this particular case I decided to use C++ exceptions with throw instead (I was already in a C++ context anyway), which works fine.
