### ISSUE TITLE
unix: reimplement EMFILE trick

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#315]
Stash away an open file descriptor. When EMFILE is returned by e.g. `accept()`, close the spare and retry the operation, then close the new file descriptor. (Note: not foolproof in multi-threaded environments.)

This is good because it signals to peers that we're overloaded / stops connections from rotting away in the listen backlog. It also mitigates issues like joyent/node#2529.

**Comment by dvv** [comment]
+1

**Comment by bnoordhuis** [comment]
Fixed in 4f5c8da.
