### ISSUE TITLE
TODO: Add API for serial ports

### ISSUE THREAD

**Issue by radare** [joyent/libuv#318]
It would be good to add support for serial ports on libuv at some point. I think that basic event api would work with COM# (windows) or /dev/ttyX (unix). But we need an API to configure the speed, parity, etc.. of the terminal.

**Comment by bnoordhuis** [comment]
That's out of scope for libuv. You're free to build something on top, of course, but libuv itself is not the place for it.

**Comment by dazhbog** [comment]
I think this is changing slowly since Node.js is used for so many other things related to the Internet of Things. Looking at the issues on the Node.js repo, I think that many people would want it, but even more use it today, with the help of a 3rd party module.
