### ISSUE TITLE
call uv_close() callbacks that are registered post-return from uv_run()

### ISSUE THREAD

**Issue by olsonjeffery** [joyent/libuv#319]
If I have a handler that was added to the loop, but is not keeping the loop from exiting (via uv_unref() ), I'd like to still be able to use uv_close(), after uv_run() returns, to register a callback to be processed once any libuv-managed memory/descriptors linked to the handle have been released.

Right now, it appears that a callback registered as such isn't executed (in my testing with a uv_async_t). So I'm left to immediately free the handle's data/ptr after uv_close() (it's still a safe call) returns, which bnoordhuis classified as a "dangerous yes" in terms of possibility. Thanks.

**Comment by piscisaureus** [comment]
@olsonjeffery What about this:

``` c
uv_run(loop) // This is the main loop`
// Here we have fallen out of the loop because the refcount dropped to zero
uv_ref(loop);
uv_close(my_async, my_async_close_cb);
uv_run(loop);
```

**Comment by saghul** [comment]
Closing, it can be achieved as @piscisaureus said (refcount now works different though).
