### ISSUE TITLE
windows: make libuv thread-safe

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#320]
Timers are stored in a static rbtree right now, there are some other static variables too. Those should all be moved into the `uv_loop_t` struct sometime soon, it's blocking the Rust guys.

**Comment by olsonjeffery** [comment]
thanks!

**Comment by piscisaureus** [comment]
@bnoordhuis Timers _are_ stored in the loop struct. RB_GENERATE_STATIC just generates functions. Where do you see thread-safety issues?

**Comment by bnoordhuis** [comment]
I was worried about [this](https://github.com/joyent/libuv/blob/fbc2154/src/win/timer.c#L34) but `uv_ticks_per_msec_` doesn't appear to be used at all.

**Comment by piscisaureus** [comment]
Did anyone experience actual thread safety issues on windows? I know there are some counters that are not embedded in the loop struct yet - but that shouldn't matter, we don't rely on them to be absolutely correct.

@olsonjeffery @bnoordhuis

**Comment by bnoordhuis** [comment]
Closing, seems we're fine.
