### ISSUE TITLE
Test failures on windows

### ISSUE THREAD

**Issue by Keno** [joyent/libuv#330]
I have buillt libuv in both mingw and MSVC and I have 8 test failure (http://pastebin.com/ARYY62ga). Is that normal?

**Comment by bnoordhuis** [comment]
> Is that normal?

The *_ref tests? Yes. Other tests may fail for a number of reasons. Some operations aren't supported on Windows XP, for example.

**Comment by piscisaureus** [comment]
The TTY test should probably be disabled

**Comment by piscisaureus** [comment]
This has been fixed.
