### ISSUE TITLE
getaddrinfo error codes

### ISSUE THREAD

**Issue by erikdubbelboer** [joyent/libuv#334]
Shouldn't `uv_getaddrinfo()` return the error codes of the underlying `getaddrinfo()` call?

Our application started throwing ENOENT exceptions on dns lookups of `localhost`. It took us a long time to figure out that our application was running out of file descriptors and `getaddrinfo()` was actually throwing an EMFILE error.

This would be a fix but it breaks the dns tests which are still looking for an ENOENT:

<pre>
diff --git a/deps/uv/src/unix/core.c b/deps/uv/src/unix/core.c
index e93a168..4bae632 100644
--- a/deps/uv/src/unix/core.c
+++ b/deps/uv/src/unix/core.c
@@ -649,7 +649,7 @@ static int uv_getaddrinfo_done(eio_req* req) {
 #else
   } else if (handle->retcode == EAI_NONAME) {
 #endif
-    uv__set_sys_error(handle->loop, ENOENT); /* FIXME compatibility hack */
+    uv__set_sys_error(handle->loop, errno);
 #if __sun
   } else if (handle->retcode == EAI_MEMORY && hostlen >= MAXHOSTNAMELEN) {
     uv__set_sys_error(handle->loop, ENOENT);
</pre>

**Comment by bnoordhuis** [comment]
> Shouldn't uv_getaddrinfo() return the error codes of the underlying getaddrinfo() call?

Alas, no. `getaddrinfo()` isn't guaranteed to set `errno` unless it returns `EAI_SYSTEM`.

**Comment by erikdubbelboer** [comment]
Then shouldn't we check for EAI_SYSTEM and set the correct error in this case? Currently there is just no way to really know why `getaddrinfo()` failed!

**Comment by bnoordhuis** [comment]
I should've anticipated that question. :-)

The reason `EAI_SYSTEM` isn't handled like that is because glibc sometimes sets `h_errno` instead of `errno`. In other words, you would get bogus error codes. UNIX is great, isn't it?

**Comment by erikdubbelboer** [comment]
Great :(

Since node uses it's own set of error codes, couldn't we we just return a custom EAI_SYSTEM like error code instead of ENOENT? Since ENOENT seems like the wrong code for these kinds of errors (out of memory, out of file descriptors, ...)

**Comment by bnoordhuis** [comment]
If your patch fixed the issue for you, then the system resolver returned `EAI_NONAME` or `EAI_NODATA`, not `EAI_SYSTEM`. You almost never get `EAI_SYSTEM`, it's the `getaddrinfo()` equivalent of `abort()`. With the other two error codes, the value of `errno` is unspecified.

**Comment by erikdubbelboer** [comment]
I guess so yes. So it returend `EAI_NONAME` but I checked `errno` and it is set to `EMFILE`. Even though `errno` is correct in this case I guess it won't aways be so I have no idea how to fix this. Maybe somehow exposing `errno` in the error thrown, but I don't have enough knowledge of how nodejs errors work to be able to fix this (of even see if it's possible).
