### ISSUE TITLE
Lifetime of buffers on uv_write

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#344]
Hi,

I was wondering what the expected lifetime for buffers passed to uv_write was so I checked the code and found what could be an inconsistency between Windows and Unix.

In Unix uv_write copies (with memcpy) all the buffers passed, so basically I could write code like this:

```
malloc some buffers here
uv_write the buffers
free the buffers
```

On Windows, OTOH, I don't see that memcpy, and according to the documentation (please correct me if I'm wrong) on WSASend (http://msdn.microsoft.com/en-us/library/windows/desktop/ms742203(v=vs.85).aspx) the buffers must not be touched until the operation is finished. I didn't try it out, but I think that freeing them right after uv_write might not be nice.

Am I on the right track here? In case I am, the Unix approach would save me some extra malloc/memcpy/free calls :-) In my case I have some Python string objects, so in order to safely write them over a TCP handle I copy their internal buffer, and free it in the write callback. If uv_write would do the copying, I could avoid that malloc/memcpy/free for the Python string internal buffer.

Thoughts?

**Comment by bnoordhuis** [comment]
/cc @piscisaureus 

It's the responsibility of the caller to keep the memory that the `uv_buf_t` structs point to alive and untouched until the write request completes. It's libuv's responsibility however to make a copy of the structs themselves.

**Comment by saghul** [comment]
Hi Ben,

Right. I mistakenly thought that in Unix the whole content of the structs themselves was copied, but it's not, yeah that makes sense :-)

You may close this if @piscisaureus confirms that copying is not required on Windows then.

**Comment by piscisaureus** [comment]
https://github.com/joyent/libuv/blob/685b36ba661933a675d809028714df577c808439/src/unix/stream.c#L935-937:

> /\* The buffers to be written must remain valid until the callback is called.
> - This is not required for the uv_buf_t array.
>   */

**Comment by saghul** [comment]
@piscisaureus Doh, I somehow missed that, sorry!
