### ISSUE TITLE
Unsafe include guards

### ISSUE THREAD

**Issue by elfring** [joyent/libuv#346]
I find your include guards like "[`UV_H`](https://github.com/joyent/libuv/blob/2ef5798c6f0513914bf83aa910b2535d9a1d5948/include/uv.h#L24)" and "[`EIO_H_`](https://github.com/joyent/libuv/blob/abf9654a55fe7c1c5b729626914c437c99d1a668/include/uv-private/eio.h#L40)" too short.
How do you think about to add an [UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier) to them so that the reuse of the header files [will become safer](http://en.wikipedia.org/wiki/Include_guard#Difficulties)?

**Comment by bnoordhuis** [comment]
Sorry but no, not going to do that.
