### ISSUE TITLE
refcount refactor

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#347]
The current refcount system kind of sucks and it also makes debugging impossible. Therefore we are going to refactor it.

First, there are new reference count principles:
- Handles add a reference to the event loop _only_ when they are active.
  - `uv_check`, `uv_idle`, `uv_prepare` are only active when they are started.
  - `uv_timer` is active when a timer is set. If the timer is repeating, it is active until it is stopped. If the timer is one-shot, it is active until it times out.
  - `uv_async` is always active.
  - `uv_stream` is active when it is reading or listening. (a pending write, shutdown connect does _not_ make the handle active. Instead the `uv_req_t` associated with the write or connect action keeps the loop alive).
  - `uv_fs_event_t` always refs (there is currently no way to start/stop an fs event watcher).
- _all_ `uv_req_t` reference the event loop until they complete.
- `uv_close(uv_handle_t*)` adds an additional reference to the event loop until the close callback is made.

Second, `uv_ref` and `uv_unref` need to be changed. Currently they take a pointer to the event loop struct as an argument, and just blindly increase or decrease the loop's reference count.  After the refactor it should work like this.
- `uv_ref` takes `uv_handle_t*` as the only argument.
- `uv_unref` and `uv_ref` are idempotent, e.g. calling `uv_unref` on a handle that is already unref'ed should not have any effect. Same for `uv_ref`ing a ref'ed handle.
- Every handle starts in ref'ed mode, In ref'ed mode a handle keeps the event loop alive when it is active.
- When a handle is unref'ed it never refs the event loop.
- `uv_ref` and `uv_unref` do not change the referencing semantics of `uv_close`. `uv_close` _always_ adds an additional reference to the event loop until the close callback is made.
- `uv_req_t`'s cannot be unref'ed. They always reference the event loop until their callback is made.

@bnoordhuis and @piscisaureus will work on this.

**Comment by creationix** [comment]
I need an API to know if a handle is "active" by active I mean it may fire a callback in the future without further API interaction.  This means there are any pending requests tied to that handle or the handle itself can emit events (like a listening tcp or readable stream).  We can probably just change the semantics of uv_is_active.

For bonus points I would like to be notified via an event (C callback) when this state changes so I can sync some other values in the various VM bindings (strength of GC reference for example).  This would mean adding an extra C function pointer, something like `on_active_change(uv_handle* handle, int is_active)`.

From my point of view I don't care if it's the handle itself that's "active" or if it just has pending requests.  I just need to know if C callbacks may be called related to this handle.

For requests themselves I may store additional data (like a one-use script callback) that needs a GC ref, but that's simple enough logic I don't need a special libuv API.  As I understand the C callback associated with a request fires once and only once, so I can simply unref in the callback.

**Comment by dvv** [comment]
+1. Very welcome. I add that since, imho, the only use of `on_active_change()` is to catch when the handle becomes "dead", I would instead propose to introduce `uv_*_done(void (*on_done)(uv_handle_t *))` registering such event.

**Comment by mitsuhiko** [comment]
With this change it's incredible hard to resurrect a loop on shutdown. By itself on_close callbacks are not called at the end of `uv_run` so I need to add a second, dummy `uv_run` afterwards to make my on_close callbacks being called. To add complexity to that, one of the callbacks that is executed when a client disconnects is to send a request through another socket.

I found no way to keep this socket alive if it wouldn't be for manual refcounting on my side.

Core issue is that you can only ref or unref a handle, you can't ref it twice. So if something is scheduled for unrefing you can't extend its lifetime beforehand.

**Comment by bnoordhuis** [comment]
@mitsuhiko An on_close callback not getting called is a bug, please file a bug report (with a test case) for that.

Not being able to ref a handle twice is a feature, not a bug. Reference counting is too easy to mess up and too bloody hard to debug, hence the idempotent approach.
