### ISSUE TITLE
Help needed with windows port of mdns addon

### ISSUE THREAD

**Issue by agnat** [joyent/libuv#349]
I've been looking into porting my [bonjour addon](https://github.com/agnat/node_mdns) to windows. Unfortunately I cannot find a way to tap into libuv's IO facilities.

The bonjour API returns a winsock2 socket at some point. I'd like to add that socket to the event loop and receive notifications whenever the socket becomes readable. Reading is done by the bonjour API.

Looking at the [request type dispatch](https://github.com/joyent/libuv/blob/master/src/win/req.c#L98) it's obvious that I can not introduce my own request type. I also haven't found a call path that always performs a zero-size read (I think that would do the trick).

A simple and quick solution could be to make `alloc_cb` optional. If it is `NULL` libuv always performs a zero-size read and the actual reading is done somewhere else (in `read_cb`).

What do you think? Could someone with libuv knowledge help me to get this (or something along the lines) landed?

**Comment by bnoordhuis** [comment]
This seems related to #316 but @piscisaureus knows the uv-win internals better than I do.

**Comment by piscisaureus** [comment]
Yes, this issue is tracked #316. I am working on a patch. Closing this issue for being duplicate.

**Comment by agnat** [comment]
Awesome, thanks.
