### ISSUE TITLE
Inspect which handles are holding the loop open

### ISSUE THREAD

**Issue by tjfontaine** [joyent/libuv#350]
Useful during troubleshooting, it would be helpful to see the list of handles keeping the loop open (missed sockets, timers, etc).

This likely depends on #347

I don't see it as being necessary for normal operation, but could be enabled in a debug build

**Comment by bnoordhuis** [comment]
I did most of the work for that in bnoordhuis/libuv@6a3f29fb but it still needs to be implemented on the uv-win side of things.
