### ISSUE TITLE
Windows: fix lstat

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#355]
Currently does the same as stat.

Since windows lacks a definition for S_IFLNK we probably need to add libuv constants for this (like UV_S_IFLNK). Also, we may need to define uv_stat_t. On unix these could be redefined as their native counterparts. @bnoordhuis Agree?

The implementation can be mostly the same as fs__stat except that the file should be opened with the FILE_FLAG_OPEN_REPARSE_POINT flag specified. Then in the returned struct we should check if it is a reparse point, and if it is we do this:

Use GetFileInformationByHandleEx to figure out if the reparse tag is a symlink or not.
- If it is a symlink, set the UV_S_IFLNK flag
- It it is not a symlink, use normal fs__stat to traverse the reparse point.

**Comment by bnoordhuis** [comment]
> @bnoordhuis Agree?

Yes.

**Comment by piscisaureus** [comment]
I think it is more conveniente to use NtQueryInformationFile with FileAllInformation. This is also what GetFileInformationByHandle does. NtQueryInformationFile will just tell us what the reparse tag is.

GetFileInformationByHandle also calls ZwQueryVolumeInformationFile, which I think we might as well just skip.

**Comment by mistaecko** [comment]
Should this be closed? `fs.lstatSync(junction).isSymbolicLink()` returns `true` on node v0.10 on Win8!
