### ISSUE TITLE
unbuffered stdin/stdout to support -i in Windows

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#358]
In order to support an --interactive flag in Windows stdin/stdout need to be unbuffered. Despite other fixes that have come through in bringing the -i flag to reality, the buffered input in Windows is killer.

The relevent part of Python's code is this:

```
if (Py_InteractiveFlag) {
#ifdef MS_WINDOWS
    /* Doesn't have to have line-buffered -- use unbuffered */
    /* Any set[v]buf(stdin, ...) screws up Tkinter :-( */
    setvbuf(stdout, (char *)NULL, _IONBF, BUFSIZ);
#else /* !MS_WINDOWS */
#ifdef HAVE_SETVBUF
    setvbuf(stdin,  (char *)NULL, _IOLBF, BUFSIZ);
    setvbuf(stdout, (char *)NULL, _IOLBF, BUFSIZ);
#endif /* HAVE_SETVBUF */
#endif /* !MS_WINDOWS */
    /* Leave stderr alone - it should be unbuffered anyway. */
}
```

And a discussion here on the specifics of setvbuf's uses in Windows http://sourceforge.net/mailarchive/forum.php?thread_name=AANLkTikt_f2gZBNeRk9D%3DQ%3DHe5Ce5GhOhbFvfwBukG7-%40mail.gmail.com&forum_name=mingw-users. The conclusion of that thread is

> It shows that enabling and disabling buffering with setvbuf works
> correctly both in the console and with a pty, i.e. a pipe. It also
> confirms that on a pipe, both stdout and stderr are buffered by
> deault. Finally, with a console, both stdout and stderr are unbuffered
> by default.

An issue with Windows seems to stem from the fact that line buffering doesn't exist and it's simply full-buffering.

> _IOLBF "For some systems, this provides line buffering. However, for Win32, the behavior is the same as _IOFBF - Full Buffering."

http://msdn.microsoft.com/en-us/library/86cebhfs(v=vs.80).aspx

**Comment by ghost** [comment]
Related Node issue https://github.com/joyent/node/issues/2754

https://github.com/joyent/node/commit/feaa8a41c7533c254923ea7333457234ed44f8f9

@TooTallNate

**Comment by piscisaureus** [comment]
In libuv, stdin is always unbuffered, except if it is a tty. If it is a tty it can be made unbuffered with uv_tty_set_mode.
