### ISSUE TITLE
About new thread in Libuv (uv_loop_new)

### ISSUE THREAD

**Issue by LostAbaddon** [joyent/libuv#366]
I've tried to create a new loop in Node.JS to do some listening stuff, such as listen the dbus message or others.
But when I tried to create a new loop, lots of error occurs.
When I use uv_loop_new, there's a segmentation fault error.
And when I create a thread, like the test/test-async.c does, it told me that symbol lookup error.
And then I use pthread to create threat by my own, the segmentation fault error occurs again.
So, how could I create a private event loop or just only a thread in Node.JS by libuv?

**Comment by bnoordhuis** [comment]
You should post your code and Makefile, there's no telling now what goes wrong. Have a look at `test/test-thread.c` to find out how to create threads and event loops. Make sure to compile _and_ link with `-pthread`.

**Comment by saghul** [comment]
No follow up, closing.
