### ISSUE TITLE
Inconsistency when calling uv_run with loop refcount 0

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#372]
I noticed a slight inconsistency in how uv_run behaves in Unix vs Windows. In unix it's now implemented as a do-while and does one iteration of the loop, whereas in Windows it's a while-do.

This means that it I create an idle handle, unref the loop and call uv_run, the callback will be called on Unix systems, and when you try to close handle it will crash because refcount goes bellow 0. On Windows, uv_run will return immediately because if checks if the refcount is > 0 first.

At a first sight it feels like a 2 line change here https://github.com/joyent/libuv/blob/master/src/unix/core.c#L178 but I may be overlooking something.

Thanks,

**Comment by bnoordhuis** [comment]
Yes, this will be fixed once the refcount branch gets merged into master.

**Comment by saghul** [comment]
Great! :-)
