### ISSUE TITLE
Load path for DLL dependencies

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#377]
In node, when people require a .node file that relies on external DLLs the search path for those DLLs is... surprising.
What we could do is add the path that contains the .node file to the DLL search path. I wonder how that works on unix though.

See also the discussion in #node.js with @pkrumins here: http://piscisaureus.no.de/node.js/latest#18:37:51.036

Thoughts? @isaacs @bnoordhuis @tootallnate

**Comment by pkrumins** [comment]
Seeing one major problem with that approach actually.

When you write your module, you dont have build\Release. It gets created only after you do `node-gyp build`, and your module gets put in there. So how do you ship the necessary dll's with your module? You can create build\Release yourself and put the dll's in there, but it doesn't look nice.

I propose this. Let's have a `gyp` directory that would be specific to modules built with gyp!

This way we can have `gyp\dll` dir for dlls that will ship with your module, have `gyp\lib` for static libs, in case you want to compile statically, and have `gyp\include` for include files.

I have this structure in my node-png-sync project (https://github.com/pkrumins/node-png-sync), it works, it's clean and I love it!

**Comment by TooTallNate** [comment]
I think the principle of least surprise (and the least amount of work at runtime) would be to have node search for DLLs in the directory of the `.node` file. Making up any new conventions is a little bit extreme IMO.

We could add a default target to `addon.gypi` that copies and of the files specified in a variable we decide on (similar to `library_files` in node.gyp), and those files would be copied into `build/Release` at build-time.

``` js
{
  'variables': {
    'build_files': [
      'gyp/dll/libpng12.dll'
    ]
  }
}
```

I can do the patch to `addon.gypi` if you guys like this approach.

**Comment by pkrumins** [comment]
Perhaps not `build_files` but `dll_files`? So if I get it right, the files specified in `dll_files` would get copied to the `build\Release` dir?

**Comment by TooTallNate** [comment]
@pkrumins Correct, they'd got copied during `node-gyp build`. I called it `build_files` to try and be generic, since the technique could be useful for other kinds of files.

**Comment by pkrumins** [comment]
That works really well!

**Comment by isaacs** [comment]
@TooTallNate So, anything in build_files gets copied directly into build/Release/?

**Comment by TooTallNate** [comment]
@isaacs Not currently, but ya that's the idea.

It should be possible by adding a target to the `addon.gypi` file that reads that variable and copies them over (might need a tiny Python script if gyp can't do it on its own).

**Comment by isaacs** [comment]
@TooTallNate that sounds like a pretty nice and simple API for doing this, then.

**Comment by TooTallNate** [comment]
Cool, I've opened an issue for the node part of it (placing the necessary files in the build dir).

@piscisaureus are you able to do the libuv part? Is it gonna be a change to `uv_dlopen`?

**Comment by piscisaureus** [comment]
@TooTallNate I can do the libuv/node bits, but I have to touch base with @bnoordhuis about how that would work on unix, whether it would be possible or even necessary etc.

So @bnoordhuis: ping

**Comment by piscisaureus** [comment]
Changed it on windows (master only), you can now put dll dependencies in the folder that holds the .node file. On unix this is not possible though.
