### ISSUE TITLE
Linux Process Title

### ISSUE THREAD

**Issue by chjj** [joyent/libuv#380]
Would there be any benefit to using `prctl(2)` to change a process' title in linux kernels later than 2.6.9? The way it's hacked in now, the title change works properly when you check `/proc/$PID/cmdline` in the proc filesystem as well as, `ps ax | grep my_title`, but it doesn't change the title otherwise: e.g. `ps -e | grep my_title` or `/proc/$PID/comm`. Would `/comm` appear to change if `prctl(2)` were used instead of hacking `argv[0]` by hand?

**Comment by bnoordhuis** [comment]
We used to do that but the downside to prctl() is that it only allows names up to 16 bytes, hence the argv hackery.

**Comment by chjj** [comment]
I see. Wish there were a better way of doing this. Oh well.
