### ISSUE TITLE
core dump in uv__pipe_accept

### ISSUE THREAD

**Issue by davepacheco** [joyent/libuv#386]
While running a Node program, I saw this:

```
Assertion failed: 0 && "EAGAIN on uv__accept(pipefd)", file src/unix/pipe.c, line 258
```

In src/unix/pipe.c, in uv__pipe_accept, we have:

```
255   sockfd = uv__accept(pipe->fd, (struct sockaddr *)&saddr, sizeof saddr);
256   if (sockfd == -1) {
257     if (errno == EAGAIN || errno == EWOULDBLOCK) {
258       assert(0 && "EAGAIN on uv__accept(pipefd)");
```

Unfortunately, uv__accept just calls accept(3) and does **not** handle EAGAIN or EWOULDBLOCK.  But both the SmartOS and MacOS man pages document that EWOULDBLOCK is a valid case, and the other primary caller of this function, uv__server_io, handles it fine:

```
176     fd = uv__accept(stream->fd, (struct sockaddr*)&addr, sizeof addr);
177
178     if (fd < 0) {
179       if (errno == EAGAIN) {
180         /* No problem. */
181         return;
```

It looks like uv__pipe_accept should have a similar check.

I observed this on Node v0.6.12, but I've verified that the relevant libuv source is the same in both Node master and libuv master.

**Comment by bnoordhuis** [comment]
Thanks for the bug report, Dave. It's fixed in 1fa1c51.

**Comment by davepacheco** [comment]
Thanks! Is there any chance this might go back into a node 0.6 release?

**Comment by bnoordhuis** [comment]
Sure. I've back-ported it in 21bee8c so it'll be part of node v0.6.16.

**Comment by davepacheco** [comment]
Great! Thanks.
