### ISSUE TITLE
test wanted: uv_ref count tests for loop handles

### ISSUE THREAD

**Issue by ry** [joyent/libuv#39]
similar to this: https://github.com/joyent/libuv/blob/c41b7143c78b3215972799d3e77b4ae65394d065/test/test-loop-handles.c#L351-359

**Comment by ry** [comment]
somewhat addressed in 1352c72e35b49a32964f694e535abccbd31b847b. Need more!

**Comment by bnoordhuis** [comment]
Closing, we have lots of refcount tests now.
