### ISSUE TITLE
uv_strerror should tell err.code in case of unknown error

### ISSUE THREAD

**Issue by japj** [joyent/libuv#394]
There is some generic error to string mapping at:

https://github.com/joyent/libuv/blob/master/src/uv-common.c#L117

However this code does NOT tell the err.code number in case of an unknown code, making it impossible to analyse issues.
(and yes, I'm going to digg deeper why exactly I ran into this)

**Comment by bnoordhuis** [comment]
That requires an API change: either the caller somehow frees the memory or the contract for `uv_strerror()` gets changed to _"the return value is only valid until the next call to uv_strerror()"_ so we can store the string in a loop-local buffer (with the caveat that functions like `uv_dlopen()` are not attached to a loop).

The second option seems like it's most convenient for libuv users. Both cases require users to update their code but the second option doesn't allow bugs to sneak in. The function prototype of `uv_strerror()` changes; if users don't update their code, it simply fails to compile.

@piscisaureus: Thoughts?

**Comment by piscisaureus** [comment]
@japj err.code does not contain any interesting information. We probably want to print the value of err._sys_errno somehow.

**Comment by piscisaureus** [comment]
@bnoordhuis Why not make it a thread local?

**Comment by bnoordhuis** [comment]
@piscisaureus: That would cause spurious memory leaks when tracing with valgrind. I suppose it's not entirely out of the question.

**Comment by japj** [comment]
@bnoordhuis @piscisaureus I was just testing node symlink support and I get:

<pre>
> var fs = require('fs');
> fs.mkdirSync('dir');
> fs.symlinkSync('dir', 'symDir', 'dir');
Error: UNKNOWN, unknown error 'C:\github\node\symDir'
    at Object.fs.symlinkSync (fs.js:561:18)
    at repl:1:4
    at REPLServer.self.eval (repl.js:111:21)
    at rli.on.e (repl.js:260:20)
    at REPLServer.self.eval (repl.js:118:5)
    at Interface.<anonymous> (repl.js:250:12)
    at Interface.EventEmitter.emit (events.js:88:17)
    at Interface._onLine (readline.js:183:10)
    at Interface._line (readline.js:502:8)
    at Interface._ttyWrite (readline.js:720:14)
</pre>


So I think there is still some windows error mapping missing, but I can't tell which error from here (although I expect it to be some kind of permission error, since I am running as a non administrator).

**Comment by saghul** [comment]
Hi @japj in Windows (>= Vista IIRC) you need to run with elevated privileges. This patch will map the "privilege not held" error to EPERM: https://github.com/joyent/libuv/pull/459 you may want to check it out.

**Comment by saghul** [comment]
This no longer really applies since we use errnos directly now. Closing.
