### ISSUE TITLE
ERROR_PROC_NOT_FOUND missing in uv error mapping (windows)

### ISSUE THREAD

**Issue by japj** [joyent/libuv#395]
GetProcAddress (used by uv_dlsym) on windows can return ERROR_PROC_NOT_FOUND in case the function is not found.

ERROR_PROC_NOT_FOUND is missing in the errorcode mapping resulting in an "unknown error" in case this occurs.

**Comment by bnoordhuis** [comment]
@piscisaureus: uv-unix returns UV_EINVAL when the symbol cannot be resolved. You'd be throwing some potentially useful information away (the actual error code) but I suppose uv-win could do the same.

**Comment by piscisaureus** [comment]
@bnoordhuis 
- Returning UV_EINVAL != UV_EUNKNOWN. Apparently GetProcAddress() returns something that maps to UV_EINVAL.
- You're supposed to call uv_dlerror for more info, right?

**Comment by japj** [comment]
node.cc apparently "expects" UV_ENOENT as a failure code at https://github.com/joyent/node/blob/master/src/node.cc#L1764

**Comment by piscisaureus** [comment]
@bnoordhuis Yeah what about we change unix to return UV_ENOENT?

**Comment by japj** [comment]
hmm.. there is a mapping at https://github.com/joyent/libuv/blob/master/include/uv.h#L108 that says:

XX( 34, ENOENT, "no such file or directory")

Which then also should read, "no such file, directory or function" ;)

**Comment by bnoordhuis** [comment]
> Yeah what about we change unix to return UV_ENOENT?

Sure, that works. As discussed on IRC, I've reworked the API. Here is the work so far: https://github.com/bnoordhuis/libuv/compare/dlopen
