### ISSUE TITLE
class structure for uv_handle_t like in ev_watcher

### ISSUE THREAD

**Issue by ry** [joyent/libuv#4]
oio_tcp_handle
  oio_npipe_handle
  oio_file_handle
  oio_tty_handle
  oio_timer_handle ?

**Comment by piscisaureus** [comment]
yes

**Comment by piscisaureus** [comment]
- No timer handle
- The drawback of having multiple handle classes is that you need multiple oio_read and oio_write implementations _or_ the user needs to cast every time read / write is called.

**Comment by ry** [comment]
casting isn't a big deal
