### ISSUE TITLE
Assertion failed: handle->write_queue_size >= req->queued_bytes, file src/win/tcp.c, line 1021

### ISSUE THREAD

**Issue by mattn** [joyent/libuv#409]
This is not an issue. I have a question. Please teach me how to fix this error.

Currently, I'm writing https://github.com/mattn/mruby-uv that this is worked on https://github.com/mruby/mruby .
And example/server.rb is working fine with single request  like following

```
ab -n 1000 http://localhost:8888/
```

But , when send multiple request, program is stoped forcely with following assertion.

```
ab -c 10 -n 100 http://localhost:8888/
```

```
Assertion failed: handle->write_queue_size >= req->queued_bytes, file src/win/tcp.c, line 1021
```

Please teach me how to fix.

**Comment by mattn** [comment]
Ah, sorry I forgot to link another staff.

https://github.com/mruby/mruby
https://github.com/mattn/mruby-uv
https://github.com/mattn/mruby-http

mruby-http have example/server.rb

**Comment by piscisaureus** [comment]
I don't think that can ever happen if you use libuv properly.
- You should allocate a new uv_write_t for every write to a handle. Do no reuse, free, move, or clobber it's memory until the write callback is made.
- Ditto for the uv_tcp_t handle; do not reuse, free, move, or clobber it's memory until the close callback is made.

**Comment by mattn** [comment]
Thanks.
