### ISSUE TITLE
How good is to free a handle without using uv_close()?

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#410]
Hi, I wonder if the following code could leak memory, file descriptors or whatever:

<pre>
uv_udp_t *my_uv_handle = (uv_udp_t *)malloc(sizeof((uv_udp_t ));

// This bind address will fail since my host does not have the 1.2.3.4 IP.
struct sockaddr_in bind_addr = uv_ip4_addr("1.2.3.4", 1234);

uv_udp_init(uv_default_loop(), my_uv_handle);

// So this returns -1:
if (uv_udp_bind(my_uv_handle, bind_addr, 0)) {
  uv_unref(uv_default_loop());
  free(my_uv_handle);
}
</pre>

I do know that it's recommended to use uv_close() rather than uv_unref(), and call free() on the close callback. But for that to work I must ensure that uv_run() is called later, and this could be not the case in my application (sin the the UDP socket failed to be set due to wrong bind IP provided by the high user).

So my question is: is it safe the above code? or would it leak something?

Thanks a lot.

**Comment by bnoordhuis** [comment]
> So my question is: is it safe the above code? or would it leak something?

It's not safe and it might leak. Always call `uv_close()` on handles you're done with.

> I must ensure that uv_run() is called later, and this could be not the case in my application

Be sure to call `uv_run()` at least once, it gives the close callbacks a chance to run. It won't block if there are no active handles or requests.

Alternatively, you can just call `exit()`, of course. :-)

**Comment by ibc** [comment]
Thanks for the explanation. However that's the problem, I don't know if the user has created a periodic timer, so if I run uv_run just to ensure that all the close callbacks are executed, I could be blocked there.

Well, hope a new method uv_stop_loop() will be available soon ;)

**Comment by bnoordhuis** [comment]
We'll probably add a `uv_run_nowait()` sometime soon.

**Comment by ibc** [comment]
That would be very interesting indeed.
