### ISSUE TITLE
uv_send_udp() does not fail if datagram size is too large

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#411]
Linux. Sending a very long data with uv_send_udp() does not fail, neither the callback funtion is called with status -1.

I've made network traces and, of course, the data leaves the machine truncated to a minor size, but UV reports no error at all.

Is this the expected behavior?

**Comment by saghul** [comment]
Hi @ibc,

I just tested that and I do see an error. When I call uv_udp_send with a string containing 65536 "X"s I get status -1 in the send callback and the last_error is set to UV_EMSGSIZE. I tried bigger values with same result (both on OSX and Linux).

There is already a test for this in libuv itself: https://github.com/joyent/libuv/blob/master/test/test-udp-dgram-too-big.c, does it fail for you?

**Comment by ibc** [comment]
I've done further testing:
- If a set a buffer longer than 65536 bytes (the max size of an UDP datagram) then indeed the send callback is called with status 21 (EMSGSIZE).
- But if I set a buffer of, i.e, 50000 bytes and send it to internet, then I clearly see doing a ngrep capture that just the first 1472 bytes are sent, the rest are discarded. And the send callback is called with status 0 (OK).

Also note that my host is not behind NAT, it has a public IP.

**Comment by bnoordhuis** [comment]
Unices almost never report EMSGSIZE errors unless:

a) you try to send a datagram > 64K, or
b) a downstream hop sends a ICMP fragmentation needed reply (which you won't see until the next socket operation)

You can verify it with `strace -e sendmsg` - it almost never reports errors.

**Comment by ibc** [comment]
It's clear, thanks a lot.

**Comment by bnoordhuis** [comment]
My pleasure. :-)
