### ISSUE TITLE
uv_bind_udp() can be called several times with same bind ip:port !

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#412]
(Linux)

I've tested that I can call uv_bind_udp() more than once by passing different uv_udp_t handles but the very same bind IP:port.

I expected EADDRINUSE error but it just works, and I can send datagrams from both handles (a network trace shows me that, indeed, datagrams come from the same source IP:port, those given as bind_addr parameter to uv_bind_udp() function).

So, is this the expected behavior? It seems strange for me. If I send data to that bind IP:port, which handle will be invocked for its data received callback? randomly? the first one? the last one?

**Comment by bnoordhuis** [comment]
It's a feature, libuv sets the SO_REUSEADDR flag on both sockets. Both are able to send but only the second socket can receive datagrams.
