### ISSUE TITLE
uv_udp_recv_cb() invoked twice (second time with nread=0)

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#414]
Hi, I've realized that when a UDP datagram arrives uv_udp_recv_cb() is executed twice, and the second time with nread=0. From the doc:

<pre>
 *  nread   Number of bytes that have been received.
 *          0 if there is no more data to read. You may
 *          discard or repurpose the read buffer.
 *          -1 if a transmission error was detected.
</pre>

So, what's the purpose of UV calling the callback with nread=0?
Why do I need to know that there is no more data to read? Just don't invoke the callback again. Am I wrong?

Is it wrong if I just free the buffer after reading the data (nread>0)?

Thanks a lot.

**Comment by bnoordhuis** [comment]
Yes, it's unnecessary. I'll remove it.

**Comment by piscisaureus** [comment]
That said, when libuv calls the read/recv callback with nread==0 it wants to give you back a buffer it requested through the alloc callback. The buffer returned by the alloc callback is "owned" by libuv.

**Comment by bnoordhuis** [comment]
That's true but it's an artifact of how we read datagrams on UNIX right now:
1. alloc buffer
2. try to read a datagram
3. call recv_cb with nread==0 if no datagram available

There's usually only a single datagram to read but uv-unix executes the steps above twice anyway to ensure that the queue is drained. That second round should be relatively easy to optimize away.

**Comment by piscisaureus** [comment]
Yep, it should be fixed. I was just explaining why nread==0 happens, and how users should deal with it.

**Comment by ibc** [comment]
Yes, I understand that recv_cb must be used regardless the datagram is empty (which is valid in UDP protocol). The issue I reported is not that but:
1. I receive an UDP (with size>0).
2. alloc_cb is called, I allocate a buffer.
3. recv_cb is called, I read nread byte and dissallocate the buffer (I'm done).
4. alloc_cb is called again !! (so I must allocate again a buffer).
5. recv_cb is called, I see nread==0 so I just dissallocate the buffer (again).

Steps 4 and 5 are useless and a waste of resources allocating/dissallocating. I've verified with tcpdump that I only receive a _single_ UDP daragram.

NOTE: In case somebody sends me an empty UDP, then steps 1,2,3 above are enough to deal with it. So I insist that steps 4 and 5 make no sense but currently they occur.

**Comment by bnoordhuis** [comment]
I'm closing this as WONTFIX. I've experimented with a number of approaches on eliminating the extra alloc/read cycle - recvmmsg(), ioctl(SIOCINQ), doing one read per tick - and they're all slower by a considerable margin.

recvmmsg() performance was particularly disappointing - it's supposed to be faster but instead it was ~30% slower than a regular recvmsg().

**Comment by ibc** [comment]
Hi, I don't want to reopen this issue since it is clear for me that the current design is the best one. But:
- It would be nice if the documentation said something about the second and empty datagram (does it just happen in *nix?).
- It would be even more nicer to document this given that, during the second uv_udp_recv_cb, the `addr` argument is NULL (as user I would expect that `addr` is always a valid `sockaddr*`, if not, please document it).

I could send a PR if you wish (please confirm me whether the same behavior also applies to Windows or not).

**Comment by saghul** [comment]
Since empty datagrams are allowed AFAIK, we sould document that when nread is 0, addr **could** be NULL.

**Comment by ibc** [comment]
Exaclty, a zero length datagram is valid.
If addr may be NULL then the API should tell the user about it.
