### ISSUE TITLE
 uv_timer_set_repeat() is ignored if timer is stopped

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#417]
(Linux)

I've realized that calling uv_timer_set_repeat() for a timer which has previously stopped with uv_timer_stop()  has no effect at all. Is this the expected behavior?

IMHO this avoids a cool feature: changing the interval in the timer callback by using:

```
uv_timer_stop();
uv_timer_set_repeat(new_interval);
uv_timer_start(same_delay, new_interval);
```

**Comment by saghul** [comment]
What about doing this? (assume the timer is repeating already)

```
uv_timer_set_repeat(timer, new_interval);
uv_timer_again(timer);
```

**Comment by ibc** [comment]
Interesting, yeah, it allows changing the interval in the callback without having to wait the previous interval. However it's still a bit ugly. Imagine the high user (using a UV wrapper) wants to pause the timer, set a new interval later, and then run it again:

```
// Pause the timer:
uv_timer_stop(timer);

// [...] Later set a different interval:
uv_timer_set_repeat(timer, new_interval);
uv_timer_again(timer);

// [...] Later unpause the timer:
uv_timer_start(timer, same_delay, new_interval);
```

This will take no effect.

**Comment by saghul** [comment]
If you 'pause' a timer and want to run it again later you need to call `uv_timer_start`, which takes the repeat argument, so you'd do:

```
//Pause the timer:
uv_timer_stop(timer);

//[...] later set a different interval and start it
uv_timer_start(timer, delay, new_interval);
```

Doesnt look ugly to me at all :-)

**Comment by ibc** [comment]
Ok, finally playing with all the available API funtions I've built a easy high-level API. Thanks :)
