### ISSUE TITLE
uv_async_send() could return error if UV is not running

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#419]
(Linux)

If I'm not wrong, uv_async_send() returns 0 even if UV is not running. In this case it becomes obviously useless since UV is not listening for uv_async notifications.

Maybe uv_async_send() should return error if the loop is not running?

**Comment by saghul** [comment]
uv_async_send is meant to be called from another thread, so there is no reliable way to check if libuv is running. No single function in libuv checks for this and I believe it's The Right Thing (TM). If the user wants to, uv_loop_alive() can be used to check if the loop is running. It's not thread-safe though.
