### ISSUE TITLE
Is it safe to run uv_run(uv_default_loop()) from a different thread?

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#423]
Hi, sorry for asking a question here (any maillist or similar for UV related questions?).

If I call uv_run(uv_default_loop()) and it correctly terminates (no more active handles), is it safe to call uv_run(uv_default_loop()) from a different OS thread?

**Comment by bnoordhuis** [comment]
> Hi, sorry for asking a question here (any maillist or similar for UV related questions?).

We're in #libuv on freenode.org

> If I call uv_run(uv_default_loop()) and it correctly terminates (no more active handles), is it safe to call uv_run(uv_default_loop()) from a different OS thread?

Yes, that's safe.

**Comment by piscisaureus** [comment]
I'd say you can consider it safe for the time moment. However I can think of extreme edge cases where this may not be true.

**Comment by bnoordhuis** [comment]
Are you thinking of memory reordering and such? That can't be helped, it's up to the caller to insert a memory barrier. gcc has a built-in `__sync_synchronize()` intrinsic, MSVC undoubtedly has something similar.

**Comment by piscisaureus** [comment]
No I am thinking about edge cases where we use CancelIo, which cancels all IO _initiated by a particular thread_ on windows. Also, we might use APCs in the future to speed up shared sockets, and APC callbacks are also thread-bound.
