### ISSUE TITLE
[unix] uv_poll_start may call uv__io_set on an active handle

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#424]
According to the documentation, if one wants to change the events being monitored by a uv_poll_t handle he should call uv_poll_start again, with the new events (https://github.com/joyent/libuv/blob/master/include/uv.h#L999).

The libev documentation, however, says that ev_X_set should not be called if the handle is active (http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#GENERIC_WATCHER_FUNCTIONS).

I was experiencing some 100% CPU usage when changing the event mask and stopping and restarting the poll handle fixed it, so I think uv_poll_start should stop the handle if it's active before calling uv__io_set.

Thoughts, @bnoordhuis ?

**Comment by saghul** [comment]
After testing with latest master CPU doesn't spike to 100% but changes to event mask have no apparent effect unless the poll handle is stopped first.

**Comment by bnoordhuis** [comment]
Fixed in 2e3e658.
