### ISSUE TITLE
Inconsistent behavior of uv_timer_start

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#425]
The behavior of uv_timer_start looks a bit inconsistent:
- On Unix if the timer is already active it returns -1 but doesn't set the errno, what about setting UV_EALREADY?
- On Windows (if my reading is correct) it doesn't seem to care about the timer already being active

IMHO the correct behavior would be giving an error if one tries to start an already active timer and setting a proper errno in such case. The only one that I thought it matches is EALREADY, but there might be a better one.

**Comment by bnoordhuis** [comment]
I kind of hate EALREADY but the UNIX convention of returning EINVAL for everything is even worse. :-)

@piscisaureus What do you think? I like what uv-win does (rearm the timer with the new settings, +1 ease of use) but it's inconsistent with the other uv_*_start() functions.

**Comment by piscisaureus** [comment]
Maybe we should just allow it. If the timer was already active, stop it first.

**Comment by bnoordhuis** [comment]
Okay, done in 028fef8.

**Comment by saghul** [comment]
Great, thanks!
