### ISSUE TITLE
`pipe_bind_error_addrinuse` failed: exit code 6 on Travis CI

### ISSUE THREAD

**Issue by japj** [joyent/libuv#426]
Apparently, Travis CI is setup for libuv but the make test has not passed since a very long time?
(see http://travis-ci.org/#!/joyent/libuv/builds )

http://travis-ci.org/#!/joyent/libuv/builds/1406925/L133

131=============================================================
132[%   0|+  41|-   0]: pipe_bind_error_addrinuse
133`pipe_bind_error_addrinuse` failed: exit code 6
134Output from process `pipe_bind_error_addrinuse`:
135Assertion failed in test/test-pipe-bind-error.c on line 56: r == -1
136=============================================================
137[% 100|+ 138|-   1]: Done.
138make: **\* [test] Error 1

**Comment by Sannis** [comment]
This looks like Travis denied to create test pipe socket `/tmp/uv-test-sock`.

**Comment by bnoordhuis** [comment]
Fixed in 3604b8d.

**Comment by bnoordhuis** [comment]
It wasn't related to Travis, by the way - that test has been failing since forever.

**Comment by japj** [comment]
nice, now atleast you will know when someone actually breaks the build again ;)

**Comment by Sannis** [comment]
FYI, Travis also beta support pull requests tests.
