### ISSUE TITLE
Remove "return 0" in uv_run_once()

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#427]
(Linux)

Current `uv_run_once()` looks like:

<pre>
int uv_run_once(uv_loop_t* loop) {
  uv__run(loop);
  return 0;
}
</pre>

The problem is that it always returns 0 so I cannot make my own loop. For example I would like to to this:

<pre>
while ( !do_stop && uv_run_once(loop) );
</pre>

So if my code sets `do_stop=1` the loop will exit (later I will clean it, no problem). For this to work, I just need to remove the "return 0" in the `run_uv_once()`:

<pre>
int uv_run_once(uv_loop_t* loop) {
  return  uv__run(loop);
}
</pre>

I don't think this would break nothing. Is it possible to do it?

**Comment by bnoordhuis** [comment]
@piscisaureus Can you review c9b590f?

**Comment by bnoordhuis** [comment]
Fixed in 7c8313b.

**Comment by ibc** [comment]
Thanks a lot.
