### ISSUE TITLE
Use sockaddr_storage  instead of sockaddr (for IPv6)

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#430]
`int uv_udp_getsockname(uv_udp_t* handle, struct sockaddr* name, int* namelen);`

`struct sockaddr` cannot store a IPv6 unless you do some annoying cast to `sockaddr_in6` or `sockaddr_storage`. So, why not to change uv_udp_getsockname() and make it to use `sockaddr_storage`?

**Comment by bnoordhuis** [comment]
How does that help? In the end you still need to cast it to sockaddr_in or sockaddr_in6. Just to be clear, you're not supposed to pass in a pointer to a literal struct sockaddr.

**Comment by ibc** [comment]
Right, but making it `sockaddr_storage` instead of `sockaddr` could avoid some coding errors. For example, in the UDP recv_cb I do a memcpy of the `addr` (struct sockaddr) for later usage. I would like to do such a memcpy without having to deal with ipv4 or ipv6 at this moment. If I do:

<pre>
memcpy(last_peer_addr, addr, sizeof(struct sockaddr));
</pre>


it will fail for IPv6 addresses (truncated). If I would see that the recv_cb() passes me a `sockaddr_storage` then it would be more obvious for me to do:

<pre>
memcpy(last_peer_addr, addr, sizeof(struct sockaddr_storage));
</pre>


And the problem would not happen. I do know that later I will have to cast to `sockaddr_in` or `sockaddr_in6`, but at least it would be cleaner until that moment and, honestly, I see no advantage in using the old `sockaddr` instead that `sockaddr_storage`.
