### ISSUE TITLE
uv_udp_recv_stop() does not discard received datagrams

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#431]
(Linux)

Pseudo code:

<pre>
# Create a UDP socket and bind:
uv_udp_init(loop, handle);
uv_udp_bind(handle, uv_ip4_addr(IP,PORT), 0);

# Start receiving:
uv_udp_recv_start(handle, allow_cb, recv_cb);

# Stop receiving:
uv_udp_recv_stop(handle);

# Datagram "HELLO" is received now but recv_cb() is not called, ok.

# After 4 seconds (uv timer) enable receiving again:
timer(4000) {
  uv_udp_recv_start(handle, allow_cb, recv_cb);
}

# At this point recv_cb() is called with datagram "HELLO" received 4 seconds ago!
</pre>

IMHO this is unexpected. It seems that `uv_udp_recv_stop()` just avoids the recv_cb() to be called, but the received datagram remains and recv_cb() would be called with such a theorically discarded datagram if `uv_udp_recv_start()` is called again.

**Comment by bnoordhuis** [comment]
That's a feature of your kernel, not a bug in libuv. `uv_udp_recv_stop()` stops watching for pending data, it doesn't close the socket. Incoming data is still queued by the kernel.

**Comment by ibc** [comment]
Ok, I was thinking that could be the reason. Then I will implement a different approach for my high-leven "udp.stop_receiving()" function: Instead of using `uv_udp_recv_stop()` I will set a boolean `do_receive` and, when it's set to 0, I will ignore UD recv callbacks.

Thanks.
