### ISSUE TITLE
UV loop exits while there is a connected uv_tcp_t

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#432]
I'm starting with UV TCP and have realized that, in case of starting a UV loop with a single TCP handler, after the handler is connected to a remote server (`uv_tcp_connect()`) the loop exits. Note that I don't set `uv_read_start()`.

Is it the expected behavior? Should I consider that a `uv_tcp_t` handler in connected state is not considered an "active" handler by UV? Reading `uv_is_active()` documentation does not help too much in this case:

<pre>
/*
 * Returns 1 if the prepare/check/idle/timer handle has been started, 0
 * otherwise. For other handle types this always returns 1.
 */
UV_EXTERN int uv_is_active(const uv_handle_t* handle);
</pre>

**Comment by ibc** [comment]
In the other side it makes really sense that, if there are no more handles, UV to exit in the above scenario since there is no way to send data in the connected handle.

**Comment by bnoordhuis** [comment]
A stream (pipe, tcp, etc.) doesn't ref the event loop if it's not reading or writing, that's why `uv_run()` returns. So yes, this is the expected behavior. :-)

**Comment by ibc** [comment]
Thanks for the explanation. It's clear (and yes, makes sense) :)
