### ISSUE TITLE
Restarting UV loop after uv__finish_close() was interrupted

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#434]
Hi, I've an issue in my Ruby binding of libuv (https://github.com/ibc/AsyncEngine). The problem is very specific:
- UV is running with some TCP connections writing data all the time to remote servers. For every write operation there is a `uv_write_cb()` that will invoke Ruby code.
- At some point (i.e. via UV timer) I perform a `uv_close` over all the TCP handles and thus, UV runs `uv__finish_close` for every TCP handle which internally iterates its list of write reqs and would call to `uv_write_cb()` with error status (EINTR).
- Now, **during** such `uv__finish_close` a Ruby exception occurs (or a not ignored signal arrives to Ruby land) so Ruby performs a `longjmp`.

The problem at this point is that `longjmp` occured while `uv__finish_close` (for any TCP handle) was executing the write req callbacks, so it was interrupted. So when calling to `uv_run()` again the function does not return because it finds active reqs, but those active reqs will NEVER be termiminated, so my program gets blocked in `uv_run()` with no active handles (just active reqs) using 100% of CPU.

I do know that `longjmp` is the problem here, but I must live with it in Ruby world. So, if there any solution/workaround I could implement to solve this exotic problem?

Well, I would like having a function `uv_clean_loop(loop)` which iterates _everything_ within the loop and cleans all, regardless some function was previously interrupted with `longjmp`, but I expect such a function wont exit in UV :)

**Comment by piscisaureus** [comment]
That's madness. We can't fix libuv in a generic way to allow this.

Can't you wrap ruby callbacks in a try...catch block and deal with exceptions before returning to libuv?

**Comment by bnoordhuis** [comment]
> The problem at this point is that longjmp occured while uv__finish_close (for any TCP handle) was executing the write req callbacks, so it was interrupted.

Sounds like Russian roulette. I'm sorry but libuv can't help you here, what you're describing is essentially non-deterministic behavior. I suggest you try to find out _why_ Ruby longjmps, then find a way to make it stop doing that.

**Comment by DrPizza** [comment]
So essentially, you want libuv to tolerate abnormal termination of _any_ function at _any_ point? I do not think this is a reasonable request.

Ruby should not be doing a damn thing with the C stack until the C stack is back within Ruby's own code. Change your signal handler to make it defer handling of the signal until outside of libuv.

**Comment by ibc** [comment]
Hi, I agree with you, and thanks a lot for the explanation. Finally I've found the way to achieve it in Ruby language by using the C function `rb_protect()` for executing Ruby callbacks. Such a function catches any exception occured while in Ruby land and leaves me know about it, so I can store such an exception (i.e. SystemExit, any Ruby exception, SingalException...), properly terminate UV (by closing all the handlers) and then raise the stored exception in Ruby land after uv_run() properly exits.

Thanks a lot.
