### ISSUE TITLE
fail to uv_write big data

### ISSUE THREAD

**Issue by nori0428** [joyent/libuv#436]
fail below.

<pre>
uv_buf_t a = uv_buf_init("very long string...", SIZE_T_MAX);
uv_write(uv_write_t* req, uv_stream_t* handle, a, 1, uv_write_cb cb)
</pre>

---

cause

uv_buf_t at line 46 - 49 in include/uv-private/uv-unix.h

<pre>
typedef struct {
  char* base;
  size_t len;
} uv_buf_t;
</pre>

uv_buf_init at line 90 in src/uv-common.c

<pre>
uv_buf_t uv_buf_init(char* base, size_t len) {
  uv_buf_t buf;
  buf.base = base;
  buf.len = len;
  return buf;
}
</pre>

uv_write2 at line 866 in unix/stream.c of libuv

<pre>
  if (bufcnt <= UV_REQ_BUFSML_SIZE) {
    req->bufs = req->bufsml;
  }
  else {
    req->bufs = malloc(sizeof(uv_buf_t) * bufcnt);
  }
</pre>

a req->bufs[x].base is not malloced. So if an event loop tries to write req divided in two or more times, req->bufs[x].base may collapse.

**Comment by saghul** [comment]
It's the responsibility of the caller to keep the buffer alive until the uv_write callback is called, IIRC.

**Comment by nori0428** [comment]
Ah OK.thanks.
