### ISSUE TITLE
windows:uv_tcp_init crash

### ISSUE THREAD

**Issue by huawuya** [joyent/libuv#438]
For tcp example,
    loop = uv_default_loop();
    r = uv_tcp_init(loop, &tcp_handle);

when running into uv_tcp_init, crash happens on uv_handle_init()
  ngx_queue_insert_tail(&loop->handle_queue, &handle->handle_queue);
becuase prev and next of loop->handle_queue and handle->handle_queue are all NULL.

After I added  " ngx_queue_init(&loop->handle_queue);" in uv_loop_init(), it is OK.

**Comment by saghul** [comment]
Apparently it was just fixed: https://github.com/joyent/libuv/commit/0c727fd7747d1532352bb622e689f2efe576e532

**Comment by bnoordhuis** [comment]
Yes, @piscisaureus unfortunately let that bug slip through. (Okay, okay - I admit I forgot to initialize the handle queue.)
