### ISSUE TITLE
windows: uv_is_readable returns true right after handle init

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#439]
On Windows, just after initializing say a TCP handle uv_is_readable returns true because it just checks to see if UV_HANDLE_EOF flag was set, which wasn't, of course.

On Unix, OTOH the test is more explicit, it has UV_STREAM_READABLE / WRITABLE flags which are set and later used for checking them in uv_is_readable / writable.

I like the Unix approach here, and if we mimic it on Windows uv_is_readable/writable can be reused (they are one-liners, but anyway).

I could work on a patch, if we agree on the approach to fix it.

Thanks,

**Comment by bnoordhuis** [comment]
Sounds good to me. @piscisaureus?

**Comment by piscisaureus** [comment]
Yes, sounds good to me. I would prefer windows to use UV_HANDLE_READABLE and UV_HANDLE_WRITABLE as well (as opposed to what it does now, using UV_HANDLE_EOF and UV_HANDLE_SHUT)

**Comment by saghul** [comment]
Closing, since it was fixed by @piscisaureus here: https://github.com/joyent/libuv/commit/032c04179033b7512187fbcd17230e564c8573f4
