### ISSUE TITLE
uv_shutdown() after uv_write() makes the loop never exit if the TCP connection succeeded

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#445]
(Linux)

Below a gist demonstrating the issue.

**Scenario:**
- Some TCP listener in 127.0.0.1:9999 (i.e. `nc -l 127.0.0.1 9999`).
- Create a uv_tcp_t handle, init it, connect to the server and start reading (to avoid the handle becoming inactive).
- Run a timer (0.5 second to ensure that the TCP connection took place).
- In the timer callback close the timer handle and run `uv_write()` followed by `uv_shutdown()` for the TCP handle.
- In the `shutdown_cb()` close the TCP handle.

**Result:**
- No more handles should remain alive since both the timer and the TCP handle have been closed with `uv_close()`.
- ...but `close_cb()` has never been called by UV so the loop does not exit !

Test it: https://gist.github.com/2868308

**NOTES:**
- If the code in the timer callback is moved to the TCP connect (success) callback , then things work as expected (`close_cb()` is called for both handles and the loop exit).

**Comment by bnoordhuis** [comment]
Thanks, fixed in 7d2ea31.

**Comment by ibc** [comment]
Thanks a lot :)
