### ISSUE TITLE
uv_cwd and uv_exepath should have similar interface

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#446]
Right now it's a mess.

**Comment by mmalecki** [comment]
The problem with `getcwd` used by `uv_cwd` is that it returns `ERANGE` when buffer is too small, so buffer can't be smaller than `MAXPATHLEN`. We'd have to truncate it ourselves to limit string length to size supplied by user.

**Comment by saghul** [comment]
How about something like this?

```
diff --git a/src/unix/core.c b/src/unix/core.c
index a843044..936d895 100644
--- a/src/unix/core.c
+++ b/src/unix/core.c
@@ -589,16 +589,14 @@ ssize_t uv__recvmsg(int fd, struct msghdr* msg, int flags) {
 }


-int uv_cwd(char* buffer, size_t size) {
-  if (buffer == NULL)
+int uv_cwd(char* buffer, size_t* size) {
+  if (buffer == NULL || size == NULL)
     return -EINVAL;

-  if (size == 0)
-    return -EINVAL;
-
-  if (getcwd(buffer, size) == NULL)
+  if (getcwd(buffer, *size) == NULL)
     return -errno;

+  *size = strlen(buffer);
   return 0;
 }
```

That would make uv_cwd have the same API as uv_exepath and others. If buffer is not big enough, well, too bad, an error is returned. Of course the Windows version also needs adjusting, but you get the idea :-)
