### ISSUE TITLE
Loop/multithreading enter/exit feature request

### ISSUE THREAD

**Issue by gyohng** [joyent/libuv#454]
Here is an idea which allows simpler handling of many async scenarios:

Inside a non-loop thread:

``` c
    uv_lock_enter(loop);
    // code to be executed within the UV thread context
    uv_lock_exit(loop);
```
- uv_lock_enter calls async_send and blocks until actually async callback is started
- async callback waits until the other thread executes uv_lock_exit
- uv_lock_enter and uv_lock_exit are working like critical sections - if they are called from within multiple threads - uv_lock_enter will block until a concurrent thread is finished with the loop
- if the loop is not running, then uv_lock_enter/uv_lock_exit work like a simple critical section

In this way the code between uv_lock_enter/uv_lock_exit can be said to execute asynchronously within the loop thread. In many typical cases such logic will make creating async requests unnecessary.

**Comment by bnoordhuis** [comment]
Correct me if I'm wrong but don't you get the same semantics with a simple mutex?

``` c
uv_mutex_lock(&the_big_lock);
// code to be executed within the UV thread context
uv_mutex_unlock(&the_big_lock);
```

**Comment by gyohng** [comment]
Maybe I'm not well informed about libuv functionality, but I understand that the above example with a mutex does not wake up the libuv loop if it was dormant (no events) and certainly doesn't lock things against the internal libuv logic happening at the same time.

My proposal is similar to sending an async event, while providing the async code in-place rather than separating it into a callback with the horrendous set of initializations and deallocations as well as thread synchronizations, since the purpose of an async callback is usually exactly this - to wake up the libuv loop from within a different thread and to execute the code as a sequential libuv event.

Please check the quick example below, which I did for my own purposes (using Qt library for semaphores, since we use it in the project anyway). I use semaphores to control the flow - basically to wait until libuv comes into a callback, to suspend the uv loop thread for the time the code executes and resume the event loop after the code is finished.

Using:

``` cpp
// This is called from a non-libuv thread
{
    UVAsyncScope locker(uvloop);

    // do whatever one wants with handles, sockets, sending events, 
    // changing uv loop structures, as this code should be essentially
    // similar to running it from inside a uv loop callback
}
```

Class declaration

``` cpp
#include <QSemaphore>
#include "uv.h"

class UVAsyncScope
{
public:
    QSemaphore enterS,exitS;
    uv_async_t async;
    uv_loop_t *uv;


    UVAsyncScope(uv_loop_t *uv_)
    {
        uv = uv_;

        if (uv)
        {
            uv_async_init(uv,&async,UVAsync_callback);
            async.data = this;
            uv_async_send(&async); // wake up the UV thread
            enterS.acquire(); // wait for the UV loop to reach into the callback
        }
    }

    ~UVAsyncScope()
    {
        if (uv)
        {
            exitS.release(); // resume the UV loop
            enterS.acquire(); // additional lock to prevent premature destroying of semaphores
        }
    }

    static void UVAsync_callback(uv_async_t *h, int)
    {
        UVAsyncScope *scope = ((UVAsyncScope*)h->data);
        scope->enterS.release(); // proceed with the scoped code execution

        // <<---- The 'scope locked' code can be said to execute at this position

        scope->exitS.acquire(); // wait until the code executes within a different thread

        uv_close((uv_handle_t *)h,UVAsync_on_close); // close the async handle        

        scope->enterS.release(); // let the destructor proceed
    }

    static void UVAsync_on_close(uv_handle_t *h)
    {
        // do nothing
    }
};
```

**Comment by bnoordhuis** [comment]
Right, I see what you mean but there's a flaw in your code example. You need to call `uv_async_init()` from the libuv thread, only `uv_async_send()` is thread-safe. (Same goes for `uv_close()`, only call it from the libuv thread.)

As to your proposal, I guess it could be implemented with an internal async handle but I'm not sure how I feel about that. We try to keep libuv lean in the sense that people should not have to pay for a feature that only some use (within limits).

@piscisaureus What do you think?

**Comment by gyohng** [comment]
uv_close is called from the libuv thread. Thank you very much for pointing about the uv_async_init - I will need to change that.

As for the suggested feature - I would expect that people would use it 90% of the time instead of issuing an async event due to a much leaner syntax, for such purposes as for example asynchronously stopping the timer, closing the handle or (as in my case) - shutting down the loop.

There is another question - I think I found another fault in my code. It's not safe to deallocate an async handle before a close_cb is actually handled?

**Comment by piscisaureus** [comment]
@bnoordhuis Actually I've been thinking about similar solutions but there are two significant concerns here: -
- If this is proposed as an alternative to uv_async then I can see it's use. However it might be mistaken for a simple way to make libuv thread-safe - which in fact it does. The only downside is that it would be very slow, since the only moment that this "async" code can run is when libuv is processing the (internal) async handle. 
   (Side note: a "proper" thread safe solution would be to acquire a lock whenever internal state is being modified by libuv; and to release it whenever user callback code is running. But the overhead of locking/unlocking is not relevant for node and only adds overhead.)
- On Windows (unlike Unix) the thread that makes a syscall has a particular significance; that is, you can't assume that it doesn't matter which thread makes a syscall. Specifically:
  - Libuv can use CancelIo (although, admittedly, only on Windows XP/2k3 and only in particular edge cases). CancelIo cancel's all i/o that was initiated by the calling thread.
  - All i/o initiated by a thread is automatically canceled when a thread exits. When this actually happens it will confuse libuv, leading to memory leaks or worse.
  -  In the future we may switch to using Asynchronous Procedure Calls in situations where the IOCP cannot be used; currently we're using events, but APCs are more scalable and have less overhead (at least, they way we would use them.) APCs are basically callbacks coming from the kernel; they are scheduled to a particular thread; if that thread isn't running the main event loop they will likely never execute, and if they run anyway (on the wrong thread) stuff will break horribly.

**Comment by bnoordhuis** [comment]
> There is another question - I think I found another fault in my code. It's not safe to deallocate an async handle before a close_cb is actually handled?

It's not. Free the memory from inside your close_cb, not before.

**Comment by bnoordhuis** [comment]
@piscisaureus I guess that's a roundabout way of saying "no, it's not possible"? :-)

**Comment by piscisaureus** [comment]
@bnoordhuis @gyohng It was a roundabout way of saying "it is possible, but it would be illegal to call libuv functions from the 'other' thread, so it's kinda pointless"

**Comment by piscisaureus** [comment]
Obviously if we could find a trick to switch to a different TEB / thread context it could work :-)

**Comment by gyohng** [comment]
As for making things very slow - well, the global libuv state mutex (with the overhead, as you note) does not save from breaking the order of operations - and the amount of additional locking required on the user side makes that solution not very beneficial either - in the fact that in the end it's better to use an async call rather than to lock everything around to ensure the proper order of execution of the custom side.

So if it is comfortable - we can just drop the subject - and I'll refactor my code to use proper async with the pre-initialization before the loop is started and deletion inside the libuv close callback.

There is another rather cumbersome and fragile way to implement the same thing to execute actually within the libuv thread context by using longjump. The syntax would be:

``` cpp
if (uv_context_enter(uvloop))
{
    // Execute some code
    uv_context_exit(uvloop);
}
```
- uv_context_enter will block on the calling thread and wait until the execution is finished, then return false
- uv_context_enter wakes up the libuv thread via an async call and makes it longjump (switch the stack) to the inside of the conditional "if" by returning true from the uv_context_enter in the newly switched context
- uv_context_exit longjumps back to the uv loop
- at this point uv_context_exit returns false on the calling thread and lets execution proceed normally

The syntax is very similar to setjmp/longjmp.

However there is another rather common pattern - a series of sequential callbacks, each depending on another. Maybe some sort of cooperative threading solution would actually work to simplify the syntax of invocation. 

I'm sorry for bringing all this up - in the project I work upon probably a simple async call will do.

**Comment by piscisaureus** [comment]
> Obviously if we could find a trick to switch to a different TEB / thread context it could work :-)

Okay, that's not going to work. I am already at the uttermost depth of processor-specific NT kernel internals, beyond anything that we would want to hack.

**Comment by gyohng** [comment]
If it is desired, I can create a setjmp/longjmp sample (which should be quite portable for any platform, that supports setjmp/longjmp), which actually switches the context and does it in the syntax as I described above.

However should anyone forget to call uv_context_exit in the end of if (...) { } body - the program probably will crash in a very hard way.

**Comment by piscisaureus** [comment]
@gyohng

> So if it is comfortable - we can just drop the subject - and I'll refactor my code to use proper async with the pre-initialization before the loop is started and deletion inside the libuv close callback.

Well, my comfort is pretty important, but it's not the reason that I'm saying no. As I explained, we can't guarantee it to work without messing up libuv's state; that's the real problem here.

``` c
if (uv_context_enter(uvloop)) {
    // Execute some code
    uv_context_exit(uvloop);
}
```

I never really though of combining setjmp with threads... I have to admit, the idea is intriguing.

**Comment by piscisaureus** [comment]
@gyohng 

> If it is desired, I can create a setjmp/longjmp sample (which should be quite portable for any platform, that supports setjmp/longjmp), which actually switches the context and does it in the syntax as I described above.

There's nothing that's stopping you from implementing a wrapper that does this for this and using it. It doesn't have to be in the libuv tree to work.

> However should anyone forget to call uv_context_exit in the end of if (...) { } body - the program probably will crash in a very hard way.

_shrug_, that's okay.

BTW, why are you not just running qt and libuv on the same thread. It seems that that would save you from all this hassle.

**Comment by gyohng** [comment]
> There's nothing that's stopping you from implementing a wrapper that does this for this and using it. It doesn't have to be in the libuv tree to work.

Ok, so that's it then. We can close the issue then. Multiplatform semaphores would be the most appreciated addition to libuv however.

> BTW, why are you not just running qt and libuv on the same thread. It seems that that would save you from all this hassle.

libuv loop has to be a separate thread (maybe several independent libuv loops in fact). The integration would be very much technically difficult, as we don't have access to the OS event loop, and QtGui is not used either (just the core classes).

Sorry - I'm new to github and libuv etc - should I click 'Close issue' at this point ? By the way, thank you very much for libuv - it's absolutely great in many ways.

**Comment by piscisaureus** [comment]
> Ok, so that's it then. We can close the issue then. Multiplatform semaphores would be the most appreciated addition to libuv however.

https://github.com/joyent/libuv/blob/0dff0e7d47453fafb72a287c0acdddd6e3f2d9de/include/uv.h#L1627-1634

> libuv loop has to be a separate thread (maybe several independent libuv loops in fact). The integration would be very much technically difficult, as we don't have access to the OS event loop, and QtGui is not used either (just the core classes)

If you say so - I was just curious.

> Sorry - I'm new to github and libuv etc - should I click 'Close issue' at this point ? By the way, thank you very much for libuv - it's absolutely great in many ways.

No problem. I will close the issue now.
