### ISSUE TITLE
uv_is_active(async_t) returns always true

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#458]
(Linux)

I expected that `uv_is_active(async_t)` would return true just between the call to `uv_async_send()` and its callback. But if I create an async handle, call to `uv_async_init()` and run the loop, then `uv_is_active(async_t)` always returns true (without previously calling to `uv_async_send()`).

**Comment by piscisaureus** [comment]
That's the correct behavior. As long as as an uv_async handle exists it sits there, waiting for uv_async_send calls. That's what constitutes 'active'. It also keeps the loop alive (unless unref'ed).

There is no uv_async_start / uv_async_stop, something that other watcher types do. This could be regarded as an api inconsistency.

**Comment by ibc** [comment]
> It also keeps the loop alive (unless unref'ed)

This is not what I see. I create a async handle, call to `uv_async_init()`, run the loop (with no other handles) and `uv_run()` immediately exits. Perhaps you mean that `uv_async_send()` keeps the loop alive?

About the API inconsistency, the fact is that I do see a use case for having `uv_is_active()` returning true _just_ between `uv_async_send()` and its callback:

I want to provide a mechanism for other threads to execute UV actions within my reactor based on libuv, so when started, my reactor creates an async handle and calls to `uv_async_init()`.

The reactor offers the API `call_from_other_thread(block)` which uses a mutex to append the given code block to an "async_blocks" Array, and calls `uv_async_send()` _just_ if it's not active (which for now makes no sense as explained in your comment).

The async callback locks the mutex and executes all the blocks within the array, and clears the array.

But since the async handle is always "active", it means that, for example, 10 consecutive calls to `call_from_other_thread(block)` would involve 10 `uv_async_send()` and 10 async callbaks, but the fact is that the first callback would exec the all the 10 blocks, while the other 9 callbacks would find the array empty.

**Comment by piscisaureus** [comment]
> This is not what I see. I create a async handle, call to uv_async_init(), run the loop (with no other handles) and uv_run() immediately exits. 

If true, that's a bug. @bnoordhuis, can you confirm?

> Perhaps you mean that uv_async_send() keeps the loop alive?

Nope.

> I want to provide a mechanism for other threads to execute UV actions within my reactor based on libuv, so when started, my reactor creates an async handle and calls to uv_async_init().
> 
> The reactor offers the API call_from_other_thread(block) which uses a mutex to append the given code block to an "async_blocks" Array, and calls uv_async_send() just if it's not active (which for now makes no sense as explained in your comment).
> 
> The async callback locks the mutex and executes all the blocks within the array, and clears the array.

That sounds like a good design to me, except for the "just if it's not active" part.

> But since the async handle is always "active", it means that, for example, 10 consecutive calls to call_from_other_thread(block) would involve 10 uv_async_send() and 10 async callbaks, but the fact is that the first callback would exec the all the 10 blocks, while the other 9 callbacks would find the array empty.

Well, first of all, you can't use uv_is_active (reliably) from a thread other than the main thread.

Second, uv_async_send already coalesces multiple uv_async_send invocations into a single callback. See https://github.com/joyent/libuv/blob/0dff0e7d47453fafb72a287c0acdddd6e3f2d9de/include/uv.h#L1068-1073. It seems to me that calling `uv_async_send()` on every invocation of `call_from_other_thread` should not cause any (performance) problems.

**Comment by bnoordhuis** [comment]
> If true, that's a bug. @bnoordhuis, can you confirm?

Well... it's intentional, that's been the behavior since libuv's inception (see e.g. ce8ff30).

**Comment by ibc** [comment]
> Well, first of all, you can't use uv_is_active (reliably) from a thread other than the main thread.

Opss, good point.

> Second, uv_async_send already coalesces multiple uv_async_send invocations into a single callback. See https://github.com/joyent/libuv/blob/0dff0e7d47453fafb72a287c0acdddd6e3f2d9de/include/uv.h#L1068-1073.

Yes, I didn't know it! so "problem" solved: )

> It seems to me that calling uv_async_send() on every invocation of call_from_other_thread should not cause any (performance) problems.

Sure, I meant "calling the async callback" for every invocation of "uv_async_send()" (at least in the "call_from_other_thread()" design above).

> If true, that's a bug.

Well, IMHO a initialized async handle should NOT keep alive the loop (except when there is a pending uv_async_send()). This is at least what I expected.

**Comment by piscisaureus** [comment]
@bnoordhuis Can you review fab7b7bbf7f72ff3e1034276246026c995b15898 ?

**Comment by bnoordhuis** [comment]
> Can you review fab7b7b?

LGTM. Merged in 5c30443.
