### ISSUE TITLE
semantics of uv_is_active()

### ISSUE THREAD

**Issue by ry** [joyent/libuv#46]
This issue is spawned by:
https://github.com/joyent/libuv/blob/c8603a74621d7151c087afdafe23b79ee0a7832e/test/test-timer-again.c#L79-88

What should `uv_is_active()` actually mean?

Suggestion: `uv_is_active()` returns true until the handle's on_close callback is fired.

**Comment by piscisaureus** [comment]
Currently we use uv_is_active to determine if a timer or loop watcher was started or not. If we change the uv_is_active semantics that is going to make our node job miserable. However we could have another api for this, e.g. uv_is_closed maybe?

**Comment by ry** [comment]
is a tcp handle ever active?

**Comment by piscisaureus** [comment]
For some handle types "active" would be a meaningless concept since they are never started or stopped.

TCP handles could be active when they are reading or accepting connections.

**Comment by bnoordhuis** [comment]
Leaky abstraction?

**Comment by ry** [comment]
it's kind of strange to have timers, async, prepare, check, idle be handles in the same way as a tcp socket (which is an abstraction of an actual file descriptor)

**Comment by bnoordhuis** [comment]
@piscisaureus and I figured out the semantics a while ago and work is ongoing to implement it. Closing.

**Comment by piscisaureus** [comment]
Continues in #347
