### ISSUE TITLE
Clarify that uv_getaddrinfo_t is a request (instead of a handle)

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#474]
The doc (uv.h) is confusing when it describes `uv_getaddrinfo_t`. It's a request rather than a handle, in fact, calling to `uv_close(uv_getaddrinfo_t)` would crash in debug mode.

So I suggest:
- Remove `uv_getaddrinfo_t getaddrinfo` from `union uv_any_handle`.
- Rename the second param in `uv_getaddrinfo()` method (replace `uv_getaddrinfo_t* handle` with `uv_getaddrinfo_t* req`).
- Move line 198 of uv.h (`typedef struct uv_getaddrinfo_s uv_getaddrinfo_t;`) below line 203 (`/* Request types */`).

**Comment by bnoordhuis** [comment]
Agreed. Fixed in f01e9d7.

**Comment by ibc** [comment]
Hi, I forgot to point that line 307 in uv.h still talks about "handle" instead of "request":

```
typedef void (*uv_getaddrinfo_cb)(uv_getaddrinfo_t* handle,
                                  int status,
                                  struct addrinfo* res);
```

I suggest replacing "handle" with "req".

**Comment by bnoordhuis** [comment]
Added in 0005b52.
