### ISSUE TITLE
3-digit version, ChangeLog, tagged release tarballs

### ISSUE THREAD

**Issue by isaacs** [joyent/libuv#475]
It'd be great if libuv had a more polished release cycle.
1. The version should be 3 digits, like `0.8.2`.  That doesn't need to be tied to node's, necessarily, but there would be an understanding that node `0.8.x` will always use libuv `0.8.x`, so it should have the same even/odd semantics.  It should also have an `IS_RELEASE` flag like node does, which puts a `-pre` on the version if it's not a release.
2. Add a `ChangeLog` file with a summary of the changes in each release.
3. When bumping the version, do a `git tag -sm <version>`, build a tarball, and upload it someplace.
4. Node should only pull in tagged releases, not arbitrary libuv commits.

All this will help make the node release cycle easier, and aid in debugging (since process.versions.uv will actually mean something.)

**Comment by bnoordhuis** [comment]
> git tag -sm <version>

@piscisaureus That means you need to set up GPG. If you have more than one key, `-u` will let you pick the right one.

**Comment by ibc** [comment]
Hi, about step 3 above:

> When bumping the version, do a git tag -sm <version>, build a tarball, and upload it someplace.

The following code will create a tag which would also become a .zip / .tar.gz file in the Github project (within "Tags" section):

```
git tag -a 0.8.2 -m "Version 0.8.2"
git push --tags
```

See for example: https://github.com/ibc/EventMachine-LE/tags

**Comment by isaacs** [comment]
Yeah, uploading a tgz is less relevant if there are consistently named
tags. Signed tags are nice though.

**Comment by saghul** [comment]
We do proper released now :-)
