### ISSUE TITLE
http.request doesn't honour HTTP/1.0

### ISSUE THREAD

**Issue by tim-smart** [joyent/libuv#481]
I was trying to make an api call to http://www.last.fm/api/show/user.getRecentTracks and it kept on responding:

``` html
<h1>400 - Bad request</h1>\nCan't pipeline to HTTP/1.0
```

If you want code examples etc. let me know.

**Comment by piscisaureus** [comment]
Did you find a bug in libuv? FYI, libuv has no http stuff built in - it only does the networking part. 

If not, could you post this in the node issue tracker?

**Comment by tim-smart** [comment]
Sorry half asleep and posted in wrong project. Ignore this.
On Jun 30, 2012 1:27 AM, "Bert Belder" <
reply@reply.github.com>
wrote:

**Comment by piscisaureus** [comment]
np :-)
