### ISSUE TITLE
callback for fs event should have same path info as passed to init?

### ISSUE THREAD

**Issue by japj** [joyent/libuv#482]
Hi, I am using nodejs 0.8.0 on windows.

Currently if I pass a path to a specific file to uv_fs_event_init_handle, the 'change' callback will only contain the filename.
i.e. I specify (in nodejs fs.watch('somedir/somefile', cb) and the callback only receives 'somefile'.

Since the exact path specified is stored in handle->filename it would make sense if the callback just gets passed that same path.

Unfortunately, uv_process_fs_event_req does a handle->cb(handle, filename, UV_CHANGE, 0) where filename is based on some generic processing that tries to unify directory and file watches and ends up containing only the filename.

This can also be confirmed by the test-fs-events.c that currently does:

<pre>
r = uv_fs_event_init(loop, &fs_event, "watch_dir/file2", fs_event_cb_file, 0);
</pre>

where fs_event_cb_file does:

<pre>
ASSERT(filename == NULL || strcmp(filename, "file2") == 0);
</pre>

instead of

<pre>
ASSERT(filename == NULL || strcmp(filename, "watch_dir/file2") == 0);
</pre>

**Comment by japj** [comment]
note, that I want to do something with the filename passed to the callback (parse the file), so I need the actual full path to it.

But I agree that the (nodejs) documentation on this isn't entirely clear (and ofcourse it is an 'unstable' api)

**Comment by bnoordhuis** [comment]
Let's not do that. It'd require libuv to malloc() + memcpy() + free() memory on every event. Which is rather wasteful if the callee is only interested in the filename part of the path.
