### ISSUE TITLE
unix: getaddrinfo req makes event loop spin

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#484]
Somewhat related to the busy loop that got fixed by 0971598. Possibly also applies to other request types that are not associated with an active handle.

Test case:

``` bash
$ strace -e epoll_wait node -e 'require("http").get("http://nodejs.org/")'
```

Prints:

```
<snip>
epoll_wait(3, {}, 64, 0)                = 0
epoll_wait(3, {}, 64, 0)                = 0
epoll_wait(3, {}, 64, 0)                = 0
epoll_wait(3, {}, 64, 0)                = 0
<snip>
```

**Comment by piscisaureus** [comment]
getaddrinfo req implies that there is an active (internal) async handle, so the loop shouldn't spin.
