### ISSUE TITLE
unix: build with autotools

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#486]
The gyp build works okay but won't see uptake by distros anytime soon.

The plain Makefile is rather limited - it only knows how to compile static debug builds, for example. Hacking on new features is both a thankless job and a barrier to entry, it's not easily discoverable or comprehensible by new libuv hackers.

Therefore, ditch the Makefile in favor of autotools generated configure and Makefile scripts. I'm no autotools fan but there's no denying it's the greatest common denominator for Unices.

Related to #475.

**Comment by luislavena** [comment]
@bnoordhuis why not CMake instead? autotools is just a plain pain.

It states is cross platform but the proper support for anything other than POSIX is bad (ala Windows, not talking about Visual Studio but MinGW or clang)

**Comment by bnoordhuis** [comment]
> why not CMake instead?

To please distro packagers. Anything that's not autotools is frowned upon.

**Comment by okuoku** [comment]
@luislavena , although I have CMake fork, I agree with @bnoordhuis .
Autotools is widely adopted and almost all of (POSIX-based) hackers know how to use it.

**Comment by luislavena** [comment]
@okuoku @bnoordhuis I'm cool with it, it will allow me to release a binary package for Windows for both x86 and x64.

But I'm dumb in relation to autotools except some stuff I did for Ruby own configure script. I could probably help getting the MinGW support for both static and dynamic library, but autotools is like a foreign language to me (and my foreign I mean another planet-kinda language)

**Comment by JustinVenus** [comment]
I am ok with autotools.  I may be able to find some time to get this started for at least Linux.  I'll send a pull request when I can get it to build and test with Fedora17 and Centos6.

**Comment by piscisaureus** [comment]
I do not want to get rid of the gyp based build btw. The autotools stuff should just be for distros.

**Comment by JustinVenus** [comment]
@piscisaureus 10-4.  It will probably be a day or too before I merge my branch into my fork.

**Comment by JustinVenus** [comment]
I have made some progress.  https://github.com/JustinVenus/libuv/compare/issue486

What works:
Linux.  builds shared and static library "sh autogen.sh; ./configure; make".  Creates a targz archive 'make dist'.  Installs in a fake root 'make DESTDIR=/var/tmp/libuv install'.

What doesn't work:
Other Platforms.  It should be easy to support them, I just haven't finished the support.
Tests and Benchmarks.  I haven't gotten to the part yet.

**Comment by JustinVenus** [comment]
Following up from yesterday.  I have a working solution in my branch[1], but I do have a few questions before I send a pull request.  Should I name the Makefile generated by autotools to something like "makefile" or should I displace the original Makefile and let autotools assume control?  I noticed that c89 is set in the original Makefile, but I was able to successfully build and test with c99 (c99 also allows the sunpro compiler to work pretty easily) ... should c89 be the default or should I let autotools determine what is supportable?  Thank you in advance for your feedback.

1) https://github.com/JustinVenus/libuv/compare/issue486

**Comment by jbergstroem** [comment]
@JustinVenus: How about creating a subdirectory for the auto\* stuff? That would at least maintain backwards compatibility and naming conflicts. I recall LLVM having a similar approach (they do cmake and auto\* in parallel).

**Comment by JustinVenus** [comment]
Brilliant, that is so simple I can't believe it didn't occur to me.

Justin
On Jul 29, 2012 12:51 AM, "Johan Bergström" <
reply@reply.github.com>
wrote:

**Comment by JustinVenus** [comment]
@jbergstroem I pulled llvm's source to see what they do, unfortunately I can't get their autotool setup to do anything but explode in error on Fedora.  I will continue to investigate how to move things around.  So far autotools isn't playing very nice with me atm.

**Comment by bnoordhuis** [comment]
Closing. It turns out we don't need autotools support after all. Fedora was happy using the Makefile provided it knows how to build a shared object (which it now does).
