### ISSUE TITLE
test-get-currentexe fails on solaris

### ISSUE THREAD

**Issue by ry** [joyent/libuv#49]
see https://github.com/joyent/libuv/blob/9fc8a7f1670e6b6f223e48ebf390dd345a888007/uv-unix.c#L1238-1239

This probably implies passing `argv` to `uv_init()`. If this is the solution then #47 should be fixed first.

**Comment by rmustacc** [comment]
This can be grabbed through /proc. I'll code up a patch for it.

**Comment by bnoordhuis** [comment]
Doesn't Solaris have `getexecname()`? Alternatively, does __progname work? It's not standardized but I think it works on all the popular Unices.

```
#include <stdio.h>

const char *__progname;

int main(void) {
  puts(__progname);
  return 0;
}
```
