### ISSUE TITLE
uv_lchown uv_lchmod

### ISSUE THREAD

**Issue by isaacs** [joyent/libuv#494]
Right now in Node, we look for the presence of `constants.O_SYMLINK`, and then do fs.open() with that flag, and then a `fchown` or `fchmod` to set the owner and mode of a symbolic link on OS X (without following the link).  The function is simply missing on other operating systems, making for an unpleasant wart of feature detection.

Also, on Windows, there is no way to set the mode on reparse points.

Proposal:

Add uv_lchown and uv_lchmod, and have Node call those directly.
1. **Darwin** call lchown or lchmod just like any other fs function.
2. **SmartOS, Linux, FreeBSD** Both of these are no-ops.  (Symbolic links don't have modes or owners separately from their targets.)
3. **Windows** lchown is a no-op (same as chown and fchown), but lchmod can set the read-only bit on the symlink or junction.

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
