### ISSUE TITLE
Where is the IOCP Worker_Thread?New guy for help

### ISSUE THREAD

**Issue by h73899** [joyent/libuv#497]
Here is the stuff:
         1、I want to write a simple tcp server,and I know how to make it directly by using IOCP on windows.
         2、But I don't know how to make it through libuv, I've seen the sample(blackhole-server、dns-server、echo-server).It seems that only one thread to handle the received data. 
         3、"Its purpose is to abstract IOCP on Windows and libev on Unix systems."; MSDN mentioned that:"The best overall maximum value to pick for the concurrency value is the number of CPUs on the computer.",but where is the worker threads or threads number.

```
 I wana konw where is the worker thread or how to make my dream true through libuv.
 Official Documents are so...to new guys like me and I got nothing even using google.

 forgive my...English...

Thanks
```

**Comment by saghul** [comment]
I don't know how many worker threads are used in the IOCP backend, but you probably shouldn't be attempting to use it directly.

If you want to create a TCP server have a look at the examples and the API for uv_tcp_t in uv.h.

**Comment by h73899** [comment]
Thanks for the reply

I know how to create a TCP server(just copy from blackhole-server.c and do some small things)

Now the problem is only one thread to handle the requests(can get threads number through task manager or other tools), no matter how many clients or requests the server got; I can't find the way to use multi-threads to do the work concurrency. 

On windows when using IOCP, the worker threads number is due to user's decision, something looks like :

```
    for(i = 0; i < SystemInfo.dwNumberOfProcessors; i++)
{
    HANDLE ThreadHandle;
    // Create a server worker thread and pass the completion port to the thread.
    if ((ThreadHandle = CreateThread(NULL, 0, ServerWorkerThread, CompletionPort,
        0, &ThreadID)) == NULL)
    {
        printf("CreateThread() failed with error %d\n", GetLastError());
        return;
    }
    // Close the thread handle
    CloseHandle(ThreadHandle);
}
```

**Comment by bnoordhuis** [comment]
Have multiple threads, each with its own event loop, and share the server handle by means of uv_write2(). We'll probably add an API someday to make handle sharing easier - the main use case now is to share handles across processes, not threads, that's why it's somewhat convoluted.
