### ISSUE TITLE
memory leak in win/fs.c

### ISSUE THREAD

**Issue by trx011** [joyent/libuv#503]
UV_FS_FREE_PATH  is used in uv_fs_req_cleanup, but never set.

if (req->flags & UV_FS_FREE_PATH && req->pathw) {
    free(req->pathw);
    req->pathw = NULL;
  }

**Comment by piscisaureus** [comment]
Did you actually find a leak? As far as I can tell we never allocate req->pathw so I don't think there's a leak, you just found some rudimentary code.

**Comment by trx011** [comment]
in  uv_fs_open()
 => UTF8_TO_UTF16(path, pathw)
 => uv_fs_req_init_async(loop, req, UV_FS_OPEN, path, pathw, cb)
 => req->pathw = (wchar_t*)pathw

**Comment by piscisaureus** [comment]
Should be fixed in 73096da21b5c5d619e866f7aefa8b896cb2eeb69.
