### ISSUE TITLE
SharpUV

### ISSUE THREAD

**Issue by gigi81** [joyent/libuv#513]
If anyone interested, I created a new C# binding for libuv.
https://github.com/gigi81/sharpuv
You can read the readme for the details.

I was wondering if the changes I had to the build scripts could be merged or adopted in some way.

Now I'm able to build libuv (on windows) with two new switches passed to the vcbuild script:
- shared/static
- x86/x64

The changes are backward compatible and they don't brake the current build behaviour.

**Comment by bnoordhuis** [comment]
Luigi, can you submit your changes as a pull request?

**Comment by gigi81** [comment]
see #514
