### ISSUE TITLE
uv_poll causing early loop exit?

### ISSUE THREAD

**Issue by mscdex** [joyent/libuv#517]
I haven't yet been able to track down the exact cause, but in a [binding I'm writing for node](https://github.com/mscdex/ssh2), my poller seems to cause the event loop to exit early (at least with the version of libuv shipped with node 0.8.5).

This only seems to happen when I set the event mask to something that is non-zero (since zero immediately causes the poller to unreference) but still causes the callback to not be executed anymore (e.g. I initially set the events to UV_WRITABLE, then after the binding engages in some network traffic, it changes to UV_READABLE, knowing that the other side won't be sending any more data until I do again).

What I found was if I re-set the events mask to UV_READABLE | UV_WRITABLE instead of just UV_READABLE when there is currently no traffic to watch for, the event loop will stay alive (at the expense of constantly executing the poller's callback every tick because the socket is still writable). I have a [comment block](https://github.com/mscdex/ssh2/blob/master/src/session.cc#L380) about this in the binding.

I have enabled debugging and tracing on the library I am binding to and am 99% sure that the library is not causing this problem.

I tried to come up with a simple, reproducible test case (using libuv master branch as of this writing), but I haven't been able to create one that exhibits the same behavior. Right now all I have to test with is my binding and at this point it's fairly simple yet.

Any help, suggestions, etc. are appreciated in this matter.

**Comment by mscdex** [comment]
I should also add that the pause between when no more events come in and when the loop exits is consistently 10 seconds from my observations.

**Comment by bnoordhuis** [comment]
On what platform is this?

> I tried to come up with a simple, reproducible test case (using libuv master branch as of this writing), but I haven't been able to create one that exhibits the same behavior.

Does your test case work if you test it against the v0.8 branch or commit 6209fe5? (That's the version of libuv that ships with node 0.8.5.)

**Comment by mscdex** [comment]
This is on Windows. I'll have to try again later today on a different branch.

**Comment by mscdex** [comment]
I've decided to scrap the binding altogether and just do it all in js-land.
