### ISSUE TITLE
[ANN] c-ares removed

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#518]
It's a bit odd to put an announcement in the issue tracker, but in absence of a mailing list it'll do.
### C-ares was removed (in master). It's not coming back.

If you need want / c-ares anyway: it's not hard to integrate it using uv_poll. 

To get the idea, look at how it was integrated into libuv just before the removal: https://github.com/joyent/libuv/blob/32f93e14cbeea53ac8e2fc1dc77207dc6b251003/src/cares.c. 
This is what was needed to move the glue code into node: joyent/node@9e55ba7

The gypified c-ares that was ripped out of libuv (and is now used in node directly) is available at https://github.com/piscisaureus/cares

@creationix @philips @loladiro @brson @saghul @olsonjeffery @txdv @gigi81
(I probably forgot many people; if you know maintainers of libuv bindings that I forgot, please add them)

**Comment by piscisaureus** [comment]
@ry probably cares as well

**Comment by saghul** [comment]
Hi @piscisaureus, thanks for the heads up, I appreciate that. FWIW pyuv master no longer uses the bundled c-ares, I created pycares for that inspired by the good old cares.c in libuv :-)

**Comment by txdv** [comment]
Maybe we could create a list for all the libuv bindings with links?
I would like to investigate some of them.

**Comment by rphillips** [comment]
subscribing myself to this thread.

**Comment by piscisaureus** [comment]
Maybe we should have an actual mailing list.

**Comment by saghul** [comment]
+1 to that.

**Comment by rphillips** [comment]
+1

**Comment by bnoordhuis** [comment]
> Maybe we should have an actual mailing list.

Didn't you create one a long time ago?

**Comment by piscisaureus** [comment]
Yeah but nobody subscribed :-). And I never posted anything. But okay, let's (re)surrect it:

## http://groups.google.com/group/libuv

**Comment by saghul** [comment]
This has been open for a while, I guess it's time to let it go :-) Closing.
