### ISSUE TITLE
linux: beef up /proc/cpuinfo parser

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#526]
See joyent/node#3749. Ensure that the following parses correctly:

```
Processor       : ARMv7 Processor rev 2 (v7l)
processor       : 0
BogoMIPS        : 596.46

processor       : 1
BogoMIPS        : 599.22

Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x1
CPU part        : 0xc09
CPU revision    : 2

Hardware        : OMAP4 Panda board
Revision        : 0020
Serial          : 0000000000000000
```

**Comment by docfaraday** [comment]
Yuck. The format of cpuinfo is pretty inconsistent. It _looks_ like you can count "processor" lines (case-sensitive), but who knows.

**Comment by stolsma** [comment]
Same problem on my Rasp PI. Added the output of  '/proc/cpuinfo', maybe you can use it... 

```
pi@raspberrypi ~ $ cat /proc/cpuinfo
Processor       : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : swp half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0002
Serial          : 000000000616ba5a
pi@raspberrypi ~ $
```

**Comment by bnoordhuis** [comment]
Fixed in 54bfb66. At least, it's fixed for me - if you guys want to double check it, I'd appreciate that.

**Comment by stolsma** [comment]
Yep, it works!!

Tested on Raspberry Pi (see above) with a patched version of libuv in Node0.8.6...

Thanks!!!!

**Comment by bnoordhuis** [comment]
Sweet, thanks for testing!

**Comment by beriberikix** [comment]
@stolsma n00b question - how did you patch libuv? I haven't found solid instructions to get v0.8.6/v0.8.7 on my RPI.

**Comment by stolsma** [comment]
@beriberikix See https://gist.github.com/3301813 and follow 'Instructions for compiling node0.8.7 with hardfloat'
