### ISSUE TITLE
uv__async_make_pending() broken in fallback case

### ISSUE THREAD

**Issue by apaprocki** [joyent/libuv#534]
While testing on Solaris/AIX using Studio 12 / XL C 11 compilers (yes, they work just fine), I noticed `uv_async_send()` was broken and failed to ever wake up the `uv_async_t` callback. After some quick poking around I noticed that the `uv__async_make_pending()` code has optimizations for x86/64 and GCC, but a broken fallback case that went unnoticed:

``` c
#if __i386__ || __x86_64__
  {
    unsigned int val = 1;
    __asm__ __volatile__("xchgl %0, %1" : "+r" (val) : "m" (*ptr));
    return val != 0;
  }
#elif __GNUC__ > 4 || __GNUC__ == 4 && __GNUC_MINOR__ >= 1 /* gcc >= 4.1 */
  return __sync_val_compare_and_swap(ptr, 0, 1) != 0;
#else
  *ptr = 1;
  return 1;
#endif
```

Essentially, `uv__async_always_make_pending()` always returns 1 in the fallback case, so that `uv_async_send()` _always_ thinks there is a pending wake-up and never writes to the pipe to signal wake-up.

The fallback case needs to change to `return 0` since the pending case is the first thing checked in the function.

**Comment by piscisaureus** [comment]
@apaprocki Thanks for reporting. Fixed in a787a16.
