### ISSUE TITLE
uv_init() for linux where is it?

### ISSUE THREAD

**Issue by matt2003** [joyent/libuv#536]
Hi All,
I am fairly new with libuv and I was wondering where is uv_init() from the unix version. I was trying to maybe upgrade to a newer version of libuv from an older version is it possible? But of course there is no uv_init to begin with it appears this must be a fairly old version

Any help is appreciated

**Comment by saghul** [comment]
uv_init is gone, you don't need to call it anymore :-)

**Comment by piscisaureus** [comment]
What @saghul said.

**Comment by matt2003** [comment]
Thats great may I ask what method should be called on linux to kick everything off? uv_run?

**Comment by saghul** [comment]
There is nothing special to be called on Linux. Just setup all the handles you want and start the loop with uv_run. You may want to have a look at uvbook: http://nikhilm.github.com/uvbook/index.html
