### ISSUE TITLE
unix: callback ordering

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#538]
This doesn't look right to me. `uv_prepare` callback should be made right before polling, and `uv_check` should be processes immediately after it.

https://github.com/joyent/libuv/blob/c77d08eb9229f738aa9d6433a1d3e1d711abfa3d/src/unix/core.c#L256-273

@bnoordhuis

**Comment by saghul** [comment]
Behavior looks aligned now: https://github.com/joyent/libuv/blob/master/src/unix/core.c#L263-L278 https://github.com/joyent/libuv/blob/master/src/win/core.c#L279-L296 can this be closed now @piscisaureus ?

**Comment by saghul** [comment]
Closing, AFAIK this was fixed already.
