### ISSUE TITLE
Question on fifo uv_work_t handling

### ISSUE THREAD

**Issue by JayBeavers** [joyent/libuv#542]
Over in node-serialport we need a FIFO guaranteed background task for writing bytes to a serial port.  I've searched through libuv for a way to do this and don't see an existing pattern.  I've written up a [gist of my proposed change](https://gist.github.com/3553827) using uv_thread, uv_mutex, and a stl queue.  Since I'm new to libuv, I would appreciate feedback on this approach.

**Comment by bnoordhuis** [comment]
The issue tracker is not really the right place for questions, we have a newsgroup: http://groups.google.com/group/libuv

The basic idea seems solid to me: queue a work req, wait for it to come back, queue the next one.

**Comment by bnoordhuis** [comment]
Oh, I forgot to mention that we have an IRC channel as well: #libuv on freenode.org. There's usually someone around.

**Comment by JayBeavers** [comment]
Thanks, answered on irc.  You gents are awesome to work with.
