### ISSUE TITLE
make test assertion failed mingw on windows7(32bit)

### ISSUE THREAD

**Issue by rayfill** [joyent/libuv#543]
I make and make test libuv on windows7(32bit) with mingw.
unit-test output some errors.

https://gist.github.com/3608082

**Comment by piscisaureus** [comment]
@rayfill Can you gist the output of `netsh winsock show catalog` for me?

**Comment by piscisaureus** [comment]
FWIW, all tests pass here with mingw32. This is a windows 7 enterprise (64 bit) system.

**Comment by rayfill** [comment]
1. fs_file_loop
   Create loop symbolic link in test. It is failed.
   My environment is UAC on. run-test.exe permit administrator, test is succeed!.
2. dlerror
   LoadLibraryEx API load to test/fixtures/load_error.node is failed.
   because I checkout using cygwin's git. load_error.node file is not executable.
   cygwin is this permission projected to windows 'フォルダのスキャン/ファイルの実行'(scan folder/execute file) permission. LoadLibraryEx API check this permission. if dropped it then return another error.
3. poll_close
   It is yet debugging now. but I think my environment problem...

**Comment by rayfill** [comment]
netsh winsock show catalog's result.
https://gist.github.com/3773964

**Comment by piscisaureus** [comment]
@rayfill I think the poll_close failure happens due to the fact that you have X-FORT LSP installed. A poll_close failure is expected on windows xp but not on windows 7, so I'll have to look into this. 

Do you have any idea where this X-FORT LSP comes from? [LSPs](http://msdn.microsoft.com/en-us/library/aa925739.aspx) are typically associated with parental control software, firewalls, and malware.

**Comment by rayfill** [comment]
I test another environment.(windows 7 32bit enterprise english and windows 7 64bit ultimate japanese)
error is not occured.
poll_close problem is probably cause from X-FORT.
(X-FORT is system management tool. It install from company. http://www.fineart-tech.com/en/index.php?option=com_content&view=article&id=2&Itemid=19 )

Thank you for your advice.

**Comment by piscisaureus** [comment]
@rayfill Reopening, I believe we can do better here. The X-Fort LSP is of a "nice" type for which there should be no need to fail poll_close.

**Comment by saghul** [comment]
Inactive for over 2 years now, closing.
