### ISSUE TITLE
Corrupted files on linux with many concurrent write calls

### ISSUE THREAD

**Issue by bobrik** [joyent/libuv#544]
https://gist.github.com/3617558 - this gist is test case + sample strace output. WTF may not appear after every run. Changing `reader()` to `setTimeout(reader, 1000)` does not change anything.

All `pread` syscalls come after last `pwrite` syscall. This only happens if many writes fired at once. Writing from time to time is ok.

OS X is not affected (i have ssd so this may be just too fast), Linux is affected (spinning disks at least).

cc @bnoordhuis @indutny

**Comment by indutny** [comment]
Info: http://mail-index.netbsd.org/netbsd-users/2010/05/26/msg006265.html

**Comment by indutny** [comment]
And also, not sure why, but if you'll initialize those buffers - error will disappear.

**Comment by bobrik** [comment]
From irc with @indutny: https://gist.github.com/3618478 100 writes < 4096 bytes, all `pread` after last `pwrite` — same results.

**Comment by piscisaureus** [comment]
So this is all on BSDs?

**Comment by bobrik** [comment]
I see this on Linux. I may ask for FreeBSD machine to check if it matters.

**Comment by bnoordhuis** [comment]
Maybe I'm missing something. You're doing lots of concurrent overlapping writes, of course you're going to get corrupted results.

**Comment by indutny** [comment]
Writes are not overlapping.

**Comment by bobrik** [comment]
@bnoordhuis they do not overlap

**Comment by bnoordhuis** [comment]
You're doing concurrent writes at the end of the file, right? Let's say thread A writes 100 bytes at position 100, thread B writes 100 bytes at position 200 and they're doing it concurrently. On most operating systems it's undetermined what actually happens. If A comes before B or vice versa, you'll probably get the right results. If A and B overlap in time, non-determinate things happen.

**Comment by bnoordhuis** [comment]
By the way, the reason that you're not seeing this on OS X is that all writes get serialized through a big mutex. It was considered necessary because pwrite() comes with even less guarantees on that platform.

**Comment by bobrik** [comment]
Yep, platforms without `pwrite` will work because of libeio emulation with mutex :)

**Comment by bnoordhuis** [comment]
That's not quite what I mean. We use pwrite() on OS X but all calls are guarded by a single Big Lock.

**Comment by bobrik** [comment]
https://gist.github.com/3620592 here we go again. sequential writes (no overlapping), but file is corrupted from time to time.

**Comment by piscisaureus** [comment]
@bnoordhuis looks valid, I can reproduce this on ubuntu.

**Comment by bobrik** [comment]
@piscisaureus there's a bug in this code, closing.

**Comment by bobrik** [comment]
Final update: this was "a+" behaviour on linux. Gist to prove that: https://gist.github.com/3621892

Maybe it should be documented somehow, because it's kind of unexpected thing to see.

Waiting for final @bnoordhuis words to close this mess.

**Comment by bnoordhuis** [comment]
> Waiting for final @bnoordhuis words to close this mess.

Hmm... go in peace, my son?

I welcome documentation patches, by the way. :-)
