### ISSUE TITLE
uv_queue_work() leaks on high load

### ISSUE THREAD

**Issue by kononencheg** [joyent/libuv#545]
There is memory leak in here:
https://github.com/LiveTex/Node-Pg/blob/master/src/connection.cc#L99 

When make request synchronously:

```
uv_queue_work(uv_default_loop(), work_item, work, connection_work_handler);
```

to

```
work(work_item);
connection_work_handler(work_item);
```

There is no such problem.

For repeating leak, you should call 

```
$ node benchmarks/pg.js 127.0.0.1 100
```

from your shell. Where 127.0.0.1 - db (postgres) address, and 100 - request count. 
Then use `top` to see how memory leaks.
Leak will happen when request count is more than 200000.

Sorry for my bad english.

**Comment by piscisaureus** [comment]
@kononencheg 
- Which OS are you using?
- How did you determine there was a leak?
- Is it possible to create a test that doesn't require me to install postgres?

**Comment by kononencheg** [comment]
- Fedora 17 x64
- After benchmark stopping memory don't freeing.
- I create special branch leak-test (https://github.com/LiveTex/Node-Pg/tree/leak-test). You not need to install postgres or libpq to test leak in it. Just make and run:
  
  $ node benchmarks/pg.js 1000000

Thanks you for your attention!

**Comment by bnoordhuis** [comment]
> After benchmark stopping memory don't freeing.

How are you verifying that? With a tool like valgrind or by looking at the output of ps?

I managed to build the module with some effort and run the benchmark. I don't see anything untoward, the benchmark runs for a bit, then sits idle. RSS tops out at 139 MB.

**Comment by kononencheg** [comment]
I'm using only output of ps.

The problem is that benchmark memory don't freeing after stopping (only V8 part reduces to 7 MB). 
But when using sync execution all memory freeing to 10 MB.

**Comment by kononencheg** [comment]
Valgrind said:

```
==333== LEAK SUMMARY:
==333==    definitely lost: 0 bytes in 0 blocks
==333==    indirectly lost: 0 bytes in 0 blocks
==333==      possibly lost: 2,496 bytes in 10 blocks
==333==    still reachable: 421,025 bytes in 310 blocks
==333==         suppressed: 0 bytes in 0 blocks
```

And i'm really don't know why it's happen.
But it's a problem because we've got to reload our node.js application once a day because of it.

**Comment by bnoordhuis** [comment]
Try it with --leak-check=full. The numbers you're seeing aren't unexpected, node/v8/libuv allocate a couple of things at start-up that are never released.

**Comment by kononencheg** [comment]
Previous result is with `--leak-check=full` flag.

> node/v8/libuv allocate a couple of things at start-up that are never released.

And where is top limit?

**Comment by bnoordhuis** [comment]
Sorry, I meant `--leak-check=full --show-reachable=yes`.

> And where is top limit?

I don't understand what you mean.

**Comment by kononencheg** [comment]
I mean, what is top limit of memory that node/v8/libuv allocating for its couple of things?

**Comment by bnoordhuis** [comment]
It depends. It's usually a couple of 100 kB.

**Comment by saghul** [comment]
Last update was 2 years ago, and there doesn't seem to be an issue with uv_queue_work, not to mention things have evolved quite a bit in that time. Feel free to reopen if you do find a leak in libuv, ideally with a C test case which demonstrates it.
