### ISSUE TITLE
refactoring proposal for unix

### ISSUE THREAD

**Issue by kazupon** [joyent/libuv#548]
In the commit 10fef50bf3, I support `uv_set_process_title` for darwin.

However, When I looked at the code to fix this commit, saw the following code, I have found that there are some duplicate code. (example: `uv_hrtime`)
- darwin.c
- freebsd.c
- netbsd.c
- openbsd.c
- linux-core.c
- sunos.c

I think we should eliminate duplicate code as much as possible. Duplicate code is the bad code.

I made ​​a file called `platform.c` in the commit 1197192. And I wrote a common code of `uv_setup_args`, `uv_set_process_title`, and `uv_get_process_title`.

I think this solution is a good idea. Because other functions such as `uv_hrtime`, this solution can be written to `platform.c`.

(I think to solve the #520.)

What do you think?

**Comment by bnoordhuis** [comment]
> In the commit 10fef50, I support uv_set_process_title for darwin.

Does it actually work? I tried the sysctl() approach a while ago and it turned out that it didn't quite work (but I forgot exactly how - only on some versions of OS X or only with ps. Something like that.)

> I made ​​a file called platform.c in the commit 1197192. And I wrote a common code of uv_setup_args, uv_set_process_title, and uv_get_process_title.

It breaks the linux build and what's more, it breaks the get/set process title functionality on linux. Have a look at `src/unix/linux/linux-core.c` to find out why.

I'm not adverse against merging duplicate code but there's a reason it's been split up into several platform files. Look at the different uv_hrtime() implementations - some of those could be merged, others not so much.

**Comment by kazupon** [comment]
@bnoordhuis
Thanks for the comments.

> Does it actually work?

Once again, I tried to check the commit 10fef50 is working again on OS X 10.8.
I checked this commit is successful in libuv test.
However, I could not check this commit with output of ps.
(integrated this commit into the node)
I need to fix this commit on my OS X and some versions of OS X.

> It breaks the linux build and what's more, it breaks the get/set process title functionality on linux. Have a look at src/unix/linux/linux-core.c to find out why.

I'm sorry.
I could not understand why the linux build is broken.

> I'm not adverse against merging duplicate code but there's a reason it's been split up into several platform files. Look at the different uv_hrtime() implementations - some of those could be merged, others not so much.

I can understand there's a reason it's been split up into several files platform.
Because there is platform-specific.
I mean, platform-specific implementation, write the code to the platform file.
However, the implementation that can be common in some platforms, we should write to write file `platform.c` common functions, to call the function in the platform file.

I'll explain as an example `uv_hrtime`.

Linux, freebsd, netbsd and openbsd is the same implementation. So, these are implemented, and the implementation of a common function in `platform.c`, to call the common functions of each file in the platform.
However, in sunos and darwin, requires the implementation of their own. So, these are unique implementation of `darwin.c`, to `sunos.c`.

**Comment by bnoordhuis** [comment]
> I'm sorry. I could not understand why the linux build is broken.

Ah sorry, I missed that 1197192 is a follow-up to 745040d.

> Linux, freebsd, netbsd and openbsd is the same implementation.

Not quite. It's true for the BSDs - they all use `clock_gettime(CLOCK_MONOTONIC)` - but on Linux it's more complex, we only use CLOCK_MONOTONIC if CLOCK_BOOTTIME is not available and that's determined at run-time.

I can see the case for merging some of the BSD code but the other platforms are too different to be worth the effort.

**Comment by bnoordhuis** [comment]
No reply in 3 months, closing.
