### ISSUE TITLE
uv_listen(): default backlog

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#55]
I wish upon a star that passing a backlog of -1 or 0 to uv_listen() would pick a sane platform default, like SOMAXCONN for *NIX systems.

**Comment by ry** [comment]
I'm happy to have a default but is `SOMAXCONN` really what one wants here? We should just default to some appropriately large value like 128.

**Comment by bnoordhuis** [comment]
Hmm. SOMAXCONN=128 on linux (has been since at least 2.0.27). We should probably use a larger value: both apache and nginx default to 511 and I think the nginx docs recommend bumping it to 1024. No reason not to - nowadays, even the cheapest Dell server can handle thousands of SYN/ACKs per second.

**Comment by ry** [comment]
@bnoordhuis do you still want this?

**Comment by bnoordhuis** [comment]
Yes, but let's benchmark it first.

**Comment by bnoordhuis** [comment]
Okay, I've changed my mind: no one ever complained so let's forget about it.
