### ISSUE TITLE
uv_pipe_open and uv_pipe_init question

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#566]
Does the argument ipc (in uv_pipe_open)e has any meaning when I am using uv_pipe_open afterwards?

**Comment by saghul** [comment]
Yes, it does: https://github.com/joyent/libuv/blob/master/src/win/pipe.c#L1650 If you want to use the pipe for ipc later on, you'll need to set it on uv_pipe_init.

**Comment by bnoordhuis** [comment]
What @saghul said. Also, we have a mailing list now: http://groups.google.com/group/libuv :-)
