### ISSUE TITLE
uv_spawn: PTY support

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#573]
Add an option to uv_spawn to open a PTY. 

Example code of how to create a pty can be found in [node 0.4](https://github.com/joyent/node/blob/7fd1c08b1615b57529c1bb7ae6f9a7b16e643162/src/node_stdio.cc#L239-274) and [pty.js](https://github.com/chjj/pty.js/blob/master/src/pty.cc).

Open questions/problems:
- Do we define a separate uv_pty_t, or can we piggyback this onto uv_pipe_t?
- Typically you wouldn't want to open multiple ptys; instead you'd attach fd 0-2 all to the same pty. There currently is no room in the API for that.
- There is no way to do this on Windows. Do we make it return UV_ENOSYS, or do we just create pipes?

**Comment by Sharpie** [comment]
> There is no way to do this on Windows. Do we make it return UV_ENOSYS, or do we just create pipes?

One interesting workaround on the Windows side:

  https://github.com/rprichard/winpty

A bit clunky as it spawns a new process that tries to generate a PTY stream by scraping a hidden console window. More discussion and alternative approaches can be found on the [Cygwin mailing list](http://cygwin.com/ml/cygwin/2012-09/msg00209.html).

Maybe not a solution that is solid enough to build into libuv proper---but perhaps good enough to leave an opening for those who can live with the limitations.

**Comment by rikarends** [comment]
+1 Need this to use vanilla node for serving terminals. No binary extensions!

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
