### ISSUE TITLE
Occasional crash on threadpool

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#580]
Since the new threadpool landed I occasionally get the following crash:

https://gist.github.com/3845761

Doen't happen always, but travis seems to consistently hit it with pyuv's test suite :-S

**Comment by indutny** [comment]
@bnoordhuis looks like it's related to recent uv_async_t improvements... lets discuss it on irc later today

**Comment by saghul** [comment]
@indutny I don't think so, this used to happen after libeio was removed, but before the async change. I haven't seen it anymore in a while, howevere. @bnoordhuis did you fix anything in the threadpool which could explain this?

**Comment by piscisaureus** [comment]
@indutny 

Is it because a pointer to a closed async handle is read from the pipe? Take a look at signal.c again to see how this is dealt with:-)

Maybe we should revert in the meantime?

**Comment by bnoordhuis** [comment]
@saghul I've reverted 209abba. Can you retest with the current master?

**Comment by saghul** [comment]
Thanks @bnoordhuis. As I mentioned earlier these crashes happened before the async change, but they have disappeared already. I'll close this for the moment, we can reopen it if crashes come back.
