### ISSUE TITLE
why uv.a and not libuv.a

### ISSUE THREAD

**Issue by dvv** [joyent/libuv#586]
have i missed any reason why resulting library is named in non-standard way?

**Comment by bnoordhuis** [comment]
No particular reason. Is it bothering you in any way?

**Comment by dvv** [comment]
yes, i can't get luarocks link against it, as it simply obey convenience and inserts `-luv` into `LDFLAGS`.
can we have libuv.a, or a symlink libuv.a -> uv.a? tia

**Comment by saghul** [comment]
In pyuv I rename uv.a to libuv.a so that -luv works, I would welcome the change :-)

**Comment by bnoordhuis** [comment]
Sure. Changed in 47b2cd3.

**Comment by saghul** [comment]
Thanks Ben!

**Comment by dvv** [comment]
Thank you!

**Comment by chobie** [comment]
Thank you!
