### ISSUE TITLE
Should closing handles keep the loop alive even when unref'ed?

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#593]
I would say no, but some tests (e.g. tcp_ref2) mandate otherwise. This makes tests fail on windows.

**Comment by piscisaureus** [comment]
Note that if the answer is "yes' the common implementation for `uv__handle_ref` and `uv__handle_unref` is incorrect.

**Comment by bnoordhuis** [comment]
> Should closing handles keep the loop alive even when unref'ed?

Yes.

**Comment by piscisaureus** [comment]
Solved in 149b16f
