### ISSUE TITLE
Windows7 :  pGetQueuedCompletionStatusEx(...) stuck issue

### ISSUE THREAD

**Issue by sequoiar** [joyent/libuv#598]
a tricky issue.

when libuv uses pGetQueuedCompletionStatusEx(...) as loop's poll mechanism in windows, it shows the intermittent stuck issue. if use GetQueuedCompletionStatus(...), the issue gone.

**Comment by piscisaureus** [comment]
I never experienced this. Do you have a test case to replicate this?

**Comment by piscisaureus** [comment]
Unfortunately, no response. Feel free to reopen if you can provide more info.
