### ISSUE TITLE
why " assert failed handle->reqs_pending > 0 win/tcp.c line 1025 "

### ISSUE THREAD

**Issue by richmonkey** [joyent/libuv#599]
i have an network application that uses pyuv, i build it on windows xp(32bit) with py2exe
then run it on windows 7(64bit)

**Comment by saghul** [comment]
For the record, what version are you running?

**Comment by bnoordhuis** [comment]
Please report this at pyuv. If it turns out to be a libuv bug, @saghul will forward it to us.

**Comment by saghul** [comment]
LoL, I didn't even realize this was reported in the libuv project :-) @richmonkey please report it to pyuv, with a test case to reproduce it and if it turns out it's a libuv issue I'll deal with it, as @bnoordhuis  said.

**Comment by richmonkey** [comment]
ok  i'm debuging my application  thanks
