### ISSUE TITLE
uv_fs_event_init : Symbol not found: __ZN4Tail7OnEventEP13uv_fs_event_sPKcii

### ISSUE THREAD

**Issue by whitesheep** [joyent/libuv#607]
using node-gyp to build.
Build successful but, when I start node.js script "Symbol not found" appears

**Comment by bnoordhuis** [comment]
Not a libuv bug. The linker isn't complaining that it can't find `struct uv_fs_event_s`, it's complaining that it can't find `Tail::OnEvent::uv_fs_event_s`.

**Comment by whitesheep** [comment]
ops, my fault. Thanks.
