### ISSUE TITLE
Failure in test-hrtime

### ISSUE THREAD

**Issue by tim-smart** [joyent/libuv#61]
```
`hrtime` failed: exit code 6.
Output from process `hrtime`:
diff = 101340
Assertion failed in test/test-hrtime.c on line 34: b - a >= NANOSEC / MILLISEC
```

Ubuntu 11.04, gcc version 4.5.2

**Comment by rmustacc** [comment]
The test as written is busted. It's using uv_sleep(1) which sleeps for one microsecond. However the assert is checking that the operation took at least one millisecond. The three system calls involved hopefully don't take that long. I've put together a patch that fixes it. Sending the patch out of band.
