### ISSUE TITLE
linux: use getaddrinfo_a() if available

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#617]
getaddrinfo_a() has been in glibc since forever but other libcs (uclibc, dietlibc) don't have it. Use something like this to look it up:

``` c
// look for the lib in a few places
void *handle = dlopen("/path/to/libanl.so");

 // use versioned symbol to avoid ABI issues
void *addr = dlsym(handle, "getaddrinfo_a", "GLIBC_2.2.5");
```

**Comment by ghost** [comment]
What will happen with the dlopen check when the binary has a libc statically linked into it (e.g. musl). I suspect that loading libanl.so will also load (and use) glibc. Having two different libc's linked into a single program sounds like trouble to me. And, preferably, statically linked binaries shouldn't have dlsym() included in the first place.

I'd prefer a compile-time check, similar to autoconf AC_SEARCH_LIBS(). Should other libc's implement getaddrinfo_a() in the future, then those will be used automatically as well. Alternatively, some compile-time macro to disable the dlopen() search is fine, too.

**Comment by bnoordhuis** [comment]
> Having two different libc's linked into a single program sounds like trouble to me. 

You're probably right. We don't do configure-time checks though so that's not an option.

I'll see if I can get it to work with simple `#ifdef __GLIBC__` guards.

**Comment by bnoordhuis** [comment]
Okay, I've decided against using getaddrinfo_a().  The problem with that function is that it either spawns a thread or sends a signal.  The former is undesirable because libuv has only limited possibilities for batching lookups and we don't want to spawn a million threads, the latter because signals and libraries create headaches for the user.

**Comment by amtlib-dot-dll** [comment]
@bnoordhuis Perhaps there is some update since then? According to the [manual page](http://man7.org/linux/man-pages/man3/getaddrinfo_a.3.html) no extra signals or threads would be created when `SIGEV_NONE` is applied and only one single thread is needed for `gai_suspend()` polling, just like the sample code provided in the manual page. Thanks
