### ISSUE TITLE
fix up gyp

### ISSUE THREAD

**Issue by ry** [joyent/libuv#618]
direct_dependet_settings should be link_settings in a few places
https://gist.github.com/55f402136e3f6067707e

also removes "ldlags" ... 

cc @tootallnate @bnoordhuis

**Comment by bnoordhuis** [comment]
I couldn't get the patch to merge but I landed a more or less verbatim copy with attribution in deeec42.

**Comment by ry** [comment]
thanks ben! sorry for the shitty patch
