### ISSUE TITLE
unix uv_sleep expects ms but operates in us

### ISSUE THREAD

**Issue by rmustacc** [joyent/libuv#62]
The unix version of uv_sleep comments and arguments suggest that it should be working in milliseconds. However, the code simply calls usleep(3C). usleep(3C) is defined to operate in microseconds, not milliseconds. Depending on the desired behavior either uv_sleep should tell consumers that it expects microseconds or it should multiply the argument passed into usleep by 1000.

**Comment by bnoordhuis** [comment]
This has been fixed in 9a5b47d9.
