### ISSUE TITLE
Addition of shared libraries broke MinGW build

### ISSUE THREAD

**Issue by luislavena** [joyent/libuv#625]
Hello,

After cc36fd036606a3dec452b6e40ded41db6e5bf322 it is no longer possible to compile tests or benchmarks under Windows with GCC:

```
C:\Users\Luis\Code\joyent\libuv>make test
make: *** No rule to make target `libuv.so', needed by `test/run-tests.exe'.  Stop.
```

Even if we add the necessary changes, all the C files needs to be compiled with `BUILDING_UV_SHARED` and then tests with `USING_UV_SHARED`

I wonder when gyp will support MinGW so we can stop worrying about the makefiles?

**Comment by bnoordhuis** [comment]
> I wonder when gyp will support MinGW so we can stop worrying about the makefiles?

I wouldn't put your hopes up. By and large, the gyp people only care about the platforms they use themselves. MinGW isn't one of them.

I'll take patches for the build issue (or maybe @piscisaureus can fix it). It should be pretty straightforward:
1. Add a libuv.so target to config-mingw.mk that compiles with`CPPFLAGS+=-DBUILDING_UV_SHARED`
2. Add `-DUSING_UV_SHARED` to RUNNER_CFLAGS.

You can look at config-unix.mk for inspiration.

**Comment by vtudose** [comment]
Sorry for the mess, I accidentally referenced  the commits twice.

**Comment by saghul** [comment]
We do have a MinGW makefile now, closing.

**Comment by luislavena** [comment]
@saghul there was a MinGW makefile in the past, but it failed to build tests (that is why this was opened)

Do not have time right now to verify if that issue was sorted out after, but will during the weekend.

Can you confirm the issue mentioned above was solved?

**Comment by saghul** [comment]
That's right, it doesn't build tests, sorry about that. Last update was a year ago, so feel free to open a PR with a patch when you have the time :-)
