### ISSUE TITLE
Ability to stop asynchronous requests

### ISSUE THREAD

**Issue by denik** [joyent/libuv#630]
For example, having `int uv_getaddrinfo_stop(uv_getaddrinfo_t* req);` would be nice.

Ideally, the stop would be synchronous, like `uv_timer_stop()` with a guarantee that req is not going to be accessed by libuv after this call.

If that's hard to implement, uv_close-like asynchronous stop that causes a callback to be called with `ECANCELED` on the next loop iteration would be the next best thing.

**Comment by bnoordhuis** [comment]
Ongoing work can be found here: https://github.com/joyent/libuv/compare/uv_work_cancel

> Ideally, the stop would be synchronous, like uv_timer_stop() with a guarantee that req is not going to be accessed by libuv after this call.

The uv_work_cancel() that I've implemented does a best-effort attempt to cancel the work req but if it's executing or has already been executed, it fails and returns an error.

If it's executing, you can't interrupt it and you can't wait for it to complete either because you don't know how long it'll take.

If it's finished executing, there's not much point in cancelling it. Besides, it would complicate the user's code because now he has to deal with three types of work reqs: cancelled before work_cb, cancelled after work_cb and completed.

This way, you only have two states: cancelled before work_cb or completed.

**Comment by denik** [comment]
@bnoordhuis thanks :)

I realize that if, say, getaddrinfo() started executing, there's not much we can do other than wait for it.

However, we could make sure that uv_getaddrinfo_t\* is not touched again and could be freed now. This is what I'm after because I'm reusing the memory that uv_getaddrinfo_t occupied for other requests but as far as I understand now I have to wait for the request to complete and cannot touch this memory until that because it is referenced by a thread pool worker.

**Comment by bnoordhuis** [comment]
> However, we could make sure that uv_getaddrinfo_t\* is not touched again and could be freed now.

I don't see how that could work. If the getaddrinfo code is executing, it will want to mutate the uv_getaddrinfo_t struct later on.

There's no way to signal the getaddrinfo thread that it can no longer touch the struct unless you start using, say, per-loop hash tables. That way madness and excessive complexity lies.

**Comment by denik** [comment]
> I don't see how that could work.

Perhaps, a thread pool can copy the uv_work_t struct by value, while keeping the reference to the original (user-provided) uv_work_t structure. When the request is cancelled, that reference is set to NULL, so upon finishing the job, the workers checks that and figures out that there's nobody to deliver the result to and just continues without touching any user's data structures.

Basically, it seems like an additional indirection would allow for it. no hash tables seem necessary.

But it could be that I don't understand completely what's involved as I only read the code but not really familiar with it.

**Comment by piscisaureus** [comment]
@denik Yes, there are ways to make this work. It would even be possible to not use a uv_work_t struct at all. The current approach represents a tradeoff between performance and usablility. 

If you really need it to work like this you could write your own wrapper for uv_queue_work that does exactly this. Libuv will not.

**Comment by bnoordhuis** [comment]
> Perhaps, a thread pool can copy the uv_work_t struct by value, while keeping the reference to the original (user-provided) uv_work_t structure. When the request is cancelled, that reference is set to NULL, so upon finishing the job, the workers checks that and figures out that there's nobody to deliver the result to and just continues without touching any user's data structures.

Your suggestion is not without merit but I think it would require a fairly major overhaul of the request processing pipeline and it goes against one of libuv's core values, which is to allocate as little dynamic memory as possible.

**Comment by denik** [comment]
> it goes against one of libuv's core values, which is to allocate as little dynamic memory as possible.

I agree with this and in fact, need this to avoid using dynamic memory in my libuv-based library. In the current API where I have to wait until libuv is done with request structure I have to allocate it dynamically.

If I could just tell libuv "stop using this", like I can with libev watchers, then in some cases I could use static storage for request structure.

Anyway, talk is cheap, so I plan to try to implement it to show what I mean (Perhaps I'll discover that it makes it more complicated so it's not worth it, but perhaps I'll be able to show that it brings advantages while keeping the whole thing at least as simple as it was before).

**Comment by denik** [comment]
So I've thought more about it and although it can be possible to do so for uv_getaddrinfo_t, it seems hard to do it in a generic way. Once a thread started executed work_cb it's impossible to assume how it's going to use uv_work_t*.

For now I think uv_work_cancel is the best you can do.

In my case, I just have to allocate uv_getaddrinfo_r dynamically (and dealocate it in close_cb), but it won't make a big difference.

**Comment by bnoordhuis** [comment]
I forgot to close this issue but for the record: a generic but UNIX-only uv_cancel() landed in 52c8a86 and - for future Windows compatibility - got its API reworked in 92fb84b.
