### ISSUE TITLE
.gitignore includes *.mk

### ISSUE THREAD

**Issue by dhruvbird** [joyent/libuv#636]
This prevents the .mk files from getting added if I copy everything into a new git repo. Is this intentional?

**Comment by bnoordhuis** [comment]
Yes. The gyp build generates a bunch of *.mk files that shouldn't be versioned.

**Comment by bnoordhuis** [comment]
Then again, those files are stored in out/ now. I've updated the ignore list in df1399f.

**Comment by dhruvbird** [comment]
Thanks - makes things easier for me!
