### ISSUE TITLE
Getaddrinfo linker error on Windows (MinGW)

### ISSUE THREAD

**Issue by fillest** [joyent/libuv#641]
I use code from master (44f0fcd033), Windows 7 64bit, MinGW.
I link my application with libuv.
Gyp didn't work (`mingw32-make: Nothing to be done for 'all'`) so i just `mingw32-make` and got following errors:

```
src/libuv/libuv.a(getaddrinfo.o): In function `getaddrinfo_thread_proc':
E:\src\libuv/src/win/getaddrinfo.c:88: undefined reference to `_imp__GetAddrInfo
W@16'
src/libuv/libuv.a(getaddrinfo.o): In function `uv_process_getaddrinfo_req':
E:\src\libuv/src/win/getaddrinfo.c:213: undefined reference to `_imp__FreeAddrIn
foW@4'
```

Yes, i linked with ws2_32, psapi and iphlpapi. Yes i am sure, because when i don't link with ws2_32, i get lots of Wsa-functions linker errors

**Comment by piscisaureus** [comment]
@fillest I don't get an error.

Please read http://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html/sn-Debugging_the_Code-The_Anatomy_of_a_Good_Bug_Report.html

**Comment by fillest** [comment]
Oops, sorry, it works. I localized the problem - it was -IC:/Windows/System32
