### ISSUE TITLE
ThreadPool size?

### ISSUE THREAD

**Issue by praveend** [joyent/libuv#649]
Hi,

I was going through the documentation on threadpool using uv_queue_work. Wanted to know what is the size of the thread pool provided by libuv. Is it a fixed number of threads? or Do you increase the size of the pool based on incoming requests and accordingly cut down the number of threads when incoming requests reduce?

Thanks

Praveen

**Comment by bnoordhuis** [comment]
> Is it a fixed number of threads?

Yes, with the current HEAD of master but that's due to be addressed.

The scheme we're going with is that you have roughly as many threads as cores for CPU intensive tasks plus many (tens, maybe hundreds) threadlets for fs operations.

Those fs threadlets should almost always be blocked in system calls and will run on a reduced stack (4-16 kB instead of the default 2 MB) to save address space on 32 bits machines.

The v0.8 branch still uses libeio, which employs a fairly crude grow-on-demand scheme with hard lower and upper limits. Performance is not great - it's the main reason for rewriting the UNIX thread pool and fs implementations.

uv-win, to the best of my knowledge, uses the default Windows thread pool. @piscisaureus should be able to confirm that.

**Comment by springmeyer** [comment]
Can this now be closed after the change to unix in https://github.com/joyent/libuv/commit/1e97b4567e1717bf17316230eff6e1a7350b8034?

I'm quite interested though in details from @piscisaureus in how this currently works (or might change) on windows...

On Windows with (mapbox/tilemill) we could benefit from a way to reduce the threadpool size in fact, while on linux we tend to always make it 1.5*CPU.

**Comment by piscisaureus** [comment]
@springmeyer 

Current situation as of node v0.10.0:
- uv-unix uses a custom thread pool (libeio is no longer in the mix) with a constant number of threads (4 by default, configurable with an environment variable.)
- uv-win still uses the windows thread pool implementation which auto-scales up to 512 threads.

Future directions:
- uv-unix will probably get some form of auto-scaling.
- uv-win will cease using the windows default thread pool. Instead it will use the uv-unix implementation, or a separate implementation that's very close to the unix version. There are a couple of reasons for this:
  - The windows thread pool is smart but has a lot of overhead.
  - Libuv has an API for cancelling thread pool work but windows doesn't support this.
  - We need additional flexibility to make file system operations faster (e.g. it'd be great to be able to make one thread pool operation wait for another one to complete, without relying on synchronization with the main thread.)

**Comment by springmeyer** [comment]
@piscisaureus - excited about these future directions. In terms of node v0.10.x now - does `UV_THREADPOOL_SIZE` need to be set in the shell before node is started or can it be set on nodes `process.env`?

**Comment by bnoordhuis** [comment]
In theory, setting `process.env.UV_THREADPOOL_SIZE = 42` could work if you do it really early on, before any file or DNS operations. I wouldn't rely on it though.

**Comment by springmeyer** [comment]
@bnoordhuis - okay, thanks, sounds reasonable. Our app [TileMill](mapbox.com/tilemill) provides a UI for long running export jobs in separate node processes and what I'll be testing is when/where exactly I'll need to set `UV_THREADPOOL_SIZE` to allow the user to control concurrency.

**Comment by adrai** [comment]
Can you approximately say when (version or time) the auto-scaling feature is planned?

**Comment by bnoordhuis** [comment]
> Can you approximately say when (version or time) the auto-scaling feature is planned?

Probably v0.14 (what will probably become v1.0.)  It doesn't look like I'll have time to work on it this release cycle.

**Comment by kvanbere** [comment]
Punting for the ability to alter the number of threads at runtime while inside the threadpool for consideration when someone gets around to this task. It could work like this;
- A number of threads to kill is recorded. When a thread checks for new work and this is >0, it kills itself and reduces the count by 1. This means scaling the pool down doesn't need to stop-the-world.

**Comment by adrai** [comment]
@bnoordhuis still v0.14 (v1.0)?

**Comment by bnoordhuis** [comment]
I'm not working on libuv anymore, you'll have to ask @indutny or @saghul.

**Comment by adrai** [comment]
@indutny or @saghul any news on this?

**Comment by indutny** [comment]
No work has been done on it yet, and our priorities are on other things right now.

**Comment by txdv** [comment]
What other things?

**Comment by indutny** [comment]
Stabilizing stuff before 0.12 release.

**Comment by saghul** [comment]
We are using the same threadpool on Unix and Windows now: https://github.com/joyent/libuv/commit/8d11aacb79472009189c35e8953d0fa316bfd202

It's not sure smart yet but at least we have consistent behavior across platforms. Size can still be controlled with the environment variable.

I'm going to close this now, lets treat each potential improvement as a separate issue.

**Comment by springmeyer** [comment]
Thanks for the followup @saghul!

**Comment by JoshuaWise** [comment]
> The scheme we're going with is that you have roughly as many threads as cores for CPU intensive tasks plus many (tens, maybe hundreds) threadlets for fs operations.

I wasn't aware of the different between "threads" and "threadlets".

* Which of these does `UV_THREADPOOL_SIZE` set?
* does `uv_queue_work()` schedule work to be done in a regular thread or in a "threadlet"?
