### ISSUE TITLE
Inconsistent behavior between handle_inits

### ISSUE THREAD

**Issue by kristrev** [joyent/libuv#655]
Hi,

I am not sure if this is intentional or not, but here goes. When working on an application today, I noticed that uv_poll_init and uv_udp_init behave differently. Udp_init does a memset(0), while uv_poll_init does not do this. It is not a major thing, but I guess it has potential to cause some confusion.

-Kristian

**Comment by bnoordhuis** [comment]
Fixed in 273cecc. Thanks for pointing it out.
