### ISSUE TITLE
getaddrinfo_concurrent test fail

### ISSUE THREAD

**Issue by kanongil** [joyent/libuv#658]
I have an issue in node.js where a dns.lookup erroneously returns ENOENT. Trying to trace this issue I looked at libuv, where I found that I could get a test to fail simply by changing the lookup address from 'localhost'  to something else, eg. 'nodejs.org':

```
=============================================================
[%  61|+  96|-   0]: getaddrinfo_concurrent
`getaddrinfo_concurrent` failed: timeout
Output from process `getaddrinfo_concurrent`: (no output)
=============================================================
[% 100|+ 156|-   1]: Done.
```

It makes sense that it is the concurrent test that fails since I observed that my original issue was failing on the second lookup of the same domain.

Please note that this behavior does not manifest on all setups. I have only observed it to fail on a 'CentOS 6.3'-based system, while everything works as expected on an 'Ubuntu 12.04' system.

**Comment by bnoordhuis** [comment]
Sorry, I'm not sure what the issue is. You mean node returns ENOENT for a hostname that in reality is resolvable?

**Comment by kanongil** [comment]
That was my original issue, yes. And further, it had actually already successfully resolved it, but on the second try it fails with ENOENT (after a short timeout).

Since it was not immediately possible to replicate in isolation, I dug deeper and found that I could force libuv to fail a test case.

**Comment by kanongil** [comment]
Further debugging revealed that it was caused by a local DNS configuration issue. Please ignore.
