### ISSUE TITLE
"Windows: getaddrinfo support" breaks linux build

### ISSUE THREAD

**Issue by nelsonsilva** [joyent/libuv#66]
I have to revert to HEAD^ and patch 

--- /tmp/iF6ktf_uv-unix.c
+++ /home/nfgs/Programacao/Javascript/libuv/uv-unix.c
@@ -1294,7 +1294,7 @@
 int uv_ares_init_options(ares_channel *channelptr,
                         struct ares_options *options,
                         int optmask) {
-  rc = ares_init_options(channelptr, options, optmask);
-  int rc = ares_init_options(channelptr, options, optmask);
  return rc;
  }

to be able to build in Ubuntu 10.04 64 bit.

**Comment by ry** [comment]
this was fixed in 8801925b41bccadbf87c02d41df5a402d5848f2f
