### ISSUE TITLE
build for android

### ISSUE THREAD

**Issue by dvv** [joyent/libuv#661]
Hi!

[Here](http://busybox.net/~dvv/uv-android.patch) is the patch to make libuv build under android-ndk (ver 14).
Please, consider applying.

TIA,
--Vladimir

**Comment by txdv** [comment]
I see no patch

**Comment by dvv** [comment]
"Here" is a link.

http://busybox.net/~dvv/uv-android.patch

The most irritating is that ares rely on arpa/nameser[_compat].h which are pruned from android-ndk.
An option would be to hold these somewhere under the uv tree

**Comment by saghul** [comment]
But ares is no longer part of libuv, so I guess that belongs to some new project, or a contribution to c-ares? IIRC ares master is supposed to build on Android.

**Comment by dvv** [comment]
what's ares master? this one? https://github.com/bagder/c-ares

**Comment by saghul** [comment]
Yes, that one. Go through the changelog and commits, I recall seeing some
Android related stuff there.

On Friday, December 21, 2012, Vladimir Dronnikov wrote:

> what's ares master? this one? https://github.com/bagder/c-ares
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/661#issuecomment-11612489.

## 

/Saúl
http://saghul.net | http://sipdoc.net

**Comment by dvv** [comment]
oh, right.
but libuv now depends on advanced pthread stuff like `pthread_condattr_setclock` and it's certainly missing in android-ndk.
seems full stop here...

**Comment by txdv** [comment]
#ifdef PTHREAD ?
Just define all the thread stuff out

**Comment by dvv** [comment]
How so?

**Comment by bnoordhuis** [comment]
I can't take the patch, it needs to be against the current master. I think I'm open to patches that conditionally compile out the threading stuff but in the case of Android, I suggest you complain to upstream - there is no reason for GOOG to not add e.g. pthread_condattr_setclock(), the kernel supports it just fine.
