### ISSUE TITLE
signals: uv.h comments out of date?

### ISSUE THREAD

**Issue by nikhilm** [joyent/libuv#668]
It seems signals support has progressed, but the comments in uv.h haven't been updated. Possible problem spots:
- Comment before struct uv_signal_s - TODO about only default event loop supporting signals
- Comment before uv_signal_init - Windows no-ops, but the windows functions seem to do something since commit c4dbb60cffbaba, and the comments in uv_signal_s have been updated about it.

**Comment by bnoordhuis** [comment]
Fixed in 3164f1e, thanks.
