### ISSUE TITLE
unix: Loop doesn't iterate when a signal is received

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#671]
Before libev was removed, if a signal was received when the loop was blocked for io, the signal would "wakeup" the loop (the poll would be interrupted with EINTR as far as I see) and another loop iteration would begin.

This is no longer the case and I kind of relied on it for interfacing with Python signal handlers in the following way:
- Have a internal prepare handle
- Call a specific Python API function which checks is there are pending signals and executes their respective callbacks

I know we have uv_signal_t now, but that means that the standard Python signal module can't be used together with pyuv. I'm ok with that but I'd like to know if this is a bug or a feature :-)

I played around a bit with the code by just doing `return` here: https://github.com/joyent/libuv/blob/master/src/unix/kqueue.c#L152 which is apparently what libev did, but I'm not sure if that would open a can of worms.

/cc @bnoordhuis

**Comment by saghul** [comment]
Hmm, after some more testing things look worse than I expected :-S In Python, when Ctrl-C is pressed KeyboardIterrupt is raised unless a handler for SIGINT is registered with the builtin signal module. I'm unable to get this behavior working with uv_signal_t handles, becuase libuv is handling the signal. If possible it would be nice to have the old behavior, where the loop would iterate after being interrupted by a signal back :-)

**Comment by bnoordhuis** [comment]
The current behavior (retry on EINTR) is intentional; I've always considered the libev behavior borderline buggy.

The reason is that prepare and idle handles are only supposed to run when the event loop is making some kind of forward progress (timeout, I/O pending, etc.). Not retrying on EINTR means they also run when nothing actually happened.

What solutions are possible that don't involve reverting to the old behavior?

**Comment by saghul** [comment]
I see. I supposed there was some reason behind it since the code didn't look arbitrary.

I'm not sure what can be done to achieve the same behavior (in pyuv) that doesn't involve reverting to the old behavior. If timeout is 0 then the poll will return on EINTR, but there are many cases where timeout will be -1 or some other value, so it's very easy to run into the problem. Basically I'd need to be somehow notified when a signal is received so that I can call the Python API function to process it. If you have some other idea I'm all ears :-)

I sent a pull request reverting libuv to the old behavior and tests seem to pass. Do you have practical cases where this would be a problem?

**Comment by saghul** [comment]
I'm not sure if anybody would use it (other than me), but maybe it could be made configurable? By using a loop flag:

```
if (loop->flags & UV_ITERATE_ON_EINTR)
    return;
```

**Comment by denik** [comment]
In gevent, I also rely on this feature in libev to work with Python signals properly and I also use a prepare watcher for that. It is crucial that the event loop does not silently swallows EINTRs to be able to make Python bindings that do not break normal Python behaviour.

@saghul, I'd use this flag, if there are no other options. However, this means prepare and idle and check watchers have different semantics depending on a flag, which might break libuv addons that depend on this.

What's needed is a way to run user-provided callback on EINTR, it does not have to be a prepare watcher. Could be a yet another watcher type or eintr_cb member of uv_loop.

> The reason is that prepare and idle handles are only supposed to run when the event loop is making some kind of
> forward progress (timeout, I/O pending, etc.). Not retrying on EINTR means they also run when nothing actually 
> happened.

That's not true, signal happened. If you're interested in it, that's some kind of progress.

**Comment by saghul** [comment]
Thanks for commenting, @denik! I actually relied on this heavily for my uvent experiment ;-)

My intention with that flag is to try to please everyone, but (maybe due to my lack of deep knowledge) I find the old behavior reasonable. I also thought of a eintr_cb of some sort, but it looked a bit to specific.

Btw, how does Windows react to Ctrl-C if the loop is busy polling @piscisaureus ?

**Comment by denik** [comment]
BTW, @saghul, Recent Python also has [signal.set_wakup_fd](http://docs.python.org/2/library/signal.html#signal.set_wakeup_fd) function. Perhaps it could be helpful.

**Comment by saghul** [comment]
That would indeed be an option. Use a pipe and use a Poll handle for readability and do the check on its callback. I'd go for using PySignal_SetWakeupFd, however it should only be called from the main thread :-S Performing another loop iteration still looks like the most appealing solution to me. I wonder if others implementing libuv bindings have run into this.

**Comment by bnoordhuis** [comment]
> Do you have practical cases where this would be a problem?

Yes. I have had at least two node.js add-on authors complain to me about the old behavior.

Another issue is performance: when your application receives lots of signals, it keeps doing the prepare/enter/check dance.

**Comment by bnoordhuis** [comment]
> That's not true, signal happened. If you're interested in it, that's some kind of progress.

Not from the perspective of the event loop.  _If_ you were interested, you would have registered a uv_signal_t watcher.

**Comment by saghul** [comment]
> Yes. I have had at least two node.js add-on authors complain to me about the old behavior.
> 
> Another issue is performance: when your application receives lots of signals, it keeps doing the prepare/enter/check dance.

Does the flags approach (or something similar) look reasonable to you?

**Comment by bnoordhuis** [comment]
> Does the flags approach (or something similar) look reasonable to you?

It won't win beauty pageants but I guess I could learn to live with it.

There's something I don't quite get though: python is embeddable, right? That suggests it must have means to deal with an embedder that handles signals itself, i.e. there must be some mechanism to integrate the two.

I guess @denik already pointed out the solution for 2.6 and up.

**Comment by saghul** [comment]
> There's something I don't quite get though: python is embeddable, right? That suggests it must have means to deal with an embedder that handles signals itself, i.e. there must be some mechanism to integrate the two.
> 
> I guess @denik already pointed out the solution for 2.6 and up.

Well, yes and no. I would need to creare a pipe, use a poll handle with the read end on each loop and register the writable end with the Python internal API as the signal handling fd, which could also break other things (only one can be registered at a time, and the user can change it). The prepare handle solution which used to work is much simpler and probably also works on Windows (I don't have a Windows machine with me right now to test it though).

I'll update my pull request adding a flag for this, lets see if it doesn't look too bad :-)

**Comment by txdv** [comment]
I use libuv 36b1e1a57c59ff835177e26f37742f5fb49cb353.
Somehow mono manages to catch ctrl+c immediately and terminate. I also use a watcher to catch terminal resizes.

**Comment by saghul** [comment]
Is that before or after libev removal?

On Monday, December 31, 2012, Andrius Bentkus wrote:

> I use libuv 36b1e1ahttps://github.com/joyent/libuv/commit/36b1e1a57c59ff835177e26f37742f5fb49cb353
> .
> Somehow mono manages to catch ctrl+c immediately and terminate. I also use
> a watcher to catch terminal resizes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/671#issuecomment-11773969.

## 

/Saúl
http://saghul.net | http://sipdoc.net

**Comment by saghul** [comment]
Ok, after sleeping over it, here is a way to get it working using the wakeup fd thing and a pair of connected sockets (so that it works on Windows): https://gist.github.com/4418548

There is one caveat, though: the wakeup fd thing works by writing a null byte to the given fd, which needs to be consumed, but Python will run the signal handlers _before_ consuming the data, because it will check for signals when it goes from C to Python land, so there will be another loop wakeup because that file descriptor is still readable.

Anyway, I plan to move this to C and implement a `signal_wakeup_fd` method in Loop which would read from that fd and check for Python signals in C, thus removing one of the wakeups. But that's for next year :-)

**Comment by saghul** [comment]
So, here is how I finally got it working on pyuv, FWIW: https://github.com/saghul/pyuv/commit/3b43285bc66883c4466cb4413de80842dce98621 it's a pseudo-handle which uses a uv_poll_t handle to call the Python signal processing function. Here is an example: https://github.com/saghul/pyuv/commit/6e71bf7da350c6ced6bdc4375ed6ba8cd2a9d2f2

Thanks for all the comments, I hope this can also help others.
