### ISSUE TITLE
timer started in handle's callback does not work properly

### ISSUE THREAD

**Issue by zenkj** [joyent/libuv#678]
in uv_timer_start, the timeout value relies on loop->time. but in the callback of a handler(such as uv_tcp_t), the loop->time is not correct(in uv_run2, it's updated in uv_update_time, but the callback is called in uv__io_poll, after waiting for some timeout time). Is it proper to call uv_update_time in uv__io_poll?

**Comment by bnoordhuis** [comment]
Thanks for the bug report and the clear analysis, it's fixed in 2f55353.

@piscisaureus Does it affect uv-win too? I looked at src/win/core.c but I couldn't tell.

**Comment by piscisaureus** [comment]
@bnoordhuis No, uv-win updates the current time both before and after the poll function. (Although it only updates before if there are any timers.)
