### ISSUE TITLE
unix: build failed on OS X 10.8.2

### ISSUE THREAD

**Issue by messense** [joyent/libuv#679]
This version of libuv broken when compile it on OS X 10.8.2 using clang 4.1 or gcc 4.2.1.

The cause is that the commit [edd10071eb86cdc741c6652a38eff0b4d6be561e](https://github.com/joyent/libuv/commit/edd10071eb86cdc741c6652a38eff0b4d6be561e) added a include of header file `features.h` in `libuv/src/unix/async.c`, but it seems that the `features.h` does not exist on OS X 10.8.2.

**Comment by richardhundt** [comment]
same problem with OS X 10.7.5

**Comment by bnoordhuis** [comment]
Ah, seems I introduced a GNU-ism. I'll fix it.

**Comment by bnoordhuis** [comment]
Thanks for the bug report. It's fixed in cb3c448.
