### ISSUE TITLE
Prevent uv_poll_t from being used more than once for the same fd?

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#680]
According to the description in uv.h it's not safe to use more than one uv_poll_t handle for a given fd. IIRC this limitation comes from the Windows side of things.

I can live with this, but right now the unix version asserts (https://github.com/saghul/pyuv/issues/54). A quick inspection shows that only one uv__io_t will be stored per fd here: https://github.com/joyent/libuv/blob/master/src/unix/core.c#L618 but if later a second one is added for the same fd it won't be stored. The when the second one is stopped: https://github.com/joyent/libuv/blob/master/src/unix/core.c#L644 the assert will blow up.

It would be nice if uv_poll_init\* would return an error if there is another poll handle already created for the given fd.

**Comment by bnoordhuis** [comment]
> It would be nice if uv_poll_init\* would return an error if there is another poll handle already created for the given fd.

I don't know. That means maintaining an (expensive) on-heap hash table of file descriptors.

**Comment by saghul** [comment]
Not sure about Windows, but how about making uv__io_start return an int and return -1 if loop->watchers[w->fd] != NULL && loop->watchers[w->fd] != w ?

**Comment by bnoordhuis** [comment]
That works but only for uv_poll_start, not uv_poll_init. Which is okay, I guess?

**Comment by saghul** [comment]
Well, I'd rather fail early :-) I just ran into this situation: I'm monkeypatching a Python library which uses libev and uses 2 io handles for a given fd, one for the read event and another one for the write event. I can/need to hack around it, but ideally it would be nice to have it fixed (in libuv), which can mean 2 things:
- Try to bring back the old behavior, that is, allow multiple poll handles per fd
- Completely forbid it, by failing in uv_poll_init, failing in start would be a bit unexpected IMHO

I don't know what the problems in Windows were, maybe @piscisaureus can clarify, but I would personally be ok if multiple poll handles work fine in Windows > XP/2k3.

**Comment by saghul** [comment]
After the discussion on IRC looks to me that fixing it to fail early can be tricky or come at a high cost (for libuv). I'll probably handle this in pyuv by keeping a hash table with the fds. There will probably be a performance impact, but I'll see how to cross the river once I get there ;-)

Before I close this, @piscisaureus is it ok to have 2 poll handles for the same fd (well, SOCKET thingy) on _different_ loops?

**Comment by piscisaureus** [comment]
@saghul I don't think it works in different loops but I have not tested exhaustively.

**Comment by saghul** [comment]
Thanks, @piscisaureus!
