### ISSUE TITLE
Fix `all` target dependency on Darwin (OSX)

### ISSUE THREAD

**Issue by kavu** [joyent/libuv#681]
Hi!

During the creation of libuv Homrbrew formula (mxcl/homebrew#16867) I faced a problem that `make all` building `libuv.a` on Darwin (OSX), despite that in `conig-unix.mk` we explicitly define $(SOEXT) https://github.com/joyent/libuv/blob/master/config-unix.mk#L74. 

So, I purpose to change `all: libuv.a` in Makefile (https://github.com/joyent/libuv/blob/master/Makefile#L44) to `all: libuv.$(SOEXT)` to build proper libs on all platforms.

I can submit this tiny patch if you want.

**Comment by bnoordhuis** [comment]
No can do, the default target needs to remain an archive file. Maybe I'm misunderstanding you, but why don't you build `make libuv.so` (or libuv.dylib) instead of `make all`?

**Comment by kavu** [comment]
Oh! Damn, yeah, I can, you understood correctly. Thank you!  

It's my mistake. I am really sorry for bothering you with this "bug".

BTW, `make clean` doesn't `rm` *.dylib. It's surely not a bug, just an observation.

## 

Max Riveiro

**Comment by bnoordhuis** [comment]
> BTW, `make clean` doesn't `rm` *.dylib. It's surely not a bug, just an observation.

Ah, right you are. Fixed in 9eedd32, thanks.
