### ISSUE TITLE
unix, windows: rename uv_run2 to uv_run, deprecate/remove others

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#683]
Remove `uv_run(uv_loop_t*)` and `uv_run_once(uv_loop_t*)`, then rename uv_run2 to uv_run and make that the sole entry point. Less is more.

/cc @piscisaureus

**Comment by saghul** [comment]
FWIW, uv_run_once is already gone.

**Comment by piscisaureus** [comment]
@bnoordhuis @saghul +1
