### ISSUE TITLE
windows: fix libcurl example

### ISSUE THREAD

**Issue by clemensg** [joyent/libuv#695]
Hi, I'd like to fix the example for how to use libuv with libcurl:
This was in a tutorial: `curl_multi_socket_action(curl_handle, req->io_watcher.fd, flags, &running_handles);` but did not compile, because of the changed `uv_poll_s`.
I tried to exchange the `io_watcher.fd` part with just `socket` but after that, it crashed in `uv_poll_init_socket` during `uv__handle_init`. So I guess my modification is wrong: `curl_multi_socket_action(curl_handle, req->socket, flags, &running_handles);`
(btw: req is a `uv_poll_t*`)

Oh, and I saw in the commit history that just before, the author of the example wrote `req->fd`. 

It would be great if somebody could give me a hint on how to adapt the example the right way. Especially on how to access the file descriptor without crashing on Windows. Is there something I forgot, which has to be done, in order to access req->socket ?

Here is the example code, which needs to be fixed:
https://github.com/nikhilm/uvbook/blob/master/code/uvwget/main.c

And here the said tutorial (if you are interested): http://nikhilm.github.com/uvbook/utilities.html#external-i-o-with-polling

Hopefully, someone can shed some light on it. Thank you.

**Comment by bnoordhuis** [comment]
Can you file this at https://github.com/nikhilm/uvbook/issues ? This is the tracker for library issues, not the book.
