### ISSUE TITLE
Inconsistent error codes.

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#696]
This is one big issue.
I have seen error code being different all over the place.
The error codes returned in windows code are different from the once returned in the unix code.

I will use this issue to address the issues with the error codes of multiple functions.
### setting the error

There are two ways to set the error
1. uv__set_sys_error
2. uv__set_artificial_error

sys_error uses the system error defines, like WSAEFAULT on windows, and EFAULT on unix. artificial_error uses all the UV_\* error code defines like UV_EFAULT.
I have talked to @bnoordhuis and he said that uv__set_artificial_error should be used if possible.
### Common code?

Another thing that I wanted to ask you guys is how to deal with common error code handling.
all the uv_tcp functions have common function argument checking code https://github.com/joyent/libuv/blob/master/src/uv-common.c#L245-L248.
This seems reasonable to me, but all the other functions lack this.
I think we should add all functions to uv-common and make the code in there check for different behaviour. 

I'm willing to add the patches, but give me your opinions on all the stuff.

**Comment by txdv** [comment]
uv_timer_start:

unix: https://github.com/joyent/libuv/blob/master/src/unix/timer.c#L53-L54
win: https://github.com/joyent/libuv/blob/master/src/win/timer.c#L88-L89

the unix code does some assertions on timeout and repeat to be > 0, windows does nothing.
I think the code should check if repeat is < 0 and return an EINVAL as an error code, what do you think?

**Comment by txdv** [comment]
uv_udp_recv_start:

unix: https://github.com/joyent/libuv/blob/master/src/unix/udp.c#L668-L671
win: https://github.com/joyent/libuv/blob/master/src/win/udp.c#L344

unix checks if the alloc_cb and read_cb are not null, otherwise it will return EINVAL.

In this commit https://github.com/txdv/libuv/commit/2877d513fb0541c1af9873b479cdf5f3781a637c I have rewritten all the uv_udp_\* functions to have a common wrapper in uv-common.c, so that they would have common argument checking, like this: https://github.com/txdv/libuv/blob/2877d513fb0541c1af9873b479cdf5f3781a637c/src/uv-common.c#L291-L299

I would like to hear a few comments on this proposal.

**Comment by piscisaureus** [comment]
So generally we've been on the position that if people pass in wrong parameters (e.g. passing NULL for a callback when that is not allowed) libuv should fail early and assert. Why do you think this is better?

**Comment by txdv** [comment]
Because libuv on unix does something else compared to libuv on win, I think this is just inconsistent behavior.

The uv_tcp_\* functions check for the correct handle or arguments in general, all the other functions do not check the handles and/or arguments, or do it only partially, depending on the platform. IMO if you want to iron out the API on all platforms, this should be an issue. libuv should be a library to rule all the platforms.

**Comment by bnoordhuis** [comment]
I agree that argument checking could be more consistent between uv-win and uv-unix. My thinking was to have all library entry points in shared code that first checks the arguments and then dispatches to the platform-specific implementation (e.g. uv_tcp_connect -> uv__tcp_connect).

We could have a CHECK() macro that expands to assert() in debug builds and an `if (cond) return err` in release builds.

Not a high priority issue but a nice to have.

**Comment by saghul** [comment]
Does this (error handling) still apply after the errno refactor? Looks to me like error vs asserts could be a different discussion.
