### ISSUE TITLE
Document how to use uv_fs_stat/uv_fs_fstat

### ISSUE THREAD

**Issue by Sh4rK** [joyent/libuv#704]
It should be documented that in the callback of an `uv_fs_stat`/`uv_fs_fstat` call `req->ptr` points to an `uv_statbuf_t` struct, which should be used instead of `req.stat` or `req.statbuf`.

**Comment by bnoordhuis** [comment]
@piscisaureus We might as well promote req.statbuf to public status. Thoughts?

**Comment by Sh4rK** [comment]
Currently `req.statbuf` doesn't exist on Windows, so simply "promoting" it wouldn't work.

**Comment by bnoordhuis** [comment]
It's called req.stat but that's trivial to change.

**Comment by piscisaureus** [comment]
I agree about promoting statbuf.

**Comment by bnoordhuis** [comment]
@piscisaureus Can you check bnoordhuis/libuv@1519114? I think I caught all references to req.stat but I don't have a cross-compiler installed on this machine to verify it with.

**Comment by piscisaureus** [comment]
lgtm & wfm.

Also +much for making uv_statbuf_t official!

**Comment by bnoordhuis** [comment]
Thanks, landed in da71649.
