### ISSUE TITLE
Unix: Writing permissions for GRP and OTH do not seem to work in uv_fs_mkdir and uv_fs_open

### ISSUE THREAD

**Issue by csaoh** [joyent/libuv#707]
``` php
uv_fs_mkdir(loop, &mkdir_req, "TESTDIR", 0777, mkdir_cb);
```

results in

``` bash
drwxr-xr-x    2 andrey  staff      68 12 fév 15:43 TESTDIR
```

and

``` php
uv_fs_open(loop, &open_req1, "TESTFILE2", O_WRONLY | O_CREAT, 0222, NULL);
```

results in

``` bash
--w-------    1 andrey  staff       0 12 fév 15:43 TESTFILE2
```

uv_fs_chmod works fine though. Same for the other permissions (e.g, 755 results in -rwxr-xr-x and such)

**Comment by bnoordhuis** [comment]
That's because of your umask. Libuv doesn't zero it before applying the operation because there is no way to do that in a thread-safe manner on most platforms, it's a per-process setting.
