### ISSUE TITLE
src/ and include/ directories

### ISSUE THREAD

**Issue by ry** [joyent/libuv#71]
Please reorganize the project tree so that `ares.h` and `uv.h` are in include/ and the source files are in `src/`. Patch should fix build systems on all platforms.

**Comment by ry** [comment]
wait until the multiplicity patch is landed.

**Comment by ry** [comment]
not waiting for multiplicity.

@piscisaureus can you please review http://nodejs.org/0001-Fixes-71.-src-and-include-directories.patch

**Comment by ry** [comment]
also here https://github.com/joyent/libuv/tree/reorg

**Comment by piscisaureus** [comment]
Sorry - this is unreviewable. Can you explain to me what you have done?

**Comment by ry** [comment]
i've moved the public headers into a directory `include` and source code into `src` and updated the `config-unix.mk`, `config-mingw.mk`, and `Makefile`

**Comment by piscisaureus** [comment]
Okay lgtm.
I will make the necessary modifications to the msvc projects.

**Comment by ry** [comment]
complete in 81bb15feed871a3f7fc91ce608b378ce0a6f86bc
