### ISSUE TITLE
Failing tests on Windows8.

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#711]
I have some tests failing on windows:

```
=============================================================
[%   8|+  15|-   0]: pipe_connect_to_file
`pipe_connect_to_file` failed: exit code 3
Output from process `pipe_connect_to_file`:
Assertion failed in test\test-pipe-connect-error.c on line 56: uv_last_error(uv_
default_loop()).code == UV_ENOTSOCK || uv_last_error(uv_default_loop()).code ==
UV_ECONNREFUSED
=============================================================
[%  76|+ 139|-   1]: fs_file_loop
`fs_file_loop` failed: exit code 3
Output from process `fs_file_loop`:
Assertion failed in test\test-fs.c on line 529: uv_last_error(loop).code == UV_E
LOOP
=============================================================
[%  86|+ 156|-   2]: fs_event_watch_file_twice
`fs_event_watch_file_twice` failed: exit code 3
Output from process `fs_event_watch_file_twice`:
Assertion failed in test\test-fs-event.c on line 255: 0 == uv_fs_event_init(loop
, watchers + 0, path, fail_cb, 0)
=============================================================
[%  91|+ 163|-   3]: fs_readdir_file
`fs_readdir_file` failed: exit code 3
Output from process `fs_readdir_file`:
Assertion failed in test\test-fs.c on line 1662: uv_last_error(loop).code == UV_
ENOTDIR
=============================================================
[%  94|+ 168|-   4]: threadpool_cancel_getaddrinfo
`threadpool_cancel_getaddrinfo` failed: exit code 3
Output from process `threadpool_cancel_getaddrinfo`:
Assertion failed in test\test-threadpool-cancel.c on line 90: 0 == uv_cancel((uv
_req_t*) req)
=============================================================
[%  95|+ 168|-   5]: threadpool_cancel_work
`threadpool_cancel_work` failed: exit code 3
Output from process `threadpool_cancel_work`:
Assertion failed in test\test-threadpool-cancel.c on line 90: 0 == uv_cancel((uv
_req_t*) req)
=============================================================
[%  95|+ 168|-   6]: threadpool_cancel_fs
`threadpool_cancel_fs` failed: exit code 3
Output from process `threadpool_cancel_fs`:
Assertion failed in test\test-threadpool-cancel.c on line 90: 0 == uv_cancel((uv
_req_t*) req)
=============================================================
[%  96|+ 168|-   7]: threadpool_cancel_single
`threadpool_cancel_single` failed: exit code 1
Output from process `threadpool_cancel_single`:
Failed to cancel a work req in 5,000 iterations, giving up.
=============================================================
[%  99|+ 173|-   8]: dlerror
`dlerror` failed: exit code 3
Output from process `dlerror`:
Assertion failed in test\test-dlerror.c on line 48: strstr(msg, dlerror_desc) !=
 NULL
=============================================================
[% 100|+ 173|-   9]: Done.
```

I have left the stats out.

**Comment by schlamar** [comment]
I'm seeing the following errors, too:
- fs_file_loop
- threadpool_cancel_getaddrinfo
- threadpool_cancel_work
- threadpool_cancel_fs
- threadpool_cancel_single
- dlerror

**Comment by bnoordhuis** [comment]
The threadpool_cancel_\* tests are expected to fail, they're testing functionality that hasn't been implemented yet in uv-win. The other two should pass, I think.

**Comment by schlamar** [comment]
And loop_stop is failing occasionally:

```
>Release\run-tests.exe loop_stop

`loop_stop` failed: exit code 3
Output from process `loop_stop`:
Assertion failed in test\test-loop-stop.c on line 65: prepare_called == 3
=============================================================
```

See the issue on pyuv for more details: https://github.com/saghul/pyuv/issues/85

**Comment by schlamar** [comment]
My errors are on Windows 7, BTW.

**Comment by ivanassen** [comment]
I'm seeing failing 
-  loop_stop
-  timer_huge_timeout
- timer_huge_repeat
- fs_file_loop
- fs_symlink_dir
  ...and the four threadpool_cancel_*

Also, in run-benchmarks:
- tcp_multi_accept{2,4,8} fail, assert on benchmark-multi-accept.c line 123
- async{2,4,8} fail with timeout (but async1 passes)
- async_pummel_{4,8} fail with timeout
- spawn fails with timeout
- thread_create fails with timeout
  A bunch of run-benchmarks.exe processes remain listed in Task Manager, and consume CPU.

Windows 7, release x64 EXE.

**Comment by ksubox** [comment]
I confirm same issues, especially with async_pummel.
When I test in virtual machine with 2 cores async_pummel_1 works well, but async_pummel_2 takes loooong time, so I added uv_sleep(0) after uv_async_send(handle) and it started work fast, but  async_pummel_[48] work veeery slow. I hope this symptoms will help.

Windows 8, mingw gcc 4.8.1 x64

**Comment by piscisaureus** [comment]
loop_stop is expected to fail in v0.10 but not master. The threadpool_cancel tests always fail for the moment.

The others are real issues. Unfortunately I'm extremely busy with many different things atm, and I would be very grateful if one of you could dig into the the failing tests and see what's going on.

My ususal strategy is to pick a single failing test and return it outside of the test harness. The way to do this (for tests that require no helpers atleast) is by running `run-tests.exe loop_stop loop_stop`. Subsequently I'd set a breakpoint on the failing assert and figure out what's going on. Fix the bug or test, rinse, repeat with another failure.

**Comment by schlamar** [comment]
This one is new

```
`tcp_close_accept` failed: exit code 3
Output from process `tcp_close_accept`:
Assertion failed in test\test-tcp-close-accept.c on line 102: 0 == uv_read_start((uv_stream_t*) &tcp_check, alloc_cb, read_cb)
```

**Comment by saghul** [comment]
I'm going to close this since many of the failures have already been fixed in v1.x. Please open a new issue with fresh failures if need be.
