### ISSUE TITLE
uv_find_ares_handle should use rbtree

### ISSUE THREAD

**Issue by ry** [joyent/libuv#72]
I believe the list can grow large if one is doing many concurrent queries. If that's the case the current linked-list implementation is not acceptable. I will do a test once the unix binding is done to see how many sockets are normally in use. If it does not grow much then there's nothing to worry about.

This issue corresponds to this TODO:
https://github.com/joyent/libuv/blob/fa514948fc4880f5918ae0f4244345142a761fe5/uv-win.c#L1810

Please wait for unix implementation to be complete.

**Comment by bnoordhuis** [comment]
Fixed in dfda500 with some finishing touches in 87151c8.
