### ISSUE TITLE
Don't use Python unconditionally from PATH on Windows build

### ISSUE THREAD

**Issue by schlamar** [joyent/libuv#723]
There are two problematic cases if Python is directly executed in the `vcbuild.bat` without any additionally check.
- Python is not in PATH at all (default setup)
- Python 3 is in PATH

As solution for these issues I would suggest the following workflow
1. Allow the user to set the executable directly by command line argument / environment variable. If not set: 
2. Look for `%SYSTEMDRIVE%\Python27\python.exe`. If not exists:
3. Look for `%SYSTEMDRIVE%\Python26\python.exe`. If not exists:
4. Try with `python`

Step 2-4 should cover almost every setup variation whilst the current workflow doesn't even support a default Python installation.

If someone can concretize how step 1 should look like I could implement this proposal.

**Comment by saghul** [comment]
As for 1, what about looking for the PYTHON env variable? Moreover, how about folding all cases into: use whatever the PYTHON env variable points to, else try with 'python'.

**Comment by schlamar** [comment]
The `PYTHON` variable is not set per default, so this won't cover the standard setup.

**Comment by saghul** [comment]
That's the point, PYTHON is the override, you can set it to whatever you want. Else 'python' would be attempted. If there is no Python in the path whatsoever, well, we can start guessing, but nobody guarantees that we'll find it in SYSTEMDRIVE\PythonXY, so I'd rather fail and let the user fix it by specifying a valid Python interpreter.

For pyuv I will try to find an appropriate Python executable and set the PYTHON env variable pointing right there.

**Comment by bnoordhuis** [comment]
It's documented in the README that python 2.6 or 2.7 is a prerequisite so I won't bend over backwards to accommodate people that put python3 on their PATH.

An override through a PYTHON environment variable is acceptable though. Pull requests welcome. Please sign the CLA. :-)

**Comment by saghul** [comment]
I knew you were going to say that @bnoordhuis, that's why I suggested the override :-) Just adding that allows me to solve all problems on pyuv side, so it should be fine for everyone.
