### ISSUE TITLE
uv_queue_work() - uv__req_register bug

### ISSUE THREAD

**Issue by alexei18h** [joyent/libuv#731]
It seems I've found a bug in uv_queue_work().

As I understand, it is OK to queue work items to run loop thread
from another thread - we need this to "post quit message" asynchronously
and stop run loop properly. So this is about uv_queue_work(). Look at its code. It can produce an assertion fail in
uv__req_unregister called by uv_process_work_req:

  assert(uv__has_active_reqs(loop));

The problem is that if user's WorkItem callback has been returned
so fast (for example, it is empty at all), uv_process_work_req will be
executed _before_ another thread runs uv__req_register in uv_queue_work():

if (!QueueUserWorkItem(&uv_work_thread_proc, req, WT_EXECUTELONGFUNCTION)) {
    uv__set_sys_error(loop, GetLastError());
    return -1;
  }
// We lost the race: run loop thread is already executed assert(has_active_reqs());
uv__req_register(loop, req); // This call should be placed before QueueUserWorkItem.

---

I have also written a test fuzzer: it inserts 5 work items quickly to trigger
assert(). I uploaded it:

www.sendspace.com/file/rzzn1z

(VS2010, contains a copy of libuv-master that I received today)

screenshot: http://img692.imageshack.us/img692/561/screenva.png

The solution is to call uv__req_register() before QueueUserWorkItem
and, if the last one has been failed, unregister req:
uv__req_register(...);
if (!QueueUserWorkItem())
{
  uv__req_unregister(..);
  set_sys_error(...etc...);
  return;
}

E.g. my version of 'right' code will be:
http://www.everfall.com/paste/id.php?rxblo1x9hwiz

Sorry for my bad english, my native language is another.

**Comment by alexei18h** [comment]
A little mistake in first post. Of course ,'my version of right code' is not good, I forgot to add
uv__req_unregister() line in QueueUserWorkItem fail case.

**Comment by piscisaureus** [comment]
> As I understand, it is OK to queue work items to run loop thread from another thread.

How did you come to this understanding? It's not okay.

> we need this to "post quit message" asynchronously and stop run loop properly.

You should use uv_async for this. uv_async_send() is pretty much the only thread-safe function in libuv (save synchronization primitives and functions that don't affect the loop at all.)

**Comment by alexei18h** [comment]
Oh, ok. It seems I didnt read some part of documentation. Sorry for disturbing you.

**Comment by bnoordhuis** [comment]
No problem. Closing the issue.
