### ISSUE TITLE
Use `=` instead of `?=` for setting OS env var in Makefile

### ISSUE THREAD

**Issue by GlenHertz** [joyent/libuv#737]
Hi,

I had a compile error on commit `01fe4e73a695587d7aacbb1a6b998807b7917f64` because it conditionally defines OS in the Makefile.  According to:

https://www.redhat.com/mirrors/LDP/LDP/intro-linux/html/sect_07_02.html

`OS` is a reserved env var and it seems like libuv is using it as a variable for the user to override the setting. Please use a different variable name in place of `OS` like `libuv_OS` so it doesn't conflict with user's environment. 

Thanks,

Glen

**Comment by bnoordhuis** [comment]
Fixed in a9740c9.

/cc @pfox
