### ISSUE TITLE
spawn doesn't allow parent fd to be inherited by multiple child fds

### ISSUE THREAD

**Issue by malern** [joyent/libuv#763]
I'm trying to spawn a child process whose stdout and stderr are both redirected to the same file. I'm opening the file in the parent process and assigning the same fd to both options.stdio[1].data.fd and options.stdio[2].data.fd. The child process executes correctly, but only stdout ends up going to the file.

I believe the problem is because the original fd is being closed immediately after being duplicated in uv__process_child_init. So stdout is duplicated correctly, but when it loops back round to do the same for stderr the fd is no longer valid.

https://github.com/joyent/libuv/blob/0635e297148ae8cd4065013002de4bbaab72449f/src/unix/process.c#L311-L312

I modified one of the existing tests to illustrate the problem

``` c
TEST_IMPL(spawn_output_to_file) {
  int r;
  uv_file file;
  uv_fs_t fs_req;
  uv_stdio_container_t stdio[2];

  /* Setup. */
  unlink("output_file");

  init_process_options("spawn_helper6", exit_cb);

  r = uv_fs_open(uv_default_loop(), &fs_req, "output_file", O_CREAT | O_RDWR,
      S_IREAD | S_IWRITE, NULL);
  ASSERT(r != -1);
  uv_fs_req_cleanup(&fs_req);

  file = r;

  options.stdio = stdio;
  options.stdio[0].flags = UV_IGNORE;
  options.stdio[1].flags = UV_INHERIT_FD;
  options.stdio[1].data.fd = file;
  options.stdio[2].flags = UV_INHERIT_FD;
  options.stdio[2].data.fd = file;
  options.stdio_count = 3;

  r = uv_spawn(uv_default_loop(), &process, options);
  ASSERT(r == 0);

  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  ASSERT(r == 0);

  ASSERT(exit_cb_called == 1);
  ASSERT(close_cb_called == 1);

  r = uv_fs_read(uv_default_loop(), &fs_req, file, output, sizeof(output),
      0, NULL);
  ASSERT(r == 27);
  uv_fs_req_cleanup(&fs_req);

  r = uv_fs_close(uv_default_loop(), &fs_req, file, NULL);
  ASSERT(r == 0);
  uv_fs_req_cleanup(&fs_req);

  printf("output is: %s", output);
  ASSERT(strcmp("hello world\nhello errworld\n", output) == 0);

  /* Cleanup. */
  unlink("output_file");

  MAKE_VALGRIND_HAPPY();
  return 0;
}
```

**Comment by piscisaureus** [comment]
@bnoordhuis I think you should take a look :)

**Comment by bnoordhuis** [comment]
Sorry, must've missed this one.  Thanks for the bug report, continues in #923.
