### ISSUE TITLE
Generic datagram protocol support

### ISSUE THREAD

**Issue by kristrev** [joyent/libuv#764]
Hi,

I am currently working on a small project where I want to implement a network monitor using libuv (for Linux) and Netlink sockets. Before trying to extend libuv with Netlink support, I decided to check if there were any other options. One thing I noticed is that uv_udp_open does not do any checks on for example the socket protocol before adding to the io_watcher.

Passing a netlink file descriptor, or any other datagram file descriptor (for example raw sockets), works perfectly. Before building anything that depends on this functionality, I am wondering if the behavior is intentional or if a socket protocol check will be added to uv_udp_open? 

This observation motivated me to start working on a patch, but before I spend to much time on it, is there interest in moving the generic parts of udp.c to for example datagram.c, and the public part of udp.c wraps datagram.c (for backwards compatibility)? UDP-only functions like bind will not be touched. Or would it be better to keep udp.c as it is, and make datagram.c a subset of the functionality?

**Comment by bnoordhuis** [comment]
> I am wondering if the behavior is intentional or if a socket protocol check will be added to uv_udp_open? 

It's pretty much intentional. As long as the file descriptor honors the datagram contract (works in unconnected mode, can do recvmsg and sendmsg, etc.), it'll work. There's no reason for libuv to impose artificial constraints.

> is there interest in moving the generic parts of udp.c to for example datagram.c, and the public part of udp.c wraps datagram.c (for backwards compatibility)?

Not really. It already works, right?

**Comment by kristrev** [comment]
Thanks for letting me know, then I will proceed with my application.

Yup, I agree. Maybe it should be added to the documentation, since it expands possible use cases for libuv and is not immediately clear.

**Comment by bnoordhuis** [comment]
Sure. Documentation patches are welcome.
