### ISSUE TITLE
Redundant if clause in unix/stream.c

### ISSUE THREAD

**Issue by hhchristian** [joyent/libuv#767]
There's an unnecessary check if accepted_fd is set to -1 in /src/unix/stream.c

```
void uv__server_io(...) {
  ...
  assert(stream->accepted_fd == -1);
  assert(!(stream->flags & UV_CLOSING));

  if (stream->accepted_fd == -1)
    uv__io_start(stream->loop, &stream->io_watcher, UV__POLLIN);
  ...
```

Edit: This check may be intended to take release and debug builds into account.

**Comment by bnoordhuis** [comment]
No, you're right, it's superfluous. Removed in 4a55522, thanks.
