### ISSUE TITLE
Inconsistent behavior with uv_tcp_bind on OSX and Linux

### ISSUE THREAD

**Issue by qqshfox** [joyent/libuv#769]
On OSX, after first calling `uv_tcp_bind`, it will make the bind address in use immediately, but not on Linux. Is this as expected? Or it's just an undefined behavior?

example:

``` c
#include <stdio.h>
#include <assert.h>
#include <uv.h>

int main(int argc, char const *argv[])
{
  uv_tcp_t tcp1;
  uv_tcp_t tcp2;
  int r;
  struct sockaddr_in bind_addr;

  bind_addr = uv_ip4_addr("127.0.0.1", 60000);

  r = uv_tcp_init(uv_default_loop(), &tcp1);
  assert(r == 0);
  r = uv_tcp_bind(&tcp1, bind_addr);
  assert(r == 0);

  r = uv_tcp_init(uv_default_loop(), &tcp2);
  assert(r == 0);
  r = uv_tcp_bind(&tcp2, bind_addr);
  assert(r == 0);
  r = uv_listen((uv_stream_t *)&tcp2, 10, NULL);
  if (r == -1) {
    uv_err_t err = uv_last_error(uv_default_loop());
    printf("r: %d, errno: %d, error: %s\n", r, err.code, uv_strerror(err));
  } else {
    printf("listening");
  }
  assert(r == 0);

  uv_run(uv_default_loop(), UV_RUN_DEFAULT);

  return 0;
}
```

on OS X

```
$ uname -a
Darwin Hanfei-MBP.local 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64
$ ./a.out
r: -1, errno: 5, error: address already in use
Assertion failed: (r == 0), function main, file a.c, line 32.
zsh: abort      ./a.out
```

but on Linux

```
$ uname -a
Linux hanfei-gentoo 2.6.36-gentoo-r8 #4 SMP Thu Apr 7 20:13:18 CST 2011 x86_64 Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz GenuineIntel GNU/Linux
$ ./a.out
listening
```

Which one was expected?

Thanks,
Hanfei

**Comment by qqshfox** [comment]
Another example written with raw socket:

``` c
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <errno.h>
#include <sys/socket.h>
#include <netinet/in.h>

int main(int argc, char const *argv[])
{
  struct sockaddr_in bind_addr;
  int sockfd;
  struct sockaddr_in bind_addr2;
  int sockfd2;
  int r;

  bind_addr.sin_family = AF_INET;
  bind_addr.sin_port = htons(60000);
  bind_addr.sin_addr.s_addr = INADDR_ANY;

  bind_addr2 = bind_addr;

  sockfd = socket(AF_INET, SOCK_STREAM, 0);
  assert(sockfd != -1);

  r = bind(sockfd, (struct sockaddr *)&bind_addr, sizeof(bind_addr));
  assert(r == 0);

  sockfd2 = socket(AF_INET, SOCK_STREAM, 0);
  assert(sockfd2 != -1);

  r = bind(sockfd2, (struct sockaddr *)&bind_addr2, sizeof(bind_addr2));
  if (r == -1) {
    printf("r: %d, errno: %d, error: %s\n", r, errno, strerror(errno));
  }
  assert(r == 0);

  r = listen(sockfd2, 10);
  assert(r == 0);

  return 0;
}
```

On OSX

```
$ ./b.out
r: -1, errno: 48, error: Address already in use
Assertion failed: (r == 0), function main, file b.c, line 35.
zsh: abort      ./b.out
```

On linux

```
$ ./b.out
r: -1, errno: 98, error: Address already in use
b.out: b.c:35: main: Assertion `r == 0' failed.
zsh: abort      ./b.out
```

The result showed the consistency. Maybe something wrong in my codes or even in libuv?

**Comment by saghul** [comment]
libuv sets SO_REUSEADDR when binding to the socket (https://github.com/joyent/libuv/blob/master/src/unix/tcp.c#L67), so libuv's behavior on Linux is correct and expected.

I googled a bit and found this (http://bugs.python.org/issue16594) which says that in order for BSDs (including OSX) to behave the same SO_REUSEPORT also needs to be set. Maybe libuv should do that?

I'm sure @bnoordhuis knows best.

**Comment by bnoordhuis** [comment]
The OS X behavior is the correct one, actually. We have a test for that but it doesn't cover this particular case. In a nutshell, OS X reports the error at bind() time while Linux reports it at listen() time. (Phrased differently, on OS X, first to bind wins. On Linux, first to listen wins.)

```
# OS X
$ sudo dtruss out/Debug/run-tests tcp_bind_error_addrinuse tcp_bind_error_addrinuse 2>&1 | grep -wE 'bind|listen'
bind(0xB, 0x7FFF591D0888, 0x10)          = 0 0
bind(0xC, 0x7FFF591D0888, 0x10)          = -1 Err#48
listen(0xB, 0x80, 0x20)          = 0 0

# Linux
$ strace out/Debug/run-tests tcp_bind_error_addrinuse tcp_bind_error_addrinuse 2>&1 | grep -wE 'bind|listen'
bind(10, {sa_family=AF_INET, sin_port=htons(9123), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
bind(11, {sa_family=AF_INET, sin_port=htons(9123), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(10, 128)                         = 0
listen(11, 128)                         = -1 EADDRINUSE (Address already in use)
```

If you call uv_listen() first on tcp1, then on tcp2, you get the same behavior on both platforms.

Ideally, libuv should paper over this platform difference. The only way I can think of is to make uv_bind() call listen() implicitly on Linux, to force 'first to bind' behavior. We can call listen() again if the backlog needs to be adjusted. I just wonder if there are fringe use cases that would be broken by such a change.

**Comment by bnoordhuis** [comment]
Okay, I just realized that my proposed scheme won't work if you do bind() + connect(). An implicit listen() will make the connect() syscall fail with EISCONN.

That leaves two solutions AFAICS: we a) defer the actual bind() syscall until the user calls uv_listen() or uv_tcp_connect(), or b) close this as WONTFIX. Option A is a pretty big change in the API and the ABI (libuv would need to keep a copy of the struct sockaddr_in) so I'm leaning towards B.

Thoughts?

**Comment by saghul** [comment]
Does this apply to stream sockets only? AFAIS for UDP we do use SO_REUSEPORT on BSDs (https://github.com/joyent/libuv/blob/master/src/unix/udp.c#L330) does it make any sense to use it here?

**Comment by bnoordhuis** [comment]
> Does this apply to stream sockets only?

Yes. You never call listen() on datagram sockets.

> AFAIS for UDP we do use SO_REUSEPORT on BSDs does it make any sense to use it here?

No. That makes both bind/listen syscalls succeed - but only on the BSDs - and that _would_ break existing uses.

That SO_REUSEPORT in src/unix/udp.c is something of an anomaly. I want to remove it some day but I'm afraid it will break something, somewhere.

**Comment by saghul** [comment]
On 4/9/13 3:33 AM, Ben Noordhuis wrote:

> ```
> Does this apply to stream sockets only?
> ```
> 
> Yes. You never call listen() on datagram sockets.
> 
> ```
> AFAIS for UDP we do use SO_REUSEPORT on BSDs does it make any sense
> to use it here?
> ```
> 
> No. That makes both bind/listen syscalls succeed - but only on the BSDs
> - and that /would/ break existing uses.
> 
> That SO_REUSEPORT in src/unix/udp.c is something of an anomaly. I want
> to remove it some day but I'm afraid it will break something, somewhere.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joyent/libuv/issues/769#issuecomment-16089353.

Thanks for the explanation Ben.

## 

Saúl Ibarra Corretgé
http://about.me/saghul | http://saghul.net

**Comment by stakach** [comment]
This gives a good overview of platform support: http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

Personally I think having:
- SO_REUSEADDR set on all platforms is a good thing
  - On windows this has the same effect as also setting SO_REUSEPORT
- Then also setting SO_REUSEPORT on platforms that support it (BSD, OSX, LINUX > 3.9)
- With an optional function to protect against socket stealing (Windows + Solaris)
  - Linux this is enforced by default
  - BSD, OSX has no such option

**Comment by bnoordhuis** [comment]
I've updated the uv_tcp_bind() documentation in 02e8c8e.  A robust application should be prepared to handle errors from either uv_tcp_bind() or uv_listen() anyway so IMO there is not much point in trying to paper over platform details here.
