### ISSUE TITLE
Doing uv_close inside write callback sometimes causes truncated writes

### ISSUE THREAD

**Issue by igorzi** [joyent/libuv#78]
This could be easiliy reproduced with uv webserver.  The issue is that the write callback indicates that the buffer was given to the kernel, not that it was sent to the client.  In order to ensure graceful shutdown, we need to follow http://msdn.microsoft.com/en-us/library/ms738547(v=VS.85).aspx

**Comment by piscisaureus** [comment]
Fixed in 5aa8c005ec28de2aa66d4cb457b596fdf37f5e44
