### ISSUE TITLE
Assertion failed: req->work_cb, file src\win\threadpool.c, line 46

### ISSUE THREAD

**Issue by lkim** [joyent/libuv#782]
not speak English

 for test
 npm test 

Assertion failed: req->work_cb, file src\win\threadpool.c, line 46

How to solve the error

os: win7 (32)
 nodejs:0.8.9
 npm 1.1.61

**Comment by bnoordhuis** [comment]
This is not the proper place to report that bug. I see you've also opened an issue at sylvinus/node-crawler#48.  I'm reasonably sure that module (indirectly) uses native add-ons and that's likely where the source of the bug originates.
