### ISSUE TITLE
File chang monitoring does not work well

### ISSUE THREAD

**Issue by EricChan999** [joyent/libuv#787]
According to the "File change events" section of uvbook(http://nikhilm.github.io/uvbook/filesystem.html), I made a test with following code. 

``` c
#include <stdio.h>
#include <stdlib.h>
#include "uv.h"

void on_file_changed(uv_fs_event_t* handle, const char* filename, int events,
        int status) {
    fprintf(stderr, "Change detected in %s: ", handle->filename);
    if (events == UV_RENAME)
        fprintf(stderr, "renamed");
    if (events == UV_CHANGE)
        fprintf(stderr, "changed");

    fprintf(stderr, " %s\n", filename ? filename : "");
}

int main() {
    uv_fs_event_t ev;
    uv_fs_event_init(uv_default_loop(), &ev, "/home/ubuntu/Dev/Cpp/libuv_test1/aaa", on_file_changed, 0);
    uv_run(uv_default_loop(), UV_RUN_DEFAULT);
}
```

And this is test steps and result:
1. Run the program, of cource.
2. touch /home/ubuntu/Dev/Cpp/libuv_test1/aaa, the program prints "Change detected in /home/ubuntu/Dev/Cpp/libuv_test1/aaa: changed aaa" successfully.
3. Vim /home/ubuntu/Dev/Cpp/libuv_test1/aaa and make some changes and save, the program prints
Change detected in /home/ubuntu/Dev/Cpp/libuv_test1/aaa: renamed aaa
Change detected in /home/ubuntu/Dev/Cpp/libuv_test1/aaa: changed aaa
Change detected in /home/ubuntu/Dev/Cpp/libuv_test1/aaa: renamed aaa
Change detected in /home/ubuntu/Dev/Cpp/libuv_test1/aaa: renamed aaa
4. After that, no matter what changes made to the file aaa, the program dose not print anything.

PS: My testing environment is Ubuntu 11.10 VM(Linux version 3.0.0-21-generic)

**Comment by bnoordhuis** [comment]
On what file system is the directory?

**Comment by AvianFlu** [comment]
Try this again without using vim.  Vim can do strange things with its swap files that make it look like more events are happening than should be.  I've seen this a few times before - I might be wrong, but if you use `nano` or another editor, I bet it will work like you'd expect.

**Comment by bnoordhuis** [comment]
Yes, that too. Seeing that there has been no follow-up in over a month, I'll close the issue.
