### ISSUE TITLE
Running Powershell on Windows Server 2008 (possibly Vista) as a child never exits

### ISSUE THREAD

**Issue by rjemanuele** [joyent/libuv#792]
We're using Powershell in the Rackspace Virgo Project to gather Windows System Metrics.  When spawning Powershell under Luvit, the Powershell subprocess never exist.  This can be reproduced under node.js as well.  This only occurs under Windows Server 2008 (possibly Vista also).  This does not occur under Windows 8 or Server 2012.

Test Scripts can be found here:
https://gist.github.com/rjemanuele/2aa4f36c6c34898324ba

**Comment by piscisaureus** [comment]
Figured it out, 2k8's powershell won't exit until you close the stdin pipe.
