### ISSUE TITLE
Inconsistent execution of close callbacks

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#796]
I know there were some discussions about this in the past, but somehow this never affected me, until today :-S

Here is an example program written with pyuv:

```
import pyuv

def cb1(handle):
    print "cd1"

def cb2(handle):
    print "cb2"
    handle.close()

def check1(handle):
    print "check!"


loop = pyuv.Loop()

c1 = pyuv.Check(loop)
c1.start(check1)
t1 = pyuv.Timer(loop)
t1.start(cb1, 100, 0)
t2 = pyuv.Timer(loop)
t2.start(cb2, 0.01, 0)

loop.run()
```

On unix this program will print:

```
check!
cb2
check!
# wait for 100 seconds here
...
```

whereas on Windows, it will print:

```
check!
cb2
# wait for 100 seconds here
...
```

The reason seems to be that on Windows endgames are processed _before_ blocking for i/o, but on unix they are processed after. This means that on unix the next loop iteration will not block for i/o (hence the check handle will run) but on windows it will block, because the conditions not to block are not met.

This is a synthetic example, in my real use case (the evergreen project), I have some sort of event loop driven scheduling system, where timers just insert their callbacks in a queue (when they kick), which is processed in a check handle, so on windows, this means I'm in trouble. (hopefully I explained myself correctly here)

If I move the call to `uv_process_endgames` to after running the check handles things work as I expected, though I haven't checked if there are any further implications. So I'd like the windows implementation to behave like unix on this one :-)

Thoughts @piscisaureus @bnoordhuis ?

**Comment by bnoordhuis** [comment]
@piscisaureus?
