### ISSUE TITLE
unix: support abstract AF_UNIX addresses

### ISSUE THREAD

**Issue by geertj** [joyent/libuv#797]
The method `uv_pipe_connect()` takes the pipe name as a null-terminated string. This unfortunately prevents you from specifying abstract unix socket addresses. An abstract unix socket addres for `"/tmp/foo"` is specified as `"\x00/tmp/foo"` so exactly the same but starting with a null byte.

The abstract namespace is used by e.g. the D-BUS session bus which is where I need this for.

**Comment by bnoordhuis** [comment]
Abstract socket addresses are a Linux-ism, I don't think we want to support that. If you need that functionality, you can create a socket manually and pass it to uv_pipe_open().

**Comment by geertj** [comment]
Arg.. I had hoped I would not have to bother with the details of non-blocking connect()s myself... But thanks for the tip regarding uv_pipe_open().

**Comment by bnoordhuis** [comment]
No problem. FWIW, on Linux, as long as you turn on the O_NONBLOCK flag on the socket, you don't have to worry about dealing with EINPROGRESS: either the connect() syscall succeeds or it fails with EAGAIN (when the server's backlog is full) but there never is a 'partially done' state like there is with TCP sockets.
