### ISSUE TITLE
uv.h missing <netdb.h> include

### ISSUE THREAD

**Issue by rmustacc** [joyent/libuv#81]
uv.h should be including <netdb.h> for the definition of the struct addrinfo \* for the following definitions:

typedef void (_uv_getaddrinfo_cb)(uv_getaddrinfo_t_ handle, int status, struct addrinfo\* res);

int uv_getaddrinfo(uv_getaddrinfo_t\* handle, uv_getaddrinfo_cb getaddrinfo_cb, const char\* node,  const char\* service, const struct addrinfo\* hints);

**Comment by bnoordhuis** [comment]
Closing. If this hasn't been fixed by now, I owe you a sixpack.
