### ISSUE TITLE
uv_run crash

### ISSUE THREAD

**Issue by harlentan** [joyent/libuv#810]
A : When uv_xxx_init, uv_xxx_listen in thread 1,
B: And run uv_run() in thread 2.

use the uv_default_loop().
The thread 1 will run uv_xxx_listen for sure. 

But but the uv_run crash.

**Comment by bnoordhuis** [comment]
libuv doesn't make any guarantees about thread safety. The only function that is guaranteed to be thread-safe is uv_async_send().

**Comment by piscisaureus** [comment]
In addition to that, if you want to run it on windows, be sure to call all APIs affecting a loop/handle from the same thread.
