### ISSUE TITLE
uv__update_time on Unix should return nanosec values.

### ISSUE THREAD

**Issue by achimnol** [joyent/libuv#811]
https://github.com/joyent/libuv/search?q=uv__update_time&type=Code

From the above search results, I could confirm that the Unix version's `uv_now(loop)` returns the current event timestamp in millisecond resolution instead of nanoseconds, as `uv__hrtime()` returns the result of `clock_gettime(CLOCK_MONOTONIC)` but divided by 1000000.
Is there any particular reason for this division? If not, I think it should return the value in the resolution as high as possible.

**Comment by bnoordhuis** [comment]
> Is there any particular reason for this division?

Not really. It's mostly that we didn't need a higher resolution and that milliseconds are something of the greatest common denominator (every platform has a timer with roughly that kind of granularity.)

I don't really mind changing that (all _supported_ platforms have at least microsecond granularity) but it could have a rather significant impact on projects that use libuv.

**Comment by bnoordhuis** [comment]
Now that I've thought about it some more, uv_timer_t timeouts and repeats are in milliseconds. Changing uv_now() to return nanoseconds would make things a bit inconsistent. Let's leave it as it is for now. I'll add a note to uv.h explaining when to use uv_now() and when uv_hrtime().

**Comment by achimnol** [comment]
Thanks for the reply. On most Linux systems, timer intervals less than 1msec is very unstable due to jitters occurred by the scheduler. (I've tested it using my manual implementation of a C epoll + timerfd loop.)
However, measuring more precise timing (in micro/nano-seconds) is handful to accurately calculate throughput even though the timer interval is in millisecond unit.
I'm looking forward to see `uv_hrtime()` to be a kind of official API when available on the target system. :) Maybe another API to query how much resolution it provides should be added, too.

**Comment by bnoordhuis** [comment]
> I'm looking forward to see uv_hrtime() to be a kind of official API when available on the target system.

It is, it's available on all platforms.
