### ISSUE TITLE
make on cygwin results in: ares_config.h: No such file or directory

### ISSUE THREAD

**Issue by japj** [joyent/libuv#82]
when trying to compile with cygwin I get the following error

<pre>
$ make
gcc -Ic-ares/ -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Ieio --std=gnu89 -g -c uv-unix.c -o uv-unix.o
uv-unix.c: In function `getaddrinfo_thread_proc':
uv-unix.c:1521: warning: passing arg 3 of `getaddrinfo' from incompatible pointer type
gcc -Ic-ares/ -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 --std=gnu89 -g -c uv-common.c -o uv-common.o
uv-common.c:30:25: ares_config.h: No such file or directory
make: *** [uv-common.o] Error 1
</pre>

**Comment by piscisaureus** [comment]
Fixed in 49baaa4731c31e4bef58c98b31a27914f666d3b0
