### ISSUE TITLE
stream: enforce that callee closes handle after EOF

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#827]
The recent joyent/node#5504 debacle has demonstrated that there is no reason to leave the handle open after EOF. Enforce it in libuv, presumably with a few strategically placed asserts.

/cc @piscisaureus - thoughts?

**Comment by ibc** [comment]
I don't get the point. Do you mean that libuv would call `uv_close()` itself when EOF is received?

What is the problem with manually call to it from `on_read_cb`?

**Comment by saghul** [comment]
No. The idea is to place some asserts to check that after read_cb got EOF the handle has the UV_HANDLE_CLOSING flag, ie, the user called uv_close in the callback.

**Comment by ibc** [comment]
And if the user does not call uv_close, then what? Crash?

**Comment by saghul** [comment]
Yes

**Comment by ibc** [comment]
-1.

Let me decide when to close my handle.

## 

Iñaki Baz Castillo
ibc@aliax.net

**Comment by saghul** [comment]
I'm not going to handle this right now,@ibc,  but let me tell you the resoning behind it: if a stream gets UV_EOF and you don't close it you are using a file descriptor for no purpose. If you uv_close that handle then the fd will be closed thus freeing the resources.

FWIW, we have a related precedent already: if you get an error in the read callback and you don't call uv_read_stop (at least), this assert will blow: https://github.com/joyent/libuv/blob/master/src/unix/stream.c#L1108

Anyway, as I said, I'm not going to spend cycles on this now.

**Comment by ibc** [comment]
Someone may have a uv_handle associated to a C++ class instance, and may have a single `Close()` method that calls `uv_close()` among other stuff (release dynamically allocated memory, and so on).

Please don't force me to close the uv_handle in the exact moment I read a EOF. I may prefer to defer the C++ instance destruction for any reason, and I don't want to make my code cryptographic with tons of states (`bool is_uv_handle_closed`, `bool is_uv_handle_deleted`, etc).

**Comment by bnoordhuis** [comment]
The currently implemented solution is to remove the file descriptor from the epoll/kqueue/etc. set when the callback doesn't call uv_close().  It seems to work well enough so this issue can be closed as far as I'm concerned.

**Comment by saghul** [comment]
Closing then! Thanks for clarifying, Ben :-)

**Comment by ibc** [comment]
So, in case I don't call uv_close upon receipt of EOF, it is safe to call uv_write, uv_stop_read, uv_shutdown or whatever time later, right? I mean: no crash.

**Comment by saghul** [comment]
You need to call UV_read_stop, as I pointed out above.

**Comment by ibc** [comment]
Can live with that... but I really think that this should be documented in the API.

**Comment by saghul** [comment]
Then send a patch :-)

**Comment by ibc** [comment]
PR send #1357
