### ISSUE TITLE
uv_fs_access

### ISSUE THREAD

**Issue by bodokaiser** [joyent/libuv#837]
Hello,

currently **nodejs** uses `uv_fs_stat` to check if a file exists (by looking if stat is throwing an error or not). Wouldn't it be a better approach to create a method like `uv_fs_access` to check for permissions, existence etc.?

If yes I would like to try to do this :)

**Comment by bnoordhuis** [comment]
What benefit would an access(2) binding have over stat(2)? The system call itself is marginally faster but that's nullified by the fact that it goes through the thread pool first.

**Comment by bodokaiser** [comment]
I would say you would have an API improvement as you can test against specific constants whereas you have to work with the stat object.

**Comment by bnoordhuis** [comment]
That's not a very compelling reason (to me anyway) but I'm also not dead set against it.

I'll accept a pull request provided it's of high quality. If it has to go through multiple review rounds, I'll probably be less favorably inclined.
