### ISSUE TITLE
Assertion `loop->watchers[w->fd] == w' failed.

### ISSUE THREAD

**Issue by emilsedgh** [joyent/libuv#838]
Installed Node 0.10.12 and reinstalled LDAP module.
LDAP module is built fine. However, I get this:

node: ../deps/uv/src/unix/core.c:688: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

When trying to use it.

**Comment by emilsedgh** [comment]
And here is strace output: https://gist.github.com/emilsedgh/5844406

**Comment by saghul** [comment]
Does the LDAP module use uv_poll_t handles? IIRC I've seen that assertion blow when more than one poll handle is used for the same fd.

**Comment by emilsedgh** [comment]
Hi.
Yes it does use uv_poll_t handles.
Is this a node-ldap bug then?

**Comment by saghul** [comment]
If node-ldap uses more than one poll handle for a given fd at the same
time, then yes.

On Sunday, June 23, 2013, Emil Sedgh wrote:

> Hi.
> Yes it does use uv_poll_t handles.
> Is this a node-ldap bug then?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/libuv/issues/838#issuecomment-19871381
> .

## 

/Saúl
http://saghul.net | http://about.me/saghul

**Comment by bnoordhuis** [comment]
Tentatively closing. As @saghul points out, this is almost certainly a node-ldap bug. If if turns out the bug is in libuv, holler and I'll reopen the issue.

**Comment by falnos24865** [comment]
I am getting the error:
 node: ../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
I am not using any LDAP module so it cannot be that module. I am heavily using the SerialPort module but it seems this error might be more widespread.

Node: v0.10.32

**Comment by saghul** [comment]
We've seen this one reported every now and then, but always non-deterministically and / or in a  big application. If you can reduce your test case to either a libuv test case or a node core modules only test case, which exhibits the bug deterministically, we can look into it.

**Comment by rafahoro** [comment]
I have the same issue in my code. It solved after commenting the a line to create a pipe with child's stdin (the code below was in my code, not in a library, but may help you finding the problematic line):

``` javascript
var cp = spawn(SPAWN_BIN, SPAWN_ARGS, {"env": env});
cp.stdout.pipe(process.stdout);
cp.stderr.pipe(process.stderr);
// https://github.com/Unitech/PM2/issues/659
// process.stdin.pipe is causing the following error when using PM2
//node: ../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
//process.stdin.pipe(cp.stdin);
```
