### ISSUE TITLE
File System API. eio.h should not be exposed publicly.

### ISSUE THREAD

**Issue by ry** [joyent/libuv#84]
Suggestions for API?

**Comment by DrPizza** [comment]
I was just playing around/experimenting with this, the results of which are [here](https://github.com/DrPizza/node/tree/master/deps/uv). Nothing very adventurous at the moment. It allows multiple outstanding I/Os on a file, and processes them in whatever order the system chooses. There are half finished bits (I want to have a kind of "streaming mode" with a libuv-maintained file pointer, but I wanted to double check some stuff first before continuing).

I've not touched the UNIX side, and know I have broken it; nothing too severe, I don't think, just some types will have changed and some extra #defines will be needed.

Foolishly I'm using the libuv inside node, I suppose I should really start over and fork libuv proper. Oh well.

It raises lots of questions. Like, do you want some kind of an async file open? I don't know about UNIX, but Win32 `CreateFile()` is synchronous, so we'd have to punt that to a background thread. On balance it would probably be nice to have.

This in turn raises the question of argument lists; Windows has different options to pass to `CreateFile()` than UNIX has for `open()`/`creat()`. Some common subset can no doubt be carved out and suitable mappings created, but using libraries that do that always leaves a bad taste in my mouth. Sometimes, I really do want control over `CreateFile()`, I really do want access to the `HANDLE`, and so on.

Perhaps a happy medium might be to have a standard/generic `uv_open_file()` that does whatever's possible on UNIX and Windows, and then a per-platform `uv_open_file_native()` that allows the full complexity of the underlying platform.

(At the moment, I'm just leaving file opening/creation to the caller, and have a `uv_file_init()` that binds a native file handle to uv)

Similar issues are raised of course with things like `chmod()`. Worse, in fact; there's no real way to map between UNIX permissions bits and Win32 ACLs. eio just creates do-nothing stubs, which is an option. eio is actually a little pessimistic about its stubbing out, there are a handful of things that it could provide but doesn't.

The read API acts as one would probably expect; caller allocates a buffer and the size of that buffer is used to size the read call. I'm tempted to implement a similar style for TCP/pipes, too. Sometimes--perhaps even often--I don't want to deal with partial reads, I want to read a chunk of known size all at once, with partial reads reserved for unexpected loss of connection. The current "read as much as can be read without blocking" is efficient; I just don't think it's always the easiest thing to use.

**Comment by bnoordhuis** [comment]
Closing, superseded by #104 (which I still think is a good idea).
