### ISSUE TITLE
bandwidth limitation on libuv

### ISSUE THREAD

**Issue by welkineins** [joyent/libuv#844]
In Linux, an tool call trickle is used to do bandwidth limit by wrapping glibc socket related function calls. (http://archive09.linux.com/feature/61293). However, this tool does not work with Node.js, but other tools like curl, etc, can work perfectly. I am wondering this problem might caused by libuv, since it wrap these functions again. 

So, the issue is that "Is there any ways to modify/compile node.js or libuv to make trickle work or any other ways to limit bandwidth of node.js?" 

Thanks!

**Comment by bnoordhuis** [comment]
I assume it uses LD_PRELOAD to overload the glibc wrappers? That indeed won't work with libuv because it doesn't use glibc for everything.

You either have to disable libuv's accept4() system call wrapper (and maybe a few others) or teach trickle to also overload syscall().
