### ISSUE TITLE
build error on Cygwin

### ISSUE THREAD

**Issue by tejacques** [joyent/libuv#845]
When attempting to build on cygwin I get the following error:

```
$ make
make  all-am
make[1]: Entering directory `/cygdrive/d/libuv'
  CC       libuv_la-fs-poll.lo
In file included from ./include/uv.h:62:0,
                 from src/fs-poll.c:22:
./include/uv-unix.h:148:1: error: unknown type name 'pthread_barrier_t'
Makefile:794: recipe for target `libuv_la-fs-poll.lo' failed
make[1]: *** [libuv_la-fs-poll.lo] Error 1
make[1]: Leaving directory `/cygdrive/d/libuv'
Makefile:553: recipe for target `all' failed
make: *** [all] Error 2
```

Additional Information:

```
$ CC --version
CC (GCC) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname
CYGWIN_NT-6.1-WOW64

$ echo $OS
Windows_NT
```

I came across a similar issue (from the Julia github page: https://github.com/JuliaLang/julia/issues/2512) which claims it can be caused by having the OS environment variable set, and is fixed with

`unset OS && make`

Unfortunately this make no difference.

**Comment by tjfontaine** [comment]
We generally don't support cygwin. It would be ideal if instead you built with Visual Studio (or VC Express), but failing that we try and support where feasible mingw.

That being said, current master recently went under a change which added autotools support, that has unfortunately regressed our ability to support mingw at the moment. However you can checkout the v0.10 branch which should be able to build with mingw (if it also builds with cygwin that's merely a happy accident)

**Comment by tejacques** [comment]
Thanks for the response. I did a bit more research, and it would appear that the issue is due to a lack of full pthread support on cygwin: http://cygwin.com/cygwin-api/compatibility.html.

**Comment by tkelman** [comment]
Here's a probably-futile attempt to fix the libuv build in Cygwin: https://github.com/tkelman/libuv/commit/641887f3603e2257d21db9fe0ec9212e8e4eeb19

I can't find replacements for eventfd, epoll, or inotify families of syscalls in Cygwin, so I don't think it would be straightforward to get any further. Cygwin-to-MinGW cross compilation works okay though (fails about 41 of libuv's tests on current master, but so does a MSYS MinGW build so not sure if that's expected).

**Comment by gregsskyles** [comment]
FWIW, as of version 2.5 Cygwin supports the pthread_barrier\* apis...

**Comment by tkelman** [comment]
Still doesn't support async IO though, AFAIK. You'd have to piece together posix API's and win32 IOCP's to come up with something that works.

**Comment by saghul** [comment]
FWIW, this repo is now abandoned. Please use libuv/libuv. We are currently advocating for using MSYS2 instead of Cygwin, libuv works there no problem.

**Comment by tkelman** [comment]
@saghul actually it doesn't if you try to build for msys2. It's a not very different fork of cygwin, it just adds some path mangling hacks that make it easier to pretend you aren't cross compiling when you use mingw target compilers. mingw target cross compilers work fine from cygwin. it's the posix layer that isn't complete enough to build a posix style libuv, and msys2 doesn't change that at all.

edit: here's the extent of the differences between cygwin's posix layer and msys2's: https://github.com/Alexpux/Cygwin/compare/msys2-master

**Comment by saghul** [comment]
> actually it doesn't if you try to build for msys2.

It does, it tried and succeeded.  It will use native IOCP and other Windows APIs so there is no need to emulate any of that.

**Comment by tkelman** [comment]
That's a mingw gcc then, not an msys2 gcc. Check `gcc -dumpmachine`.

**Comment by saghul** [comment]
Yeah, sorry, I meant the MSYS2 / MinGW toolchain.  The rest are not supported since nobody stepped up to maintain them.

**Comment by gregsskyles** [comment]
@tkelman, to comment on your first comment of today, yes. The very first things on the (alphabetical) list of unsupported APIs in Cygwin are aio_*. So yes, a lot of work still to be done if one wants libuv to be buildable in the Cygwin environment. However, I think most people are more interested in being able to build and use other software (e.g., NeoVim; I got here via the path of trying to build Perl6, for another example) that uses libuv in Cygwin. It seems like it should be fairly straightforward to implement a thin wrapper that's callable from Cygwin around the Win32 version of libuv. What I don't know is if Cygwin supports any sort of mechanism for the callbacks that async IO requires (though I can't see why not). And, if my (admittedly feeble) understanding of libuv is correct, it abstracts async IO in both Win32 and Linux, so it essentially implements what is missing in Cygwin in the first place.

**Comment by tkelman** [comment]
Do you really need a cygwin (or msys2 posix) build of these things? You can build and run applications using the mingw cross compilers inside cygwin, and it'll probably be less work.

**Comment by gregsskyles** [comment]
Probably not, unless you want the latest features and the windows ports are slow to appear. I'm in it mostly for the learning. I've learned a lot more about what's going on under the hood of Cygwin by attempting this. Thanks to your comments, I'm going to go find out more about mingw, which I've heard of but don't really understand yet.

**Comment by tkelman** [comment]
`x86_64-w64-mingw32-gcc` and it gives you applications that don't depend on cygwin to run. Can even cross compile for windows from linux!
