### ISSUE TITLE
build: re-add mingw support

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#847]
It should be possible to build libuv with autotools + MSYS.

/cc @luislavena

**Comment by luislavena** [comment]
Thank you @bnoordhuis for this, but I thought that by having autotools we could use to build with it instead.

In theory the modifications to the Makefile for autotools aren't that big and I believe libtool already provides a way to generate both shared and static library.

I'll look into autotools a bit next month and chime in then.

Thank you for providing a solution.

**Comment by bnoordhuis** [comment]
Patches to build with autotools are welcome. I added the Makefile so MinGW users have something to build with. I didn't want to spend too much time on it.
