### ISSUE TITLE
win: uv_hrtime() return non-incremental value

### ISSUE THREAD

**Issue by witchu** [joyent/libuv#850]
on windows server (windows with high performance frequency) when call uv_hrtime() many times, return values will decrease sometimes.

to fix please apply:

<pre>

1a39914af186f5db73ba8507d60da5d3bb3e39dc
 src/win/util.c |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/win/util.c b/src/win/util.c
index f19d30a..2deb39d 100644
--- a/src/win/util.c
+++ b/src/win/util.c
@@ -460,8 +460,8 @@ uint64_t uv_hrtime(void) {
   /* performance counter frequency, and there may not be much headroom to */
   /* multiply by NANOSEC without overflowing, we use 128-bit math instead. */
   return ((uint64_t) counter.LowPart * NANOSEC / hrtime_frequency_) +
-         (((uint64_t) counter.HighPart * NANOSEC / hrtime_frequency_)
-         &lt;&lt; 32);
+         (((uint64_t) counter.HighPart * NANOSEC / hrtime_frequency_) &lt;&lt; 32) +
+         (((uint64_t) counter.HighPart * NANOSEC % hrtime_frequency_) * 4294967296 / hrtime_frequency_);
 }

</pre>

**Comment by Keno** [comment]
Can we get this applied?
