### ISSUE TITLE
Configure error on OSX 10.6

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#851]
Latest master gives me the following error on OSX 10.6. Any clues?

```
./configure: line 12071: syntax error near unexpected token `;'
./configure: line 12071: `; then'
```

**Comment by saghul** [comment]
The problem seems to be related to some platform detection. This is the code generated on OSX, which gives the above error:

```
 if case $host_os in
  aix*) true ;;
  *) false ;;
esac
; then
  AIX_TRUE=
  AIX_FALSE='#'
else
  AIX_TRUE='#'
  AIX_FALSE=
fi
```

And this is what my Linux machine has generated, which works ok:

```
 if case $host_os in
  aix*) true ;;
  *) false ;;
esac
; then
  AIX_TRUE=
  AIX_FALSE='#'
else
  AIX_TRUE='#'
  AIX_FALSE=
fi
```

In case it helps, OSX 10.6 ships with autoconf 2.61, which is probably ancient, but 10.6 is the Windows XP of the Macs ;-)

**Comment by bnoordhuis** [comment]
If this is a game of "Spot the 5 differences", I give up - the snippets look identical to me.

**Comment by saghul** [comment]
They look identical, but after editing the resulting configure file like this it worked:

```
 if case $host_os in
  aix*) true ;;
  *) false ;;
esac; then
  AIX_TRUE=
  AIX_FALSE='#'
else
  AIX_TRUE='#'
  AIX_FALSE=
fi
```

Note that the semicolon is on the same line as the 'esac'.

Looks like I pasted the same thing twice in my previous note, sorry, this is the real output from my Linux machine:

```
if case $host_os in #(
 aix*) :
   true ;; #(
 *) :
   false ;;
esac; then
  AIX_TRUE=
 AIX_FALSE='#'
else
AIX_TRUE='#'
AIX_FALSE=
fi
```

Here the esac statement has the semicolon on the same line.

**Comment by bnoordhuis** [comment]
Okay, I see what you mean.  I think you're looking at an autoconf bug, the case/esac code is generated from an AS_CASE macro in configure.ac.  I'd switch to AS_IF macros but then you can't pattern-match on $host_os anymore...  I'll entertain patches. :-)

**Comment by saghul** [comment]
By looking around, I does indeed seem to be an autoconf bug, FML. My autotools-fu is inexistent, but I'll try to come up with a patch when I find some time.

**Comment by saghul** [comment]
I updated my autoconf / automake, they are ancient on OSX 10.6, and I don't really have the time / patience to fix this. Closing.

**Comment by mscdex** [comment]
I just wanted to say I ran into this error too on 10.6. :-\

EDIT: Installing autoconf/automake 2.69 fixed things....

**Comment by saghul** [comment]
@mscdex yeah, I installed them with homebrew and linked them because they are "keg only" or something and that did the trick for me.
