### ISSUE TITLE
build: infinite configure loop with autotools

### ISSUE THREAD

**Issue by mscdex** [joyent/libuv#856]
At least on NetBSD, using the autotools method of building causes an infinite "./configure" loop when doing `make`.

**Comment by mscdex** [comment]
Ok, so the workaround for this problem was to:

```
1. mv /bin/sh /bin/sh.orig
2. ln -s `which bash` /bin/sh
3. sh autogen.sh
4. ./configure
5. find . | xargs touch
6. gmake && gmake check
```

**Comment by bnoordhuis** [comment]
What happens when you revert 2f3124a?

**Comment by bnoordhuis** [comment]
No follow-up, closing.  FWIW, it works for me on OpenBSD and FreeBSD.
