### ISSUE TITLE
build: OpenBSD/NetBSD cannot build with gyp_uv

### ISSUE THREAD

**Issue by mscdex** [joyent/libuv#857]
Doing `./gyp_uv -f make` works, but then `gmake -C out` results in:

```
gmake: Entering directory `/home/foo/libuv/out'
  ACTION Regenerating Makefile
sh: ./gyp_uv: not found
gmake: *** [Makefile] Error 127
gmake: Leaving directory `/home/foo/libuv/out'
```

**Comment by bnoordhuis** [comment]
That sounds like a gyp or environmental issue. It shouldn't regenerate the Makefile unless one of the *.gyp or *.gypi files has changed. It's also looking for gyp_uv in the wrong directory.

**Comment by mscdex** [comment]
Ok, I updated gyp and it starts compiling now, but it's not picking the right files as it fails with this:

```
  CC(target) /home/foo/libuv/out/Debug/obj.target/libuv/src/unix/linux-core.o
../src/unix/linux-core.c:33:23: fatal error: sys/prctl.h: No such file or directory
compilation terminated.
gmake: *** [/home/foo/libuv/out/Debug/obj.target/libuv/src/unix/linux-core.o] Error 1
gmake: Leaving directory `/home/foo/libuv/out'
```

**Comment by mscdex** [comment]
Now `build/gyp/pylib/gyp/common.py` has to be [patched](https://gist.github.com/mscdex/a64a3930a5a8db0843ec) for libuv to build properly. I've posted an [issue](https://code.google.com/p/gyp/issues/detail?id=358) over on gyp's tracker.

**Comment by bnoordhuis** [comment]
Closing, I was able to build libuv with gyp on OpenBSD recently.

**Comment by mscdex** [comment]
Perhaps it works with OpenBSD now, but not NetBSD (at least without the previously mentioned patch) :-\
