### ISSUE TITLE
osx run-tests and run-benchmarks dependency issues

### ISSUE THREAD

**Issue by redchair123** [joyent/libuv#859]
the raw "-lm" is being treated as a framework dependency, which triggers warnings in xcode.

Ideally the gyp uses libm.dylib for osx rather than "-lm"

**Comment by bnoordhuis** [comment]
Not sure what you mean. Maybe post a patch?

**Comment by saghul** [comment]
No follow up, closing. If this is still a problem and you know how to fix it please provide a patch :-)
