### ISSUE TITLE
Need a way to do a connect() in libuv using something other than AF_INET

### ISSUE THREAD

**Issue by jacklund** [joyent/libuv#860]
I'm trying to write a node.js interface to Bluetooth LE. The interface itself looks exactly like TCP, except the sockaddr family is `AF_BLUETOOTH` rather than `AF_INET` (along with one or two other fairly trivial differences). However, there is a test in `uv_tcp_connect` which checks for `AF_INET`, and if not set that way, aborts. I certainly understand this, as this is the TCP connect interface, but I need access to the `connect()` call in such a way that I can specify the parameters I need, but also hook into the libuv event loop.

I have to admit this is very frustrating, because it seems like all the general-purpose calls have been made private, but the public calls aren't general enough to cover anything other than file, pipe, TCP and UDP I/O, unless I'm missing something. There are several of the private calls that would work for me, if I had access to them, but they've been made inaccessible as far as I can tell.

Admittedly, I'm a libuv newbie, so if there's another way to do what I'm trying to do, I'd be very grateful to hear it.

Thanks.

**Comment by saghul** [comment]
You can create the socket yourself with the family you want and use a uv_poll_t handle, which works on arbitrary fds,  to asynchronously monitor it for read / write operations.

**Comment by bnoordhuis** [comment]
What @saghul said, the uv_poll_*() family of functions is what you want.

**Comment by jacklund** [comment]
Thanks! I'll give that a try.
