### ISSUE TITLE
getaddrinfo_fail timeout on `make check` 

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#861]
The test 'getaddrinfo_fail' times out when running `make check` on Lubuntu 13.04

```
`getaddrinfo_fail` failed: timeout
Output from process `getaddrinfo_fail`: (no output)
```

**Comment by bnoordhuis** [comment]
It's probably harmless. People have reported that before and it usually turns out their upstream DNS server is slow in returning an NXDOMAIN response.
