### ISSUE TITLE
Makefile.am missing 'subdir-objects'

### ISSUE THREAD

**Issue by dmazzella** [joyent/libuv#866]
Hi all,
i have found a problem in Makefile.am

[developer@localhost libuv-master]$ sh autogen.sh 
- libtoolize
- aclocal -I m4
- autoconf
- automake --add-missing
  automake: warnings are treated as errors
  Makefile.am:30: warning: source file 'src/fs-poll.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  automake: warning: possible forward-incompatibility.
  automake: At least a source file is in a subdirectory, but the 'subdir-objects'
  automake: automake option hasn't been enabled.  For now, the corresponding output
  automake: object file(s) will be placed in the top-level directory.  However,
  automake: this behaviour will change in future Automake versions: they will
  automake: unconditionally cause object files to be placed in the same subdirectory
  automake: of the corresponding sources.
  automake: You are advised to start using 'subdir-objects' option throughout your
  automake: project, to avoid future incompatibilities.
  Makefile.am:30: warning: source file 'src/inet.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/uv-common.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/version.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/async.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/core.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/dl.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/fs.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/getaddrinfo.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/loop-watcher.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/loop.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/pipe.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/poll.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/process.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/signal.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/stream.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/tcp.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/thread.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/threadpool.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/timer.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/tty.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:30: warning: source file 'src/unix/udp.c' is in a subdirectory,
  Makefile.am:30: but option 'subdir-objects' is disabled
  Makefile.am:151: warning: source file 'src/unix/aix.c' is in a subdirectory,
  Makefile.am:151: but option 'subdir-objects' is disabled
  Makefile.am:157: warning: source file 'src/unix/darwin.c' is in a subdirectory,
  Makefile.am:157: but option 'subdir-objects' is disabled
  Makefile.am:157: warning: source file 'src/unix/darwin-proctitle.c' is in a subdirectory,
  Makefile.am:157: but option 'subdir-objects' is disabled
  Makefile.am:157: warning: source file 'src/unix/fsevents.c' is in a subdirectory,
  Makefile.am:157: but option 'subdir-objects' is disabled
  Makefile.am:157: warning: source file 'src/unix/kqueue.c' is in a subdirectory,
  Makefile.am:157: but option 'subdir-objects' is disabled
  Makefile.am:157: warning: source file 'src/unix/proctitle.c' is in a subdirectory,
  Makefile.am:157: but option 'subdir-objects' is disabled
  Makefile.am:169: warning: source file 'src/unix/freebsd.c' is in a subdirectory,
  Makefile.am:169: but option 'subdir-objects' is disabled
  Makefile.am:169: warning: source file 'src/unix/kqueue.c' is in a subdirectory,
  Makefile.am:169: but option 'subdir-objects' is disabled
  Makefile.am:174: warning: source file 'src/unix/linux-core.c' is in a subdirectory,
  Makefile.am:174: but option 'subdir-objects' is disabled
  Makefile.am:174: warning: source file 'src/unix/linux-inotify.c' is in a subdirectory,
  Makefile.am:174: but option 'subdir-objects' is disabled
  Makefile.am:174: warning: source file 'src/unix/linux-syscalls.c' is in a subdirectory,
  Makefile.am:174: but option 'subdir-objects' is disabled
  Makefile.am:174: warning: source file 'src/unix/proctitle.c' is in a subdirectory,
  Makefile.am:174: but option 'subdir-objects' is disabled
  Makefile.am:183: warning: source file 'src/unix/kqueue.c' is in a subdirectory,
  Makefile.am:183: but option 'subdir-objects' is disabled
  Makefile.am:183: warning: source file 'src/unix/netbsd.c' is in a subdirectory,
  Makefile.am:183: but option 'subdir-objects' is disabled
  Makefile.am:188: warning: source file 'src/unix/kqueue.c' is in a subdirectory,
  Makefile.am:188: but option 'subdir-objects' is disabled
  Makefile.am:188: warning: source file 'src/unix/openbsd.c' is in a subdirectory,
  Makefile.am:188: but option 'subdir-objects' is disabled
  Makefile.am:194: warning: source file 'src/unix/sunos.c' is in a subdirectory,
  Makefile.am:194: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/blackhole-server.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/dns-server.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/echo-server.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/run-tests.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/runner-unix.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/runner.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-active.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-async.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-barrier.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-callback-order.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-callback-stack.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-condvar.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-connection-fail.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-cwd-and-chdir.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-delayed-accept.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-dlerror.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-embed.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-fail-always.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-fs-event.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-fs-poll.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-fs.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-get-currentexe.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-get-loadavg.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-get-memory.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-getaddrinfo.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-getsockname.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-hrtime.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-idle.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-ip6-addr.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-ipc-send-recv.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-ipc.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-loop-handles.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-loop-stop.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-multiple-listen.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-mutexes.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-osx-select.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-pass-always.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-ping-pong.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-pipe-bind-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-pipe-connect-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-platform-output.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-poll-close.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-poll.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-process-title.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-ref.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-run-nowait.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-run-once.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-semaphore.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-shutdown-close.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-shutdown-eof.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-signal-multiple-loops.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-signal.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-spawn.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-stdio-over-pipes.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-bind-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-bind6-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-close-while-connecting.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-close.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-connect-error-after-write.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-connect-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-connect-timeout.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-connect6-error.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-flags.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-open.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-read-stop.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-shutdown-after-write.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-unexpected-read.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-write-to-half-open-connection.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tcp-writealot.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-thread.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-threadpool-cancel.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-threadpool.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-timer-again.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-timer-from-check.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-timer.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-tty.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-dgram-too-big.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-ipv6.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-multicast-join.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-multicast-ttl.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-open.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-options.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-udp-send-and-recv.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-util.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled
  Makefile.am:57: warning: source file 'test/test-walk-handles.c' is in a subdirectory,
  Makefile.am:57: but option 'subdir-objects' is disabled

for resolve il you can put the line" AUTOMAKE_OPTIONS = subdir-objects" at the top of Makefile.am

Regards,
D.

**Comment by bnoordhuis** [comment]
Out of curiosity, what version of automake is that?

**Comment by dmazzella** [comment]
automake (GNU automake) 1.14

**Comment by bnoordhuis** [comment]
Right. I usually test with 1.12, that's why I hadn't seen that warning yet. Thanks for the report, fixed in c82cea1.

**Comment by dmazzella** [comment]
;)
