### ISSUE TITLE
when i build this on ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#876]
sh autogen.sh 
autogen.sh: 17: [: unexpected operator
- libtoolize
- aclocal -I m4
- autoconf
- automake --add-missing
  configure.ac:19: option `serial-tests' not recognized

**Comment by jbergstroem** [comment]
Out of curiosity, what shell is that? ash?

**Comment by luoqi** [comment]
bash

**Comment by bnoordhuis** [comment]
Fixed in 0e4fa70, thanks for the bug report.  It's curious, I've known for at least 15 years that = is how you compare strings yet I keep making the same damn mistake...

I fixed the serial-tests a few days ago in e4c1483.  If it's still causing trouble for you, please post the output of `autoconf --version`, `automake --version` and `aclocal --version`.

**Comment by luoqi** [comment]
root@b:~# autoconf --version
autoconf (GNU Autoconf) 2.68
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html, http://gnu.org/licenses/exceptions.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
root@b:~# automake --version
automake (GNU automake) 1.11.3
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl-2.0.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey tromey@redhat.com
       and Alexandre Duret-Lutz adl@gnu.org.
root@b:~# acloacl --version
No command 'acloacl' found, did you mean:
 Command 'aclocal' from package 'automake1.10' (main)
 Command 'aclocal' from package 'automake' (main)
 Command 'aclocal' from package 'automake1.4' (main)
 Command 'aclocal' from package 'automake1.7' (universe)
 Command 'aclocal' from package 'automake1.9' (main)
acloacl: command not found
root@b:~# 

# 

thank you!

**Comment by bnoordhuis** [comment]
Does that mean it's still not working for you with the current HEAD of master?

By the way, it's spelled 'aclocal'.

**Comment by luoqi** [comment]
it worked nice!
1,i change the '==' by '='.
2,remove 'xxx-tests'.#sorry i forgeted it!.

# 

aclocal --version
aclocal (GNU automake) 1.11.3
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl-2.0.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey tromey@redhat.com
       and Alexandre Duret-Lutz adl@gnu.org.

**Comment by itbrandonsilva** [comment]
I'm actually (just pulled) having the same issue:

libtoolize: putting auxiliary files in `.'.
libtoolize: linking file`./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
- aclocal -I m4
- autoconf
- automake --add-missing
  configure.ac:19: option `serial-tests' not recognized

Further attempts yield only:
- libtoolize
- aclocal -I m4
- autoconf
- automake --add-missing
  configure.ac:19: option `serial-tests' not recognized

**Comment by itbrandonsilva** [comment]
Updated to latest version versions of autoconf and automake and no longer have any problems.

Previous versions:
Autoconf 2.68
Automake 1.11.3

**Comment by Schoonology** [comment]
With 0e4fa70, I'm still getting this issue (on the same version of Ubuntu), but I'm running Automake 1.11.3, which is the latest for Ubuntu.

Should I update to 1.12?

**Comment by bnoordhuis** [comment]
Can you guys try acf1310?  It's going through CI right now but it wouldn't hurt to have some independent confirmation.

> Should I update to 1.12?

No.  I try to maintain compatibility with 1.9 and up.  It's good to get the bug reports.

**Comment by Schoonology** [comment]
With 1.11.3, acf1310 worked like a charm, Ben. Thanks for the quick turnaround.

**Comment by bnoordhuis** [comment]
Thanks for testing, Michael. Landed in master.

**Comment by swinghu** [comment]
If you still have same problem ,it may be cause by "build-essential"
You should do sudo apt-get install build-essential libtool

reference:http://unix.stackexchange.com/questions/118550/autoreconf-fails-with-cant-exec-libtoolize
