### ISSUE TITLE
uv_timer_start(&timer,timer_cb,0,1000) cause an SIGSEGV

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#878]
uv_timer_start(&timer,timer_cb,0,1000);
----------------------------------------------^
i want the timer_cb immediately call when program started.
!!! the SIGSEGV create core file.
gdb the core file,maby point anywhere of my code!!!

when i use:
uv_timer_start(&timer,timer_cb,1,1000);

SIGNAL disapear!

**Comment by bnoordhuis** [comment]
Sorry, your report is almost incomprehensible.  Please post a complete test case and we'll take it from there.
