### ISSUE TITLE
assertion failed:req-inl.h line:219 expression: 0

### ISSUE THREAD

**Issue by dawnarc** [joyent/libuv#879]
![error](https://f.cloud.github.com/assets/3351764/957322/c3e9550c-044e-11e3-8faf-37cf42dbeb8c.png)
![error3](https://f.cloud.github.com/assets/3351764/957323/c3ead1fc-044e-11e3-8e44-5ce0d1487085.png)
![error2](https://f.cloud.github.com/assets/3351764/957324/c3eee4cc-044e-11e3-9160-99ce63d318a9.png)
![error4](https://f.cloud.github.com/assets/3351764/957325/c415de24-044e-11e3-8c0d-caed8d45fe81.png)
![error5](https://f.cloud.github.com/assets/3351764/957326/c417c32e-044e-11e3-9cc4-b5f822ab0508.png)

my env is:VS2012 sp2. develop on win7 x64 ultimate sp1. deploy on win2003 x64 enterprise sp2.
libuv version is 0.10.4. 

test case is about like this:
invoke uv_write function in multithread, when thread count is only 1, application runs fine. when the count of thread increase. assertion fail above would appear.

my partial code:

bool Client::SendData(char\* data, int size)
{
    //char b_len[PACK_LEN_HEAD];
    LOCK(m_Lock);
    if(size > m_SendMaxSize)
    {
        LOG_ERROR("size > m_SendMaxSize!! size:" << size << " ClientIP:" << this->m_RemoteIP);  
        return false;
    }

```
if(m_IsFree)
{
    LOG_ERROR("Client was close!!! index:" << m_Index);
    return false;
}

memcpy(m_SendPool, &size, PACK_LEN_HEAD);
memcpy(m_SendPool + PACK_LEN_HEAD, data, size);

uv_write_t* req = (uv_write_t*)malloc(sizeof *req);
req->data = new char[4];
memset(req->data, '\0', 4);
memcpy(req->data, 'aa', 2);
uv_buf_t buf = uv_buf_init(m_SendPool, PACK_LEN_HEAD + size);
//LOG_TRACE("[SendData] write.len:" << m_write_req.buf.len << " index:" << m_Index);
int r = uv_write(req, (uv_stream_t*)m_tcp_client, &buf, 1, KoanNetSrvImpl::after_write);
if(0 != r)
{
    uv_err_t err = uv_last_error(m_Loop);
    LOG_ERROR("[Client::SendData] " << uv_strerror(err) << " [syserr]:" << err.sys_errno_);
    ASSERT(0);
}
UNLOCK(m_Lock);
return r == 0;
```

}

**Comment by bnoordhuis** [comment]
Libuv is not thread-safe.  I can't give you advice on how to model your program (the issue tracker isn't really the place for that anyway) but the usual approach is to either have a) one event loop per thread, or b) one event loop thread where I/O happens and a bunch of worker threads that do CPU-bound processing.

**Comment by dawnarc** [comment]
ok, thx for your suggestion :)
