### ISSUE TITLE
Inconsistencies in powershell on windows

### ISSUE THREAD

**Issue by danielchatfield** [joyent/libuv#881]
I can't track down what exactly is the problem but setting the color using an ANSI code to magenta in powershell actually sets it to a dark blue color (which makes it almost impossible to read).

**Comment by danielchatfield** [comment]
Easiest way to reproduce issue is to `npm install` something - the `GET` or `200` etc. should be magenta.

**Comment by piscisaureus** [comment]
@danielchatfield Did you remap console colors in the console property page. It should look like this:

http://screencast.com/t/NnYfC7B5Dj

I don't really want to make libuv "compensate" for remapped colors.

**Comment by danielchatfield** [comment]
@piscisaureus To make sure this wasn't an issue with my setup I started a fresh EC2 instance running Windows Server 2012 and the issue occurred there as well.

**Comment by piscisaureus** [comment]
I have no clue, then. Libuv just uses `SetConsoleTextAttribute` ([here](https://github.com/joyent/libuv/blob/c82e7033a5d6c604b891c1f722cf23a063c202b0/src/win/tty.c#L1210-L1243)) as it should.

@sblom @jepickett Do you have any idea?

@glennblock @tjanczuk Powershell users, ever ran into this?

**Comment by danielchatfield** [comment]
I've just confirmed that this isn't a node bug (problem happens with python as well).

**Comment by danielchatfield** [comment]
This is my best guess at what is happening:

Powershell has a deep blue background colour by default and I suppose some Microsoft dev decided that since on windows you can only set the background to 16 different colours using `setConsoleTextAttribute` they would have to redefine one of those colours as the deep blue. Quite why they didn't just implement an API that allows a 256 colour spectrum like every other terminal, or even better: support ANSI codes, I don't know.

I guess the best thing to do is to always use the intense magenta `\x1b[95m` and steer clear of `\x1b[35m` in npm modules.

**Comment by okuoku** [comment]
You can change console 16 colour palette with SetConsoleScreenBufferInfoEx  :-p

Personally, I do not use blue background; we can change it with some script ( e.g. http://stackingcode.com/blog/2011/11/14/zenburn-powershell )
