### ISSUE TITLE
assert did not call uv_close()!!???

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#884]
shutdown_cb(uv_shutdown_t_req,int status){
uv_close((uv_handle_t_)req->handle,close_cb);
free(req);
}
close_cb(uv_handle_t*handle){
  onclose(handle);//server 
}

read_cb(uv_stream_t_stream,ssize_t nread,uv_buf_t buf){
if(nread<0){
uv_shutdown_t_ req=(uv_shutdown_t_)malloc(sizeof(uv_shutdown_t));
uv_shutdown(req,(uv_handle_t_)stream,shutdown_cb);
}
}

sometimes got this:

src/unix/stream.c:1027: uv__read: Assertion `!uv__io_active(&stream->io_watcher, 1) && "stream->read_cb(status=-1) did not call uv_close()"' failed.
Aborted

**Comment by bnoordhuis** [comment]
Libuv expects you to call uv_close() on error.  uv_shutdown() just shuts down the write end of the connection.

In what particular scenario would you call shutdown(SHUT_WR) rather than close() on a socket that's in an error state?

**Comment by luoqi** [comment]
is that you mean,if(nread<0),i do uv_close()?
but i did with uv_close,my server work good long time!

**Comment by bnoordhuis** [comment]
Yes (if I understand you correctly, I suspect there's a bit of a language barrier.)  Close the handle on error and you should be good.

**Comment by luoqi** [comment]
thank you!
