### ISSUE TITLE
process suspend with many connecting!

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#886]
i make many uv_connect in my server with a uv_listen in one uv_default_loop.
if connect_cb(status !=0 ) and i set a timer to reconnecting after 10 seconds.
sometimes later the process suspended and the cpu is 100% in command top!

**Comment by bnoordhuis** [comment]
And again, please see my comment [here](https://github.com/joyent/libuv/issues/888#issuecomment-22829847), the bug tracker is for reporting bugs.  Please only open issues if you think you have found a bug in libuv and have a reproducible test case.
