### ISSUE TITLE
Can i user pthread_mutex_lock or unlock?

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#888]
Can i user pthread_mutex_lock or unlock,in read_cb and write_cb and timer_cb?
and may i must to use it?
if i has many server and connections?

**Comment by bnoordhuis** [comment]
Can you stop opening issues for what are basically 'help needed' questions?  The bug tracker is for, well, reporting bugs.  Please use the mailing list: http://groups.google.com/group/libuv

**Comment by luoqi** [comment]
ok,thank you,and i never know 'help needed',but i now clear!

**Comment by luoqi** [comment]
ohhhh,i can't open the google groups,chrome return ERR_ADDRESS_INVALID!
any other site or docment for this?

**Comment by bnoordhuis** [comment]
Maybe a temporary hiccup? It works for me.
