### ISSUE TITLE
uv_write in uv_queue_work Segmentation fault

### ISSUE THREAD

**Issue by luoqi** [joyent/libuv#889]
log.txt
uv_read
proc
uv_write
uv_write ok
uv_read
proc
uv_write
uv_read
proc
uv_write
uv_write ok
uv_write ok
Segmentation fault(core dumped)

gdb
bt
uv__write
uv_write2
uv_write
......

**Comment by saghul** [comment]
Do you expect anybody to just guess what is going on based on the log of an application for which you didn't provide the source code? Please try to make meaningful bug reports by attaching some test program that shows the failure, for example. Otherwise there is no way to help you.

**Comment by luoqi** [comment]
if i not use uv_queue_work.
only call proc function,the server is work good.
but the proc function will process mysql maby use long time.

**Comment by luoqi** [comment]
typedef struct __WORK{
    void\* srv;
    uv_tcp_t\* pc;
    long len;
    void\* data;
}_WORK;
static void work_cb(uv_work_t_req){
    _WORK_ w=(_WORK*)req->data;

```
dbserver* pdb=(dbserver*)w->srv;

pack<> p;
p.put(w->data,w->len);
pdb->proc(w->pc,p);

//SAFEFREE(w->data);
```

}
static void after_work_cb(uv_work_t*req,int status){
    MYASSERT(status==0);
    SAFEFREE(req->data);
    SAFEFREE(req);
}

bool dbserver::dosrvmsg(uv_tcp_t\* pc,pack<>& p){

```
uv_work_t* req=(uv_work_t*)MALLOC(sizeof(uv_work_t));

_WORK* w=(_WORK*)MALLOC(sizeof(_WORK));
w->srv=this;
w->pc=pc;
w->len=p.len();
void* data=MALLOC(w->len);
w->data=data;
memcpy(data,p.data(),w->len);

req->data=w;

int r=uv_queue_work(uv_default_loop(),req,work_cb,after_work_cb);
//int r=uv_work_queue(uv_default_loop(),req,work_cb,after_work_cb);
MYASSERT(r==0);
```

//if not use above codes, it work good 
    //proc(pc,p);

```
return true;
```

}
void dbserver::proc(uv_tcp_t*pc,pack<>&p){
    ...
    m_db.exec_proc(sql);
    ...

```
m_srv.sendmsg(...);
```

}

**Comment by bnoordhuis** [comment]
See [my comment](https://github.com/joyent/libuv/issues/888#issuecomment-22829847) on your other issue - please use the mailing list for this.

A note on test cases: they should be succinct and self-contained, i.e. not pull in a million dependencies without which it won't compile.
