### ISSUE TITLE
mingw broken: cc: Command not found 

### ISSUE THREAD

**Issue by japj** [joyent/libuv#89]
It seems on mingw, it tries to use cc instead of gcc.. as a result I get:

<pre>
japj@PC-MD8860 /c/github/libuv
$ make
cc -Iinclude -g --std=gnu89 -D_WIN32_WINNT=0x0501 -Isrc/ares/config_win32 -c src/uv-win.c -o src/uv-win.o
make: cc: Command not found
make: *** [src/uv-win.o] Error 127
</pre>

**Comment by japj** [comment]
according to git bisect, this commit broke mingw (update comment, because I was still one step away from first bad commit) :

$ git bisect bad
9518ab65949257384bf7e407d8502a6437fdda4b is the first bad commit
commit 9518ab65949257384bf7e407d8502a6437fdda4b
Author: Ryan Dahl ry@tinyclouds.org
Date:   Thu Jul 7 08:32:29 2011 -0700

```
Allow user to specify CC env var (CC=clang make)
```

:100644 100644 a115277a9deaf6860425f3664dddbbaf1e3a24fe be8abca1cbe14bc2a6068c495f836b8d4e513fdf M      config-mingw.mk
:100644 100644 2def593b7fdb179e7f2424fa2d8cd7ea0ba585f8 862af2d47b086d8b206314bfdac19a922b66313c M      config-unix.mk

**Comment by bnoordhuis** [comment]
9518ab6 uses ?= conditional assignment (assign unless already set) but `make` has CC set to `cc` by default.

PS: this happens on Unices too but since `cc` is a symlink to `gcc`, it doesn't actually break the build.
