### ISSUE TITLE
segfault on windows using tcp

### ISSUE THREAD

**Issue by stakach** [joyent/libuv#899]
I'm having issues on Windows doing anything with TCP after linking to a dynamic libuv.dll library

All other libuv features work without issue and I'm struggling to work out the issue.
The same code runs fine on Linux and OSX

The project in question is here: https://github.com/cotag/libuv (ruby bindings to libuv)
The failing test on windows: https://github.com/cotag/libuv/blob/master/spec/tcp_spec.rb

**Comment by bnoordhuis** [comment]
Sorry, but there is not enough information for me here to act on.  Can you try to create a reduced test case?  Please make sure it's standalone, i.e. requires just libuv and nothing else.

Failing that, run your project in a debugger and capture the stack trace at the point of the segmentation fault, then post that here.

**Comment by retep998** [comment]
I believe I may have run into the same problem, but this time using Rust using libgreen which uses libuv. I even have a backtrace!

https://github.com/rust-lang/rust/issues/15231

EDIT: Nevermind, it seems to have been purely a race condition with Rust.
