### ISSUE TITLE
udp: make SO_REUSEADDR / SO_REUSEPORT opt-in

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#905]
See commit d3308c2.  Libuv sets SO_REUSEADDR on both UDP and TCP sockets.

For TCP, it makes sense ("let me re-use this port that's in the TIME_WAIT state".)

For UDP, SO_REUSEADDR means something completely different: in effect, it lets you steal the port from another process provided that other process also set the flag.

Libuv's behavior here is kind of confusing and AFAICT there is no reason for it to be like that except as an unfortunate accident of history.

I propose we move it out of uv_udp_open() and uv_udp_bind() and make it explicit through e.g. a uv_udp_reuse_addr() function or maybe change the function prototype of the first two to take an additional flag argument.

@piscisaureus RFC, please.

**Comment by piscisaureus** [comment]
@bnoordhuis 

Seems reasonable. Can we just use that flags field that also bears `UV_UDP_IPV6ONLY` ?

**Comment by saghul** [comment]
Oh, looks like this one was fixed :-) https://github.com/joyent/libuv/commit/3558d65d2f173ff7a8148d340a31741aaa5b35f9
