### ISSUE TITLE
windows: PATH=";.;" causes uv_spawn to infinitely loop

### ISSUE THREAD

**Issue by alexcrichton** [joyent/libuv#909]
Using this code:

``` c
#include "uv.h"
#include <stdio.h>

uv_loop_t *loop;
uv_process_t child_req;
uv_process_options_t options;

void on_exit(uv_process_t *p, int exit_status, int term_status) {
    printf("%p %d %d\n", p, exit_status, term_status);
}

int main() {
    loop = uv_default_loop();

    char* args[3];
    args[0] = "mkdir";
    args[1] = "test-dir";
    args[2] = NULL;

    options.exit_cb = on_exit;
    options.file = "mkdir";
    options.args = args;

    int ret;
    if ((ret = uv_spawn(loop, &child_req, options)) != 0) {
        fprintf(stderr, "%s\n", uv_strerror(ret));
        return 1;
    }

    return uv_run(loop, UV_RUN_DEFAULT);
}
```

The code will infinitely loop on windows when run with `PATH=";.;"`. I ran this in mingw, but it may be a problem elsewhere. We found this when working on rust, and @vadimcn fixed the issue with this patch:

``` patch
diff --git a/src/win/process.c b/src/win/process.c
index 477e5e4..e2eb3a3 100644
--- a/src/win/process.c
+++ b/src/win/process.c
@@ -374,15 +374,6 @@ static WCHAR* search_path(const WCHAR *file,
                                   name_has_ext);

     while (result == NULL) {
-      if (*dir_end == L'\0') {
-        break;
-      }
-
-      /* Skip the separator that dir_end now points to */
-      if (dir_end != path) {
-        dir_end++;
-      }
-
       /* Next slice starts just after where the previous one ended */
       dir_start = dir_end;

@@ -393,27 +384,33 @@ static WCHAR* search_path(const WCHAR *file,
       }

       /* If the slice is zero-length, don't bother */
-      if (dir_end - dir_start == 0) {
-        continue;
+      if (dir_end - dir_start > 0) {
+        dir_path = dir_start;
+        dir_len = dir_end - dir_start;
+
+        /* Adjust if the path is quoted. */
+        if (dir_path[0] == '"' || dir_path[0] == '\'') {
+          ++dir_path;
+          --dir_len;
+        }
+
+        if (dir_path[dir_len - 1] == '"' || dir_path[dir_len - 1] == '\'') {
+          --dir_len;
+        }
+
+        result = path_search_walk_ext(dir_path, dir_len,
+                                      file, file_len,
+                                      cwd, cwd_len,
+                                      name_has_ext);
       }

-      dir_path = dir_start;
-      dir_len = dir_end - dir_start;
-
-      /* Adjust if the path is quoted. */
-      if (dir_path[0] == '"' || dir_path[0] == '\'') {
-        ++dir_path;
-        --dir_len;
-      }
-
-      if (dir_path[dir_len - 1] == '"' || dir_path[dir_len - 1] == '\'') {
-        --dir_len;
+      /* Stop if reached end of the line */
+      if (*dir_end == L'\0') {
+        break;
       }
-
-      result = path_search_walk_ext(dir_path, dir_len,
-                                    file, file_len,
-                                    cwd, cwd_len,
-                                    name_has_ext);
+      
+      /* Skip the separator that dir_end now points to */
+      dir_end++;
     }
   }

```

I haven't looked too much into it, but I figured that I should report it here as well to make sure you guys are aware of it!

**Comment by vadimcn** [comment]
BTW, handling of quoted path components also looks wrong to me - after finding the opening quote, search_path should continue till it hits the closing one.  This path `c:\dir1;"c:\dir2;foo;bar";c:\dir3` contains 3 components, not 5.

**Comment by piscisaureus** [comment]
Piling up issues - I see we treat a single quote as a quotation char but that's not okay.

**Comment by piscisaureus** [comment]
I have no time to fix PATH parsing right now. However I did some investigation into how quotes inside PATH are interpreted. Here are the rules that cmd.exe follows:
- A path entry may contain quoted parts. Quoted parts are valid even in the middle of a path, e.g. `c:\win"dows"\system32` would be perfectly legal, and it would search `c:\windows\system32`.
- However a path entry may not contain any _empty_ quoted parts, so `c:\""windows` is invalid. If cmd.exe encounters this it abandons PATH scanning completely. It will however look in directories that are 'to the left' of the offending construct.
- The last PATH entry may contain an unbalanced quote, it is treated as if it were implicitly closed. So `PATH=c:\windows;"c:\stuff` searches both `c:\windows` and `c:\stuff`.
- Only a double quote `"` is treated as a quotation mark - a single quote isn't.
- Note that a quotation mark character is not valid inside a filename on windows (*). Therefore there is no way, or need, to escape characters.

(*) terms and condition apply

**Comment by vadimcn** [comment]
BTW2: Does it bother uv folks that path searching is a synchronous operation?  If some path component points to an unavailable network location, GetFileAttributes() may take a looong time.

**Comment by piscisaureus** [comment]
@vadimcn 

It used to bother me to some extent but we've got bigger fish to fry. However if you feel like writing a patch, you're welcome :)

One of the problems would be that some programs might rely on the pid of the spawned process to be available immediately, which is not possible if we make the path search async. We'd probably have to add a callback that gets called when the process has been spawned and a pid is available.

@bnoordhuis Any comments?

**Comment by bnoordhuis** [comment]
Sounds fine to me.  On that subject, it kind of bothers me that uv_spawn() sometimes returns errors synchronously and sometimes asynchronously.  IMO, for ease of use and consistency it should always be async.

**Comment by piscisaureus** [comment]
@bnoordhuis I think currently it reports almost all "handle-able" errors asynchronously. Only out-of-resource conditions and errors due to invalid arguments are reported immediately. I'd be open to fixing that, although the same issue with `uv_write` (on windows) bothers me much more.

**Comment by saghul** [comment]
@piscisaureus should the patch be applied? I talked to some Rust guys on IRC and apparently this is still needed.

**Comment by piscisaureus** [comment]
Yes this is an actual bug. It's been a while but iirc there was something wrong with the obvious patch too...

Verstuurd vanaf mijn iPad

Op 29 mrt. 2014 om 10:39 heeft "Sa?l Ibarra Corretg?" <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@piscisaureushttps://github.com/piscisaureus should the patch be applied? I talked to some Rust guys on IRC and apparently this is still needed.

##

**Comment by saghul** [comment]
On 03/29/2014 12:15 PM, Bert Belder wrote:

> Yes this is an actual bug. It's been a while but iirc there was
> something wrong with the obvious patch too...

Ah, ok then.
