### ISSUE TITLE
`spawn_setuid_setgid` failed: exit code 134

### ISSUE THREAD

**Issue by notorand-it** [joyent/libuv#910]
libuv is failing the "make check" on Linux Ubuntu 12.04.4 (32bits).
Source has been downloaded today from https://github.com/joyent/libuv/archive/master.zip

A core has been dumped in the build directory.
This is the last part of the output:
# 

`spawn_setuid_setgid` failed: exit code 134
Output from process `spawn_setuid_setgid`:
exit_cb
# Assertion failed in test/test-spawn.c on line 60: exit_status == 1
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `/usr/src/libuv-master'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`/usr/src/libuv-master'
make: **\* [check] Error 2

I don't know whether I needto attach extra files for details.

**Comment by bnoordhuis** [comment]
That's probably harmless.  Am I right that the following conditions hold?
- You run the test as root.
- The permissions on the run-tests binary won't allow another user to run it.

The test changes UID and GID to user 'nobody' and then tries to execute the run-tests binary again.  If you have a restrictive umask set up, that won't work.  In that case, exit_code will probably be UV_EACCES.

**Comment by bnoordhuis** [comment]
No follow-up.  I'll assume the write-up from my previous comment is correct.  :-)  Cheers.
