### ISSUE TITLE
v0.11.11 causes assertion errors in Node

### ISSUE THREAD

**Issue by isaacs** [joyent/libuv#911]
```
$ cat c.js
process.on('exit', function() {
  console.log('ok');
});

$ ./node c.js
ok
Assertion failed: (!uv__has_active_reqs(loop)), function uv__loop_delete, file ../deps/uv/src/unix/loop.c, line 150.
Abort trap: 6
```

Commenting out line 150 of `src/unix/loop.c` makes everything work fine.

This was added in 3f2d4d535867a99170b4964f2e3db1ef70968c23 by @bnoordhuis (indeed, it's all that 3f2d4d535867a99170b4964f2e3db1ef70968c23 does), so perhaps Node is one of those programs calling `uv_loop_delete()` when there are still outstanding work reqs?

**Comment by isaacs** [comment]
By the way, it may well be that this is a node bug rather than a libuv bug.  Just tracked down an otherwise-seems-to-be-fine Node program to this line in libuv, so figured we could start over here.

**Comment by piscisaureus** [comment]
Yes, this is a node bug. Probably it's [this](https://github.com/joyent/node/blob/a9eb96d/src/node.cc#L3182) invocation, so it only affects the debug build.

Deleting a loop that has pending requests (or open handles) can lead to memory corruption and other badness. Therefore removing this assertion is not the way forward.

**Comment by tjfontaine** [comment]
On the contrary, run `python tools/test.py internet` you'll see that test-dns will fail, and there are other scenarios in release mode this happens

**Comment by tjfontaine** [comment]
didn't actually mean to reopen.

**Comment by bnoordhuis** [comment]
> run python tools/test.py internet you'll see that test-dns will fail, and there are other scenarios in release mode this happens

Yeah, NDEBUG is never defined in UNIX builds.

I added that call to uv_loop_delete() in joyent/node@556b890 with the express purpose of catching bugs.  Seems it works. :-)

The tests all pass for me on Linux and OS X, including the internet ones, but I can reproduce it with Isaac's example.  I'll take a look - node probably needs to walk the open handles and close them before exiting.
