### ISSUE TITLE
AIX does not work

### ISSUE THREAD

**Issue by chaocc** [joyent/libuv#916]
game on aix,using uv_tcp_t,but error.
uv__platform_loop_init,uv__platform_loop_delete,uv__io_poll won‘t define inside aix.c.
if the uv_tpc_t can work on aix platform？
 thinks.

**Comment by bnoordhuis** [comment]
AIX is not a supported platform but I'll entertain patches.  There is a libuv fork somewhere that has AIX support (maintained by IBM people, if I'm not mistaken), maybe bug them about upstreaming their changes.  Good luck. :-)
