### ISSUE TITLE
doc: add documentation

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#924]
- [ ] write a tutorial or short primer?
- [ ] write manual / reference documentation
- [ ] generate and upload docs with every release

/cc @piscisaureus

**Comment by saghul** [comment]
I started writing API documentation here: https://github.com/libuv/api-docs. Live version is here, updated with every commit: http://libuv.readthedocs.org/en/latest/

**Comment by saghul** [comment]
This should cover the last 2 points of the list, which should hopefully be enough for now: https://github.com/joyent/libuv/pull/1459

**Comment by saghul** [comment]
#1459 landed, closing!
