### ISSUE TITLE
v0.11.13 getaddrinfo_fail: status < 0

### ISSUE THREAD

**Issue by curiousleo** [joyent/libuv#925]
`make check` fails with

```
`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
```

**Comment by bnoordhuis** [comment]
Sorry for the delayed reply.  Do you get that test failure consistently?

**Comment by curiousleo** [comment]
Hi, no worries! I just pulled the latest changes from master, and `make check` passes now.

**Comment by bnoordhuis** [comment]
That's great to hear, thanks for following up.
