### ISSUE TITLE
windows: use multimedia timer instead of GetTickCount

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#929]
Instead of using `GetTickCount()`, use a multimedia timer (`timeGetTime()`).

`timeGetTime` has millisecond resolution is is still reasonably fast.

I means we could get rid of that silly timer forward-fudging after calling `GetQueuedCompletionStatus`.

The downside is that libuv and libuv users now have to link with the `winmm` library.

For node it doesn't matter because v8 requires winmm anyway - for the same reason: it uses timeGetTime to implement the Date object.

**Comment by bnoordhuis** [comment]
Can't you load winmm dynamically?

**Comment by piscisaureus** [comment]
@bnoordhuis Yes, but what would be the advantage of that?

**Comment by bnoordhuis** [comment]
That libuv users don't have to link to winmm?  It's basically the same thing we do now for ApplicationServices / CoreServices / CoreFoundation on OS X.

**Comment by donatasm** [comment]
And why not use `QueryPerformanceCounter` and `QueryPerformanceFrequency` instead? `timeGetTime` function can still have a precision of 5 milliseconds or more. Would it be difficult to change `DWORD` to `LARGE_INTEGER` to store ticks? Timers would be more precise and it would last a bit longer than 49.71 days until overflow.

**Comment by piscisaureus** [comment]
@donatasm A long time ago libuv did that, but it had detrimental effects on performance.

**Comment by jjqq2013** [comment]
I think it's better use NtGetSystemTime. It is more actuate than GetTickCount. (In fact GetTickCount is based on result of NtGetSystemTime)
Regards.

**Comment by saghul** [comment]
Closing as it's beaing dealt with in https://github.com/joyent/libuv/pull/1165.

**Comment by piscisaureus** [comment]
Actually closing :)
