### ISSUE TITLE
Properly handle file change events 

### ISSUE THREAD

**Issue by helmus** [joyent/libuv#938]
Is there any reason why the file change api callback only has `UV_RENAME` and `UV_CHANGE` ?

It seems to me like handling rename/add/remove events would not be to difficult as these are being flattened intentionally in the implementation both on unix and windows.

**Comment by bnoordhuis** [comment]
It's because rename and change are the greatest common denominator.  When you say 'unix', I assume you mean 'linux' but libuv also runs on platforms like the BSDs and Solaris that have distinctly less flexible file system event APIs.
