### ISSUE TITLE
uv_read_start return value and read_cb

### ISSUE THREAD

**Issue by klutzy** [joyent/libuv#944]
Hello! When I was debugging Rust, I found `uv_read_start` may not call `read_cb` in some cases. Since Rust's I/O currently utilizes callback for scheduling, it is critical to know whether `read_cb` is called by uv or not.

Initially I guessed that the return value from `uv_read_start` indicates whether `read_cb` is called or not. However, it is not true on win32: it returns [zero for tty](https://github.com/joyent/libuv/blob/master/src/win/tty.c#L814) if it has `UV_HANDLE_READ_PENDING` flag.

So I now think: return value only means that there was no critical error, not necessarily that `read_cb` has been called. Is it right? Then I'm also curious if there is a way to know it.

**Comment by bnoordhuis** [comment]
> So I now think: return value only means that there was no critical error, not necessarily that read_cb has been called. Is it right?

That's correct.  uv_read_start() merely tells libuv to start listening for incoming data.  If or when your callback is invoked is indeterminate but it will be at least one event loop tick in the future.  Does that answer your question?

**Comment by klutzy** [comment]
It is now clear to me. Thanks!
