### ISSUE TITLE
uv_pipe_bind fail on windows 7 64 bit , compiled use mingw-w64

### ISSUE THREAD

**Issue by armgong** [joyent/libuv#947]
# define TEST_PIPENAME "test-pipe"

int main(int argc, char **argv)
{
  uv_pipe_t server1, server2;
  int r;

  r = uv_pipe_init(uv_default_loop(), &server1, 0);
  assert(r == 0);
  r = uv_pipe_bind(&server1, TEST_PIPENAME);
  assert(r == 0); //****************fail on this line,mean uv_pipe_bind fail

  return 0;
}

**Comment by saghul** [comment]
That's not a valid pipe name on Windows, AFAIK, try this one instead: https://github.com/joyent/libuv/blob/master/test/task.h#L39

**Comment by armgong** [comment]
it works ,thanks a lot
