### ISSUE TITLE
windows (w64-mingw32) s,-lphlpapi2,-liphlpapi,

### ISSUE THREAD

**Issue by rurban** [joyent/libuv#951]
I needed to replace `-lphlpapi2` by the older `-liphlpapi` on my w64-mingw32 environment.
stackoverflow also suggests that GetAdaptersAddresses is provided by `-liphlpapi`

http://stackoverflow.com/questions/10972794/undefined-reference-to-getadaptersaddresses20-but-i-included-liphlpapi

I'm not sure how to check for this in a m4 on mingw.

```
diff --git a/Makefile.am b/Makefile.am
index a06596f..f65ccf6 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -41,7 +41,7 @@ include_HEADERS += include/uv-win.h include/tree.h
 AM_CPPFLAGS += -I$(top_srcdir)/src/win \
                -DWIN32_LEAN_AND_MEAN \
                -D_WIN32_WINNT=0x0600
-LIBS += -lws2_32 -lpsapi -lphlpapi2
+LIBS += -lws2_32 -lpsapi -liphlpapi
 libuv_la_SOURCES += src/win/async.c \
                     src/win/atomicops-inl.h \
                     src/win/core.c \
```

**Comment by saghul** [comment]
@rurban I just tested the autotools build on a freshly updated MinGW (using mingw-get.exe) and I didn't get any problem. Is this an issue only with the w64 version and not the original one?

**Comment by rurban** [comment]
@saghul yes, w64-mingw32 only

**Comment by saghul** [comment]
@rurban do you know of any preprocessor define which applies only to w64-mingw32? You can get a list of all of them as follows:

```
gcc -dM -E - < /dev/null
```

**Comment by rurban** [comment]
Sorry, a bit late. It's not that easy, as I see no significant differences.
The real problem is the different win32api.

old mingw32 vs w64-mingw32 on linux (cross compilers):

```
$ diff -bu0 i686-pc-mingw32-gcc.defs i686-w64-mingw32-gcc.defs
--- i686-pc-mingw32-gcc.defs    2014-04-25 15:52:45.865025048 -0500
+++ i686-w64-mingw32-gcc.defs   2014-04-25 15:50:43.934166503 -0500
@@ -27 +27 @@
-#define __GNUC_PATCHLEVEL__ 3
+#define __GNUC_PATCHLEVEL__ 2
@@ -61,0 +62 @@
+#define _REENTRANT 1
@@ -79,0 +81 @@
+#define __USING_SJLJ_EXCEPTIONS__ 1
@@ -82,0 +85 @@
+#define __ATOMIC_HLE_RELEASE 131072
@@ -84,0 +88 @@
+#define __ATOMIC_HLE_ACQUIRE 65536
@@ -88 +91,0 @@
-#define __GCC_HAVE_DWARF2_CFI_ASM 1
@@ -105 +108 @@
-#define __VERSION__ "4.7.3"
+#define __VERSION__ "4.8.2"
@@ -213 +216 @@
-#define __GNUC_MINOR__ 7
+#define __GNUC_MINOR__ 8
```

on a cygwin systems it's:

```
$ diff -bu0 i686-pc-mingw32-gcc.defs i686-w64-mingw32-gcc.defs
--- i686-pc-mingw32-gcc.defs    2014-04-25 15:37:54.382575000 -0500
+++ i686-w64-mingw32-gcc.defs   2014-04-25 15:42:12.446975000 -0500
@@ -27 +27 @@
-#define __GNUC_PATCHLEVEL__ 3
+#define __GNUC_PATCHLEVEL__ 2
@@ -79,0 +80 @@
+#define __USING_SJLJ_EXCEPTIONS__ 1
@@ -82,0 +84 @@
+#define __ATOMIC_HLE_RELEASE 131072
@@ -84,0 +87 @@
+#define __ATOMIC_HLE_ACQUIRE 65536
@@ -88 +90,0 @@
-#define __GCC_HAVE_DWARF2_CFI_ASM 1
@@ -105 +107 @@
-#define __VERSION__ "4.7.3"
+#define __VERSION__ "4.8.2"
@@ -213 +215 @@
-#define __GNUC_MINOR__ 7
+#define __GNUC_MINOR__ 8
```

**Comment by saghul** [comment]
Hey @rurban, I just found something. Apparently this is how you tell MinGW and MinGW-w64 appart in a C file:

```
#ifdef __MINGW32__
#include <_mingw.h> /* private MinGW header */
# ifdef __MINGW64_VERSION_MAJOR
#  define __this_is_mingw_w64__ /* or whatever */
# else
#  define __this_is_mingw_org__ /* or whatever */
# endif
#endif /* __MINGW32__ */
```

Not sure how we can use this in autoconf though :-/

**Comment by tkelman** [comment]
`AC_PREPROC_IFELSE` ? http://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Running-the-Preprocessor.html

Hm, was the requested change here already made in https://github.com/joyent/libuv/commit/4c6294e69b007b1038f3dc452a68703371c19789 ?

**Comment by saghul** [comment]
Testes MinGW-w64 and go no problems, can this be closed?

**Comment by saghul** [comment]
I've been testing MinGW (both mingw32 and mingw-w64 projects) lately and never ran into this. Closing.
