### ISSUE TITLE
Allow build with "Command Line Tools for Xcode" (again)

### ISSUE THREAD

**Issue by schlamar** [joyent/libuv#953]
I have a setup on OSX according to the homebrew installation manual: https://github.com/mxcl/homebrew/wiki/Installation and using the "Command Line Tools for Xcode" instead of the complete Xcode app. 

I would like to build libuv with the Command Line Tools but it looks like there is no way to build the current master of libuv without having Xcode installed. Both instructions fail:

```
$ sh autogen.sh 
+ glibtoolize
autogen.sh: line 43: glibtoolize: command not found

$ ./gyp_uv -f make
['-f', 'make', '/Users/marc/Documents/python/pylibuv/libuv/uv.gyp', '-I', '/Users/marc/Documents/python/pylibuv/libuv/common.gypi', '--depth=.', '-Goutput_dir=/Users/marc/Documents/python/pylibuv/libuv/out', '--generator-output', '/Users/marc/Documents/python/pylibuv/libuv/out', '-Dgcc_version=42', '-Dclang=1', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dlibrary=static_library', '-Dcomponent=static_library']
xcode-select: Error: No Xcode is selected. Use xcode-select -switch /Applications/Xcode.app to select /Applications/Xcode.app, or see the xcode-select manpage (man xcode-select) for further information.
Error: /usr/bin/xcode-select returned unexpected error.

gyp: Error 1 running xcodebuild
Error running GYP
```

This worked fine in the v10 branch (by just using "make").

**Comment by schlamar** [comment]
Ok, this is an upstream bug:
- https://code.google.com/p/gyp/issues/detail?id=292
- https://github.com/joyent/node/issues/3681#issuecomment-23140289

**Comment by bnoordhuis** [comment]
@schlamar You can install glibtoolize with `brew install libtool`
