### ISSUE TITLE
github master 'make check' fails

### ISSUE THREAD

**Issue by jvburnes** [joyent/libuv#974]
I cloned 'master' (version 11.14) onto my ubuntu 13.04 machine, did the usual 'sh autogen.sh' make sequence.  The build worked, but the 'make check' failed in the following way:
# 

`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `./libuv'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`./libuv'
make: **\* [check] Error 2

**Comment by indutny** [comment]
Don't tell me you have "xyzzy.xyzzy.xyzzy" domain in network. What does `dig xyzzy.xyzzy.xyzzy` return on your machine?

**Comment by jvburnes** [comment]
Strangely it does resolve.   I suppose the test was supposed to fail.   The inside corporate dns probably resolves to some generic web server.

**Comment by jvburnes** [comment]
Would the lookup failure test be valid if you performed a lookup on an invalid name?

**Comment by indutny** [comment]
Heh, I think you can just ignore failure then. Generally, this test is working for everyone.
