### ISSUE TITLE
unix: Could posix_spawn be used to improve uv_spawn?

### ISSUE THREAD

**Issue by alexcrichton** [joyent/libuv#978]
I've been using `uv_spawn` recently, and one of the weird things which I've found from using it is that both `fork` can fail, and then the child's `exec` can also fail, but one is reported as the return of `uv_spawn` and the other is reported via the `exit_cb`. This seems a little odd, as in theory both are a "spawn failure" and would both be reported as a return value of `uv_spawn`.

I'm curious if libuv would consider using the `posix_spawn` function instead of fork/exec? I certainly don't claim to be an expert on the posix_spawn, but it appears to combine the fork/exec into one, and I think that using it would solve this problem of reporting an exec failure immediately instead of delaying it for a callback. One thing that I would be concerned about is whether `posix_spawn` is supported everywhere, which I'm not sure of.

I briefly glanced at the windows code, and it looked like the "exec error" is reported asynchronously to behave the same as the unix implementation, but it could easily be modified to be returned immediately instead.

I've also heard of the suggestion of using a pipe with `O_CLOEXEC` set. That way you can know if the process successfully invoked `exec` or not from the caller side of things. I'm not sure this is completely feasible, as I'd want the calling thread to block on this read (waiting for the child to finish `exec`), and the block could possibly take awhile.

**Comment by bnoordhuis** [comment]
> I've been using uv_spawn recently, and one of the weird things which I've found from using it is that both fork can fail, and then the child's exec can also fail, but one is reported as the return of uv_spawn and the other is reported via the exit_cb. This seems a little odd, as in theory both are a "spawn failure" and would both be reported as a return value of uv_spawn.

That's something we can change.  My gut reaction is to change it to reporting all errors to the callback because that's more in line with other API functions.  On the other hand, returning the error might be more convenient and is faster (relevant if you're walking directories in search of the binary to execute.) 

> I'm curious if libuv would consider using the posix_spawn function instead of fork/exec? I certainly don't claim to be an expert on the posix_spawn, but it appears to combine the fork/exec into one, and I think that using it would solve this problem of reporting an exec failure immediately instead of delaying it for a callback. One thing that I would be concerned about is whether posix_spawn is supported everywhere, which I'm not sure of.

I've toyed with the idea in the past but that would leave out users of older openbsd and netbsd releases in the cold (both didn't get a working posix_spawn until last year.)  I guess it's possible to emulate basic posix_spawn functionality on those platforms.

> I've also heard of the suggestion of using a pipe with O_CLOEXEC set. That way you can know if the process successfully invoked exec or not from the caller side of things.

Libuv already does that.  In fact, I think that was one of my first contributions to libuv   :-)

**Comment by alexcrichton** [comment]
Oh interesting! I see I didn't read the code closely enough. How would you feel about changing the api to report the exec error synchronously then? I think it would still be nice if the error to `exec` is reported as returned by `uv_spawn` instead of the callback, though, because it seems like more of a spawn error then a reason to invoke `exit_cb`. It also seems like all the information is available by the time `uv_spawn` returns, so perhaps not that difficult to implement.

Additionally, then there wouldn't be a dual meaning in the `exit_cb` of what `exit_status` is. Currently it looks like if it's negative it indicates a spawn failure, but if it's non-negative it's an exit code.

The only other argument I've ever heard of for posix_spawn is that it's orders of magnitude faster on linux, but leaving old users behind and/or having an implementation of posix_spawn for older users also sounds fairly difficult, so it may not outweigh the benefits of being a little faster at creating new processes.

**Comment by bnoordhuis** [comment]
> The only other argument I've ever heard of for posix_spawn is that it's orders of magnitude faster on linux

That's because glibc's posix_spawn implementation calls vfork() instead of fork() when possible.

vfork() is indeed a bit faster (though not earth-shattering so unless, for example, your process has really big page tables that need copying) but unsafe with almost all operations except execve().

It wouldn't really help in libuv anyway because we normally have to set up file descriptors and such after the fork.  Besides, any potential speedup probably gets drowned out by the overhead of the dynamic linker. :-)

**Comment by jneu** [comment]
@alexcrichton and @bnoordhuis -
I'm interested in the opposite use case: I'm trying to spawn a large number of processes at one time. Think a `make` clone that needs to spawn worker processes, most of which will succeed.

Any thoughts about having two APIs? Use `uv_spawn()` for find-as-many-errors-as-possible-synchronously for fast-fail sequential needs, and a new `void uv_async_spawn()` for reporting all errors asynchronously? The new API would allow for spawning of a large number of children quickly and cleans up the error reporting by pushing all of it to the callback. I'm going to prototype out this type of support to see if there's any real performance gain, but I would love to hear your thoughts.

**Comment by alexcrichton** [comment]
When I submitted a patch to close this issue, there wasn't much asynchronous-ness to reporting the error. On both windows and linux the process would block waiting to receive the error, and then it would just simply report the error in the callback instead of as the return value to `uv_spawn`. Basically, from an implementation perspective, all of the machinery was there to `return error` instead of `return 0; report_error_later();`.

If a new API, `uv_async_spawn` were to be created, then I would imagine that `uv_spawn` would be obsoleted. This would however require a large restructuring of the existing code in order to truly asynchronously report errors. I'm not very familiar with the windows code, but at least for the unix code this would be returning immediately after the call to `fork()`, but that may not be possible (I didn't write the code in the first place so I'm probably glossing over details).

From what I remember when reading the code, a "super asynchronous" error reporting method conceptually seems the way to go, but implementation-wise it seemed like it may be difficult, but I could very well be wrong!

**Comment by saghul** [comment]
I find the behavior after https://github.com/joyent/libuv/commit/f764bff699e9897c3ed795a838acd9c1c8ec8133 to be correct. If either fork or exec failed we consider uv_spawn as failed, if the process was started you'll get the termination status in the callback.

**Comment by jneu** [comment]
> I'm not very familiar with the windows code, but at least for the unix code this would be returning immediately after the call to fork(), but that may not be possible

This is exactly what I'd like to performance test. It seems like making this non-blocking would be a performance gain when spawning lots of children, but I may just be imagining it. :-)
