### ISSUE TITLE
darwin: fsevents reports events from before watcher start

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#986]
Run in node:

```
$ node -e ' \
  var assert = require("assert");  \
  var fs = require("fs"); \
  fs.writeFileSync("x", "x"); \
  fs.watch(".", assert.fail);  \
'
```

The above works as expected on linux (it just sits there) but throws the following exception on darwin:

```
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: "rename" undefined "x"
    at FSWatcher.EventEmitter.emit (events.js:101:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1011:12)
```

/cc @indutny

**Comment by indutny** [comment]
Not something I could affect, perhaps FSEvents is sending previously received event.

**Comment by bnoordhuis** [comment]
That's what happens, yes.  Can't we filter out such events with e.g. FSEventsGetLastEventIdForDeviceBeforeTime()?

**Comment by indutny** [comment]
The event will most likely have EventId bigger than this time, but I can recheck it if you want me to.

**Comment by indutny** [comment]
@bnoordhuis I'm afraid it won't work with mounted directories... I mean, you may watch `/a`, which has `/a/b` which is a mount of another device. Perhaps, I'm stressing it too much and it will work just fine?

**Comment by indutny** [comment]
Also, I've just measured event ids. And they seem to be bigger than `FSEventsGetCurrentEventId()` that I took right before starting FSEventStream.

So I guess it is just an OSX bug, and not something that we could fix there.
