### ISSUE TITLE
libuv breaks GNU Make jobserver file descriptors

### ISSUE THREAD

**Issue by timbertson** [joyent/libuv#997]
libuv unconditionally sets FD_CLOEXEC on the first 16 file descriptors when trying to disable stdio inheritance:

https://github.com/joyent/libuv/blob/master/src/unix/core.c#L605

When you invoke a nodejs process via the makefile rule:

```
+node <...>
```

make sets `$MAKEFLAGS` to include --jobserver-fds=3,4 (these are the two ends of the jobserver pipe make created) and passes these open FDs to the node process. But when that node spawns a child that tries to interact with the jobserver, the FDs have been closed by the libuv code under the incorrect assumption that they were stdio descriptors.

Simple test case to show the problem:

Makefile:

```
test:
    @echo "## via bash"
    @+bash -c 'make dummy1 dummy2'

    @echo "## via node"
    @+node -e 'require("child_process").spawn("make", ["dummy1","dummy2"], {stdio:"inherit"}, function() {});'

dummy1:
    @echo 'dummy1'

dummy2:
    @echo 'dummy2'

.PHONY: test dummy1 dummy2
```

invocation:

```
$ make -j2 test
```

output:

```
$ make -j2 test
## via bash
make[1]: Entering directory `/tmp/lubuv-bug'
dummy1
dummy2
make[1]: Leaving directory `/tmp/lubuv-bug'
## via node
make[1]: Entering directory `/tmp/lubuv-bug'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
dummy1
dummy2
make[1]: Leaving directory `/tmp/lubuv-bug'
```

While this is only a warning here (and it falls back to a serialized build), some jobserver-compatible programs (e.g `apenwarr/redo`) will abort when encountering invalid jobserver file descriptors, so it's a bigger issue in that case.

**Comment by timbertson** [comment]
ping @bnoordhuis and @piscisaureus (4d7f1e1864983c9ffc76a52af3346777806767ee).

Let me know if this is a nodejs bug (perhaps it shouldn't be calling `uv_disable_stdio_inheritance`), but that fact that the function name says "stdio" makes me think it's being overly aggressive.

**Comment by sam-github** [comment]
http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

You are using the option `stdio: "inherit"`, described as "inherit - [process.stdin, process.stdout, process.stderr] or [0,1,2]". Looks like you should be using `stdio: [0,1,2,3,4]` if you want to pass fds 3 and 4 to your child.

**Comment by timbertson** [comment]
I don't necessarily know what FDs I want to pass through to the child - in fact the given node script is completely unaware of the presence of a make jobserver (this is known by the parent and child, but not necessarily the .js script).

Also, the fact that make happens to use FDs 3 and 4 is an implementation detail (it presumably just uses the lowest two FDs available when it runs). If I wanted to ensure FD 100 was not closed, would I need to pass a 100-length array to the `stdio` setting? Is there no way to say "inherit all open FDs"?

**Comment by bnoordhuis** [comment]
> Let me know if this is a nodejs bug (perhaps it shouldn't be calling uv_disable_stdio_inheritance), but that fact that the function name says "stdio" makes me think it's being overly aggressive.

The name is not great.  It's a hack that work around a node.js quirk and arguably shouldn't have been in libuv in the first place.  If it's causing trouble, please don't use it.

This issue makes me think that it's a good idea to remove it.  @piscisaureus Thoughts?

**Comment by sam-github** [comment]
Parse MAKEFLAGS so you know what fds to pass. Setting a hundred-length array is not hard:

```
opts = {stdio: []}
opts.stdio[100] = 100
spawn(…, opts)
```

**Comment by timbertson** [comment]
@sam-github I know that I could workaround this specific problem, but I'm claiming the behaviour in general is broken. Requiring every nodejs script that spawns child processes to "parse $MAKEFLAGS just in case it's being run by make" is not a reasonable solution by any stretch of the imagination. It also doesn't fix any _other_ system that passes open FDs to children and expects them to remain open in grand-children - which is (as far as I know) a perfectly valid thing to do.

**Comment by piscisaureus** [comment]
This is on purpose.

If you want to pass an open FD to a child process in node do this:

``` js
child_process.spawn('program', 
                    ['arg1', 'arg2'],
                    { stdio: ['pipe', 'pipe', 'pipe', 'inherit', 'inherit'] });
```

**Comment by piscisaureus** [comment]
Ok, I see that the 'inherit' solution has been suggested earlier. However I disagree that the assumption that open FDs are passed to grand-children is acceptable. Node tries to make sure that a child process inherits _only_ whatever has been explicitly requested. We added this to make 'test-child-process-detached' pass.

**Comment by timbertson** [comment]
@piscisaureus I'm not sure if you noticed this part, but the nodejs code in question potentially has _no idea_ it is being invoked by make. So the suggested solution of "explicitly pass any FDs you want to not get closed" is not feasible. e.g I might use some module which runs child processes internally - clearly it's unacceptable to require all code and libraries that spawn child processes to always "parse $MAKEFLAGS just in case it specifies FDs which should be inherited".

It sounds like perhaps this auto-close behaviour is only warranted when the `detached` option is true? If not, could there at least be an option in the child_process module to opt in or out of this auto-close behaviour?

Also, is it not kind of weird that the FD _is_ inherited with increasing probability once the file descriptors in question reach number 18 and above?
