### ISSUE TITLE
windows: build broken on 0.10

### ISSUE THREAD

**Issue by schlamar** [joyent/libuv#998]
I tried to build libuv 0.10 on 983fa68 (from pyuv release 0.10.7). 

But the gyp build step is completely broken. It spins up an infinitely loop, constantly printing the error "no module named gyp_uv" in multiprocessing/forking.py.

A workaround (or possible solution?) is to add `--no-parallel` to the execution of gyp_uv in vcbuild.bat.

Gyp revision is `d0176c0`.

**Comment by saghul** [comment]
A fix for this was committed recently: https://github.com/joyent/libuv/commit/991409e461e3973f006bf951b3e7513578a41be2 can you check if latest libuv v0.10 branch builds ok with pyuv? If so I'll make a new release bumping the libuv revision.

**Comment by schlamar** [comment]
Yes, libuv v0.10.19 builds fine with pyuv 0.10 branch.

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?

**Comment by saghul** [comment]
What libuv revision are you trying to build?

**Comment by robin-yue** [comment]
Now,I met the same error "no module named gyp_uv" in multiprocessing/forking.py".when run "vcbuild.bat" to compile the latest libuv code project on win7 using vs2012.Any solution for this problem?
